const KEY_NAME = [
  '  KeyName  [\\\\Machine\\]FullKey',
  '           Machine  Name of remote machine - omitting defaults to the',
  '                    current machine. Only HKLM and HKU are available on remote',
  '                    machines.',
  '           FullKey  ROOTKEY\\SubKey',
  '           ROOTKEY  [ HKLM | HKCU | HKCR | HKU | HKCC ]',
  '           SubKey   The full name of a registry key under the selected ROOTKEY',
];

const VIEW_SWITCHES = [
  '  /reg:32  Specifies the key should be accessed using the 32-bit registry view.',
  '',
  '  /reg:64  Specifies the key should be accessed using the 64-bit registry view.',
];

export const REG_HELP = [
  'REG Operation [Parameter List]',
  '',
  '  Operation  [ QUERY   | ADD    | DELETE  | COPY    |',
  '               SAVE    | LOAD   | UNLOAD  | RESTORE |',
  '               COMPARE | EXPORT | IMPORT  | FLAGS ]',
  '',
  'Return Code: (Except for REG COMPARE)',
  '',
  '  0 - Successful',
  '  1 - Failed',
  '',
  'For help on a specific operation type:',
  '',
  '  REG Operation /?',
  '',
  'Examples:',
  '',
  '  REG QUERY /?',
  '  REG ADD /?',
  '  REG DELETE /?',
  '  REG COPY /?',
  '  REG SAVE /?',
  '  REG RESTORE /?',
  '  REG LOAD /?',
  '  REG UNLOAD /?',
  '  REG COMPARE /?',
  '  REG EXPORT /?',
  '  REG IMPORT /?',
  '  REG FLAGS /?',
].join('\n');

export const REG_OPERATION_HELP: Readonly<Record<string, string>> = {
  query: [
    'REG QUERY KeyName [/v ValueName | /ve] [/s]',
    '          [/se Separator] [/f Data] [/k] [/d] [/c] [/e] [/t Type] [/z]',
    '',
    ...KEY_NAME,
    '',
    '  /v       Queries for a specific registry key values.',
    '           If omitted, all values for the key are queried.',
    '           Argument to switch is optional when specified along with /f',
    '           switch. Specifies to query for value name.',
    '',
    '  /ve      Queries for the default value or empty value name (Default).',
    '',
    '  /s       Queries all subkeys and values recursively (like dir /s).',
    '',
    '  /se      Specifies the single value separator character to use in',
    '           the case of REG_MULTI_SZ (length of 1 only)',
    '           Defaults to "\\0" as the separator.',
    '',
    '  /f       Specifies the data or pattern to search for.',
    '           Use double quotes if a string contains spaces. Defaults to "*".',
    '',
    '  /k       Specifies to search in key names only.',
    '',
    '  /d       Specifies to search in data only.',
    '',
    '  /c       Specifies that the search is case sensitive.',
    '           The default search is case insensitive.',
    '',
    '  /e       Specifies to return only exact matches.',
    '           By default all the matches are returned.',
    '',
    '  /t       Specifies registry value data type.',
    '           Valid types are:',
    '           REG_SZ, REG_MULTI_SZ, REG_EXPAND_SZ,',
    '           REG_DWORD, REG_QWORD, REG_BINARY, REG_NONE',
    '           Defaults to all types.',
    '',
    '  /z       Verbose: shows the numeric equivalent for the type of the',
    '           value name.',
    '',
    ...VIEW_SWITCHES,
  ].join('\n'),
  add: [
    'REG ADD KeyName [/v ValueName | /ve] [/t Type] [/s Separator] [/d Data] [/f]',
    '        [/reg:32 | /reg:64]',
    '',
    ...KEY_NAME,
    '',
    '  /v       The value name, under the selected Key, to add.',
    '',
    '  /ve      adds an empty value name (Default) for the key.',
    '',
    '  /t       RegKey data types',
    '           [ REG_SZ    | REG_MULTI_SZ | REG_EXPAND_SZ |',
    '             REG_DWORD | REG_QWORD    | REG_BINARY    | REG_NONE ]',
    '           If omitted, REG_SZ is assumed.',
    '',
    '  /s       Specify one character that you use as the separator in your data',
    '           string for REG_MULTI_SZ. If omitted, use "\\0" as the separator.',
    '',
    '  /d       The data to assign to the registry ValueName being added.',
    '',
    '  /f       Force overwriting the existing registry entry without prompt.',
    '',
    ...VIEW_SWITCHES,
  ].join('\n'),
  delete: [
    'REG DELETE KeyName [/v ValueName | /ve | /va] [/f]',
    '           [/reg:32 | /reg:64]',
    '',
    ...KEY_NAME,
    '',
    '  ValueName  The value name, under the selected Key, to delete.',
    '             When omitted, all subkeys and values under the Key are deleted.',
    '',
    '  /ve      delete the value of empty value name (Default).',
    '',
    '  /va      delete all values under this key.',
    '',
    '  /f       Forces the deletion without prompt.',
    '',
    ...VIEW_SWITCHES,
  ].join('\n'),
  copy: [
    'REG COPY KeyName1 KeyName2 [/s] [/f]',
    '',
    '  KeyName  [\\\\Machine\\]FullKey',
    '           Machine  Name of remote machine - omitting defaults to the',
    '                    current machine. Only HKLM and HKU are available on remote',
    '                    machines.',
    '           FullKey  ROOTKEY\\SubKey',
    '           ROOTKEY  [ HKLM | HKCU | HKCR | HKU | HKCC ]',
    '           SubKey   The full name of a registry key under the selected ROOTKEY',
    '',
    '  /s       Copies all subkeys and values under the key.',
    '',
    '  /f       Forces the copy without prompt.',
  ].join('\n'),
  export: [
    'REG EXPORT KeyName FileName [/y]',
    '',
    '  KeyName  ROOTKEY[\\SubKey] (local machine only).',
    '  FileName The name of the disk file to export.',
    '  /y       Force overwriting the existing file without prompt.',
    '',
    ...VIEW_SWITCHES,
  ].join('\n'),
  import: [
    'REG IMPORT FileName',
    '',
    '  FileName The name of the disk file to import (local machine only).',
    '',
    ...VIEW_SWITCHES,
  ].join('\n'),
};
