-- =====================================================
-- Oracle E-Commerce Database Seed Script
-- Schema: ECOMMERCE
-- Description: Complete e-commerce database with
--              customers, products, orders, etc.
-- =====================================================

-- =====================================================
-- TABLE: CATEGORIES
-- =====================================================
CREATE TABLE CATEGORIES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    PARENT_ID NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_CATEGORIES START WITH 1 INCREMENT BY 1;

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Electronics', 'Electronic devices and accessories', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Clothing', 'Apparel and fashion items', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Books', 'Physical and digital books', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Home & Garden', 'Home decor and garden supplies', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Sports', 'Sports equipment and accessories', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Computers', 'Desktop and laptop computers', 1);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Smartphones', 'Mobile phones and tablets', 1);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Audio', 'Headphones, speakers, and audio equipment', 1);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Mens Clothing', 'Clothing for men', 2);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Womens Clothing', 'Clothing for women', 2);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Fiction', 'Fiction books and novels', 3);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID) VALUES (SEQ_CATEGORIES.NEXTVAL, 'Non-Fiction', 'Educational and informational books', 3);

-- =====================================================
-- TABLE: CUSTOMERS
-- =====================================================
CREATE TABLE CUSTOMERS (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE SEQ_CUSTOMERS START WITH 1 INCREMENT BY 1;

INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'john.doe@email.com', '$2b$10$xyz123hashedpassword', 'John', 'Doe', '+1-555-0101');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'jane.smith@email.com', '$2b$10$abc456hashedpassword', 'Jane', 'Smith', '+1-555-0102');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'bob.wilson@email.com', '$2b$10$def789hashedpassword', 'Bob', 'Wilson', '+1-555-0103');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'alice.johnson@email.com', '$2b$10$ghi012hashedpassword', 'Alice', 'Johnson', '+1-555-0104');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'charlie.brown@email.com', '$2b$10$jkl345hashedpassword', 'Charlie', 'Brown', '+1-555-0105');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'emma.davis@email.com', '$2b$10$mno678hashedpassword', 'Emma', 'Davis', '+1-555-0106');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'michael.garcia@email.com', '$2b$10$pqr901hashedpassword', 'Michael', 'Garcia', '+1-555-0107');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'sophia.martinez@email.com', '$2b$10$stu234hashedpassword', 'Sophia', 'Martinez', '+1-555-0108');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'william.anderson@email.com', '$2b$10$vwx567hashedpassword', 'William', 'Anderson', '+1-555-0109');
INSERT INTO CUSTOMERS (ID, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE) VALUES (SEQ_CUSTOMERS.NEXTVAL, 'olivia.taylor@email.com', '$2b$10$yza890hashedpassword', 'Olivia', 'Taylor', '+1-555-0110');

-- =====================================================
-- TABLE: ADDRESSES
-- =====================================================
CREATE TABLE ADDRESSES (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ADDRESS_TYPE VARCHAR2(20) DEFAULT 'shipping',
    STREET_ADDRESS VARCHAR2(255) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    STATE_PROVINCE VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20) NOT NULL,
    COUNTRY VARCHAR2(100) DEFAULT 'USA',
    IS_DEFAULT NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE SEQ_ADDRESSES START WITH 1 INCREMENT BY 1;

INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 1, 'shipping', '123 Main Street', 'New York', 'NY', '10001', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 1, 'billing', '123 Main Street', 'New York', 'NY', '10001', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 2, 'shipping', '456 Oak Avenue', 'Los Angeles', 'CA', '90001', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 3, 'shipping', '789 Pine Road', 'Chicago', 'IL', '60601', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 4, 'shipping', '321 Elm Street', 'Houston', 'TX', '77001', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 5, 'shipping', '654 Maple Drive', 'Phoenix', 'AZ', '85001', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 6, 'shipping', '987 Cedar Lane', 'Philadelphia', 'PA', '19101', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 7, 'shipping', '147 Birch Court', 'San Antonio', 'TX', '78201', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 8, 'shipping', '258 Walnut Way', 'San Diego', 'CA', '92101', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 9, 'shipping', '369 Cherry Place', 'Dallas', 'TX', '75201', 'USA', 1);
INSERT INTO ADDRESSES (ID, CUSTOMER_ID, ADDRESS_TYPE, STREET_ADDRESS, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY, IS_DEFAULT) VALUES (SEQ_ADDRESSES.NEXTVAL, 10, 'shipping', '741 Ash Boulevard', 'San Jose', 'CA', '95101', 'USA', 1);

-- =====================================================
-- TABLE: PRODUCTS
-- =====================================================
CREATE TABLE PRODUCTS (
    ID NUMBER PRIMARY KEY,
    SKU VARCHAR2(50) NOT NULL UNIQUE,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    PRICE NUMBER(10, 2) NOT NULL,
    COST NUMBER(10, 2),
    CATEGORY_ID NUMBER,
    STOCK_QUANTITY NUMBER DEFAULT 0,
    WEIGHT NUMBER(8, 2),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_PRODUCTS START WITH 1 INCREMENT BY 1;

INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'LAPTOP-001', 'ProBook 15 Laptop', '15.6 inch Full HD, Intel i7, 16GB RAM, 512GB SSD', 1299.99, 950.00, 6, 50, 2.10);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'LAPTOP-002', 'UltraSlim 14 Laptop', '14 inch 4K Display, Intel i5, 8GB RAM, 256GB SSD', 899.99, 650.00, 6, 75, 1.50);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'PHONE-001', 'SmartPhone Pro X', '6.7 inch OLED, 128GB, 5G, Triple Camera', 999.99, 700.00, 7, 100, 0.20);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'PHONE-002', 'SmartPhone Lite', '6.1 inch LCD, 64GB, 4G, Dual Camera', 499.99, 300.00, 7, 150, 0.18);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'HEADPHONE-001', 'NoiseCancel Pro Headphones', 'Wireless ANC Headphones, 30hr battery', 349.99, 180.00, 8, 200, 0.25);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'HEADPHONE-002', 'SportBuds Wireless', 'True Wireless Earbuds, Water resistant', 149.99, 70.00, 8, 300, 0.05);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'SHIRT-001', 'Classic Cotton T-Shirt', '100 percent Cotton, Crew neck, Multiple colors', 29.99, 8.00, 9, 500, 0.20);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'SHIRT-002', 'Premium Polo Shirt', 'Pique cotton polo, Button collar', 59.99, 18.00, 9, 300, 0.25);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'DRESS-001', 'Elegant Summer Dress', 'Floral print, A-line cut, Knee length', 89.99, 35.00, 10, 150, 0.30);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'DRESS-002', 'Professional Blazer', 'Tailored fit, Single breasted', 149.99, 60.00, 10, 100, 0.50);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'BOOK-001', 'The Art of Programming', 'Comprehensive guide to software development', 49.99, 15.00, 12, 200, 0.80);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'BOOK-002', 'Mystery at Midnight', 'Bestselling thriller novel', 24.99, 7.00, 11, 400, 0.40);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'BOOK-003', 'Cooking Made Easy', '500 recipes for beginners', 34.99, 12.00, 12, 250, 1.00);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'SPEAKER-001', 'BoomBox Portable Speaker', 'Bluetooth 5.0, 20W, 12hr battery', 79.99, 35.00, 8, 180, 0.60);
INSERT INTO PRODUCTS (ID, SKU, NAME, DESCRIPTION, PRICE, COST, CATEGORY_ID, STOCK_QUANTITY, WEIGHT) VALUES (SEQ_PRODUCTS.NEXTVAL, 'TABLET-001', 'ProTab 10', '10.1 inch Tablet, 64GB, Wi-Fi plus LTE', 449.99, 280.00, 7, 80, 0.45);

-- =====================================================
-- TABLE: ORDERS
-- =====================================================
CREATE TABLE ORDERS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    STATUS VARCHAR2(30) DEFAULT 'pending',
    SUBTOTAL NUMBER(10, 2) NOT NULL,
    TAX NUMBER(10, 2) DEFAULT 0,
    SHIPPING_COST NUMBER(10, 2) DEFAULT 0,
    TOTAL NUMBER(10, 2) NOT NULL,
    SHIPPING_ADDRESS_ID NUMBER,
    BILLING_ADDRESS_ID NUMBER,
    PAYMENT_METHOD VARCHAR2(50),
    NOTES VARCHAR2(4000),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_ORDERS START WITH 1 INCREMENT BY 1;

INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 1, 'ORD-2024-001', 'delivered', 1299.99, 104.00, 0.00, 1403.99, 1, 2, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 2, 'ORD-2024-002', 'delivered', 529.98, 42.40, 5.99, 578.37, 3, 3, 'paypal');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 3, 'ORD-2024-003', 'shipped', 349.99, 28.00, 0.00, 377.99, 4, 4, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 1, 'ORD-2024-004', 'processing', 89.97, 7.20, 5.99, 103.16, 1, 2, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 4, 'ORD-2024-005', 'delivered', 999.99, 80.00, 0.00, 1079.99, 5, 5, 'debit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 5, 'ORD-2024-006', 'pending', 179.98, 14.40, 5.99, 200.37, 6, 6, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 2, 'ORD-2024-007', 'delivered', 449.99, 36.00, 0.00, 485.99, 3, 3, 'paypal');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 6, 'ORD-2024-008', 'shipped', 1799.98, 144.00, 0.00, 1943.98, 7, 7, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 7, 'ORD-2024-009', 'processing', 74.98, 6.00, 5.99, 86.97, 8, 8, 'credit_card');
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NUMBER, STATUS, SUBTOTAL, TAX, SHIPPING_COST, TOTAL, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, PAYMENT_METHOD) VALUES (SEQ_ORDERS.NEXTVAL, 3, 'ORD-2024-010', 'delivered', 149.99, 12.00, 5.99, 167.98, 4, 4, 'debit_card');

-- =====================================================
-- TABLE: ORDER_ITEMS
-- =====================================================
CREATE TABLE ORDER_ITEMS (
    ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE NUMBER(10, 2) NOT NULL,
    TOTAL_PRICE NUMBER(10, 2) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER_ITEMS START WITH 1 INCREMENT BY 1;

INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 1, 1, 1, 1299.99, 1299.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 2, 4, 1, 499.99, 499.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 2, 7, 1, 29.99, 29.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 3, 5, 1, 349.99, 349.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 4, 7, 3, 29.99, 89.97);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 5, 3, 1, 999.99, 999.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 6, 6, 1, 149.99, 149.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 6, 7, 1, 29.99, 29.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 7, 15, 1, 449.99, 449.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 8, 1, 1, 1299.99, 1299.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 8, 4, 1, 499.99, 499.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 9, 12, 2, 24.99, 49.98);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 9, 13, 1, 24.99, 24.99);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES (SEQ_ORDER_ITEMS.NEXTVAL, 10, 10, 1, 149.99, 149.99);

-- =====================================================
-- TABLE: REVIEWS
-- =====================================================
CREATE TABLE REVIEWS (
    ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    RATING NUMBER(1) CHECK (RATING >= 1 AND RATING <= 5),
    TITLE VARCHAR2(255),
    REVIEW_TEXT VARCHAR2(4000),
    IS_VERIFIED NUMBER(1) DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_REVIEWS START WITH 1 INCREMENT BY 1;

INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 1, 1, 5, 'Excellent laptop!', 'Fast, reliable, and great battery life. Highly recommend for developers.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 1, 3, 4, 'Good but pricey', 'Great performance but a bit expensive. Still worth it though.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 3, 5, 5, 'Best phone I have owned', 'Amazing camera and the screen is gorgeous. Battery lasts all day.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 5, 3, 5, 'Perfect noise cancellation', 'These headphones are incredible. Cannot hear anything with ANC on.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 7, 2, 4, 'Comfortable fit', 'Nice quality cotton, fits true to size. Would buy again.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 11, 4, 5, 'Must-read for programmers', 'Comprehensive and well-written. Every developer should read this.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 12, 7, 4, 'Could not put it down', 'Great thriller with unexpected twists. Finished it in two days.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 6, 6, 4, 'Great for workouts', 'Good sound quality and they stay in place during exercise.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 15, 2, 5, 'Perfect tablet', 'Use it for reading, streaming, and light work. Very versatile.', 1);
INSERT INTO REVIEWS (ID, PRODUCT_ID, CUSTOMER_ID, RATING, TITLE, REVIEW_TEXT, IS_VERIFIED) VALUES (SEQ_REVIEWS.NEXTVAL, 9, 8, 5, 'Beautiful dress', 'The fabric quality is excellent and it fits perfectly.', 1);

-- =====================================================
-- TABLE: SHOPPING_CARTS
-- =====================================================
CREATE TABLE SHOPPING_CARTS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_CARTS START WITH 1 INCREMENT BY 1;

CREATE TABLE CART_ITEMS (
    ID NUMBER PRIMARY KEY,
    CART_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER DEFAULT 1,
    ADDED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_CART_ITEMS START WITH 1 INCREMENT BY 1;

INSERT INTO SHOPPING_CARTS (ID, CUSTOMER_ID) VALUES (SEQ_CARTS.NEXTVAL, 8);
INSERT INTO SHOPPING_CARTS (ID, CUSTOMER_ID) VALUES (SEQ_CARTS.NEXTVAL, 9);
INSERT INTO SHOPPING_CARTS (ID, CUSTOMER_ID) VALUES (SEQ_CARTS.NEXTVAL, 10);

INSERT INTO CART_ITEMS (ID, CART_ID, PRODUCT_ID, QUANTITY) VALUES (SEQ_CART_ITEMS.NEXTVAL, 1, 2, 1);
INSERT INTO CART_ITEMS (ID, CART_ID, PRODUCT_ID, QUANTITY) VALUES (SEQ_CART_ITEMS.NEXTVAL, 1, 6, 2);
INSERT INTO CART_ITEMS (ID, CART_ID, PRODUCT_ID, QUANTITY) VALUES (SEQ_CART_ITEMS.NEXTVAL, 2, 14, 1);
INSERT INTO CART_ITEMS (ID, CART_ID, PRODUCT_ID, QUANTITY) VALUES (SEQ_CART_ITEMS.NEXTVAL, 2, 7, 3);
INSERT INTO CART_ITEMS (ID, CART_ID, PRODUCT_ID, QUANTITY) VALUES (SEQ_CART_ITEMS.NEXTVAL, 3, 3, 1);

-- =====================================================
-- TABLE: INVENTORY_LOG
-- =====================================================
CREATE TABLE INVENTORY_LOG (
    ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    CHANGE_TYPE VARCHAR2(20) NOT NULL,
    QUANTITY_CHANGE NUMBER NOT NULL,
    PREVIOUS_QUANTITY NUMBER NOT NULL,
    NEW_QUANTITY NUMBER NOT NULL,
    REASON VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_INVENTORY_LOG START WITH 1 INCREMENT BY 1;

INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 1, 'sale', -1, 51, 50, 'Order ORD-2024-001');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 4, 'sale', -1, 151, 150, 'Order ORD-2024-002');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 7, 'sale', -1, 501, 500, 'Order ORD-2024-002');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 5, 'sale', -1, 201, 200, 'Order ORD-2024-003');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 3, 'sale', -1, 101, 100, 'Order ORD-2024-005');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 1, 'restock', 20, 50, 70, 'Supplier delivery');
INSERT INTO INVENTORY_LOG (ID, PRODUCT_ID, CHANGE_TYPE, QUANTITY_CHANGE, PREVIOUS_QUANTITY, NEW_QUANTITY, REASON) VALUES (SEQ_INVENTORY_LOG.NEXTVAL, 7, 'restock', 100, 497, 597, 'Supplier delivery');

-- =====================================================
-- TABLE: COUPONS
-- =====================================================
CREATE TABLE COUPONS (
    ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(50) NOT NULL UNIQUE,
    DISCOUNT_TYPE VARCHAR2(20) NOT NULL,
    DISCOUNT_VALUE NUMBER(10, 2) NOT NULL,
    MIN_ORDER_AMOUNT NUMBER(10, 2),
    MAX_USES NUMBER,
    CURRENT_USES NUMBER DEFAULT 0,
    VALID_FROM DATE,
    VALID_UNTIL DATE,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE SEQ_COUPONS START WITH 1 INCREMENT BY 1;

INSERT INTO COUPONS (ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_USES, VALID_FROM, VALID_UNTIL) VALUES (SEQ_COUPONS.NEXTVAL, 'WELCOME10', 'percentage', 10.00, 50.00, 1000, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'));
INSERT INTO COUPONS (ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_USES, VALID_FROM, VALID_UNTIL) VALUES (SEQ_COUPONS.NEXTVAL, 'SAVE20', 'percentage', 20.00, 100.00, 500, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'));
INSERT INTO COUPONS (ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_USES, VALID_FROM, VALID_UNTIL) VALUES (SEQ_COUPONS.NEXTVAL, 'FLAT50', 'fixed', 50.00, 200.00, 200, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'));
INSERT INTO COUPONS (ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_USES, VALID_FROM, VALID_UNTIL) VALUES (SEQ_COUPONS.NEXTVAL, 'FREESHIP', 'shipping', 100.00, 75.00, NULL, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'));
INSERT INTO COUPONS (ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_USES, VALID_FROM, VALID_UNTIL) VALUES (SEQ_COUPONS.NEXTVAL, 'VIP25', 'percentage', 25.00, 150.00, 100, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'));

-- =====================================================
-- CREATE INDEXES
-- =====================================================
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_PRODUCTS_SKU ON PRODUCTS(SKU);
CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_REVIEWS_PRODUCT ON REVIEWS(PRODUCT_ID);
CREATE INDEX IDX_ADDRESSES_CUSTOMER ON ADDRESSES(CUSTOMER_ID);

COMMIT;

-- =====================================================
-- Database Summary
-- =====================================================
-- Tables: 12
-- Sequences: 11
-- Indexes: 7
-- Total records: ~100
-- Schema: ECOMMERCE
-- =====================================================
