/**
 * FlexCube Universal Banking (FCUBS) — FCUBSLIVE schema DDL definitions.
 *
 * Tables modeled after the Oracle FLEXCUBE data dictionary:
 *   - STTM_CUSTOMER          — Core customer master
 *   - STTM_CUST_ACCOUNT      — Customer accounts (savings, current, etc.)
 *   - STTB_ACCOUNT            — GL/Account master
 *   - STTM_KYC_MASTER         — KYC reference master
 *   - STTM_KYC_RETAIL         — KYC retail customer details
 *   - SMTB_USER               — System users (bank staff)
 *   - ACTB_HISTORY            — Account transaction history
 *   - ACTB_ACCBAL_HISTORY     — Account balance history
 *   - CLTB_ACCOUNT_APPS_MASTER — Loan/CL account master
 *   - CLTB_ACCOUNT_SCHEDULES  — Loan repayment schedules
 *   - CYTB_RATES_HISTORY      — Currency exchange rates history
 *   - DETB_RTL_TELLER         — Retail teller transactions
 *   - FBTB_TILL_TXN_DETAIL_HIST — Till/cash transaction details
 */

export const FCUBSLIVE_DDL: string[] = [
  // ── STTM_CUSTOMER — Core customer master ──────────────────────────
  `CREATE TABLE FCUBSLIVE.STTM_CUSTOMER (
     CUSTOMER_NO VARCHAR2(20) NOT NULL,
     CUSTOMER_NAME1 VARCHAR2(105),
     SHORT_NAME VARCHAR2(20),
     CUSTOMER_TYPE CHAR(1),
     CUSTOMER_CATEGORY VARCHAR2(10),
     COUNTRY VARCHAR2(3),
     NATIONALITY VARCHAR2(3),
     ADDRESS_LINE1 VARCHAR2(105),
     ADDRESS_LINE2 VARCHAR2(105),
     ADDRESS_LINE3 VARCHAR2(105),
     ADDRESS_LINE4 VARCHAR2(105),
     PINCODE VARCHAR2(10),
     LANGUAGE VARCHAR2(3),
     LOCAL_BRANCH VARCHAR2(3),
     FULL_NAME VARCHAR2(105),
     CREDIT_RATING VARCHAR2(10),
     GROUP_CODE VARCHAR2(10),
     RISK_CATEGORY VARCHAR2(10),
     SSN VARCHAR2(25),
     UNIQUE_ID_NAME VARCHAR2(20),
     UNIQUE_ID_VALUE VARCHAR2(50),
     CIF_CREATION_DATE DATE,
     CIF_STATUS VARCHAR2(1),
     FROZEN CHAR(1),
     DECEASED CHAR(1),
     RECORD_STAT CHAR(1),
     AUTH_STAT CHAR(1),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE,
     MOD_NO NUMBER(4)
   )`,

  // ── STTM_CUST_ACCOUNT — Customer accounts ─────────────────────────
  `CREATE TABLE FCUBSLIVE.STTM_CUST_ACCOUNT (
     CUST_AC_NO VARCHAR2(20) NOT NULL,
     BRANCH_CODE VARCHAR2(3) NOT NULL,
     CUST_NO VARCHAR2(20) NOT NULL,
     CCY VARCHAR2(3),
     ACCOUNT_CLASS VARCHAR2(6),
     AC_DESC VARCHAR2(105),
     AC_OPEN_DATE DATE,
     ACCOUNT_TYPE VARCHAR2(1),
     ACC_STATUS VARCHAR2(1),
     ACY_CURR_BALANCE NUMBER(22,3),
     ACY_AVL_BAL NUMBER(22,3),
     ACY_BLOCKED_AMOUNT NUMBER(22,3),
     ACY_OPENING_BAL NUMBER(22,3),
     LCY_CURR_BALANCE NUMBER(22,3),
     ACY_TOVER_CR NUMBER(22,3),
     ACY_MTD_TOVER_CR NUMBER(22,3),
     ACY_MTD_TOVER_DR NUMBER(22,3),
     ACY_TODAY_TOVER_CR NUMBER(22,3),
     ACY_TODAY_TOVER_DR NUMBER(22,3),
     AC_STAT_DORMANT CHAR(1),
     AC_STAT_FROZEN CHAR(1),
     AC_STAT_NO_CR CHAR(1),
     AC_STAT_NO_DR CHAR(1),
     AC_STAT_BLOCK CHAR(1),
     AC_STAT_STOP_PAY CHAR(1),
     CHEQUE_BOOK_FACILITY CHAR(1),
     ATM_FACILITY CHAR(1),
     PASSBOOK_FACILITY CHAR(1),
     JOINT_AC_INDICATOR CHAR(1),
     MODE_OF_OPERATION CHAR(1),
     RECORD_STAT CHAR(1),
     AUTH_STAT CHAR(1),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE,
     MOD_NO NUMBER(4)
   )`,

  // ── STTB_ACCOUNT — GL/Account master ──────────────────────────────
  `CREATE TABLE FCUBSLIVE.STTB_ACCOUNT (
     AC_GL_NO VARCHAR2(20) NOT NULL,
     BRANCH_CODE VARCHAR2(3) NOT NULL,
     AC_GL_CCY VARCHAR2(3),
     AC_GL_DESC VARCHAR2(105),
     CUST_NO VARCHAR2(20),
     CUST_NAME1 VARCHAR2(105),
     AC_CLASS VARCHAR2(6),
     AC_OR_GL CHAR(1),
     GL_CATEGORY CHAR(1),
     AC_OPEN_DATE DATE,
     AC_STAT_DORMANT CHAR(1),
     AC_STAT_FROZEN CHAR(1),
     AC_STAT_NO_CR CHAR(1),
     AC_STAT_NO_DR CHAR(1),
     AC_GL_REC_STATUS CHAR(1),
     AUTH_STAT CHAR(1),
     ALT_AC_NO VARCHAR2(20),
     IBAN_AC_NO VARCHAR2(34)
   )`,

  // ── STTM_KYC_MASTER — KYC reference master ───────────────────────
  `CREATE TABLE FCUBSLIVE.STTM_KYC_MASTER (
     KYC_REF_NO VARCHAR2(16) NOT NULL,
     KYC_CUST_TYPE VARCHAR2(1),
     KYC_DESC VARCHAR2(105),
     RISK_LEVEL VARCHAR2(10),
     RECORD_STAT VARCHAR2(1),
     AUTH_STAT VARCHAR2(1),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE,
     MOD_NO NUMBER(4)
   )`,

  // ── STTM_KYC_RETAIL — KYC retail details ──────────────────────────
  `CREATE TABLE FCUBSLIVE.STTM_KYC_RETAIL (
     KYC_REF_NO VARCHAR2(16) NOT NULL,
     NATIONALITY VARCHAR2(3),
     BIRTH_DATE DATE,
     BIRTH_PLACE VARCHAR2(50),
     BIRTH_COUNTRY VARCHAR2(3),
     PASSPORT_NO VARCHAR2(20),
     PASSPORT_EXPIRY_DATE DATE,
     RESIDENT VARCHAR2(1),
     SALARY_INCOME VARCHAR2(20),
     BUSINESS_INCOME VARCHAR2(20),
     TOTAL_INCOME NUMBER(22,3),
     TOTAL_NET_WORTH NUMBER(22,3),
     PEP VARCHAR2(1),
     ACC_PURPOSE VARCHAR2(50),
     LOCAL_ADDR VARCHAR2(200),
     LOCAL_ADDR_COUNTRY VARCHAR2(3),
     MOBILE_TEL_NO VARCHAR2(20),
     OFFICE_TEL_NO VARCHAR2(20)
   )`,

  // ── SMTB_USER — System users (bank staff) ─────────────────────────
  `CREATE TABLE FCUBSLIVE.SMTB_USER (
     USER_ID VARCHAR2(12) NOT NULL,
     USER_NAME VARCHAR2(35),
     USER_PASSWORD VARCHAR2(100),
     USER_STATUS CHAR(1),
     HOME_BRANCH VARCHAR2(3),
     DEPT_CODE VARCHAR2(3),
     USER_LANGUAGE VARCHAR2(3),
     USER_EMAIL VARCHAR2(50),
     USER_MOBILE VARCHAR2(20),
     START_DATE DATE,
     END_DATE DATE,
     FORCE_PASSWD_CHANGE NUMBER(1),
     MAX_TXN_AMT NUMBER(22,3),
     MULTIBRANCH_ACCESS VARCHAR2(1),
     USER_CATEGORY CHAR(1),
     RECORD_STAT CHAR(1),
     AUTH_STAT CHAR(1),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE,
     MOD_NO NUMBER(4)
   )`,

  // ── ACTB_HISTORY — Account transaction history ────────────────────
  `CREATE TABLE FCUBSLIVE.ACTB_HISTORY (
     AC_NO VARCHAR2(20) NOT NULL,
     AC_BRANCH VARCHAR2(3),
     AC_CCY VARCHAR2(3),
     TRN_DT DATE,
     VALUE_DT DATE,
     TRN_REF_NO VARCHAR2(16),
     EVENT VARCHAR2(4),
     DRCR_IND CHAR(1),
     FCY_AMOUNT NUMBER(22,3),
     LCY_AMOUNT NUMBER(22,3),
     EXCH_RATE NUMBER(14,8),
     TRN_CODE VARCHAR2(3),
     MODULE VARCHAR2(2),
     PRODUCT VARCHAR2(4),
     RELATED_ACCOUNT VARCHAR2(20),
     RELATED_CUSTOMER VARCHAR2(20),
     RELATED_REFERENCE VARCHAR2(16),
     USER_ID VARCHAR2(12),
     BATCH_NO VARCHAR2(6),
     INSTRUMENT_CODE VARCHAR2(20),
     EXTERNAL_REF_NO VARCHAR2(20),
     STMT_DT DATE,
     AC_ENTRY_SR_NO NUMBER(10),
     FINANCIAL_CYCLE VARCHAR2(4),
     PERIOD_CODE VARCHAR2(6)
   )`,

  // ── ACTB_ACCBAL_HISTORY — Account balance history ─────────────────
  `CREATE TABLE FCUBSLIVE.ACTB_ACCBAL_HISTORY (
     ACCOUNT VARCHAR2(20) NOT NULL,
     BRANCH_CODE VARCHAR2(3),
     ACC_CCY VARCHAR2(3),
     BKG_DATE DATE NOT NULL,
     ACY_OPENING_BAL NUMBER(22,3),
     ACY_CLOSING_BAL NUMBER(22,3),
     ACY_CLOSING_AVLBAL NUMBER(22,3),
     ACY_CLOSING_BLOCK NUMBER(22,3),
     ACY_CLOSING_UNCOLL NUMBER(22,3),
     ACY_CR_TUR NUMBER(22,3),
     ACY_DR_TUR NUMBER(22,3),
     LCY_OPENING_BAL NUMBER(22,3),
     LCY_CLOSING_BAL NUMBER(22,3),
     LCY_CR_TUR NUMBER(22,3),
     LCY_DR_TUR NUMBER(22,3)
   )`,

  // ── CLTB_ACCOUNT_APPS_MASTER — Loan account master ────────────────
  `CREATE TABLE FCUBSLIVE.CLTB_ACCOUNT_APPS_MASTER (
     ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
     BRANCH_CODE VARCHAR2(3),
     CUSTOMER_ID VARCHAR2(20),
     PRODUCT_CODE VARCHAR2(4),
     CURRENCY VARCHAR2(3),
     AMOUNT_FINANCED NUMBER(22,3),
     AMOUNT_DISBURSED NUMBER(22,3),
     BOOK_DATE DATE,
     VALUE_DATE DATE,
     MATURITY_DATE DATE,
     END_DATE DATE,
     NO_OF_INSTALLMENTS NUMBER(5),
     EMI_AMOUNT NUMBER(22,3),
     EMI_FREQ NUMBER(2),
     EMI_FREQ_UNIT VARCHAR2(1),
     ACCOUNT_STATUS VARCHAR2(1),
     MODULE_CODE VARCHAR2(2),
     LIQUIDATION_MODE VARCHAR2(1),
     AUTH_STAT VARCHAR2(1),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE
   )`,

  // ── CLTB_ACCOUNT_SCHEDULES — Loan repayment schedules ─────────────
  `CREATE TABLE FCUBSLIVE.CLTB_ACCOUNT_SCHEDULES (
     ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
     BRANCH_CODE VARCHAR2(3),
     COMPONENT_NAME VARCHAR2(10),
     SCHEDULE_NO NUMBER(5) NOT NULL,
     SCHEDULE_DUE_DATE DATE,
     SCHEDULE_ST_DATE DATE,
     AMOUNT_DUE NUMBER(22,3),
     AMOUNT_SETTLED NUMBER(22,3),
     AMOUNT_OVERDUE NUMBER(22,3),
     AMOUNT_WAIVED NUMBER(22,3),
     EMI_AMOUNT NUMBER(22,3),
     SCH_STATUS VARCHAR2(1),
     CAPITALIZED VARCHAR2(1),
     SETTLEMENT_CCY VARCHAR2(3),
     LCY_EQUIVALENT NUMBER(22,3)
   )`,

  // ── CYTB_RATES_HISTORY — Currency exchange rates ──────────────────
  `CREATE TABLE FCUBSLIVE.CYTB_RATES_HISTORY (
     BRANCH_CODE VARCHAR2(3) NOT NULL,
     CCY1 VARCHAR2(3) NOT NULL,
     CCY2 VARCHAR2(3) NOT NULL,
     RATE_DATE DATE NOT NULL,
     RATE_SERIAL NUMBER(4),
     RATE_TYPE VARCHAR2(4),
     MID_RATE NUMBER(18,8),
     BUY_RATE NUMBER(18,8),
     SALE_RATE NUMBER(18,8),
     RATE_DT_STAMP DATE
   )`,

  // ── DETB_RTL_TELLER — Retail teller transactions ──────────────────
  `CREATE TABLE FCUBSLIVE.DETB_RTL_TELLER (
     TRN_REF_NO VARCHAR2(16) NOT NULL,
     BRANCH_CODE VARCHAR2(3),
     TXN_ACC VARCHAR2(20),
     TXN_CCY VARCHAR2(3),
     TXN_AMOUNT NUMBER(22,3),
     LCY_AMOUNT NUMBER(22,3),
     TXN_CODE VARCHAR2(3),
     TXN_STATUS VARCHAR2(1),
     TRN_DT DATE,
     VALUE_DT DATE,
     PRODUCT_CODE VARCHAR2(4),
     DR_ACC VARCHAR2(20),
     NARRATIVE VARCHAR2(105),
     MODULE VARCHAR2(2),
     EXCH_RATE NUMBER(14,8),
     MAKER_ID VARCHAR2(12),
     MAKER_DT_STAMP DATE,
     CHECKER_ID VARCHAR2(12),
     CHECKER_DT_STAMP DATE,
     AUTH_STAT VARCHAR2(1),
     EVENT_CODE VARCHAR2(4),
     ESN NUMBER(4)
   )`,

  // ── FBTB_TILL_TXN_DETAIL_HIST — Till/cash details ────────────────
  `CREATE TABLE FCUBSLIVE.FBTB_TILL_TXN_DETAIL_HIST (
     BRANCHCODE VARCHAR2(3) NOT NULL,
     TILL_ID VARCHAR2(4) NOT NULL,
     XREF VARCHAR2(16),
     CCYCODE VARCHAR2(3),
     DENOMCODE VARCHAR2(10),
     INFLOW NUMBER(22,3),
     OUTFLOW NUMBER(22,3),
     POSTINGDATE DATE
   )`,
];
