export const LdapRc = {
  SUCCESS: 0x00,
  OPERATIONS_ERROR: 0x01,
  PROTOCOL_ERROR: 0x02,
  TIMELIMIT_EXCEEDED: 0x03,
  SIZELIMIT_EXCEEDED: 0x04,
  COMPARE_FALSE: 0x05,
  COMPARE_TRUE: 0x06,
  STRONG_AUTH_NOT_SUPPORTED: 0x07,
  STRONG_AUTH_REQUIRED: 0x08,
  PARTIAL_RESULTS: 0x09,
  REFERRAL: 0x0a,
  ADMINLIMIT_EXCEEDED: 0x0b,
  UNAVAILABLE_CRITICAL_EXTENSION: 0x0c,
  CONFIDENTIALITY_REQUIRED: 0x0d,
  SASL_BIND_IN_PROGRESS: 0x0e,
  NO_SUCH_ATTRIBUTE: 0x10,
  UNDEFINED_TYPE: 0x11,
  INAPPROPRIATE_MATCHING: 0x12,
  CONSTRAINT_VIOLATION: 0x13,
  TYPE_OR_VALUE_EXISTS: 0x14,
  INVALID_SYNTAX: 0x15,
  NO_SUCH_OBJECT: 0x20,
  ALIAS_PROBLEM: 0x21,
  INVALID_DN_SYNTAX: 0x22,
  IS_LEAF: 0x23,
  ALIAS_DEREF_PROBLEM: 0x24,
  PROXIED_AUTHZ_FAILURE: 0x2f,
  INAPPROPRIATE_AUTH: 0x30,
  INVALID_CREDENTIALS: 0x31,
  INSUFFICIENT_ACCESS: 0x32,
  BUSY: 0x33,
  UNAVAILABLE: 0x34,
  UNWILLING_TO_PERFORM: 0x35,
  LOOP_DETECT: 0x36,
  NAMING_VIOLATION: 0x40,
  OBJECT_CLASS_VIOLATION: 0x41,
  NOT_ALLOWED_ON_NONLEAF: 0x42,
  NOT_ALLOWED_ON_RDN: 0x43,
  ALREADY_EXISTS: 0x44,
  NO_OBJECT_CLASS_MODS: 0x45,
  RESULTS_TOO_LARGE: 0x46,
  AFFECTS_MULTIPLE_DSAS: 0x47,
  VLV_ERROR: 0x4c,
  OTHER: 0x50,
  CUP_RESOURCES_EXHAUSTED: 0x71,
  CUP_SECURITY_VIOLATION: 0x72,
  CUP_INVALID_DATA: 0x73,
  CUP_UNSUPPORTED_SCHEME: 0x74,
  CUP_RELOAD_REQUIRED: 0x75,
  CANCELLED: 0x76,
  NO_SUCH_OPERATION: 0x77,
  TOO_LATE: 0x78,
  CANNOT_CANCEL: 0x79,
  ASSERTION_FAILED: 0x7a,
  PROXIED_AUTHORIZATION_DENIED: 0x7b,
  SYNC_REFRESH_REQUIRED: 0x1000,
  X_SYNC_REFRESH_REQUIRED: 0x4100,
  X_NO_OPERATION: 0x410e,
  X_ASSERTION_FAILED: 0x410f,
  TXN_SPECIFY_OKAY: 0x4120,
  TXN_ID_INVALID: 0x4121,
  SERVER_DOWN: -1,
  LOCAL_ERROR: -2,
  ENCODING_ERROR: -3,
  DECODING_ERROR: -4,
  TIMEOUT: -5,
  AUTH_UNKNOWN: -6,
  FILTER_ERROR: -7,
  USER_CANCELLED: -8,
  PARAM_ERROR: -9,
  NO_MEMORY: -10,
  CONNECT_ERROR: -11,
  NOT_SUPPORTED: -12,
  CONTROL_NOT_FOUND: -13,
  NO_RESULTS_RETURNED: -14,
  MORE_RESULTS_TO_RETURN: -15,
  CLIENT_LOOP: -16,
  REFERRAL_LIMIT_EXCEEDED: -17,
  X_CONNECTING: -18,
} as const;

const MESSAGES = new Map<number, string>([
  [LdapRc.SUCCESS, 'Success'],
  [LdapRc.OPERATIONS_ERROR, 'Operations error'],
  [LdapRc.PROTOCOL_ERROR, 'Protocol error'],
  [LdapRc.TIMELIMIT_EXCEEDED, 'Time limit exceeded'],
  [LdapRc.SIZELIMIT_EXCEEDED, 'Size limit exceeded'],
  [LdapRc.COMPARE_FALSE, 'Compare False'],
  [LdapRc.COMPARE_TRUE, 'Compare True'],
  [LdapRc.STRONG_AUTH_NOT_SUPPORTED, 'Authentication method not supported'],
  [LdapRc.STRONG_AUTH_REQUIRED, 'Strong(er) authentication required'],
  [LdapRc.REFERRAL, 'Referral'],
  [LdapRc.ADMINLIMIT_EXCEEDED, 'Administrative limit exceeded'],
  [LdapRc.UNAVAILABLE_CRITICAL_EXTENSION, 'Critical extension is unavailable'],
  [LdapRc.CONFIDENTIALITY_REQUIRED, 'Confidentiality required'],
  [LdapRc.SASL_BIND_IN_PROGRESS, 'SASL bind in progress'],
  [LdapRc.NO_SUCH_ATTRIBUTE, 'No such attribute'],
  [LdapRc.UNDEFINED_TYPE, 'Undefined attribute type'],
  [LdapRc.INAPPROPRIATE_MATCHING, 'Inappropriate matching'],
  [LdapRc.CONSTRAINT_VIOLATION, 'Constraint violation'],
  [LdapRc.TYPE_OR_VALUE_EXISTS, 'Type or value exists'],
  [LdapRc.INVALID_SYNTAX, 'Invalid syntax'],
  [LdapRc.NO_SUCH_OBJECT, 'No such object'],
  [LdapRc.ALIAS_PROBLEM, 'Alias problem'],
  [LdapRc.INVALID_DN_SYNTAX, 'Invalid DN syntax'],
  [LdapRc.ALIAS_DEREF_PROBLEM, 'Alias dereferencing problem'],
  [LdapRc.INAPPROPRIATE_AUTH, 'Inappropriate authentication'],
  [LdapRc.INVALID_CREDENTIALS, 'Invalid credentials'],
  [LdapRc.INSUFFICIENT_ACCESS, 'Insufficient access'],
  [LdapRc.BUSY, 'Server is busy'],
  [LdapRc.UNAVAILABLE, 'Server is unavailable'],
  [LdapRc.UNWILLING_TO_PERFORM, 'Server is unwilling to perform'],
  [LdapRc.LOOP_DETECT, 'Loop detected'],
  [LdapRc.NAMING_VIOLATION, 'Naming violation'],
  [LdapRc.OBJECT_CLASS_VIOLATION, 'Object class violation'],
  [LdapRc.NOT_ALLOWED_ON_NONLEAF, 'Operation not allowed on non-leaf'],
  [LdapRc.NOT_ALLOWED_ON_RDN, 'Operation not allowed on RDN'],
  [LdapRc.ALREADY_EXISTS, 'Already exists'],
  [LdapRc.NO_OBJECT_CLASS_MODS, 'Cannot modify object class'],
  [LdapRc.AFFECTS_MULTIPLE_DSAS, 'Operation affects multiple DSAs'],
  [LdapRc.VLV_ERROR, 'Virtual List View error'],
  [LdapRc.OTHER, 'Other (e.g., implementation specific) error'],
  [LdapRc.PARTIAL_RESULTS, 'Partial results and referral received'],
  [LdapRc.IS_LEAF, 'Entry is a leaf'],
  [LdapRc.RESULTS_TOO_LARGE, 'Results too large'],
  [LdapRc.CANCELLED, 'Cancelled'],
  [LdapRc.NO_SUCH_OPERATION, 'No Operation to Cancel'],
  [LdapRc.TOO_LATE, 'Too Late to Cancel'],
  [LdapRc.CANNOT_CANCEL, 'Cannot Cancel'],
  [LdapRc.ASSERTION_FAILED, 'Assertion Failed'],
  [LdapRc.X_ASSERTION_FAILED, 'Assertion Failed (X)'],
  [LdapRc.PROXIED_AUTHORIZATION_DENIED, 'Proxied Authorization Denied'],
  [LdapRc.PROXIED_AUTHZ_FAILURE, 'Proxy Authorization Failure (X)'],
  [LdapRc.SYNC_REFRESH_REQUIRED, 'Content Sync Refresh Required'],
  [LdapRc.X_SYNC_REFRESH_REQUIRED, 'Content Sync Refresh Required (X)'],
  [LdapRc.X_NO_OPERATION, 'No Operation (X)'],
  [LdapRc.CUP_RESOURCES_EXHAUSTED, 'LCUP Resources Exhausted'],
  [LdapRc.CUP_SECURITY_VIOLATION, 'LCUP Security Violation'],
  [LdapRc.CUP_INVALID_DATA, 'LCUP Invalid Data'],
  [LdapRc.CUP_UNSUPPORTED_SCHEME, 'LCUP Unsupported Scheme'],
  [LdapRc.CUP_RELOAD_REQUIRED, 'LCUP Reload Required'],
  [LdapRc.TXN_SPECIFY_OKAY, 'TXN specify okay'],
  [LdapRc.TXN_ID_INVALID, 'TXN ID is invalid'],
  [LdapRc.SERVER_DOWN, "Can't contact LDAP server"],
  [LdapRc.LOCAL_ERROR, 'Local error'],
  [LdapRc.ENCODING_ERROR, 'Encoding error'],
  [LdapRc.DECODING_ERROR, 'Decoding error'],
  [LdapRc.TIMEOUT, 'Timed out'],
  [LdapRc.AUTH_UNKNOWN, 'Unknown authentication method'],
  [LdapRc.FILTER_ERROR, 'Bad search filter'],
  [LdapRc.USER_CANCELLED, 'User cancelled operation'],
  [LdapRc.PARAM_ERROR, 'Bad parameter to an ldap routine'],
  [LdapRc.NO_MEMORY, 'Out of memory'],
  [LdapRc.CONNECT_ERROR, 'Connect error'],
  [LdapRc.NOT_SUPPORTED, 'Not Supported'],
  [LdapRc.CONTROL_NOT_FOUND, 'Control not found'],
  [LdapRc.NO_RESULTS_RETURNED, 'No results returned'],
  [LdapRc.MORE_RESULTS_TO_RETURN, 'More results to return'],
  [LdapRc.CLIENT_LOOP, 'Client Loop'],
  [LdapRc.REFERRAL_LIMIT_EXCEEDED, 'Referral Limit Exceeded'],
  [LdapRc.X_CONNECTING, 'Connecting (X)'],
]);

export function ldapErr2String(code: number): string {
  const known = MESSAGES.get(code);
  if (known !== undefined) return known;
  if (code < 0) return 'Unknown API error';
  if (code >= 0x1000 && code <= 0x3fff) return 'Unknown (extension) error';
  if (code >= 0x4000 && code <= 0xffff) return 'Unknown (private extension) error';
  return 'Unknown error';
}
