import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

function buildCommands(): DebugCommandInput[] {
  return [
    { section: 'navigation & contexte', cmd: 'pwd' },
    'cd /',
    'pwd',
    'cd /etc',
    'pwd',
    'cd ..',
    'pwd',
    'cd /var/log',
    'pwd',
    'cd -',
    'pwd',
    'cd ~',
    'pwd',
    'cd',
    'pwd',
    'cd /root && pwd',
    'cd /tmp; pwd',
    'cd /chemin/inexistant_xyz',
    'pwd',
    'cd /etc/hostname',

    { section: 'listing — ls', cmd: 'ls' },
    'ls /',
    'ls -l',
    'ls -la',
    'ls -al /etc',
    'ls -lh /var/log',
    'ls -lha /',
    'ls -a',
    'ls -A',
    'ls -d */',
    'ls -ld /etc',
    'ls -R /etc',
    'ls -lt /var/log',
    'ls -ltr /var/log',
    'ls -lS /var/log',
    'ls -lr',
    'ls -i /etc',
    'ls -n /etc',
    'ls -F /',
    'ls -1 /etc',
    'ls --color=auto /',
    'ls /etc /var /usr',
    'ls /bin/ls',
    'ls -l /bin/ls',
    'ls /etc/*.conf',
    'ls /etc/passwd /etc/shadow /etc/group',
    'ls /repertoire_inexistant_xyz',
    'ls -Z /etc',
    'ls --zorglub',

    { section: 'arborescence & disque — tree/du/df', cmd: 'tree /etc' },
    'tree -L 1 /',
    'tree -d /var',
    'tree -a /root',
    'du /var/log',
    'du -h /var/log',
    'du -sh /var',
    'du -sh /etc',
    'du -a /etc | head',
    'du -h --max-depth=1 /',
    'du -c /var/log',
    'df',
    'df -h',
    'df -h /',
    'df -i',
    'df -T',
    'df -k',
    'du -sh /chemin/inexistant_xyz',
    'df /chemin/inexistant_xyz',

    { section: 'création de fichiers — touch/echo/redir', cmd: 'cd /tmp' },
    'touch fichier1.txt',
    'ls -l fichier1.txt',
    'touch fichier2.txt fichier3.txt fichier4.txt',
    'ls -l fichier*.txt',
    'echo "ligne unique" > simple.txt',
    'cat simple.txt',
    'echo "ligne ajoutee" >> simple.txt',
    'cat simple.txt',
    'printf "a\\nb\\nc\\n" > lettres.txt',
    'cat lettres.txt',
    'echo "via tee" | tee tee.txt',
    'cat tee.txt',
    'echo "append tee" | tee -a tee.txt',
    'cat tee.txt',
    'touch -t 202001010000 daté.txt',
    'ls -l daté.txt',
    'touch fichier1.txt',
    'stat fichier1.txt',
    'touch /repertoire/inexistant_xyz/fichier.txt',

    { section: 'répertoires — mkdir/rmdir', cmd: 'mkdir projet' },
    'ls -ld projet',
    'mkdir -p projet/src/lib/utils',
    'ls -R projet',
    'mkdir -p a/b/c d/e/f',
    'ls -R a d',
    'mkdir -m 700 securisé',
    'ls -ld securisé',
    'mkdir projet',
    'rmdir securisé',
    'ls -ld securisé',
    'rmdir projet/src/lib/utils',
    'ls -R projet',
    'rmdir -p a/b/c',
    'ls -R a',
    'rmdir projet',
    'mkdir',
    'rmdir /etc',

    { section: 'copie — cp', cmd: 'cd /tmp' },
    'cp simple.txt copie.txt',
    'cat copie.txt',
    'cp simple.txt lettres.txt copie_vers/',
    'mkdir copie_vers',
    'cp simple.txt lettres.txt copie_vers/',
    'ls copie_vers',
    'cp -r projet projet_backup',
    'ls -R projet_backup',
    'cp -p simple.txt preserve.txt',
    'ls -l preserve.txt simple.txt',
    'cp -v lettres.txt verbose.txt',
    'cp -i simple.txt copie.txt',
    'cp -n simple.txt copie.txt',
    'cp -a projet projet_archive',
    'cp fichier_inexistant_xyz cible.txt',
    'cp simple.txt',

    { section: 'déplacement & renommage — mv', cmd: 'mv copie.txt renomme.txt' },
    'ls -l renomme.txt copie.txt',
    'mkdir destination',
    'mv renomme.txt destination/',
    'ls destination',
    'mv fichier2.txt fichier3.txt destination/',
    'ls destination',
    'mv -v fichier4.txt deplace4.txt',
    'mv -i simple.txt tee.txt',
    'mv -n simple.txt tee.txt',
    'mv projet_backup projet_renomme',
    'ls -ld projet_renomme',
    'mv fichier_inexistant_xyz cible.txt',
    'mv destination',

    { section: 'suppression — rm', cmd: 'rm verbose.txt' },
    'ls verbose.txt',
    'rm -v preserve.txt',
    'rm -f fichier_inexistant_xyz',
    'rm -i lettres.txt',
    'rm -r destination',
    'ls -ld destination',
    'rm -rf projet_renomme projet_archive',
    'ls -ld projet_renomme',
    'rm *.txt',
    'ls *.txt',
    'rm -r projet',
    'rm',
    'rm -rf /',
    'rm /etc/passwd',

    { section: 'liens — ln', cmd: 'cd /tmp' },
    'echo "cible du lien" > cible_lien.txt',
    'ln cible_lien.txt lien_dur.txt',
    'ls -li cible_lien.txt lien_dur.txt',
    'cat lien_dur.txt',
    'ln -s cible_lien.txt lien_symbolique.txt',
    'ls -l lien_symbolique.txt',
    'cat lien_symbolique.txt',
    'ln -s /etc/passwd lien_passwd',
    'ls -l lien_passwd',
    'readlink lien_symbolique.txt',
    'readlink -f lien_symbolique.txt',
    'realpath lien_symbolique.txt',
    'ln -s cible_inexistante_xyz lien_casse',
    'ls -l lien_casse',
    'readlink lien_casse',
    'ln -sf /etc/hostname lien_passwd',
    'ls -l lien_passwd',
    'ln',
    'ln -s',

    { section: 'lecture — cat/head/tail/more', cmd: 'cat /etc/passwd' },
    'cat /etc/os-release',
    'cat -n /etc/passwd',
    'cat -A /etc/hostname',
    'cat -b /etc/passwd',
    'cat -s /etc/passwd',
    'cat /etc/passwd /etc/group',
    'head /etc/passwd',
    'head -n 3 /etc/passwd',
    'head -c 20 /etc/passwd',
    'tail /etc/passwd',
    'tail -n 5 /etc/passwd',
    'tail -c 30 /etc/passwd',
    'head -n 1 /etc/os-release',
    'tail -n 1 /etc/os-release',
    'cat /fichier/inexistant_xyz',
    'head /repertoire_inexistant_xyz',

    { section: 'métadonnées — stat/file/wc', cmd: 'stat /etc/passwd' },
    'stat /etc',
    'stat -c "%n %s %a %U:%G" /etc/passwd',
    'stat -c "%F" /etc',
    'stat -c "%F" /etc/passwd',
    'stat --format="%a %n" /etc/hostname',
    'stat -t /etc/passwd',
    'file /etc/passwd',
    'file /etc',
    'file /bin/ls',
    'file /etc/hostname',
    'wc /etc/passwd',
    'wc -l /etc/passwd',
    'wc -w /etc/passwd',
    'wc -c /etc/passwd',
    'wc -L /etc/passwd',
    'stat /fichier/inexistant_xyz',
    'file /fichier/inexistant_xyz',

    { section: 'recherche — find', cmd: 'find /etc -maxdepth 1' },
    'find /etc -maxdepth 1 -type f',
    'find /etc -maxdepth 1 -type d',
    'find /etc -name "*.conf"',
    'find /etc -maxdepth 2 -name "host*"',
    'find / -maxdepth 2 -name passwd',
    'find /var -type d -maxdepth 2',
    'find /etc -maxdepth 1 -type f -name "p*"',
    'find /tmp -maxdepth 1',
    'find /etc -maxdepth 1 -size +1k',
    'find /etc -maxdepth 1 -newer /etc/hostname',
    'find /etc -maxdepth 1 -perm 644',
    'find /etc -maxdepth 1 -user root',
    'find /etc -name "*.conf" -type f',
    'find /etc -maxdepth 1 -empty',
    'find /chemin_inexistant_xyz',
    'find /etc -truc',

    { section: 'localisation — which/whereis/locate/type', cmd: 'which ls' },
    'which cat grep ls',
    'which commande_inexistante_xyz',
    'whereis ls',
    'whereis bash',
    'whereis grep',
    'type ls',
    'type cd',
    'type -a echo',
    'command -v ls',
    'command -v cd',
    'locate passwd',
    'updatedb',
    'locate hostname',
    'which',
    'whereis',

    { section: 'permissions — chmod/chown/umask', cmd: 'cd /tmp' },
    'touch perm.txt',
    'ls -l perm.txt',
    'chmod 644 perm.txt',
    'ls -l perm.txt',
    'chmod 755 perm.txt',
    'ls -l perm.txt',
    'chmod u+x perm.txt',
    'ls -l perm.txt',
    'chmod g-w perm.txt',
    'ls -l perm.txt',
    'chmod o=r perm.txt',
    'ls -l perm.txt',
    'chmod a+x perm.txt',
    'ls -l perm.txt',
    'chmod 600 perm.txt',
    'stat -c "%a" perm.txt',
    'mkdir permdir',
    'chmod -R 700 permdir',
    'ls -ld permdir',
    'umask',
    'umask -S',
    'umask 022',
    'umask',
    'umask 077',
    'touch apres_umask.txt',
    'ls -l apres_umask.txt',
    'chmod 999 perm.txt',
    'chmod abc perm.txt',
    'chmod 644 fichier_inexistant_xyz',

    { section: 'propriété — chown/chgrp', cmd: 'chown root perm.txt' },
    'ls -l perm.txt',
    'chown root:root perm.txt',
    'ls -l perm.txt',
    'chgrp root perm.txt',
    'ls -l perm.txt',
    'chown -R root:root permdir',
    'ls -ld permdir',
    'chown utilisateur_inexistant_xyz perm.txt',
    'chgrp groupe_inexistant_xyz perm.txt',
    'chown root fichier_inexistant_xyz',

    { section: 'chemins — basename/dirname/realpath/mktemp', cmd: 'basename /usr/local/bin/ls' },
    'basename /usr/local/bin/ls .sh',
    'basename /etc/',
    'dirname /usr/local/bin/ls',
    'dirname /etc/passwd',
    'dirname fichier_relatif.txt',
    'realpath /etc/../etc/passwd',
    'realpath .',
    'realpath ..',
    'readlink -f /etc/passwd',
    'mktemp',
    'mktemp -d',
    'mktemp /tmp/debug.XXXXXX',
    'basename',
    'dirname',

    { section: 'montage & blocs — mount/lsblk', cmd: 'mount' },
    'mount | head',
    'lsblk',
    'lsblk -f',
    'lsblk -a',
    'df -h',
    'cat /proc/mounts | head',
    'cat /etc/fstab',
    'umount /chemin/inexistant_xyz',
    'mount /dev/inexistant_xyz /mnt',

    { section: 'redirections & pipes composés', cmd: 'ls /etc > /tmp/liste_etc.txt' },
    'wc -l /tmp/liste_etc.txt',
    'ls /var >> /tmp/liste_etc.txt',
    'cat /tmp/liste_etc.txt | head -5',
    'cat /etc/passwd | wc -l',
    'cat /etc/passwd | grep root',
    'find /etc -maxdepth 1 -type f | wc -l',
    'ls /etc | sort | head',
    'ls /etc 2> /tmp/err.txt; cat /tmp/err.txt',
    'cat < /etc/hostname',
    'echo "test $(hostname)"',
    'echo "il y a $(ls /etc | wc -l) entrées dans /etc"',
    'cat /tmp/liste_etc.txt | tail -3 > /tmp/fin.txt',
    'cat /tmp/fin.txt',

    { section: 'mal formées — fin de transcript', cmd: 'lss -la' },
    'cpp a b',
    'cat',
    'ls -',
    'find',
    'stat',
    'cd /tmp && echo "fin du transcript filesystem"',
  ];
}

describe('debug — Linux filesystem & file operations (PC + server)', () => {
  it('exercises filesystem & file operations from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-FS-DBG', 130, 130);
    await runAndDump(
      'linux-pc-filesystem-files',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-FS-DBG (linux-pc) — focus: système de fichiers & opérations fichiers',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-FS-DBG', 210, 210);
    await runAndDump(
      'linux-server-filesystem-files',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-FS-DBG (linux-server) — focus: système de fichiers & opérations fichiers',
      'linux',
    );
  }, 240_000);
});
