import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

function buildCommands(): DebugCommandInput[] {
  return [
    { section: 'préparation jeux de données', cmd: 'cd /tmp' },
    'printf "banane\\npomme\\ncerise\\npomme\\nfraise\\nbanane\\n" > fruits.txt',
    'cat fruits.txt',
    'printf "3\\n1\\n10\\n2\\n20\\n1\\n" > nombres.txt',
    'cat nombres.txt',
    'printf "alice:30:paris\\nbob:25:lyon\\ncarol:35:paris\\ndan:28:nice\\n" > gens.csv',
    'cat gens.csv',
    'printf "  espaces  avant et apres  \\nMAJUSCULE minuscule\\nUNE LIGNE\\n" > divers.txt',
    'cat divers.txt',
    'seq 1 20 > seq.txt',
    'cat seq.txt',

    { section: 'echo & printf', cmd: 'echo hello world' },
    'echo "guillemets doubles"',
    "echo 'guillemets simples'",
    'echo -n "sans newline"',
    'echo -e "tab\\tici\\nnouvelle ligne"',
    'echo $HOME',
    'echo $PATH',
    'echo $USER',
    'echo "user=$USER home=$HOME"',
    'echo ${HOSTNAME}',
    'printf "%s\\n" un deux trois',
    'printf "%d + %d = %d\\n" 2 3 5',
    'printf "%-10s|%10s|\\n" gauche droite',
    'printf "%05.2f\\n" 3.14159',
    'echo {a,b,c}',
    'echo {1..5}',
    'echo *.txt',

    { section: 'cat — options', cmd: 'cat fruits.txt' },
    'cat -n fruits.txt',
    'cat -b fruits.txt',
    'cat -A divers.txt',
    'cat -E fruits.txt',
    'cat -T divers.txt',
    'cat -s fruits.txt',
    'cat fruits.txt nombres.txt',
    'cat fruits.txt - < /dev/null',
    'tac fruits.txt',
    'cat fichier_inexistant_xyz',

    { section: 'grep — base', cmd: 'grep pomme fruits.txt' },
    'grep -n pomme fruits.txt',
    'grep -c pomme fruits.txt',
    'grep -i POMME fruits.txt',
    'grep -v pomme fruits.txt',
    'grep -w pomme fruits.txt',
    'grep -o pomme fruits.txt',
    'grep -l pomme fruits.txt nombres.txt',
    'grep -L pomme fruits.txt nombres.txt',
    'grep -r root /etc/hostname',
    'grep --color=auto root /etc/passwd',
    'grep -A1 bob gens.csv',
    'grep -B1 carol gens.csv',
    'grep -C1 bob gens.csv',
    'grep "" fruits.txt',
    'grep motif_absent_xyz fruits.txt',

    { section: 'grep — expressions régulières', cmd: 'grep "^p" fruits.txt' },
    'grep "e$" fruits.txt',
    'grep "^banane$" fruits.txt',
    'grep "an" fruits.txt',
    'grep "[bc]" fruits.txt',
    'grep "[0-9]" nombres.txt',
    'grep -E "pomme|cerise" fruits.txt',
    'grep -E "^[a-z]+:[0-9]+" gens.csv',
    'grep -E "paris$" gens.csv',
    'egrep "(pomme|fraise)" fruits.txt',
    'fgrep "pomme" fruits.txt',
    'grep -P "\\d+" nombres.txt',
    'grep -e pomme -e cerise fruits.txt',
    'grep root /etc/passwd /etc/group',
    'grep -rn paris gens.csv',

    { section: 'head & tail', cmd: 'head fruits.txt' },
    'head -n 2 fruits.txt',
    'head -n -2 seq.txt',
    'head -c 10 fruits.txt',
    'tail fruits.txt',
    'tail -n 2 fruits.txt',
    'tail -n +3 seq.txt',
    'tail -c 12 fruits.txt',
    'head -n 1 gens.csv',
    'tail -n 1 gens.csv',
    'head seq.txt nombres.txt',
    'tail -q seq.txt nombres.txt',

    { section: 'wc — comptage', cmd: 'wc fruits.txt' },
    'wc -l fruits.txt',
    'wc -w gens.csv',
    'wc -c fruits.txt',
    'wc -m divers.txt',
    'wc -L divers.txt',
    'wc -l fruits.txt nombres.txt seq.txt',
    'cat fruits.txt | wc -l',
    'ls /etc | wc -l',

    { section: 'sort — tri', cmd: 'sort fruits.txt' },
    'sort -r fruits.txt',
    'sort -u fruits.txt',
    'sort -n nombres.txt',
    'sort -rn nombres.txt',
    'sort -nu nombres.txt',
    'sort -k1 gens.csv',
    'sort -t: -k2 -n gens.csv',
    'sort -t: -k3 gens.csv',
    'sort -f divers.txt',
    'sort -c nombres.txt',
    'sort -b divers.txt',
    'sort fruits.txt | uniq',
    'sort nombres.txt | head -3',

    { section: 'uniq — dédoublonnage', cmd: 'sort fruits.txt | uniq' },
    'sort fruits.txt | uniq -c',
    'sort fruits.txt | uniq -d',
    'sort fruits.txt | uniq -u',
    'sort -n nombres.txt | uniq',
    'sort -n nombres.txt | uniq -c',
    'uniq fruits.txt',
    'sort fruits.txt | uniq -c | sort -rn',

    { section: 'cut — extraction de colonnes', cmd: 'cut -d: -f1 gens.csv' },
    'cut -d: -f2 gens.csv',
    'cut -d: -f1,3 gens.csv',
    'cut -d: -f2- gens.csv',
    'cut -c1-3 fruits.txt',
    'cut -c1 fruits.txt',
    'cut -d: -f1 /etc/passwd',
    'cut -d: -f1,7 /etc/passwd | head',
    'cut -f1 gens.csv',
    'cut -d, -f1 gens.csv',

    { section: 'tr — translittération', cmd: "echo 'hello' | tr a-z A-Z" },
    "echo 'HELLO' | tr A-Z a-z",
    "echo 'a-b-c' | tr '-' '_'",
    "echo 'aaa bbb' | tr -s 'a'",
    "echo 'hello123world' | tr -d '0-9'",
    "echo 'hello' | tr -c 'a-z' '*'",
    "echo 'abcdef' | tr 'abc' 'xyz'",
    'cat fruits.txt | tr a-z A-Z',
    "echo 'tab\\tici' | tr '\\t' ' '",
    "echo 'compte' | tr -cd 'a-z'",

    { section: 'sed — édition de flux', cmd: "sed 's/pomme/POMME/' fruits.txt" },
    "sed 's/pomme/POMME/g' fruits.txt",
    "sed -n '2p' fruits.txt",
    "sed -n '1,3p' fruits.txt",
    "sed '2d' fruits.txt",
    "sed '1,2d' fruits.txt",
    "sed 's/^/>> /' fruits.txt",
    "sed 's/$/ <</' fruits.txt",
    "sed -e 's/pomme/P/' -e 's/banane/B/' fruits.txt",
    "sed 's/[aeiou]//g' fruits.txt",
    "sed -n '$p' fruits.txt",
    "sed '/pomme/d' fruits.txt",
    "sed 's/:/ - /g' gens.csv",
    "echo 'hello world' | sed 's/o/0/g'",
    "sed -i 's/cerise/CERISE/' fruits.txt",
    'cat fruits.txt',

    { section: 'awk — traitement par champs', cmd: "awk '{print $1}' gens.csv" },
    "awk -F: '{print $1}' gens.csv",
    "awk -F: '{print $1, $3}' gens.csv",
    "awk -F: '{print $2}' gens.csv",
    "awk -F: '$2 > 28 {print $1}' gens.csv",
    "awk -F: '{print NR, $0}' gens.csv",
    "awk -F: '{print NF}' gens.csv",
    "awk 'END {print NR}' fruits.txt",
    "awk '{sum += $1} END {print sum}' nombres.txt",
    "awk -F: '{print toupper($1)}' gens.csv",
    "awk -F: '/paris/ {print $1}' gens.csv",
    "awk 'NR==2' fruits.txt",
    "awk 'length > 5' fruits.txt",
    "awk -F: 'BEGIN{print \"nom age\"} {print $1, $2}' gens.csv",
    "awk -F: '{ages+=$2} END{print ages/NR}' gens.csv",
    "cat /etc/passwd | awk -F: '{print $1}' | head",

    { section: 'paste / join / rev / nl', cmd: 'paste fruits.txt nombres.txt' },
    'paste -d, fruits.txt nombres.txt',
    'paste -s fruits.txt',
    'rev fruits.txt',
    "echo 'abcdef' | rev",
    'nl fruits.txt',
    'nl -ba fruits.txt',
    'fold -w 5 fruits.txt',
    'column -t gens.csv',
    'column -s: -t gens.csv',

    { section: 'pipelines composés', cmd: 'cat /etc/passwd | cut -d: -f1 | sort | head' },
    'cat /etc/passwd | wc -l',
    'ls /etc | grep conf | sort | head',
    'sort fruits.txt | uniq -c | sort -rn | head -3',
    'cat gens.csv | awk -F: \'{print $3}\' | sort | uniq -c',
    'cat nombres.txt | sort -n | tail -1',
    'cat nombres.txt | sort -n | head -1',
    'grep paris gens.csv | cut -d: -f1 | tr a-z A-Z',
    'cat /etc/passwd | grep -c bash',
    'seq 1 100 | awk \'{s+=$1} END{print s}\'',
    'seq 1 10 | paste -sd+ | bc',
    'echo "1 2 3 4 5" | tr " " "\\n" | sort -rn',
    'cat fruits.txt | sort | uniq | wc -l',

    { section: 'redirections & substitution', cmd: 'echo "sortie" > /tmp/out.txt' },
    'cat /tmp/out.txt',
    'echo "ajout" >> /tmp/out.txt',
    'cat /tmp/out.txt',
    'wc -l < /tmp/out.txt',
    'grep root /etc/passwd > /tmp/root.txt 2>&1',
    'cat /tmp/root.txt',
    'ls /inexistant_xyz 2> /tmp/erreur.txt; cat /tmp/erreur.txt',
    'echo "il y a $(wc -l < /etc/passwd) utilisateurs"',
    'echo "date: $(date +%Y)"',
    'cat <<< "here string en entrée"',
    'sort <<< "c\\nb\\na"',
    'NOM=debug; echo "valeur=$NOM"',
    'export VERBE=tester; echo $VERBE',

    { section: 'comparaison — diff/comm/cmp', cmd: 'cp fruits.txt fruits2.txt' },
    "sed -i 's/fraise/mangue/' fruits2.txt",
    'diff fruits.txt fruits2.txt',
    'diff -u fruits.txt fruits2.txt',
    'diff -y fruits.txt fruits2.txt',
    'diff -q fruits.txt fruits2.txt',
    'diff fruits.txt fruits.txt',
    'sort fruits.txt > a.sorted',
    'sort fruits2.txt > b.sorted',
    'comm a.sorted b.sorted',
    'comm -12 a.sorted b.sorted',
    'comm -3 a.sorted b.sorted',
    'cmp fruits.txt fruits2.txt',
    'cmp fruits.txt fruits.txt',
    'diff fichier_inexistant_xyz fruits.txt',

    { section: 'découpe & assemblage — split/csplit', cmd: 'split -l 2 seq.txt morceau_' },
    'ls morceau_*',
    'cat morceau_aa',
    'split -n 3 seq.txt part_',
    'ls part_*',
    'cat part_* | wc -l',
    'split -b 10 fruits.txt octets_',
    'ls octets_*',

    { section: 'expansion & espaces — expand/fmt/pr', cmd: 'expand -t 4 divers.txt' },
    'unexpand divers.txt',
    'fmt -w 20 fruits.txt',
    'fmt -s fruits.txt',
    'pr -t fruits.txt',
    'pr -n fruits.txt',
    'fold -w 3 fruits.txt',
    'fold -s -w 10 divers.txt',

    { section: 'xargs & boucles', cmd: 'echo "a b c" | xargs' },
    'echo "fichier1 fichier2 fichier3" | xargs -n1',
    'ls /etc/*.conf | xargs -n1 basename',
    'echo "1 2 3" | xargs -I{} echo "valeur={}"',
    'seq 1 5 | xargs echo',
    'find /etc -maxdepth 1 -name "*.conf" | xargs wc -l',
    'echo "pomme banane" | xargs -d" " -n1 echo',
    'for f in fruits nombres seq; do echo "=> $f"; done',
    'for i in 1 2 3; do echo "iter $i"; done',
    'i=0; while [ $i -lt 3 ]; do echo "while $i"; i=$((i+1)); done',

    { section: 'calcul — bc/expr/let/$(())', cmd: 'echo "2 + 3" | bc' },
    'echo "10 / 3" | bc',
    'echo "scale=2; 10/3" | bc',
    'echo "2^10" | bc',
    'expr 5 + 3',
    'expr 10 \\* 4',
    'expr 17 % 5',
    'expr length "bonjour"',
    'echo $((7 * 6))',
    'echo $((100 % 7))',
    'echo $((2 ** 8))',
    'let x=5+5; echo $x',
    'seq 1 10 | paste -sd+ - | bc',

    { section: 'hachage & encodage — sums/base64/md5', cmd: 'md5sum fruits.txt' },
    'sha1sum fruits.txt',
    'sha256sum fruits.txt',
    'md5sum fruits.txt nombres.txt',
    "echo -n 'hello' | md5sum",
    "echo 'données' | base64",
    "echo 'ZG9ubsOpZXMK' | base64 -d",
    'cksum fruits.txt',

    { section: 'tee multi-cibles & /dev', cmd: 'echo "diffusion" | tee /tmp/t1.txt /tmp/t2.txt' },
    'cat /tmp/t1.txt /tmp/t2.txt',
    'cat fruits.txt | tee /tmp/copie_pipe.txt | wc -l',
    'echo "vers null" > /dev/null',
    'cat /dev/null',
    'head -c 5 /dev/zero | wc -c',
    'echo "stdout"; echo "stderr" >&2',

    { section: 'analyse fichiers système', cmd: 'cut -d: -f1 /etc/passwd | sort | head' },
    'cut -d: -f3 /etc/passwd | sort -n | tail -5',
    'grep -c bash /etc/passwd',
    'grep "/bin/bash" /etc/passwd | cut -d: -f1',
    'awk -F: \'$3 >= 1000 {print $1}\' /etc/passwd',
    'awk -F: \'$3 == 0 {print $1}\' /etc/passwd',
    'cut -d: -f1 /etc/group | sort | head',
    'wc -l /etc/passwd /etc/group',
    'grep -v "^#" /etc/hostname',
    'sort -t: -k3 -n /etc/passwd | head',
    'awk -F: \'{print $7}\' /etc/passwd | sort | uniq -c',
    'cat /etc/os-release | grep -E "^NAME|^VERSION"',
    'cat /etc/os-release | cut -d= -f1',
    'grep -i ubuntu /etc/os-release',
    'cat /proc/cpuinfo | grep -c processor',
    'cat /proc/meminfo | head -3',
    'cat /proc/meminfo | awk \'/MemTotal/ {print $2, $3}\'',
    'free | awk \'/Mem/ {print $2}\'',
    'cat /etc/passwd | sort | uniq | wc -l',
    'cut -d: -f6 /etc/passwd | sort | head',
    'cut -d: -f1,3,6 /etc/passwd | head',
    'getent passwd | head',
    'grep root /etc/passwd | awk -F: \'{print "uid="$3" home="$6}\'',

    { section: 'mal formées — fin de transcript', cmd: 'grepp pomme fruits.txt' },
    'grep',
    "sed 's/incomplet",
    "awk '{print",
    'cut fruits.txt',
    'sort -z -k',
    'tr a',
    'cat | | wc',
    'echo "fin du transcript text & pipes"',
  ];
}

describe('debug — Linux text processing & pipes (PC + server)', () => {
  it('exercises text processing, filters and pipelines from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-TXT-DBG', 140, 140);
    await runAndDump(
      'linux-pc-text-pipes',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-TXT-DBG (linux-pc) — focus: traitement de texte, filtres & pipelines',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-TXT-DBG', 220, 220);
    await runAndDump(
      'linux-server-text-pipes',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-TXT-DBG (linux-server) — focus: traitement de texte, filtres & pipelines',
      'linux',
    );
  }, 240_000);
});
