/**
 * Debug run — Linux PROCESSES & SERVICES on a PC and a server.
 *
 * Replays a large, structured command list through the in-browser bash
 * terminal of a `LinuxPC` and a `LinuxServer`. The intent is purely
 * diagnostic: no assumptions are made about which commands are
 * implemented — the transcript records success, error message, or JS
 * exception verbatim so a human can diff it and decide what to fix.
 *
 * Coverage strategy:
 *   • inventory commands (ps / pstree / pgrep / top / /proc)
 *   • the SET-then-SHOW pattern: mutate state with one command, read it
 *     back with another (nice/renice, ulimit, sysctl, systemctl
 *     enable/disable, service start/stop, crontab)
 *   • composed scenarios (set → verify → restore)
 *   • deliberately MALFORMED commands and error-path inputs
 *
 * Transcripts →
 *   debug-output/linux/linux-pc-services-processes_results_debug.txt
 *   debug-output/linux/linux-server-services-processes_results_debug.txt
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

/**
 * The shared command script. Reused for both the PC and the server so
 * the two transcripts can be diffed against each other to spot
 * device-class differences in process/service behaviour.
 */
function buildCommands(): DebugCommandInput[] {
  return [
    // ── 1. environnement & identité ───────────────────────────────
    { section: 'environnement & identité', cmd: 'whoami' },
    'id',
    'id -u',
    'id -un',
    'hostname',
    'hostnamectl',
    'uname -a',
    'uname -r',
    'uname -s -n -m',
    'cat /etc/os-release',
    'cat /etc/hostname',
    'echo $SHELL',
    'echo $$',
    'echo "shell pid=$$ ppid=$PPID"',
    'tty',
    'pwd',
    'date',
    'date -u',
    'uptime',
    'uptime -p',
    'runlevel',
    'who',
    'w',

    // ── 2. inventaire des processus — ps ──────────────────────────
    { section: 'inventaire ps', cmd: 'ps' },
    'ps aux',
    'ps -ef',
    'ps -e',
    'ps -A',
    'ps -el',
    'ps -ely',
    'ps -f',
    'ps -fl',
    'ps ax',
    'ps axu',
    'ps -e f',
    'ps --forest',
    'ps -ejH',
    'ps axjf',
    'ps -p 1',
    'ps -p 1,2',
    'ps -p $$',
    'ps --pid 1',
    'ps -C bash',
    'ps -C systemd',
    'ps -u root',
    'ps -U root',
    'ps --ppid 1',
    'ps -o pid,ppid,user,stat,pcpu,pmem,comm',
    'ps -o pid=,comm=',
    'ps -eo pid,ni,pri,comm',
    'ps -eo pid,tty,time,cmd',
    'ps axo pid,stat,euser,cmd --sort=-pcpu',
    'ps aux --sort=-%mem',
    'ps aux --sort=-%cpu',
    'ps -e --sort=start_time',
    'ps -e --sort=-rss',
    'ps h -e -o pid',
    'ps -e --no-headers',
    'ps -L -p 1',
    'ps -T -p 1',
    'ps -e -o pid,nlwp,comm',
    'ps --version',
    'ps w',
    'ps ww aux',
    'ps -e | wc -l',
    'ps aux | grep bash | grep -v grep',
    // malformés / cas d'erreur
    'ps -Z',
    'ps --zorglub',
    'ps -p abc',
    'ps -p 999999',
    'ps -C processus_inexistant_xyz',

    // ── 3. arbre des processus — pstree ───────────────────────────
    { section: 'pstree', cmd: 'pstree' },
    'pstree -p',
    'pstree -a',
    'pstree -n',
    'pstree -A',
    'pstree -p 1',
    'pstree -s $$',
    'pstree -u',
    'pstree -h',
    'pstree root',
    'pstree -p abc',
    'pstree 999999',

    // ── 4. recherche — pgrep / pidof ──────────────────────────────
    { section: 'pgrep / pidof', cmd: 'pidof systemd' },
    'pidof bash',
    'pidof init',
    'pidof -s bash',
    'pgrep bash',
    'pgrep -l bash',
    'pgrep -a bash',
    'pgrep -f bash',
    'pgrep -u root',
    'pgrep -u root -l',
    'pgrep -c bash',
    'pgrep -n bash',
    'pgrep -o bash',
    'pgrep -x bash',
    'pgrep -d, bash',
    'pgrep -x ba',
    'pgrep processus_inexistant_xyz',
    'pidof processus_inexistant_xyz',
    'pgrep',
    'pgrep -Z bash',

    // ── 5. temps réel — top / vmstat / free ───────────────────────
    { section: 'top / vmstat / free', cmd: 'top -b -n 1' },
    'top -b -n 1 | head -20',
    'top -b -n 1 -o %CPU',
    'top -b -n 1 -o %MEM',
    'top -b -n 1 -p 1',
    'top -b -n 1 -u root',
    'top -H -b -n 1',
    'vmstat',
    'vmstat 1 3',
    'vmstat -s',
    'free',
    'free -h',
    'free -m',
    'free -g',
    'free -k',
    'free -b',
    'free -t',
    'free -w',
    'mpstat',
    'mpstat -P ALL',
    'iostat',
    'iostat -x',
    'top -z',
    'top -b -n abc',

    // ── 6. /proc — introspection ──────────────────────────────────
    { section: '/proc', cmd: 'ls /proc' },
    'cat /proc/cpuinfo',
    'cat /proc/meminfo',
    'cat /proc/loadavg',
    'cat /proc/uptime',
    'cat /proc/version',
    'cat /proc/stat | head',
    'cat /proc/1/status',
    'cat /proc/1/cmdline',
    'cat /proc/1/comm',
    'cat /proc/self/status',
    'cat /proc/self/cmdline',
    'cat /proc/self/limits',
    'ls /proc/1',
    'ls /proc/1/fd',
    'cat /proc/sys/kernel/hostname',
    'cat /proc/sys/kernel/ostype',
    'cat /proc/sys/kernel/pid_max',
    'cat /proc/sys/fs/file-max',
    'cat /proc/999999/status',
    'cat /proc/inexistant',

    // ── 7. priorités CPU — SET puis SHOW ──────────────────────────
    { section: 'priorités (nice/renice/chrt/ionice)', cmd: 'nice' },
    'nice -n 10 sleep 30 &',
    'ps -o pid,ni,comm -C sleep',
    'nice -n 19 sleep 30 &',
    'ps -o pid,ni,comm -C sleep',
    'nice --adjustment=5 sleep 30 &',
    'ps -o pid,ni,comm -C sleep',
    'renice 5 -p $$',
    'ps -o pid,ni,comm -p $$',
    'renice -n 8 -p $$',
    'ps -o pid,ni,comm -p $$',
    'renice 0 -p $$',
    'ps -o pid,ni,comm -p $$',
    'renice -10 -p $$',
    'ps -o pid,ni,comm -p $$',
    'renice 5 -u root',
    'chrt -p $$',
    'chrt -m',
    'chrt -p 1',
    'ionice -p $$',
    'ionice -c 2 -n 0 -p $$',
    'ionice -p $$',
    'taskset -p $$',
    'taskset -pc $$',
    'nice -n abc sleep 1',
    'renice abc -p $$',
    'renice 5 -p 999999',
    'renice 5',
    'chrt -p abc',
    'ionice -c 9 -p $$',

    // ── 8. limites ressources — SET puis SHOW (ulimit) ────────────
    { section: 'ulimit', cmd: 'ulimit -a' },
    'ulimit -n',
    'ulimit -u',
    'ulimit -f',
    'ulimit -s',
    'ulimit -c',
    'ulimit -t',
    'ulimit -v',
    'ulimit -l',
    'ulimit -Hn',
    'ulimit -Sn',
    'ulimit -n 4096',
    'ulimit -n',
    'ulimit -S -n 2048',
    'ulimit -S -n',
    'ulimit -c unlimited',
    'ulimit -c',
    'ulimit -f 1000000',
    'ulimit -f',
    'ulimit -a',
    'ulimit -n abc',
    'ulimit -x',
    'ulimit -n -5',

    // ── 9. paramètres noyau — SET puis SHOW (sysctl) ──────────────
    { section: 'sysctl', cmd: 'sysctl -a | head -20' },
    'sysctl kernel.hostname',
    'sysctl kernel.pid_max',
    'sysctl kernel.threads-max',
    'sysctl fs.file-max',
    'sysctl vm.swappiness',
    'sysctl net.ipv4.ip_forward',
    'sysctl -w vm.swappiness=30',
    'sysctl vm.swappiness',
    'sysctl -w net.ipv4.ip_forward=1',
    'sysctl net.ipv4.ip_forward',
    'sysctl -w kernel.pid_max=99999',
    'sysctl kernel.pid_max',
    'cat /proc/sys/kernel/pid_max',
    'sysctl -w net.ipv4.ip_forward=0',
    'sysctl net.ipv4.ip_forward',
    'sysctl -p',
    'sysctl --system',
    'sysctl kernel.cle_inexistante',
    'sysctl -w kernel.cle_inexistante=1',
    'sysctl -w vm.swappiness',
    'sysctl -w vm.swappiness=abc',
    'sysctl',

    // ── 10. contrôle de jobs ──────────────────────────────────────
    { section: 'jobs / bg / fg / nohup', cmd: 'sleep 60 &' },
    'jobs',
    'jobs -l',
    'jobs -p',
    'sleep 90 &',
    'jobs',
    'sleep 120 &',
    'jobs -l',
    'kill %1',
    'jobs',
    'fg %2',
    'bg %2',
    'disown %2',
    'jobs',
    'nohup sleep 200 &',
    'jobs',
    'ps -C sleep -o pid,ppid,stat,comm',
    'wait',
    'fg %99',
    'bg %99',
    'kill %99',
    'disown %99',
    'fg',
    'jobs %abc',

    // ── 11. signaux & terminaison ─────────────────────────────────
    { section: 'kill / killall / pkill / timeout', cmd: 'sleep 300 &' },
    'ps -C sleep -o pid,comm',
    'kill -l',
    'kill -l 9',
    'kill -l SIGTERM',
    'kill -0 $$',
    'kill -SIGTERM %1',
    'sleep 300 &',
    'kill -15 $!',
    'sleep 300 &',
    'kill -9 $!',
    'sleep 300 &',
    'kill -TERM $!',
    'sleep 300 &',
    'pkill sleep',
    'pgrep sleep',
    'sleep 300 &',
    'killall sleep',
    'sleep 300 &',
    'killall -9 sleep',
    'killall -v sleep',
    'pkill -f "sleep 300"',
    'pkill -u root sleep',
    'timeout 1 sleep 5',
    'timeout 2 sleep 1',
    'timeout --signal=KILL 1 sleep 5',
    'timeout -s TERM 1 sleep 5',
    'kill',
    'kill abc',
    'kill -99 1',
    'kill -SIGFOO 1',
    'kill 999999',
    'kill -9 999999',
    'killall',
    'killall processus_inexistant_xyz',
    'pkill',
    'pkill processus_inexistant_xyz',
    'kill -9 1',
    'kill 1',

    // ── 12. systemd — état & inventaire ───────────────────────────
    { section: 'systemctl inventaire', cmd: 'systemctl' },
    'systemctl --version',
    'systemctl status',
    'systemctl is-system-running',
    'systemctl list-units',
    'systemctl list-units --type=service',
    'systemctl list-units --type=service --state=running',
    'systemctl list-units --type=service --all',
    'systemctl list-units --state=failed',
    'systemctl list-unit-files',
    'systemctl list-unit-files --type=service',
    'systemctl list-unit-files --state=enabled',
    'systemctl --failed',
    'systemctl --type=service',
    'systemctl get-default',
    'systemctl status cron',
    'systemctl status ssh',
    'systemctl status sshd',
    'systemctl status systemd-journald',
    'systemctl status systemd-logind',
    'systemctl status dbus',
    'systemctl cat cron',
    'systemctl show cron',
    'systemctl show -p MainPID cron',
    'systemctl show -p ActiveState,SubState cron',
    'systemctl list-dependencies cron',
    'systemctl list-sockets',
    'systemctl list-timers',
    'systemctl status service_inexistant_xyz',
    'systemctl statuss cron',
    'systemctl --type=truc',
    'systemctl show -p CleInconnue cron',

    // ── 13. systemd — SET (enable/disable/mask) puis SHOW ─────────
    { section: 'enable/disable/mask', cmd: 'systemctl is-enabled cron' },
    'systemctl is-active cron',
    'systemctl is-failed cron',
    'systemctl disable cron',
    'systemctl is-enabled cron',
    'systemctl enable cron',
    'systemctl is-enabled cron',
    'systemctl enable --now cron',
    'systemctl is-active cron',
    'systemctl mask cron',
    'systemctl is-enabled cron',
    'systemctl status cron',
    'systemctl unmask cron',
    'systemctl is-enabled cron',
    'systemctl preset cron',
    'systemctl enable ssh',
    'systemctl is-enabled ssh',
    'systemctl disable --now ssh',
    'systemctl is-active ssh',
    'systemctl enable --now ssh',
    'systemctl enable service_inexistant_xyz',
    'systemctl disable service_inexistant_xyz',
    'systemctl is-enabled service_inexistant_xyz',
    'systemctl mask',
    'systemctl enable',

    // ── 14. systemd — start/stop/restart + journalctl ─────────────
    { section: 'start/stop/restart + journalctl', cmd: 'systemctl start cron' },
    'systemctl is-active cron',
    'systemctl status cron',
    'systemctl stop cron',
    'systemctl is-active cron',
    'systemctl start cron',
    'systemctl restart cron',
    'systemctl is-active cron',
    'systemctl reload cron',
    'systemctl reload-or-restart cron',
    'systemctl try-restart cron',
    'systemctl kill cron',
    'systemctl kill -s SIGTERM cron',
    'systemctl reset-failed cron',
    'systemctl daemon-reload',
    'journalctl',
    'journalctl -n 20',
    'journalctl -n 50 --no-pager',
    'journalctl -u cron',
    'journalctl -u cron -n 20',
    'journalctl -u cron --since "today"',
    'journalctl -p err',
    'journalctl -p err -n 10',
    'journalctl -k',
    'journalctl -b',
    'journalctl --disk-usage',
    'journalctl --list-boots',
    'systemctl start service_inexistant_xyz',
    'systemctl stop service_inexistant_xyz',
    'systemctl restart service_inexistant_xyz',
    'journalctl -u service_inexistant_xyz',
    'journalctl -p truc',
    'systemctl start',

    // ── 15. systemd — créer une unité, daemon-reload, vérifier ────
    { section: 'créer une unité systemd', cmd: 'mkdir -p /etc/systemd/system' },
    'printf "[Unit]\\nDescription=Service demo debug\\nAfter=network.target\\n\\n[Service]\\nType=simple\\nExecStart=/bin/sleep 3600\\nRestart=on-failure\\n\\n[Install]\\nWantedBy=multi-user.target\\n" > /etc/systemd/system/debugdemo.service',
    'cat /etc/systemd/system/debugdemo.service',
    'ls -l /etc/systemd/system/',
    'systemctl daemon-reload',
    'systemctl cat debugdemo',
    'systemctl status debugdemo',
    'systemctl enable debugdemo',
    'systemctl is-enabled debugdemo',
    'systemctl start debugdemo',
    'systemctl is-active debugdemo',
    'systemctl show -p ExecStart debugdemo',
    'systemctl show -p Description debugdemo',
    'systemctl restart debugdemo',
    'systemctl stop debugdemo',
    'systemctl is-active debugdemo',
    'systemctl disable debugdemo',
    'systemctl is-enabled debugdemo',
    'rm /etc/systemd/system/debugdemo.service',
    'systemctl daemon-reload',
    'systemctl status debugdemo',

    // ── 16. service / SysV / runlevels ────────────────────────────
    { section: 'service / SysV', cmd: 'service --status-all' },
    'service cron status',
    'service cron stop',
    'service cron status',
    'service cron start',
    'service cron restart',
    'service cron reload',
    'runlevel',
    'who -r',
    'systemctl get-default',
    'systemctl list-units --type=target',
    'service service_inexistant_xyz status',
    'service cron truc',
    'service',
    'service cron',

    // ── 17. cron / at — SET puis SHOW ─────────────────────────────
    { section: 'cron / at', cmd: 'crontab -l' },
    'crontab -l -u root',
    'echo "*/5 * * * * /usr/bin/true" | crontab -',
    'crontab -l',
    'crontab -r',
    'crontab -l',
    'at -l',
    'atq',
    'echo "echo hello" | at now + 5 minutes',
    'atq',
    'ls /etc/cron.d',
    'ls /etc/cron.daily',
    'cat /etc/crontab',
    'crontab -l -u utilisateur_inexistant_xyz',
    'crontab -z',
    'atq -x',

    // ── 18. lsof / fuser / pidstat ────────────────────────────────
    { section: 'lsof / fuser', cmd: 'lsof' },
    'lsof -p 1',
    'lsof -p $$',
    'lsof -u root',
    'lsof -i',
    'lsof -i :22',
    'lsof /var/log',
    'lsof -c bash',
    'fuser /var/log',
    'fuser -v /var/log',
    'pidstat',
    'pidstat 1 2',
    'pidstat -p 1',
    'pmap 1',
    'pmap -x $$',
    'lsof -p 999999',
    'fuser /chemin/inexistant_xyz',
    'pmap 999999',
    'pidstat -p abc',

    // ── 19. scénarios composés : set → vérifier → restaurer ───────
    { section: 'scénario A — priorité job de fond', cmd: 'sleep 400 &' },
    'echo "PID cible: $!"',
    'ps -o pid,ni,comm -p $!',
    'renice 15 -p $!',
    'ps -o pid,ni,comm -p $!',
    'renice 0 -p $!',
    'ps -o pid,ni,comm -p $!',
    'kill $!',
    'ps -C sleep -o pid,comm',
    { section: 'scénario B — sysctl set/show/restore', cmd: 'sysctl vm.swappiness' },
    'sysctl -w vm.swappiness=60',
    'sysctl vm.swappiness',
    'sysctl -w vm.swappiness=10',
    'sysctl vm.swappiness',
    { section: 'scénario C — cycle service', cmd: 'systemctl is-active cron' },
    'systemctl stop cron',
    'systemctl is-active cron',
    'systemctl start cron',
    'systemctl is-active cron',
    'systemctl restart cron',
    'systemctl status cron',
    { section: 'scénario D — enable persistance', cmd: 'systemctl disable cron' },
    'systemctl is-enabled cron',
    'systemctl enable cron',
    'systemctl is-enabled cron',
    { section: 'scénario E — pipeline analyse', cmd: 'ps -eo pid,pcpu,comm --sort=-pcpu | head -5' },
    'ps -eo pid,pmem,comm --sort=-pmem | head -5',
    'ps -e | wc -l',
    'systemctl list-units --type=service --state=running | wc -l',

    // ── 20. commandes mal formées & messages d'erreur ─────────────
    { section: 'mal formées — command not found', cmd: 'pss aux' },
    'systemtctl status cron',
    'killl 1',
    'nicee -n 5 sleep 1',
    'reniec 5 -p 1',
    'jobss',
    { section: 'mal formées — options/opérandes invalides', cmd: 'ps --sort=' },
    'ps -o',
    'ps -p',
    'kill -s',
    'kill --signal',
    'renice',
    'renice -p',
    'nice -n',
    'chrt',
    'ionice -c',
    'taskset',
    'top -p',
    'free -X',
    'vmstat -Q',
    'sysctl -w',
    'systemctl enable --now',
    'systemctl --type',
    'journalctl -u',
    'crontab',
    'ulimit -',
    { section: 'mal formées — argument numérique attendu', cmd: 'sleep abc' },
    'timeout abc sleep 1',
    'timeout 1',
    'kill -- -1abc',
    'renice ++5 -p 1',
    { section: 'mal formées — syntaxe shell invalide', cmd: 'kill 1 2 3 4 5 6 7 8 9 abc' },
    'ps aux | | head',
    'systemctl status cron ; ; systemctl is-active cron',
    'echo "fin du transcript"',
  ];
}

describe('debug — Linux processes & services (PC + server)', () => {
  it('exercises processes & services from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-SP-DBG', 120, 120);
    await runAndDump(
      'linux-pc-services-processes',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-SP-DBG (linux-pc) — focus: processus & services',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-SP-DBG', 200, 200);
    await runAndDump(
      'linux-server-services-processes',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-SP-DBG (linux-server) — focus: processus & services',
      'linux',
    );
  }, 240_000);
});
