import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

function buildCommands(): DebugCommandInput[] {
  return [
    { section: 'interfaces — ip link', cmd: 'ip link' },
    'ip link show',
    'ip -br link',
    'ip -s link',
    'ip link show eth0',
    'ip link show lo',
    'ip link set eth0 up',
    'ip link show eth0',
    'ip link set eth0 down',
    'ip link show eth0',
    'ip link set eth0 up',
    'ip link set eth0 mtu 1400',
    'ip link show eth0',
    'ip link set eth0 mtu 1500',
    'ip link set dev eth0 address 02:00:00:aa:bb:cc',
    'ip link show eth0',
    'ip link set lo up',
    'ip link show interface_inexistante_xyz',
    'ip link set eth0 truc',

    { section: 'adresses — ip address (set/show)', cmd: 'ip address' },
    'ip address show',
    'ip -br address',
    'ip -4 address show',
    'ip -6 address show',
    'ip addr show eth0',
    'ip addr add 192.168.10.2/24 dev eth0',
    'ip addr show eth0',
    'ip -br addr show eth0',
    'ip addr add 192.168.10.3/24 dev eth0',
    'ip addr show eth0',
    'ip addr del 192.168.10.3/24 dev eth0',
    'ip addr show eth0',
    'ip addr add 10.0.0.1/8 dev eth0',
    'ip addr show eth0',
    'ip addr flush dev eth0',
    'ip addr show eth0',
    'ip addr add 192.168.10.2/24 dev eth0',
    'ip addr add 256.1.1.1/24 dev eth0',
    'ip addr add 192.168.10.5 dev interface_inexistante_xyz',

    { section: 'config legacy — ifconfig', cmd: 'ifconfig' },
    'ifconfig -a',
    'ifconfig eth0',
    'ifconfig lo',
    'ifconfig -s',
    'ifconfig eth0 down',
    'ifconfig eth0',
    'ifconfig eth0 up',
    'ifconfig eth0 192.168.20.2 netmask 255.255.255.0',
    'ifconfig eth0',
    'ifconfig eth0 mtu 1450',
    'ifconfig eth0',
    'ifconfig interface_inexistante_xyz',

    { section: 'routage — ip route (set/show)', cmd: 'ip route' },
    'ip route show',
    'ip -4 route',
    'ip route list',
    'ip route show table main',
    'ip route add default via 192.168.10.1',
    'ip route',
    'ip route add 172.16.0.0/16 via 192.168.10.254',
    'ip route',
    'ip route add 10.10.10.0/24 dev eth0',
    'ip route',
    'ip route get 8.8.8.8',
    'ip route get 192.168.10.50',
    'ip route del 10.10.10.0/24',
    'ip route',
    'ip route del default',
    'ip route',
    'ip route add default via 192.168.10.1',
    'ip route add 1.2.3.0/24 via 99.99.99.99',
    'ip route add reseau_invalide via x',

    { section: 'routage legacy — route', cmd: 'route' },
    'route -n',
    'route -e',
    'route add default gw 192.168.10.1',
    'route -n',
    'route add -net 172.20.0.0 netmask 255.255.0.0 gw 192.168.10.254',
    'route -n',
    'route del -net 172.20.0.0 netmask 255.255.0.0',
    'route -n',
    'netstat -rn',

    { section: 'voisinage — ip neigh / arp', cmd: 'ip neigh' },
    'ip neigh show',
    'ip -s neigh',
    'ip neigh show dev eth0',
    'ip neigh add 192.168.10.10 lladdr 02:00:00:11:22:33 dev eth0',
    'ip neigh',
    'ip neigh del 192.168.10.10 dev eth0',
    'ip neigh flush dev eth0',
    'ip neigh',
    'arp',
    'arp -n',
    'arp -a',
    'arp -e',
    'arp -s 192.168.10.20 02:00:00:44:55:66',
    'arp -a',
    'arp -d 192.168.10.20',
    'arp -a',
    'arp -i eth0',

    { section: 'connectivité — ping', cmd: 'ping -c 1 127.0.0.1' },
    'ping -c 2 127.0.0.1',
    'ping -c 1 192.168.10.2',
    'ping -c 3 -i 1 127.0.0.1',
    'ping -c 1 -W 1 192.168.10.99',
    'ping -c 1 -s 100 127.0.0.1',
    'ping -c 1 -t 64 127.0.0.1',
    'ping -c 1 -n 127.0.0.1',
    'ping -c 1 -q 127.0.0.1',
    'ping -c 1 10.255.255.254',
    'ping -c 1 hote_inexistant_xyz',
    'ping6 -c 1 ::1',
    'ping -c abc 127.0.0.1',
    'ping',

    { section: 'traçage de chemin — traceroute/mtr', cmd: 'traceroute 127.0.0.1' },
    'traceroute -n 127.0.0.1',
    'traceroute -m 5 192.168.10.1',
    'traceroute -w 1 192.168.10.99',
    'traceroute hote_inexistant_xyz',
    'tracepath 127.0.0.1',
    'mtr -r -c 1 127.0.0.1',
    'mtr --report 192.168.10.1',

    { section: 'DNS — dig / nslookup / host', cmd: 'dig example.com' },
    'dig +short example.com',
    'dig A example.com',
    'dig AAAA example.com',
    'dig MX example.com',
    'dig NS example.com',
    'dig TXT example.com',
    'dig @8.8.8.8 example.com',
    'dig -x 8.8.8.8',
    'dig +trace example.com',
    'nslookup example.com',
    'nslookup example.com 8.8.8.8',
    'nslookup 8.8.8.8',
    'host example.com',
    'host -t MX example.com',
    'host 8.8.8.8',
    'getent hosts localhost',
    'cat /etc/resolv.conf',
    'cat /etc/hosts',
    'dig domaine_inexistant_xyz.invalid',

    { section: 'sockets — ss / netstat', cmd: 'ss' },
    'ss -t',
    'ss -u',
    'ss -l',
    'ss -tln',
    'ss -uln',
    'ss -tlnp',
    'ss -a',
    'ss -s',
    'ss -tn state established',
    'netstat',
    'netstat -tln',
    'netstat -uln',
    'netstat -tlnp',
    'netstat -an | head',
    'netstat -s | head',
    'netstat -i',
    'netstat -rn',
    'lsof -i :22',
    'ss -tln sport = :22',

    { section: 'HTTP — curl / wget', cmd: 'curl http://192.168.10.1' },
    'curl -I http://192.168.10.1',
    'curl -s http://192.168.10.1',
    'curl -v http://192.168.10.1',
    'curl -o /tmp/page.html http://192.168.10.1',
    'curl -L http://192.168.10.1',
    'curl --max-time 2 http://192.168.10.99',
    'curl http://hote_inexistant_xyz',
    'wget http://192.168.10.1',
    'wget -q http://192.168.10.1',
    'wget -O /tmp/dl.html http://192.168.10.1',
    'wget --timeout=2 http://192.168.10.99',
    'curl',

    { section: 'paramètres réseau — sysctl', cmd: 'sysctl net.ipv4.ip_forward' },
    'sysctl net.ipv4.conf.all.forwarding',
    'sysctl -w net.ipv4.ip_forward=1',
    'sysctl net.ipv4.ip_forward',
    'cat /proc/sys/net/ipv4/ip_forward',
    'sysctl -w net.ipv4.ip_forward=0',
    'sysctl net.ipv4.ip_forward',
    'sysctl net.ipv4.tcp_syncookies',
    'sysctl net.ipv6.conf.all.disable_ipv6',
    'sysctl -a 2>/dev/null | grep ip_forward',
    'sysctl net.ipv4.cle_inexistante',

    { section: 'pare-feu — iptables / ufw', cmd: 'iptables -L' },
    'iptables -L -n',
    'iptables -L -v -n',
    'iptables -t nat -L',
    'iptables -S',
    'iptables -A INPUT -p tcp --dport 22 -j ACCEPT',
    'iptables -L INPUT -n',
    'iptables -A INPUT -p icmp -j ACCEPT',
    'iptables -L INPUT -n --line-numbers',
    'iptables -D INPUT -p icmp -j ACCEPT',
    'iptables -L INPUT -n',
    'iptables -F',
    'iptables -L -n',
    'iptables -P INPUT DROP',
    'iptables -L -n',
    'iptables -P INPUT ACCEPT',
    'ufw status',
    'ufw status verbose',
    'ufw allow 22/tcp',
    'ufw status',
    'ufw deny 23',
    'ufw status numbered',
    'iptables -Z',
    'iptables -A INPUT -j TRUC',

    { section: 'capture & ARP — tcpdump / arping', cmd: 'tcpdump -c 1' },
    'tcpdump -i eth0 -c 1',
    'tcpdump -i eth0 -n -c 1',
    'tcpdump -D',
    'arping -c 1 192.168.10.1',
    'arping -c 2 -I eth0 192.168.10.1',
    'arping -c 1 192.168.10.99',

    { section: 'clés & SSH', cmd: 'ssh-keygen -t rsa -b 2048 -f /tmp/id_rsa -N ""' },
    'ls -l /tmp/id_rsa /tmp/id_rsa.pub',
    'cat /tmp/id_rsa.pub',
    'ssh-keygen -t ed25519 -f /tmp/id_ed25519 -N ""',
    'ssh-keygen -lf /tmp/id_rsa.pub',
    'ssh-keygen -y -f /tmp/id_rsa',
    'ssh -V',
    'ssh root@192.168.10.99',
    'ssh-keyscan 192.168.10.1',

    { section: 'DHCP client', cmd: 'dhclient eth0' },
    'dhclient -v eth0',
    'dhclient -r eth0',
    'ip addr show eth0',
    'dhclient interface_inexistante_xyz',

    { section: 'scénario composé — config IP complète', cmd: 'ip addr flush dev eth0' },
    'ip link set eth0 up',
    'ip addr add 192.168.50.10/24 dev eth0',
    'ip route add default via 192.168.50.1',
    'ip addr show eth0',
    'ip route',
    'ping -c 1 192.168.50.10',
    'ip neigh',
    'ip -br addr',
    'ip route get 192.168.50.1',
    'ip route flush table main',
    'ip route',

    { section: 'inventaire réseau consolidé', cmd: 'ip -br link' },
    'ip -br addr',
    'ip route show | wc -l',
    'ss -tln | wc -l',
    'cat /proc/net/dev | head',
    'cat /proc/net/route | head',
    'hostname -I',
    'hostname',
    'ip addr show | grep inet',

    { section: 'IPv6 — adresses & routes', cmd: 'ip -6 addr show' },
    'ip -6 addr show eth0',
    'ip -6 route show',
    'ip -6 neigh show',
    'ip addr add 2001:db8::10/64 dev eth0',
    'ip -6 addr show eth0',
    'ip -6 route add default via 2001:db8::1',
    'ip -6 route show',
    'ping6 -c 1 ::1',
    'ping -6 -c 1 2001:db8::10',
    'ip addr del 2001:db8::10/64 dev eth0',
    'ip -6 addr show eth0',
    'ip -6 route flush',
    'cat /proc/sys/net/ipv6/conf/all/disable_ipv6',
    'ip link show eth0 | grep -i link',

    { section: 'statistiques & compteurs', cmd: 'ip -s link show eth0' },
    'cat /proc/net/dev',
    'ifconfig eth0 | grep -E "RX|TX"',
    'netstat -i',
    'ss -s',
    'cat /proc/net/snmp | head',
    'cat /proc/net/sockstat',
    'ip -s -s link show eth0',

    { section: 'résolution & hostname', cmd: 'hostname' },
    'hostname -f',
    'hostname -i',
    'hostname -I',
    'hostname -s',
    'hostname -d',
    'cat /etc/nsswitch.conf',
    'getent hosts localhost',
    'getent ahosts localhost',
    'nslookup -type=any example.com',

    { section: 'ethtool & MTU', cmd: 'ethtool eth0' },
    'ethtool -i eth0',
    'ethtool -S eth0',
    'ip link show eth0 | grep mtu',
    'cat /sys/class/net/eth0/mtu',
    'cat /sys/class/net/eth0/address',
    'cat /sys/class/net/eth0/operstate',
    'ls /sys/class/net',

    { section: 'mal formées — fin de transcript', cmd: 'ipp link' },
    'ip',
    'ip addr add',
    'ip route add',
    'ping --truc 127.0.0.1',
    'iptabless -L',
    'netstatt',
    'ss --zorglub',
    'echo "fin du transcript networking"',
  ];
}

describe('debug — Linux networking (PC + server)', () => {
  it('exercises networking commands from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-NET-DBG', 150, 150);
    await runAndDump(
      'linux-pc-networking',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-NET-DBG (linux-pc) — focus: réseau (ip/ping/route/dns/sockets/firewall)',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-NET-DBG', 230, 230);
    await runAndDump(
      'linux-server-networking',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-NET-DBG (linux-server) — focus: réseau (ip/ping/route/dns/sockets/firewall)',
      'linux',
    );
  }, 300_000);
});
