import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

function buildCommands(): DebugCommandInput[] {
  return [
    { section: 'identité courante', cmd: 'whoami' },
    'id',
    'id -u',
    'id -g',
    'id -un',
    'id -gn',
    'id -G',
    'id -Gn',
    'groups',
    'logname',
    'echo $USER',
    'echo $HOME',
    'echo $UID',
    'who',
    'who am i',
    'w',
    'users',
    'last',
    'lastb',
    'last -n 5',

    { section: 'bases de comptes — inventaire', cmd: 'cat /etc/passwd' },
    'cat /etc/group',
    'head -5 /etc/passwd',
    'getent passwd',
    'getent group',
    'getent passwd root',
    'getent group root',
    'cut -d: -f1 /etc/passwd | sort',
    'cut -d: -f1 /etc/group | sort',
    'awk -F: \'$3 >= 1000 {print $1}\' /etc/passwd',
    'awk -F: \'$3 == 0 {print $1}\' /etc/passwd',
    'getent passwd 0',
    'getent passwd utilisateur_inexistant_xyz',

    { section: 'création utilisateur — useradd (SET puis SHOW)', cmd: 'useradd alice' },
    'getent passwd alice',
    'id alice',
    'useradd -m -s /bin/bash bob',
    'getent passwd bob',
    'id bob',
    'useradd -u 1500 -c "Carol Dupont" carol',
    'getent passwd carol',
    'useradd -d /home/dan -m dan',
    'getent passwd dan',
    'useradd -r service1',
    'getent passwd service1',
    'useradd -m -s /bin/zsh eve',
    'getent passwd eve',
    'useradd alice',
    'useradd -u 0 doublon_root',
    'useradd',
    'cut -d: -f1 /etc/passwd | grep -E "alice|bob|carol|dan|eve"',

    { section: 'modification — usermod', cmd: 'usermod -c "Alice Martin" alice' },
    'getent passwd alice',
    'usermod -s /bin/sh alice',
    'getent passwd alice',
    'usermod -d /home/alice2 alice',
    'getent passwd alice',
    'usermod -l alicia alice',
    'getent passwd alicia',
    'usermod -L bob',
    'passwd -S bob',
    'usermod -U bob',
    'passwd -S bob',
    'usermod -u 1600 carol',
    'getent passwd carol',
    'usermod -aG sudo bob',
    'id bob',
    'usermod utilisateur_inexistant_xyz',

    { section: 'mots de passe — passwd / chage', cmd: 'passwd -S alicia' },
    'passwd -S bob',
    'passwd -S root',
    'echo "bob:NouveauPass123" | chpasswd',
    'passwd -S bob',
    'passwd -l dan',
    'passwd -S dan',
    'passwd -u dan',
    'passwd -S dan',
    'passwd -d eve',
    'passwd -S eve',
    'chage -l bob',
    'chage -M 90 bob',
    'chage -l bob',
    'chage -m 7 bob',
    'chage -l bob',
    'chage -E 2026-12-31 bob',
    'chage -l bob',
    'chage -W 14 bob',
    'chage -l bob',
    'passwd -S utilisateur_inexistant_xyz',
    'chage -l utilisateur_inexistant_xyz',

    { section: 'groupes — groupadd / groupmod / gpasswd', cmd: 'groupadd developpeurs' },
    'getent group developpeurs',
    'groupadd -g 2000 ops',
    'getent group ops',
    'groupadd admins',
    'getent group admins',
    'groupmod -n devs developpeurs',
    'getent group devs',
    'groupmod -g 2100 ops',
    'getent group ops',
    'gpasswd -a bob devs',
    'getent group devs',
    'gpasswd -a carol devs',
    'getent group devs',
    'gpasswd -d bob devs',
    'getent group devs',
    'usermod -aG devs,ops eve',
    'id eve',
    'groups eve',
    'groupadd devs',
    'groupadd',

    { section: 'suppression — userdel / groupdel', cmd: 'userdel dan' },
    'getent passwd dan',
    'userdel -r eve',
    'getent passwd eve',
    'groupdel admins',
    'getent group admins',
    'groupdel ops',
    'getent group ops',
    'userdel utilisateur_inexistant_xyz',
    'groupdel groupe_inexistant_xyz',
    'cut -d: -f1 /etc/passwd | grep -E "alicia|bob|carol"',

    { section: 'escalade — su / sudo', cmd: 'sudo -l' },
    'sudo whoami',
    'sudo id',
    'sudo -n true',
    'sudo cat /etc/shadow',
    'sudo -u bob whoami',
    'sudo -k',
    'sudo -v',
    'su --help',
    'su -c whoami root',
    'whoami',
    'sudo commande_inexistante_xyz',

    { section: 'permissions symboliques — chmod', cmd: 'cd /tmp' },
    'touch p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod u+x p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod g+w p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod o-r p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod a+r p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod u=rwx,g=rx,o= p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod ug+s p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod +t p_chmod.txt',
    'ls -l p_chmod.txt',
    'chmod -t p_chmod.txt',
    'ls -l p_chmod.txt',

    { section: 'permissions octales — chmod', cmd: 'chmod 644 p_chmod.txt' },
    'stat -c "%a %A" p_chmod.txt',
    'chmod 600 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'chmod 755 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'chmod 750 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'chmod 4755 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'chmod 2755 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'chmod 1777 p_chmod.txt',
    'stat -c "%a %A" p_chmod.txt',
    'mkdir p_chmoddir',
    'chmod -R 700 p_chmoddir',
    'stat -c "%a" p_chmoddir',
    'chmod 999 p_chmod.txt',
    'chmod abc p_chmod.txt',
    'chmod 644 fichier_inexistant_xyz',

    { section: 'propriété — chown / chgrp', cmd: 'chown root p_chmod.txt' },
    'ls -l p_chmod.txt',
    'chown root:root p_chmod.txt',
    'ls -l p_chmod.txt',
    'chgrp devs p_chmod.txt',
    'ls -l p_chmod.txt',
    'chown :devs p_chmod.txt',
    'ls -l p_chmod.txt',
    'chown bob p_chmod.txt',
    'ls -l p_chmod.txt',
    'chown -R root:root p_chmoddir',
    'ls -ld p_chmoddir',
    'chown --reference=p_chmod.txt p_chmoddir',
    'chown utilisateur_inexistant_xyz p_chmod.txt',
    'chgrp groupe_inexistant_xyz p_chmod.txt',

    { section: 'umask & masque', cmd: 'umask' },
    'umask -S',
    'umask 022',
    'umask',
    'touch sous_022.txt',
    'ls -l sous_022.txt',
    'mkdir sous_022dir',
    'ls -ld sous_022dir',
    'umask 077',
    'umask -S',
    'touch sous_077.txt',
    'ls -l sous_077.txt',
    'umask 0022',

    { section: 'ACL — getfacl / setfacl', cmd: 'getfacl p_chmod.txt' },
    'setfacl -m u:bob:rwx p_chmod.txt',
    'getfacl p_chmod.txt',
    'setfacl -m g:devs:r-x p_chmod.txt',
    'getfacl p_chmod.txt',
    'ls -l p_chmod.txt',
    'setfacl -x u:bob p_chmod.txt',
    'getfacl p_chmod.txt',
    'setfacl -b p_chmod.txt',
    'getfacl p_chmod.txt',
    'setfacl -d -m u:bob:rwx p_chmoddir',
    'getfacl p_chmoddir',
    'getfacl fichier_inexistant_xyz',

    { section: 'scénario composé — projet partagé', cmd: 'groupadd projetX' },
    'useradd -m -G projetX membre1',
    'useradd -m -G projetX membre2',
    'getent group projetX',
    'mkdir -p /srv/projetX',
    'chgrp projetX /srv/projetX',
    'chmod 2770 /srv/projetX',
    'ls -ld /srv/projetX',
    'id membre1',
    'id membre2',
    'gpasswd -a membre1 projetX',
    'getent group projetX',
    'userdel membre2',
    'groupdel projetX',

    { section: 'fichiers de configuration comptes', cmd: 'cat /etc/login.defs' },
    'grep -E "UID_MIN|UID_MAX|GID_MIN" /etc/login.defs',
    'grep -E "PASS_MAX_DAYS|PASS_MIN_DAYS|PASS_WARN_AGE" /etc/login.defs',
    'cat /etc/default/useradd',
    'ls -la /etc/skel',
    'cat /etc/shells',
    'cat /etc/sudoers',
    'ls -l /etc/sudoers.d',
    'cat /etc/subuid',
    'cat /etc/subgid',
    'ls -l /etc/passwd /etc/shadow /etc/group /etc/gshadow',
    'stat -c "%a %n" /etc/passwd',
    'stat -c "%a %n" /etc/shadow',

    { section: 'home & profil utilisateur', cmd: 'ls -la /home' },
    'ls -la /root',
    'ls -ld /home/bob',
    'echo $HOME',
    'echo ~',
    'echo ~root',
    'cat /etc/profile | head',
    'ls -la /etc/profile.d',
    'getent passwd bob | cut -d: -f6',
    'getent passwd bob | cut -d: -f7',

    { section: 'NSS & résolution comptes — getent', cmd: 'getent passwd | wc -l' },
    'getent group | wc -l',
    'getent passwd root',
    'getent passwd 0',
    'getent group root',
    'getent group 0',
    'getent shadow root',
    'getent passwd alicia bob carol',
    'getent group devs',
    'getent initgroups bob',
    'getent ahosts localhost',
    'getent services ssh',
    'getent protocols tcp',

    { section: 'verrouillage & sécurité — faillock/chage', cmd: 'passwd -S root' },
    'chage -l root',
    'faillock',
    'faillock --user bob',
    'faillock --user bob --reset',
    'usermod -L carol',
    'passwd -S carol',
    'usermod -U carol',
    'passwd -S carol',
    'chage -d 0 carol',
    'chage -l carol',
    'chage -E -1 carol',
    'chage -l carol',
    'passwd --status carol',

    { section: 'appartenance & vérification croisée', cmd: 'groups bob' },
    'groups carol',
    'groups root',
    'id -nG bob',
    'id -nG carol',
    'lid bob',
    'members devs',
    'getent group devs | cut -d: -f4',
    'usermod -aG devs carol',
    'id carol',
    'gpasswd -d carol devs',
    'id carol',
    'newgrp devs',

    { section: 'mal formées — fin de transcript', cmd: 'usradd toto' },
    'chmodd 644 p_chmod.txt',
    'chown',
    'usermod',
    'passwd',
    'chage',
    'groupadd -g abc grp',
    'useradd -u abc user',
    'id --truc',
    'echo "fin du transcript users & perms"',
  ];
}

describe('debug — Linux users, groups & permissions (PC + server)', () => {
  it('exercises user/group management and permissions from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-USR-DBG', 160, 160);
    await runAndDump(
      'linux-pc-users-perms',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-USR-DBG (linux-pc) — focus: utilisateurs, groupes & permissions',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-USR-DBG', 240, 240);
    await runAndDump(
      'linux-server-users-perms',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-USR-DBG (linux-server) — focus: utilisateurs, groupes & permissions',
      'linux',
    );
  }, 300_000);
});
