import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { runAndDump, createLinuxRunner, type DebugCommandInput } from './_dump';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

function buildCommands(): DebugCommandInput[] {
  return [
    { section: 'identité système — uname/os', cmd: 'uname' },
    'uname -a',
    'uname -s',
    'uname -n',
    'uname -r',
    'uname -v',
    'uname -m',
    'uname -p',
    'uname -i',
    'uname -o',
    'uname -s -r -m',
    'cat /etc/os-release',
    'cat /etc/issue',
    'cat /proc/version',
    'lsb_release -a',
    'arch',
    'uname --truc',

    { section: 'hôte & temps — hostnamectl/timedatectl', cmd: 'hostname' },
    'hostname -f',
    'hostname -s',
    'hostnamectl',
    'hostnamectl status',
    'cat /etc/hostname',
    'date',
    'date -u',
    'date +%Y-%m-%d',
    'date "+%H:%M:%S"',
    'date +%s',
    'date -d "2026-01-01"',
    'date --iso-8601=seconds',
    'timedatectl',
    'timedatectl status',
    'cal',
    'uptime',
    'uptime -p',
    'uptime -s',
    'date --truc',

    { section: 'CPU — lscpu/nproc/proc', cmd: 'lscpu' },
    'nproc',
    'nproc --all',
    'cat /proc/cpuinfo',
    'cat /proc/cpuinfo | grep -c processor',
    'cat /proc/cpuinfo | grep "model name" | head -1',
    'cat /proc/loadavg',
    'cat /proc/stat | head -1',
    'lscpu | grep -E "^CPU|Model|MHz"',
    'getconf _NPROCESSORS_ONLN',

    { section: 'mémoire — free/vmstat/proc', cmd: 'free' },
    'free -h',
    'free -m',
    'free -g',
    'free -k',
    'free -b',
    'free -t',
    'free -w',
    'free -s 1 -c 1',
    'cat /proc/meminfo',
    'cat /proc/meminfo | head -5',
    'grep -E "MemTotal|MemFree|MemAvailable" /proc/meminfo',
    'grep -E "SwapTotal|SwapFree" /proc/meminfo',
    'vmstat',
    'vmstat 1 2',
    'vmstat -s',
    'swapon --show',
    'swapon -s',

    { section: 'disques — df/du', cmd: 'df' },
    'df -h',
    'df -h /',
    'df -i',
    'df -T',
    'df -k',
    'df -m',
    'df -h --total',
    'df --output=source,size,used,avail,target',
    'du -sh /etc',
    'du -sh /var',
    'du -sh /tmp',
    'du -h --max-depth=1 /var',
    'du -ch /etc/*.conf',
    'du -a /etc | sort -rn | head -5',
    'df /chemin/inexistant_xyz',

    { section: 'blocs & montages — lsblk/mount', cmd: 'lsblk' },
    'lsblk -f',
    'lsblk -a',
    'lsblk -o NAME,SIZE,TYPE,MOUNTPOINT',
    'lsblk -p',
    'blkid',
    'mount',
    'mount | column -t | head',
    'cat /proc/mounts | head',
    'cat /etc/fstab',
    'findmnt',
    'findmnt /',
    'umount /chemin/inexistant_xyz',
    'mount /dev/inexistant_xyz /mnt',

    { section: 'noyau — sysctl/dmesg/modules', cmd: 'sysctl -a | head -20' },
    'sysctl kernel.hostname',
    'sysctl kernel.osrelease',
    'sysctl kernel.ostype',
    'sysctl kernel.version',
    'sysctl kernel.pid_max',
    'sysctl vm.swappiness',
    'sysctl -w vm.swappiness=40',
    'sysctl vm.swappiness',
    'sysctl -w vm.swappiness=60',
    'cat /proc/sys/kernel/hostname',
    'cat /proc/sys/kernel/pid_max',
    'dmesg | head',
    'dmesg -T | head',
    'dmesg --level=err',
    'lsmod',
    'lsmod | head',
    'modinfo overlay',
    'sysctl kernel.cle_inexistante',

    { section: 'environnement & shell', cmd: 'env' },
    'env | head',
    'printenv',
    'printenv PATH',
    'printenv HOME',
    'echo $PATH',
    'echo $SHELL',
    'echo $PWD',
    'echo $?',
    'export DEMO_VAR=hello',
    'echo $DEMO_VAR',
    'env | grep DEMO_VAR',
    'unset DEMO_VAR',
    'echo "[$DEMO_VAR]"',
    'set | head',
    'declare -p PATH',
    'alias',
    "alias ll='ls -la'",
    'alias',
    'unalias ll',
    'type ll',
    'history',
    'history | tail -5',
    'shopt',
    'locale',
    'echo $LANG',

    { section: 'paquets — apt/dpkg', cmd: 'apt --version' },
    'apt list --installed',
    'apt list --installed 2>/dev/null | head',
    'apt-cache search bash',
    'apt-get --version',
    'dpkg --version',
    'dpkg -l',
    'dpkg -l | head',
    'dpkg -l bash',
    'dpkg -L bash',
    'dpkg -s bash',
    'dpkg --get-selections | head',
    'apt show bash',
    'apt policy bash',
    'apt update',
    'apt install paquet_inexistant_xyz',
    'dpkg -l paquet_inexistant_xyz',

    { section: 'archives & compression — tar/gzip/zip', cmd: 'cd /tmp' },
    'mkdir -p arch_src && echo data1 > arch_src/a.txt && echo data2 > arch_src/b.txt',
    'ls -R arch_src',
    'tar -cf arch.tar arch_src',
    'ls -l arch.tar',
    'tar -tf arch.tar',
    'tar -czf arch.tar.gz arch_src',
    'ls -l arch.tar.gz',
    'tar -tzf arch.tar.gz',
    'mkdir extract && tar -xf arch.tar -C extract',
    'ls -R extract',
    'gzip arch_src/a.txt',
    'ls -l arch_src',
    'gunzip arch_src/a.txt.gz',
    'ls -l arch_src',
    'gzip -k arch_src/b.txt',
    'ls -l arch_src',
    'zip -r arch.zip arch_src',
    'ls -l arch.zip',
    'unzip -l arch.zip',
    'tar -xf archive_inexistante_xyz.tar',

    { section: 'hachage & intégrité', cmd: 'md5sum /etc/hostname' },
    'sha1sum /etc/hostname',
    'sha256sum /etc/hostname',
    'sha256sum /etc/hostname /etc/os-release',
    'cksum /etc/hostname',
    'sha256sum /etc/hostname > /tmp/sums.txt && sha256sum -c /tmp/sums.txt',
    "echo -n 'abc' | sha256sum",

    { section: 'journalisation — logger/journalctl/dmesg', cmd: 'logger "message de test debug"' },
    'logger -p user.info "info debug"',
    'logger -t debugtag "tag debug"',
    'journalctl -n 10 --no-pager',
    'journalctl -p err -n 5',
    'journalctl -b',
    'journalctl --disk-usage',
    'dmesg | tail',
    'tail -n 5 /var/log/syslog',
    'ls -l /var/log',

    { section: 'utilitaires divers', cmd: 'seq 1 5' },
    'seq 0 2 10',
    'sleep 0.1',
    'true; echo $?',
    'false; echo $?',
    'test -f /etc/hostname; echo $?',
    'test -d /etc; echo $?',
    '[ -e /etc/passwd ]; echo $?',
    'yes | head -3',
    'watch -n 1 -c 1 date',
    'time true',
    'tput cols',
    'stty -a',

    { section: 'scénario composé — bilan système', cmd: 'echo "=== HOST ==="; hostname; uname -r' },
    'echo "=== CPU ==="; nproc; uptime',
    'echo "=== MEM ==="; free -h | head -2',
    'echo "=== DISK ==="; df -h / | tail -1',
    'echo "=== TOP DIRS ==="; du -sh /etc /var /tmp 2>/dev/null',
    'echo "kernel=$(uname -r) host=$(hostname)"',
    'df -h | awk \'NR==1 || /\\/$/\'',
    'free -m | awk \'/Mem/ {printf "RAM: %d/%d MB\\n", $3, $2}\'',

    { section: 'introspection /proc', cmd: 'ls /proc' },
    'cat /proc/uptime',
    'cat /proc/loadavg',
    'cat /proc/version',
    'cat /proc/cmdline',
    'cat /proc/filesystems | head',
    'cat /proc/partitions',
    'cat /proc/devices | head',
    'cat /proc/swaps',
    'cat /proc/1/status | head',
    'cat /proc/1/cmdline',
    'cat /proc/self/status | head',
    'cat /proc/sys/kernel/threads-max',
    'cat /proc/sys/fs/file-max',
    'cat /proc/sys/fs/file-nr',
    'ls /proc/self',
    'cat /proc/interrupts | head',

    { section: 'introspection /sys', cmd: 'ls /sys' },
    'ls /sys/class',
    'ls /sys/class/net',
    'ls /sys/block',
    'cat /sys/devices/system/cpu/online',
    'cat /sys/class/net/lo/mtu',
    'ls /sys/kernel',
    'cat /sys/kernel/hostname 2>/dev/null || hostname',

    { section: 'formats de date avancés', cmd: 'date "+%A %d %B %Y"' },
    'date "+%j"',
    'date "+%V"',
    'date "+%u"',
    'date "+%Z %z"',
    'date -u "+%Y-%m-%dT%H:%M:%SZ"',
    'date -d "next monday"',
    'date -d "yesterday"',
    'date -d "1 hour ago"',
    'date -d "@0"',
    'date -d "@1700000000"',
    'TZ=UTC date',
    'cal -3',

    { section: 'matériel & firmware', cmd: 'lspci' },
    'lspci | head',
    'lsusb',
    'lshw -short',
    'dmidecode -t system',
    'cat /sys/class/dmi/id/product_name 2>/dev/null',
    'sensors',
    'lscpu -e',

    { section: 'limites & ressources — ulimit', cmd: 'ulimit -a' },
    'ulimit -n',
    'ulimit -u',
    'ulimit -s',
    'ulimit -f',
    'ulimit -c',
    'ulimit -v',
    'ulimit -Hn',
    'ulimit -Sn',
    'ulimit -n 4096',
    'ulimit -n',
    'getconf PAGE_SIZE',
    'getconf LONG_BIT',
    'getconf -a | head',

    { section: 'snapshot processus & charge', cmd: 'ps aux | head' },
    'ps -ef | head',
    'ps -eo pid,ppid,pcpu,pmem,comm --sort=-pcpu | head -5',
    'top -b -n 1 | head -12',
    'uptime',
    'cat /proc/loadavg',
    'pgrep -l systemd',
    'ps -e | wc -l',
    'free -m && df -h /',

    { section: 'horloge & disponibilité', cmd: 'timedatectl show' },
    'date +%s',
    'cat /proc/uptime | awk \'{print $1" secondes"}\'',
    'uptime -p',
    'who -b',
    'last reboot 2>/dev/null | head',

    { section: 'mal formées — fin de transcript', cmd: 'unamee -a' },
    'dff -h',
    'freee',
    'sysctl -w',
    'tar',
    'dpkg -l | | head',
    'apt',
    'lsblkk',
    'echo "fin du transcript system & disk"',
  ];
}

describe('debug — Linux system, disk & packages (PC + server)', () => {
  it('exercises system info, disk, kernel and package commands from the bash terminal', async () => {
    const commands = buildCommands();
    expect(commands.length).toBeGreaterThanOrEqual(300);

    const pc = new LinuxPC('linux-pc', 'L-PC-SYS-DBG', 170, 170);
    await runAndDump(
      'linux-pc-system-disk',
      commands,
      createLinuxRunner(pc),
      'host=L-PC-SYS-DBG (linux-pc) — focus: système, disque, noyau & paquets',
      'linux',
    );

    const srv = new LinuxServer('linux-server', 'L-SRV-SYS-DBG', 250, 250);
    await runAndDump(
      'linux-server-system-disk',
      commands,
      createLinuxRunner(srv),
      'host=L-SRV-SYS-DBG (linux-server) — focus: système, disque, noyau & paquets',
      'linux',
    );
  }, 300_000);
});
