/**
 * Debug — Vues clés Oracle (V$, GV$, DBA_*) — 300+ vues exercées.
 */

import { describe, it, beforeEach } from 'vitest';
import { LinuxServer } from '@/network/devices/LinuxServer';
import { resetCounters } from '@/network/core/types';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { removeOracleDatabase, getOracleDatabase } from '@/terminal/commands/database';
import { createSqlPlusRunner, runOracleDump, type OracleDebugLine } from './_oracle-dump';

beforeEach(() => { resetCounters(); resetDeviceCounters(); Logger.reset(); });

describe('debug — Oracle key views', () => {
  it('SELECT sur toutes les vues clés V$/DBA_/GV$', () => {
    const srv = new LinuxServer('linux-server', 'ora-views', 100, 100);
    getOracleDatabase(srv.id);
    const runner = createSqlPlusRunner(srv);

    // Helper inline — chaque vue produit une ligne. On exécute LIMIT pour rester rapide.
    const select = (view: string) => `SELECT * FROM ${view} WHERE rownum < 5;`;

    const lines: OracleDebugLine[] = [
      // ── 1. instance & DB ─────────────────────────────────────────
      { section: 'instance & db', cmd: select('v$instance') },
      select('v$database'),
      select('v$option'),
      select('v$version'),
      select('v$license'),
      select('v$instance_recovery'),
      select('v$instance_cache_transfer'),
      select('gv$instance'),
      select('v$active_instances'),
      select('v$cluster_instance'),
      select('v$nodes'),
      select('v$rac_global_view'),
      select('v$thread'),
      select('v$threads'),
      select('product_component_version'),

      // ── 2. parameters ────────────────────────────────────────────
      { section: 'parameters', cmd: select('v$parameter') },
      select('v$parameter2'),
      select('v$spparameter'),
      select('v$nls_parameters'),
      select('v$nls_valid_values'),
      select('v$obsolete_parameter'),
      select('v$system_parameter'),
      select('v$system_parameter2'),
      select('nls_database_parameters'),
      select('nls_instance_parameters'),
      select('nls_session_parameters'),

      // ── 3. processes & sessions ─────────────────────────────────
      { section: 'processes & sessions', cmd: select('v$session') },
      select('v$process'),
      select('v$session_wait'),
      select('v$session_event'),
      select('v$session_wait_history'),
      select('v$session_wait_class'),
      select('v$session_metric'),
      select('v$session_metric_history'),
      select('v$session_object_cache'),
      select('v$session_cursor_cache'),
      select('v$session_connect_info'),
      select('v$session_blockers'),
      select('v$session_longops'),
      select('v$bgprocess'),
      select('v$mystat'),
      select('v$sesstat'),
      select('v$statname'),
      select('v$sess_io'),
      select('v$sess_time_model'),
      select('v$session_fix_control'),
      select('gv$session'),
      select('gv$process'),

      // ── 4. SQL / cursor ──────────────────────────────────────────
      { section: 'SQL', cmd: select('v$sql') },
      select('v$sqlarea'),
      select('v$sqlstats'),
      select('v$sql_plan'),
      select('v$sql_plan_statistics'),
      select('v$sql_plan_statistics_all'),
      select('v$sql_workarea'),
      select('v$sql_workarea_active'),
      select('v$sql_workarea_histogram'),
      select('v$sqlfn_metadata'),
      select('v$sqlfn_arg_metadata'),
      select('v$sql_bind_capture'),
      select('v$sql_shared_cursor'),
      select('v$sql_shared_memory'),
      select('v$sql_cursor'),
      select('v$sql_monitor'),
      select('v$sql_plan_monitor'),
      select('v$sql_text'),
      select('v$sql_text_with_newlines'),
      select('v$open_cursor'),
      select('v$db_object_cache'),
      select('v$librarycache'),
      select('v$libraryobj'),
      select('v$libcache_locks'),

      // ── 5. memory ────────────────────────────────────────────────
      { section: 'memory', cmd: select('v$sga') },
      select('v$sgainfo'),
      select('v$sgastat'),
      select('v$sga_dynamic_components'),
      select('v$sga_dynamic_free_memory'),
      select('v$sga_resize_ops'),
      select('v$sga_current_resize_ops'),
      select('v$sga_target_advice'),
      select('v$pgastat'),
      select('v$pga_target_advice'),
      select('v$process_memory'),
      select('v$process_memory_detail'),
      select('v$buffer_pool'),
      select('v$buffer_pool_statistics'),
      select('v$bh'),
      select('v$db_cache_advice'),
      select('v$cache_stats'),
      select('v$shared_pool_advice'),
      select('v$shared_pool_reserved'),
      select('v$rowcache'),
      select('v$rowcache_subordinate'),
      select('v$java_pool_advice'),
      select('v$streams_pool_advice'),
      select('v$memory_target_advice'),
      select('v$memory_dynamic_components'),
      select('v$memory_resize_ops'),

      // ── 6. statistics ────────────────────────────────────────────
      { section: 'statistics', cmd: select('v$sysstat') },
      select('v$sysmetric'),
      select('v$sysmetric_history'),
      select('v$sysmetric_summary'),
      select('v$system_event'),
      select('v$system_wait_class'),
      select('v$active_session_history'),
      select('v$system_metric'),
      select('v$system_metric_history'),
      select('v$eventmetric'),
      select('v$waitclassmetric'),
      select('v$waitclassmetric_history'),
      select('v$filemetric'),
      select('v$filemetric_history'),
      select('v$iofuncmetric'),
      select('v$iofuncmetric_summary'),
      select('v$sysmetric_history'),
      select('v$service_stats'),
      select('v$servicemetric'),
      select('v$servicemetric_history'),
      select('v$enqueue_stat'),
      select('v$enqueue_statistics'),

      // ── 7. waits / events ────────────────────────────────────────
      { section: 'waits', cmd: select('v$event_name') },
      select('v$eventmetric'),
      select('v$system_event'),
      select('v$session_event'),
      select('v$session_wait'),
      select('v$session_wait_history'),
      select('v$active_session_history'),
      select('v$wait_chains'),
      select('v$latch'),
      select('v$latchholder'),
      select('v$latch_parent'),
      select('v$latch_children'),
      select('v$latchname'),
      select('v$mutex_sleep'),
      select('v$mutex_sleep_history'),

      // ── 8. tablespaces / datafiles ──────────────────────────────
      { section: 'tablespaces / datafiles', cmd: select('v$tablespace') },
      select('v$datafile'),
      select('v$tempfile'),
      select('v$logfile'),
      select('v$log'),
      select('v$log_history'),
      select('v$datafile_header'),
      select('v$datafile_copy'),
      select('v$filestat'),
      select('v$tempstat'),
      select('v$filespace_usage'),
      select('v$controlfile'),
      select('v$controlfile_record_section'),
      select('v$temp_extent_map'),
      select('v$temp_extent_pool'),
      select('v$tempseg_usage'),
      select('v$sort_segment'),
      select('v$backup'),
      select('v$datafile_block_check'),
      select('v$encrypted_tablespaces'),
      select('v$tablespace_thread'),

      // ── 9. archivelog / redo ─────────────────────────────────────
      { section: 'archivelog / redo', cmd: select('v$archived_log') },
      select('v$archive_dest'),
      select('v$archive_processes'),
      select('v$archive_dest_status'),
      select('v$archive_gap'),
      select('v$recovery_log'),
      select('v$recovery_progress'),
      select('v$recovery_file_dest'),
      select('v$recovery_area_usage'),
      select('v$flash_recovery_area_usage'),
      select('v$logmnr_contents'),
      select('v$logmnr_logs'),
      select('v$logmnr_dictionary'),

      // ── 10. flashback ────────────────────────────────────────────
      { section: 'flashback', cmd: select('v$flashback_database_log') },
      select('v$flashback_database_logfile'),
      select('v$flashback_database_stat'),
      select('v$flashback_txn_mods'),
      select('v$flashback_txn_graph'),

      // ── 11. backups ──────────────────────────────────────────────
      { section: 'backups', cmd: select('v$backup_set') },
      select('v$backup_piece'),
      select('v$backup_files'),
      select('v$backup_redolog'),
      select('v$backup_archivelog_details'),
      select('v$backup_datafile'),
      select('v$backup_corruption'),
      select('v$copy_corruption'),
      select('v$database_block_corruption'),
      select('v$rman_status'),
      select('v$rman_output'),
      select('v$rman_backup_job_details'),
      select('v$rman_backup_type'),

      // ── 12. locks / enqueue ─────────────────────────────────────
      { section: 'locks', cmd: select('v$lock') },
      select('v$locked_object'),
      select('v$enqueue_lock'),
      select('v$transaction'),
      select('v$transaction_enqueue'),
      select('v$global_transaction'),

      // ── 13. dispatcher / shared server ──────────────────────────
      { section: 'dispatcher / shared server', cmd: select('v$dispatcher') },
      select('v$dispatcher_rate'),
      select('v$dispatcher_config'),
      select('v$shared_server'),
      select('v$shared_server_monitor'),
      select('v$queue'),
      select('v$circuit'),
      select('v$listener_network'),

      // ── 14. services ────────────────────────────────────────────
      { section: 'services', cmd: select('v$services') },
      select('v$active_services'),
      select('v$service_stats'),
      select('v$servicemetric'),
      select('v$servicemetric_history'),

      // ── 15. RAC / GV$ ───────────────────────────────────────────
      { section: 'RAC', cmd: select('gv$instance') },
      select('gv$session'),
      select('gv$process'),
      select('gv$sqlarea'),
      select('gv$sql'),
      select('gv$lock'),
      select('gv$transaction'),
      select('gv$session_wait'),
      select('gv$session_event'),
      select('gv$active_session_history'),

      // ── 16. DBA_* views ─────────────────────────────────────────
      { section: 'DBA_*', cmd: select('dba_users') },
      select('dba_roles'),
      select('dba_profiles'),
      select('dba_role_privs'),
      select('dba_sys_privs'),
      select('dba_tab_privs'),
      select('dba_col_privs'),
      select('dba_objects'),
      select('dba_tables'),
      select('dba_views'),
      select('dba_indexes'),
      select('dba_ind_columns'),
      select('dba_tab_columns'),
      select('dba_tab_comments'),
      select('dba_col_comments'),
      select('dba_constraints'),
      select('dba_cons_columns'),
      select('dba_sequences'),
      select('dba_synonyms'),
      select('dba_triggers'),
      select('dba_procedures'),
      select('dba_arguments'),
      select('dba_source'),
      select('dba_dependencies'),
      select('dba_errors'),
      select('dba_segments'),
      select('dba_extents'),
      select('dba_free_space'),
      select('dba_tablespaces'),
      select('dba_data_files'),
      select('dba_temp_files'),
      select('dba_ts_quotas'),
      select('dba_rollback_segs'),
      select('dba_recyclebin'),
      select('dba_tab_partitions'),
      select('dba_tab_subpartitions'),
      select('dba_part_tables'),
      select('dba_part_indexes'),
      select('dba_ind_partitions'),
      select('dba_ind_subpartitions'),
      select('dba_subpart_key_columns'),
      select('dba_part_key_columns'),
      select('dba_mviews'),
      select('dba_mview_logs'),
      select('dba_mview_refresh_times'),
      select('dba_mview_keys'),
      select('dba_jobs'),
      select('dba_jobs_running'),
      select('dba_scheduler_jobs'),
      select('dba_scheduler_programs'),
      select('dba_scheduler_schedules'),
      select('dba_scheduler_job_log'),
      select('dba_scheduler_job_run_details'),
      select('dba_scheduler_windows'),
      select('dba_scheduler_credentials'),
      select('dba_db_links'),
      select('dba_directories'),
      select('dba_libraries'),
      select('dba_resumable'),
      select('dba_addm_findings'),
      select('dba_advisor_findings'),
      select('dba_advisor_recommendations'),
      select('dba_advisor_actions'),
      select('dba_outstanding_alerts'),
      select('dba_alert_history'),
      select('dba_alert_arguments'),
      select('dba_audit_trail'),
      select('dba_audit_session'),
      select('dba_audit_object'),
      select('dba_audit_statement'),
      select('dba_fga_audit_trail'),
      select('dba_priv_audit_opts'),
      select('dba_obj_audit_opts'),
      select('dba_stmt_audit_opts'),
      select('dba_policies'),
      select('dba_policy_groups'),
      select('dba_audit_policies'),
      select('unified_audit_trail'),
      select('dba_2pc_pending'),
      select('dba_2pc_neighbors'),
      select('dba_tab_statistics'),
      select('dba_ind_statistics'),
      select('dba_col_statistics'),
      select('dba_tab_histograms'),
      select('dba_optstat_operations'),
      select('dba_optstat_operation_tasks'),
      select('dba_tab_modifications'),
      select('dba_rsrc_consumer_groups'),
      select('dba_rsrc_plans'),
      select('dba_rsrc_plan_directives'),
      select('dba_rsrc_mappings'),
      select('dba_rsrc_group_mappings'),
      select('dba_hist_snapshot'),
      select('dba_hist_database_instance'),
      select('dba_hist_sysstat'),
      select('dba_hist_sysmetric_summary'),
      select('dba_hist_sysmetric_history'),
      select('dba_hist_sqlstat'),
      select('dba_hist_active_sess_history'),
      select('dba_hist_wr_control'),
      select('dba_hist_baseline'),

      // ── 17. ALL_ + USER_ ─────────────────────────────────────────
      { section: 'ALL_ / USER_', cmd: select('all_users') },
      select('all_objects'),
      select('all_tables'),
      select('all_views'),
      select('all_indexes'),
      select('all_tab_columns'),
      select('all_constraints'),
      select('all_db_links'),
      select('all_tab_privs'),
      select('all_synonyms'),
      select('user_tables'),
      select('user_views'),
      select('user_indexes'),
      select('user_tab_columns'),
      select('user_constraints'),
      select('user_sequences'),
      select('user_synonyms'),
      select('user_objects'),
      select('user_jobs'),
      select('user_source'),
      select('user_dependencies'),
      select('user_errors'),
      select('user_role_privs'),
      select('user_sys_privs'),
      select('user_tab_privs'),
      select('user_col_privs'),
      select('user_ts_quotas'),
      select('user_resumable'),
      select('user_triggers'),
      select('user_procedures'),

      // ── 18. fixed / dictionary ──────────────────────────────────
      { section: 'fixed views', cmd: 'SELECT * FROM v$fixed_table WHERE rownum < 10;' },
      'SELECT name FROM v$fixed_table ORDER BY name FETCH FIRST 30 ROWS ONLY;',
      'SELECT * FROM v$fixed_view_definition WHERE rownum < 5;',
      'SELECT * FROM dict WHERE rownum < 30;',
      'SELECT * FROM dict_columns WHERE rownum < 30;',
      'SELECT * FROM dictionary WHERE rownum < 30;',

      // ── 19. closing ─────────────────────────────────────────────
      { section: 'closing', cmd: 'SELECT count(*) AS total_dba_views FROM dict WHERE table_name LIKE \'DBA\\_%\' ESCAPE \'\\\';' },
      'SELECT count(*) AS total_v$ FROM v$fixed_table;',
      'EXIT;',
    ];

    runOracleDump('oracle-key-views', 'LinuxServer ora-views — Oracle ORCL OPEN', lines, runner);
    runner.dispose();
    removeOracleDatabase(srv.id);
  });
});
