import type { ToolResult } from './AuditToolHost';

export interface AugenrulesHost {
  listDirectory(path: string): string[] | null;
  readFile(path: string): string | null;
  writeFile(path: string, content: string, mode: number): void;
  loadRules(path: string): ToolResult;
}

const DESTINATION_FILE = '/etc/audit/audit.rules';
const SOURCE_RULES_DIR = '/etc/audit/rules.d';
const SUFFIX = 'prev';
const GENERATED_HEADER = `## This file is automatically generated from ${SOURCE_RULES_DIR}`;
const USAGE = '[--check|--load]';

function versionCompare(left: string, right: string): number {
  const split = (text: string): Array<string | number> => text.match(/\d+|\D+/g)?.map((part) => (/^\d/.test(part) ? Number(part) : part)) ?? [];
  const a = split(left);
  const b = split(right);
  for (let i = 0; i < Math.min(a.length, b.length); i++) {
    if (a[i] === b[i]) continue;
    if (typeof a[i] === 'number' && typeof b[i] === 'number') return (a[i] as number) - (b[i] as number);
    return String(a[i]) < String(b[i]) ? -1 : 1;
  }
  return a.length - b.length;
}

export function compileRules(sources: readonly string[]): string {
  let minusE = '';
  let minusD = '';
  let minusF = '';
  let minusB = '';
  const rest: string[] = [];
  const records = sources.join('').split('\n');
  if (records[records.length - 1] === '') records.pop();
  for (const record of records) {
    const line = record.replace(/\r$/, '');
    if (line.length < 1) continue;
    if (/^s*#/.test(line)) continue;
    if (/^s*-e/.test(line)) { minusE = line; continue; }
    if (/^s*-Ds*$/.test(line)) { minusD = line; continue; }
    if (/^s*-f/.test(line)) { minusF = line; continue; }
    if (/^s*-b/.test(line)) { minusB = line; continue; }
    rest.push(line);
  }
  return `${GENERATED_HEADER}\n${minusD}\n${minusB}\n${minusF}\n${rest.map((line) => `${line}\n`).join('')}${minusE}\n`;
}

export function runAugenrules(host: AugenrulesHost, args: string[], program = 'augenrules'): ToolResult {
  let stdout = '';
  let stderr = '';
  let checkOnly = false;
  let load = false;
  let retval = 0;
  const finish = (code: number): ToolResult => ({ stdout, stderr, exitCode: code, interleaved: stdout + stderr });
  const tryLoad = (): void => {
    if (!load) return;
    const loaded = host.loadRules(DESTINATION_FILE);
    stdout += loaded.stdout;
    stderr += loaded.stderr;
    retval = loaded.exitCode;
  };
  for (const argument of args) {
    if (argument === '--check') checkOnly = true;
    else if (argument === '--load') load = true;
    else {
      stdout += `Usage: ${program} ${USAGE}\n`;
      return finish(1);
    }
  }
  const entries = host.listDirectory(SOURCE_RULES_DIR);
  if (entries === null) {
    stdout += `${program}: No rules directory - ${SOURCE_RULES_DIR}\n`;
    tryLoad();
    return finish(1);
  }
  const names = entries.filter((name) => /\.rules$/.test(name)).sort(versionCompare);
  const sources = names.map((name) => host.readFile(`${SOURCE_RULES_DIR}/${name}`) ?? '');
  const compiled = compileRules(sources);
  const existing = host.readFile(DESTINATION_FILE);
  if (existing === compiled) {
    stdout += `${program}: No change\n`;
    tryLoad();
    return finish(retval);
  }
  if (checkOnly) {
    stdout += `${program}: Rules have changed and should be updated\n`;
    return finish(0);
  }
  if (existing !== null) host.writeFile(`${DESTINATION_FILE}.${SUFFIX}`, existing, 0o640);
  host.writeFile(DESTINATION_FILE, compiled, 0o640);
  tryLoad();
  return finish(retval);
}
