/*
 * Probe: the simulated host runs the same audit kernel model the auditctl 3.1.2 oracle was checked against
 * (AuditKernelState behind LinuxAuditRules), loads its rules the way the Ubuntu auditd.service does
 * (ExecStartPost=-/sbin/augenrules --load, itself checked by augenrules-oracle.test.ts), and writes the kernel's
 * CONFIG_CHANGE and USER records.  Formats: kernel audit_log_rule_change / audit_do_config_change.
 * Measured before the change (git stash push -u -- src/network): 14 of the 17 cases fall - the old model had no
 * augenrules, no CONFIG_CHANGE records, no -m/-C/-q, no exclude/user lists and no rate limit.  The three that pass
 * either way are witnesses: 'a watch still fires on a write' (non-regression of the fire path), 'never,exit before
 * always,exit suppresses the event' (the old model let any never rule suppress) and 'wipes runtime-only rules on an
 * auditd restart but reloads those of rules.d' (the old model also cleared on restart and re-read rules.d).
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { LinuxPC } from '@/network/devices/LinuxPC';
import { MACAddress, resetCounters } from '@/network/core/types';
import { Logger } from '@/network/core/Logger';

async function rootHost(): Promise<LinuxPC> {
  const pc = new LinuxPC('AuditHost', 0, 0);
  await pc.executeCommand('sudo su -');
  return pc;
}

const configChanges = async (pc: LinuxPC): Promise<string[]> =>
  (await pc.executeCommand('cat /var/log/audit/audit.log')).split('\n').filter((line) => line.startsWith('type=CONFIG_CHANGE'));

describe('audit kernel model on the simulated host', () => {
  beforeEach(() => {
    resetCounters();
    MACAddress.resetCounter();
    Logger.reset();
  });

  it('boots with the Ubuntu default rules.d: backlog 8192, wait time 60000, failure 1, auditd registered', async () => {
    const pc = await rootHost();
    const status = await pc.executeCommand('auditctl -s');
    expect(status).toMatch(/^enabled 1\nfailure 1\npid [1-9]\d*\nrate_limit 0\nbacklog_limit 8192\nlost 0\nbacklog 0\nbacklog_wait_time 60000\n/);
    expect(await pc.executeCommand('auditctl -l')).toBe('No rules');
  });

  it('compiles /etc/audit/audit.rules from rules.d exactly as augenrules does', async () => {
    const pc = await rootHost();
    expect(await pc.executeCommand('cat /etc/audit/audit.rules')).toBe(
      '## This file is automatically generated from /etc/audit/rules.d\n-D\n-b 8192\n-f 1\n--backlog_wait_time 60000\n');
  });

  it('augenrules --check reports a stale compilation and --load installs it and keeps the previous file', async () => {
    const pc = await rootHost();
    expect(await pc.executeCommand('augenrules --check')).toBe('augenrules: No change');
    await pc.executeCommand('echo "-w /etc/passwd -p wa -k pw" >> /etc/audit/rules.d/audit.rules');
    expect(await pc.executeCommand('augenrules --check')).toBe('augenrules: Rules have changed and should be updated');
    await pc.executeCommand('augenrules --load');
    expect(await pc.executeCommand('auditctl -l')).toBe('-w /etc/passwd -p wa -k pw');
    expect(await pc.executeCommand('ls /etc/audit')).toContain('audit.rules.prev');
  });

  it('logs the kernel CONFIG_CHANGE record for a rule added and removed, key quoted and list number', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -w /etc/hosts -p w -k hosts_w');
    await pc.executeCommand('auditctl -W /etc/hosts -p w -k hosts_w');
    const lines = (await configChanges(pc)).filter((line) => line.includes('op=add_rule') || line.includes('op=remove_rule'));
    expect(lines[0]).toMatch(/: auid=1000 ses=1 subj=unconfined op=add_rule key="hosts_w" list=4 res=1$/);
    expect(lines[1]).toMatch(/: auid=1000 ses=1 subj=unconfined op=remove_rule key="hosts_w" list=4 res=1$/);
  });

  it('logs a keyless rule as key=(null) and names the exclude list 5', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -a never,exclude -F msgtype=CWD');
    const lines = await configChanges(pc);
    expect(lines[lines.length - 1]).toMatch(/op=add_rule key=\(null\) list=5 res=1$/);
  });

  it('logs the configuration change with its old value, and res=0 when the system is locked', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -e 0');
    await pc.executeCommand('auditctl -e 2');
    await pc.executeCommand('auditctl -e 1');
    const lines = await configChanges(pc);
    expect(lines.slice(-3).map((line) => line.replace(/^type=CONFIG_CHANGE msg=audit\([^)]*\): /, ''))).toEqual([
      'op=set audit_enabled=0 old=1 auid=1000 ses=1 subj=unconfined res=1',
      'op=set audit_enabled=2 old=0 auid=1000 ses=1 subj=unconfined res=1',
      'op=set audit_enabled=1 old=2 auid=1000 ses=1 subj=unconfined res=0',
    ]);
  });

  it('records the boot-time configuration with the unset audit uid and session', async () => {
    const pc = await rootHost();
    const lines = await configChanges(pc);
    expect(lines.some((line) => /op=set audit_backlog_limit=8192 old=64 auid=4294967295 ses=4294967295 subj=unconfined res=1$/.test(line))).toBe(true);
  });

  it('sends a user message with -m and logs it as a USER record', async () => {
    const pc = await rootHost();
    expect(await pc.executeCommand('auditctl -m hello')).toBe('');
    const log = await pc.executeCommand('cat /var/log/audit/audit.log');
    expect(log).toMatch(/type=USER msg=audit\([^)]*\): pid=\d+ uid=0 auid=1000 ses=1 subj=unconfined msg='text=hello exe="\/usr\/sbin\/auditctl" hostname=\? addr=\? terminal=pts\/0 res=success'/);
  });

  it('drops the records of an excluded type from every event', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -a never,exclude -F msgtype=CWD');
    await pc.executeCommand('auditctl -w /etc/hosts -p w -k hosts_w');
    await pc.executeCommand('echo x >> /etc/hosts');
    const events = await pc.executeCommand('ausearch -k hosts_w -m SYSCALL,PATH,CWD,PROCTITLE');
    expect(events).toContain('type=SYSCALL');
    expect(events).not.toContain('type=CWD');
  });

  it('lets the first matching rule decide: never,exit before always,exit suppresses the event', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -a never,exit -S all -F dir=/tmp');
    await pc.executeCommand('auditctl -w /tmp/probe -p w -k tmp_probe');
    await pc.executeCommand('touch /tmp/probe');
    expect(await pc.executeCommand('ausearch -m SYSCALL -k tmp_probe')).toContain('<no matches>');
  });

  it('keeps the always rule when it comes before the never rule', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -w /tmp/probe -p w -k tmp_probe');
    await pc.executeCommand('auditctl -a never,exit -S all -F dir=/tmp');
    await pc.executeCommand('touch /tmp/probe');
    expect(await pc.executeCommand('ausearch -m SYSCALL -k tmp_probe')).toContain('type=SYSCALL');
  });

  it('evaluates the uid field of a syscall rule against the real uid of the caller', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -a always,exit -F arch=b64 -S openat -S open -F uid=0 -k as_root');
    await pc.executeCommand('auditctl -a always,exit -F arch=b64 -S openat -S open -F uid=1000 -k as_user');
    await pc.executeCommand('cat /etc/hostname');
    expect(await pc.executeCommand('ausearch -m SYSCALL -k as_root')).toContain('type=SYSCALL');
    expect(await pc.executeCommand('ausearch -m SYSCALL -k as_user')).toContain('<no matches>');
  });

  it('counts lost records once the rate limit of the second is exhausted', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -w /tmp/rate -p w -k rate_probe');
    await pc.executeCommand('auditctl -r 2');
    await pc.executeCommand('touch /tmp/rate');
    await pc.executeCommand('touch /tmp/rate');
    const lost = Number(/^lost (\d+)$/m.exec(await pc.executeCommand('auditctl -s'))?.[1]);
    expect(lost).toBeGreaterThan(0);
  });

  it('refuses every rule change once locked, even through an auditd restart', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -w /etc/hosts -p w -k kept');
    await pc.executeCommand('auditctl -e 2');
    expect(await pc.executeCommand('auditctl -D')).toBe('Error deleting rule (Operation not permitted)\nThere was an error while processing parameters');
    await pc.executeCommand('systemctl restart auditd');
    expect(await pc.executeCommand('auditctl -l')).toBe('-w /etc/hosts -p w -k kept');
    expect(await pc.executeCommand('auditctl -s')).toMatch(/^enabled 2\n/);
  });

  it('wipes runtime-only rules on an auditd restart but reloads those of rules.d', async () => {
    const pc = await rootHost();
    await pc.executeCommand('echo "-w /etc/passwd -p wa -k durable" >> /etc/audit/rules.d/audit.rules');
    await pc.executeCommand('auditctl -w /etc/hosts -p w -k volatile');
    await pc.executeCommand('systemctl restart auditd');
    expect(await pc.executeCommand('auditctl -l')).toBe('-w /etc/passwd -p wa -k durable');
  });

  it('stops reading a rules file at the first faulty line and names it', async () => {
    const pc = await rootHost();
    await pc.executeCommand('printf "%s\\n" "-w /etc/hosts -p w" "-a bogus,exit" "-w /etc/shadow" > /tmp/r.rules');
    expect(await pc.executeCommand('auditctl -R /tmp/r.rules')).toBe('Append rule - bad keyword bogus,exit\nThere was an error in line 2 of /tmp/r.rules');
    expect(await pc.executeCommand('auditctl -l')).toBe('-w /etc/hosts -p w');
  });

  it('a watch still fires on a write', async () => {
    const pc = await rootHost();
    await pc.executeCommand('auditctl -w /etc/hosts -p w -k hosts_w');
    await pc.executeCommand('echo x >> /etc/hosts');
    expect(await pc.executeCommand('ausearch -k hosts_w -m SYSCALL')).toContain('type=SYSCALL');
  });
});
