/**
 * Scénario 7 — Réplication AD entre deux contrôleurs de domaine.
 *
 * Transcription littérale et fidèle : promotion de DC02 en DC additionnel
 * via Install-ADDSDomainController, topologie de réplication
 * (Get-ADReplicationConnection, repadmin /showrepl, /replsummary),
 * propagation d'un objet créé sur DC01 vers DC02 (repadmin /syncall),
 * et diagnostic des erreurs de réplication (Get-ADReplicationFailure,
 * EventIDs 1863/1864/1865, dcdiag /test:replications).
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { resetCounters, IPAddress, SubnetMask } from '@/network/core/types';
import { WindowsServer } from '@/network/devices/WindowsServer';
import { GenericSwitch } from '@/network/devices/GenericSwitch';
import { Cable } from '@/network/hardware/Cable';
import { resetDeviceCounters } from '@/network/devices/DeviceFactory';
import { Logger } from '@/network/core/Logger';
import { PowerShellSubShell } from '@/terminal/subshells/PowerShellSubShell';

beforeEach(() => {
  resetCounters();
  resetDeviceCounters();
  Logger.reset();
});

const ps = (d: WindowsServer) => PowerShellSubShell.create(d).subShell;
const run = async (sh: ReturnType<typeof ps>, l: string) => (await sh.processLine(l)).output.join('\n');

async function buildDc01(): Promise<WindowsServer> {
  const dc1 = new WindowsServer('DC01');
  dc1.getPorts()[0].configureIP(new IPAddress('192.168.10.10'), new SubnetMask('255.255.255.0'));
  dc1.setCurrentUser('Administrator');
  await run(ps(dc1), 'Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools -IncludeAllSubFeature -Restart:$false');
  await run(ps(dc1), 'Install-ADDSForest -DomainName "mandeng.lan" -DomainNetBiosName "MANDENG" -SafeModeAdministratorPassword (ConvertTo-SecureString "DSRM@Mandeng2025!" -AsPlainText -Force) -Force:$true');
  return dc1;
}

async function buildTwoDcs(): Promise<{ dc1: WindowsServer; dc2: WindowsServer }> {
  const dc1 = await buildDc01();
  const dc2 = new WindowsServer('DC02');
  const sw = new GenericSwitch('switch-generic', 'SW1');
  new Cable('c-dc1').connect(dc1.getPorts()[0], sw.getPorts()[0]);
  new Cable('c-dc2').connect(dc2.getPorts()[0], sw.getPorts()[1]);
  dc2.getPorts()[0].configureIP(new IPAddress('192.168.10.11'), new SubnetMask('255.255.255.0'));
  dc2.setCurrentUser('Administrator');
  await run(ps(dc2), 'Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools');
  await run(ps(dc2), [
    'Install-ADDSDomainController',
    '-DomainName "mandeng.lan"',
    '-Credential "Administrator:DSRM@Mandeng2025!"',
    '-Server "192.168.10.10"',
    '-InstallDns:$true',
    '-CreateDnsDelegation:$false',
    '-DatabasePath "C:\\Windows\\NTDS"',
    '-LogPath "C:\\Windows\\NTDS"',
    '-SysvolPath "C:\\Windows\\SYSVOL"',
    '-SafeModeAdministratorPassword (ConvertTo-SecureString "DSRM@Mandeng2025!" -AsPlainText -Force)',
    '-SiteName "Default-First-Site-Name"',
    '-Force:$true',
  ].join(' '));
  return { dc1, dc2 };
}

describe('Scénario 7 — réplication AD entre DC01 et DC02 (mandeng.lan)', () => {
  describe('promotion du second contrôleur de domaine (DC02)', () => {
    it('Install-ADDSDomainController promeut DC02 en DC additionnel du domaine mandeng.lan existant', async () => {
      const { dc2 } = await buildTwoDcs();
      const out = await run(ps(dc2), 'Get-ADDomainController -Filter *');
      expect(out).toContain('DC02');
    });

    it('DC02 réplique toute la base AD depuis DC01 lors de la promotion (les objets existants sont visibles)', async () => {
      const { dc2 } = await buildTwoDcs();
      const out = await run(ps(dc2), 'Get-ADDomainController -Filter *');
      expect(out).toContain('DC01');
      expect(out).toContain('DC02');
    });

    it('les rôles FSMO restent sur DC01 après la promotion de DC02 (pas de transfert automatique)', async () => {
      const { dc2 } = await buildTwoDcs();
      const out = await run(ps(dc2), 'Get-ADDomain | Select-Object InfrastructureMaster, PDCEmulator, RIDMaster');
      expect(out).toMatch(/DC01/);
    });
  });

  describe('vérification de la topologie de réplication', () => {
    it('Get-ADReplicationConnection -Filter * liste les partenaires de réplication de DC02', async () => {
      const { dc2 } = await buildTwoDcs();
      const out = await run(ps(dc2), 'Get-ADReplicationConnection -Filter * | Select-Object Name, AutoGenerated, ReplicateFromDirectoryServer, InterSiteTransportProtocol');
      expect(out).not.toMatch(/not recognized/i);
    });

    it('repadmin /showrepl DC01.mandeng.lan indique "was successful" pour la dernière tentative', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await dc1.executeCmdCommand('repadmin /showrepl DC01.mandeng.lan');
      expect(out).toMatch(/was successful/i);
    });

    it('repadmin /replsummary affiche Fails = 0 pour DC01 et DC02', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await dc1.executeCmdCommand('repadmin /replsummary');
      expect(out).toContain('DC01.mandeng.lan');
      expect(out).toContain('DC02.mandeng.lan');
      expect(out).toMatch(/Fails\s*0/);
    });
  });

  describe('test de propagation d\'un objet', () => {
    it('un utilisateur créé sur DC01 (-Server DC01.mandeng.lan) est visible sur DC02 après repadmin /syncall DC01 /AdeP', async () => {
      const { dc1, dc2 } = await buildTwoDcs();
      await run(ps(dc1), 'New-ADUser -Name "Test-Replication" -SamAccountName "test-repl" -Path "OU=Utilisateurs,OU=Mandeng,DC=mandeng,DC=lan" -Enabled $false -Server "DC01.mandeng.lan"');
      await dc1.executeCmdCommand('repadmin /syncall DC01 /AdeP');

      const out = await run(ps(dc2), 'Get-ADUser "test-repl" -Server "DC02.mandeng.lan" -ErrorAction SilentlyContinue');
      expect(out).toContain('test-repl');
    });

    it('replicateFrom() (le moteur de réplication réel du simulateur) propage effectivement un objet créé sur DC01 vers DC02', async () => {
      const { dc1, dc2 } = await buildTwoDcs();
      await run(ps(dc1), 'New-ADUser -Name "Test-Replication" -SamAccountName "test-repl" -Path "OU=Utilisateurs,OU=Mandeng,DC=mandeng,DC=lan" -Enabled $false -Server "DC01.mandeng.lan"');

      const result = dc2.replicateFrom('192.168.10.10');
      expect(result.ok).toBe(true);
      expect(result.applied).toBeGreaterThan(0);

      const out = await run(ps(dc2), 'Get-ADUser "test-repl" -Server "DC02.mandeng.lan"');
      expect(out).toContain('test-repl');
    });
  });

  describe('détection et diagnostic des erreurs de réplication', () => {
    it('Get-ADReplicationFailure -Scope Forest ne retourne aucun résultat en fonctionnement normal', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await run(ps(dc1), 'Get-ADReplicationFailure -Scope Forest | Select-Object Server, Partner, FirstFailureTime, FailureCount, LastError, FailureType');
      expect(out.trim()).toBe('');
    });

    it('Get-WinEvent recherche les EventIDs 1863/1864/1865/1083/1168 du journal Directory Service', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await run(ps(dc1), "Get-WinEvent -FilterHashtable @{ LogName = 'Directory Service'; Id = @(1863, 1864, 1865, 1083, 1168); StartTime = (Get-Date).AddHours(-24) } | Select-Object TimeCreated, Id, Message | Format-List");
      expect(out).not.toMatch(/not recognized/i);
    });

    it('dcdiag /test:replications /v exécute la batterie de tests de réplication et PASSED sur un lab sain', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await dc1.executeCmdCommand('dcdiag /test:replications /v');
      expect(out).toMatch(/passed test replications/i);
    });

    it('repadmin /syncall /AdeP force la synchronisation immédiate de toutes les partitions', async () => {
      const { dc1 } = await buildTwoDcs();
      const out = await dc1.executeCmdCommand('repadmin /syncall /AdeP');
      expect(out).toContain('DC=mandeng,DC=lan');
    });
  });
});
