const COMMON_AUTH = [
  '#',
  '# /etc/pam.d/common-auth - authentication settings common to all services',
  '#',
  '# This file is included from other service-specific PAM config files,',
  '# and should contain a list of the authentication modules that define',
  '# the central authentication scheme for use on the system',
  '# (e.g., /etc/shadow, LDAP, Kerberos, etc.).  The default is to use the',
  '# traditional Unix authentication mechanisms.',
  '#',
  '# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.',
  '# To take advantage of this, it is recommended that you configure any',
  '# local modules either before or after the default block, and use',
  '# pam-auth-update to manage selection of other modules.  See',
  '# pam-auth-update(8) for details.',
  '',
  '# here are the per-package modules (the "Primary" block)',
  'auth\t[success=1 default=ignore]\tpam_unix.so nullok',
  '# here\'s the fallback if no module succeeds',
  'auth\trequisite\t\t\tpam_deny.so',
  '# prime the stack with a positive return value if there isn\'t one already;',
  '# this avoids us returning an error just because nothing sets a success code',
  '# since the modules above will each just jump around',
  'auth\trequired\t\t\tpam_permit.so',
  '# and here are more per-package modules (the "Additional" block)',
  'auth\toptional\t\t\tpam_cap.so',
  '# end of pam-auth-update config',
  '',
].join('\n');

const COMMON_ACCOUNT = [
  '#',
  '# /etc/pam.d/common-account - authorization settings common to all services',
  '#',
  '# This file is included from other service-specific PAM config files,',
  '# and should contain a list of the authorization modules that define',
  '# the central access policy for use on the system.  The default is to',
  '# only deny service to users whose accounts are expired in /etc/shadow.',
  '#',
  '# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.',
  '# To take advantage of this, it is recommended that you configure any',
  '# local modules either before or after the default block, and use',
  '# pam-auth-update to manage selection of other modules.  See',
  '# pam-auth-update(8) for details.',
  '#',
  '',
  '# here are the per-package modules (the "Primary" block)',
  'account\t[success=1 new_authtok_reqd=done default=ignore]\tpam_unix.so ',
  '# here\'s the fallback if no module succeeds',
  'account\trequisite\t\t\tpam_deny.so',
  '# prime the stack with a positive return value if there isn\'t one already;',
  '# this avoids us returning an error just because nothing sets a success code',
  '# since the modules above will each just jump around',
  'account\trequired\t\t\tpam_permit.so',
  '# and here are more per-package modules (the "Additional" block)',
  '# end of pam-auth-update config',
  '',
].join('\n');

const COMMON_PASSWORD = [
  '#',
  '# /etc/pam.d/common-password - password-related modules common to all services',
  '#',
  '# This file is included from other service-specific PAM config files,',
  '# and should contain a list of modules that define the services to be',
  '# used to change user passwords.  The default is pam_unix.',
  '',
  '# Explanation of pam_unix options:',
  '# The "yescrypt" option enables',
  '#hashed passwords using the yescrypt algorithm, introduced in Debian',
  '#11.  Without this option, the default is Unix crypt.  Prior releases',
  '#used the option "sha512"; if a shadow password hash will be shared',
  '#between Debian 11 and older releases replace "yescrypt" with "sha512"',
  '#for compatibility .  The "obscure" option replaces the old',
  '#`OBSCURE_CHECKS_ENAB\' option in login.defs.  See the pam_unix manpage',
  '#for other options.',
  '',
  '# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.',
  '# To take advantage of this, it is recommended that you configure any',
  '# local modules either before or after the default block, and use',
  '# pam-auth-update to manage selection of other modules.  See',
  '# pam-auth-update(8) for details.',
  '',
  '# here are the per-package modules (the "Primary" block)',
  'password\trequisite\t\t\tpam_pwquality.so retry=3',
  'password\t[success=1 default=ignore]\tpam_unix.so obscure use_authtok try_first_pass yescrypt',
  '# here\'s the fallback if no module succeeds',
  'password\trequisite\t\t\tpam_deny.so',
  '# prime the stack with a positive return value if there isn\'t one already;',
  '# this avoids us returning an error just because nothing sets a success code',
  '# since the modules above will each just jump around',
  'password\trequired\t\t\tpam_permit.so',
  '# and here are more per-package modules (the "Additional" block)',
  '# end of pam-auth-update config',
  '',
].join('\n');

const COMMON_SESSION = [
  '#',
  '# /etc/pam.d/common-session - session-related modules common to all services',
  '#',
  '# This file is included from other service-specific PAM config files,',
  '# and should contain a list of modules that define tasks to be performed',
  '# at the start and end of sessions of *any* kind (both interactive and',
  '# non-interactive).',
  '#',
  '# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.',
  '# To take advantage of this, it is recommended that you configure any',
  '# local modules either before or after the default block, and use',
  '# pam-auth-update to manage selection of other modules.  See',
  '# pam-auth-update(8) for details.',
  '',
  '# here are the per-package modules (the "Primary" block)',
  'session\t[default=1]\t\t\tpam_permit.so',
  '# here\'s the fallback if no module succeeds',
  'session\trequisite\t\t\tpam_deny.so',
  '# prime the stack with a positive return value if there isn\'t one already;',
  '# this avoids us returning an error just because nothing sets a success code',
  '# since the modules above will each just jump around',
  'session\trequired\t\t\tpam_permit.so',
  '# The pam_umask module will set the umask according to the system default in',
  '# /etc/login.defs and user settings, solving the problem of different',
  '# umask settings with different shells, display managers, remote sessions etc.',
  '# See "man pam_umask".',
  'session optional\t\t\tpam_umask.so',
  '# and here are more per-package modules (the "Additional" block)',
  'session\trequired\tpam_unix.so ',
  'session\toptional\t\t\tpam_systemd.so ',
  '# end of pam-auth-update config',
  '',
].join('\n');

const COMMON_SESSION_NONINTERACTIVE = [
  '#',
  '# /etc/pam.d/common-session-noninteractive - session-related modules',
  '# common to all non-interactive services',
  '#',
  '# This file is included from other service-specific PAM config files,',
  '# and should contain a list of modules that define tasks to be performed',
  '# at the start and end of all non-interactive sessions.',
  '#',
  '# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.',
  '# To take advantage of this, it is recommended that you configure any',
  '# local modules either before or after the default block, and use',
  '# pam-auth-update to manage selection of other modules.  See',
  '# pam-auth-update(8) for details.',
  '',
  '# here are the per-package modules (the "Primary" block)',
  'session\t[default=1]\t\t\tpam_permit.so',
  '# here\'s the fallback if no module succeeds',
  'session\trequisite\t\t\tpam_deny.so',
  '# prime the stack with a positive return value if there isn\'t one already;',
  '# this avoids us returning an error just because nothing sets a success code',
  '# since the modules above will each just jump around',
  'session\trequired\t\t\tpam_permit.so',
  '# The pam_umask module will set the umask according to the system default in',
  '# /etc/login.defs and user settings, solving the problem of different',
  '# umask settings with different shells, display managers, remote sessions etc.',
  '# See "man pam_umask".',
  'session optional\t\t\tpam_umask.so',
  '# and here are more per-package modules (the "Additional" block)',
  'session\trequired\tpam_unix.so ',
  '# end of pam-auth-update config',
  '',
].join('\n');

const SSHD = [
  '# PAM configuration for the Secure Shell service',
  '',
  '# Standard Un*x authentication.',
  '@include common-auth',
  '',
  '# Disallow non-root logins when /etc/nologin exists.',
  'account    required     pam_nologin.so',
  '',
  '# Uncomment and edit /etc/security/access.conf if you need to set complex',
  '# access limits that are hard to express in sshd_config.',
  '# account  required     pam_access.so',
  '',
  '# Standard Un*x authorization.',
  '@include common-account',
  '',
  '# SELinux needs to be the first session rule.  This ensures that any',
  '# lingering context has been cleared.  Without this it is possible that a',
  '# module could execute code in the wrong domain.',
  'session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close',
  '',
  '# Set the loginuid process attribute.',
  'session    required     pam_loginuid.so',
  '',
  '# Create a new session keyring.',
  'session    optional     pam_keyinit.so force revoke',
  '',
  '# Standard Un*x session setup and teardown.',
  '@include common-session',
  '',
  '# Print the message of the day upon successful login.',
  '# This includes a dynamically generated part from /run/motd.dynamic',
  '# and a static (admin-editable) part from /etc/motd.',
  'session    optional     pam_motd.so  motd=/run/motd.dynamic',
  'session    optional     pam_motd.so noupdate',
  '',
  '# Print the status of the user\'s mailbox upon successful login.',
  'session    optional     pam_mail.so standard noenv # [1]',
  '',
  '# Set up user limits from /etc/security/limits.conf.',
  'session    required     pam_limits.so',
  '',
  '# Read environment variables from /etc/environment and',
  '# /etc/security/pam_env.conf.',
  'session    required     pam_env.so # [1]',
  '# In Debian 4.0 (etch), locale-related environment variables were moved to',
  '# /etc/default/locale, so read that as well.',
  'session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale',
  '',
  '# SELinux needs to intervene at login time to ensure that the process starts',
  '# in the proper default security context.  Only sessions which are intended',
  '# to run in the user\'s context should be run after this.',
  'session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open',
  '',
  '# Standard Un*x password updating.',
  '@include common-password',
  '',
].join('\n');

const LOGIN = [
  '#',
  '# The PAM configuration file for the Shadow `login\' service',
  '#',
  '',
  '# Enforce a minimal delay in case of failure (in microseconds).',
  '# (Replaces the `FAIL_DELAY\' setting from login.defs)',
  '# Note that other modules may require another minimal delay. (for example,',
  '# to disable any delay, you should add the nodelay option to pam_unix)',
  'auth       optional   pam_faildelay.so  delay=3000000',
  '',
  '# Outputs an issue file prior to each login prompt (Replaces the',
  '# ISSUE_FILE option from login.defs). Uncomment for use',
  '# auth       required   pam_issue.so issue=/etc/issue',
  '',
  '# Disallows root logins except on tty\'s listed in /etc/securetty',
  '# (Replaces the `CONSOLE\' setting from login.defs)',
  '#',
  '# With the default control of this module:',
  '#   [success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die]',
  '# root will not be prompted for a password on insecure lines.',
  '# if an invalid username is entered, a password is prompted (but login',
  '# will eventually be rejected)',
  '#',
  '# You can change it to a "requisite" module if you think root may mis-type',
  '# her login and should not be prompted for a password in that case. But be',
  '# careful: this could leave an information leak.',
  '#',
  '# auth       [success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die] pam_securetty.so',
  '',
  '# Disallows other than root logins when /etc/nologin exists',
  '# (Replaces the `NOLOGINS_FILE\' option from login.defs)',
  'auth       requisite  pam_nologin.so',
  '',
  '# SELinux needs to be the first session rule.  This ensures that any',
  '# lingering context has been cleared.  Without this it is possible that a',
  '# module could execute code in the wrong domain.',
  '# When the module is present, "required" would be sufficient (When SELinux',
  '# is disabled, this returns success.)',
  'session [success=ok ignore=ignore module_unknown=ignore default=bad] pam_selinux.so close',
  '',
  '# Sets the loginuid process attribute',
  'session    required     pam_loginuid.so',
  '',
  '# Prints the message of the day upon successful login.',
  'session    optional   pam_motd.so motd=/run/motd.dynamic',
  'session    optional   pam_motd.so noupdate',
  '',
  '# Prints the last login info upon successful login',
  'session    optional   pam_lastlog.so',
  '',
  '# Prints the status of the user\'s mailbox upon successful login',
  'session    optional   pam_mail.so standard',
  '',
  '# Create a new session keyring.',
  'session    optional   pam_keyinit.so force revoke',
  '',
  '# Standard Un*x authentication.',
  '@include common-auth',
  '',
  '# This allows certain extra groups to be granted to a user',
  '# based on things like time of day, tty, service, and user.',
  '# Please edit /etc/security/group.conf to fit your needs',
  '# (Replaces the `CONSOLE_GROUPS\' option in login.defs)',
  'auth       optional   pam_group.so',
  '',
  '# Uncomment and edit /etc/security/time.conf if you need to set',
  '# time restrainst on logins.',
  '# (Replaces the `PORTTIME_CHECKS_ENAB\' option from login.defs',
  '# as well as /etc/porttime)',
  '# account    requisite  pam_time.so',
  '',
  '# Uncomment and edit /etc/security/access.conf if you need to',
  '# set access limits.',
  '# (Replaces /etc/login.access file)',
  '# account  required       pam_access.so',
  '',
  '# Sets up user limits according to /etc/security/limits.conf',
  '# (Replaces the use of /etc/limits in old login)',
  'session    required   pam_limits.so',
  '',
  '# Standard Un*x account and session',
  '@include common-account',
  '@include common-session',
  '@include common-password',
  '',
].join('\n');

const SU = [
  '#',
  '# The PAM configuration file for the Shadow `su\' service',
  '#',
  '',
  '# This allows root to su without passwords (normal operation)',
  'auth       sufficient pam_rootok.so',
  '',
  '# Uncomment this to force users to be a member of group root',
  '# before they can use `su\'. You can also add "group=foo"',
  '# to the end of this line if you want to use a group other',
  '# than the default "root" (but this may have side effect of',
  '# denying "root" user, unless she\'s a member of "foo" or explicitly',
  '# permitted earlier by e.g. "sufficient pam_rootok.so").',
  '# (Replaces the `SU_WHEEL_ONLY\' option from login.defs)',
  '# auth       required   pam_wheel.so',
  '',
  '# Uncomment this if you want wheel members to be able to',
  '# su without a password.',
  '# auth       sufficient pam_wheel.so trust',
  '',
  '# Uncomment this if you want members of a specific group to not',
  '# be allowed to use su at all.',
  '# auth       required   pam_wheel.so deny group=nosu',
  '',
  '# Uncomment and edit /etc/security/time.conf if you need to set',
  '# time restrainst on su usage.',
  '# (Replaces the `PORTTIME_CHECKS_ENAB\' option from login.defs',
  '# as well as /etc/porttime)',
  '# account    requisite  pam_time.so',
  '',
  '# This module parses environment configuration file(s)',
  '# and also allows you to use an extended config',
  '# file /etc/security/pam_env.conf.',
  '#',
  '# parsing /etc/environment needs "readenv=1"',
  'session       required   pam_env.so readenv=1',
  '# locale variables are also kept into /etc/default/locale in etch',
  '# reading this file *in addition to /etc/environment* does not hurt',
  'session       required   pam_env.so readenv=1 envfile=/etc/default/locale',
  '',
  '# Defines the MAIL environment variable',
  '# However, userdel also needs MAIL_DIR and MAIL_FILE variables',
  '# in /etc/login.defs to make sure that removing a user',
  '# also removes the user\'s mail spool file.',
  '# See comments in /etc/login.defs',
  '#',
  '# "nopen" stands to avoid reporting new mail when su\'ing to another user',
  'session    optional   pam_mail.so nopen',
  '',
  '# Sets up user limits according to /etc/security/limits.conf',
  '# (Replaces the use of /etc/limits in old login)',
  'session    required   pam_limits.so',
  '',
  '# The standard Unix authentication modules, used with',
  '# NIS (man nsswitch) as well as normal /etc/passwd and',
  '# /etc/shadow entries.',
  '@include common-auth',
  '@include common-account',
  '@include common-session',
  '',
].join('\n');

const SU_L = [
  '# This file is used by su -l / su - (login shell)',
  '',
  'auth       sufficient pam_rootok.so',
  '',
  'session       required   pam_env.so readenv=1',
  'session       required   pam_env.so readenv=1 envfile=/etc/default/locale',
  '',
  'session    optional   pam_mail.so nopen',
  '',
  'session    required   pam_limits.so',
  '',
  '@include common-auth',
  '@include common-account',
  '@include common-session',
  '',
].join('\n');

const SUDO = [
  '#%PAM-1.0',
  '',
  'session    required   pam_env.so readenv=1 user_readenv=0',
  'session    required   pam_env.so readenv=1 envfile=/etc/default/locale user_readenv=0',
  '@include common-auth',
  '@include common-account',
  '@include common-session-noninteractive',
  '',
].join('\n');

const PASSWD = [
  '#',
  '# The PAM configuration file for the Shadow `passwd\' service',
  '#',
  '',
  '@include common-password',
  '',
].join('\n');

const OTHER = [
  '#',
  '# /etc/pam.d/other - specify the PAM fallback behaviour',
  '#',
  '# Note that this file is used for any unspecified service; for example',
  '#if /etc/pam.d/cron  specifies no session modules but cron calls',
  '#pam_open_session, the session module out of /etc/pam.d/other is',
  '#used.  If you really want nothing to happen then use pam_permit.so or',
  '#pam_deny.so as appropriate.',
  '',
  '# We fall back to the system default in /etc/pam.d/common-*',
  '#',
  '',
  '@include common-auth',
  '@include common-account',
  '@include common-password',
  '@include common-session',
  '',
].join('\n');

const CRON = [
  '# The PAM configuration file for the cron daemon',
  '',
  '@include common-auth',
  '',
  '# Sets up user limits according to /etc/security/limits.conf',
  '# (Replaces the use of /etc/limits in old login)',
  'session    required   pam_limits.so',
  '',
  '# Read environment variables from pam_env\'s default files, /etc/environment',
  '# and /etc/security/pam_env.conf.',
  'session       required   pam_env.so',
  '',
  '# In addition, read system locale information',
  'session       required   pam_env.so envfile=/etc/default/locale',
  '',
  '@include common-account',
  '@include common-session-noninteractive',
  '',
  '# Sets up user limits, please define limits for cron tasks',
  '# through /etc/security/limits.conf',
  'session    required   pam_limits.so',
  '',
].join('\n');

const LIMITS_CONF = [
  '# /etc/security/limits.conf',
  '#',
  '#Each line describes a limit for a user in the form:',
  '#',
  '#<domain>        <type>  <item>  <value>',
  '#',
  '#Where:',
  '#<domain> can be:',
  '#        - a user name',
  '#        - a group name, with @group syntax',
  '#        - the wildcard *, for default entry',
  '#        - the wildcard %, can be also used with %group syntax,',
  '#                 for maxlogin limit',
  '#        - NOTE: group and wildcard limits are not applied to root.',
  '#          To apply a limit to the root user, <domain> must be',
  '#          the literal username root.',
  '#',
  '#<type> can have the two values:',
  '#        - "soft" for enforcing the soft limits',
  '#        - "hard" for enforcing hard limits',
  '#',
  '#<item> can be one of the following:',
  '#        - core - limits the core file size (KB)',
  '#        - data - max data size (KB)',
  '#        - fsize - maximum filesize (KB)',
  '#        - memlock - max locked-in-memory address space (KB)',
  '#        - nofile - max number of open file descriptors',
  '#        - rss - max resident set size (KB)',
  '#        - stack - max stack size (KB)',
  '#        - cpu - max CPU time (MIN)',
  '#        - nproc - max number of processes',
  '#        - as - address space limit (KB)',
  '#        - maxlogins - max number of logins for this user',
  '#        - maxsyslogins - max number of logins on the system',
  '#        - priority - the priority to run user process with',
  '#        - locks - max number of file locks the user can hold',
  '#        - sigpending - max number of pending signals',
  '#        - msgqueue - max memory used by POSIX message queues (bytes)',
  '#        - nice - max nice priority allowed to raise to values: [-20, 19]',
  '#        - rtprio - max realtime priority',
  '#',
  '#<domain>      <type>  <item>         <value>',
  '#',
  '',
  '#*               soft    core            0',
  '#root            hard    core            100000',
  '#*               hard    rss             10000',
  '#@student        hard    nproc           20',
  '#@faculty        soft    nproc           20',
  '#@faculty        hard    nproc           50',
  '#ftp             hard    nproc           0',
  '#ftp             -       chroot          /ftp',
  '#@student        -       maxlogins       4',
  '',
  '# End of file',
  '',
].join('\n');

const PAM_ENV_CONF = [
  '#',
  '# This is the configuration file for pam_env(8), see its manual page for',
  '# details.',
  '#',
  '',
  '# Defines the DISPLAY and REMOTEHOST variables from PAM items.',
  '#',
  '#REMOTEHOST\tDEFAULT=localhost\tOVERRIDE=@{PAM_RHOST}',
  '#DISPLAY\tDEFAULT=${REMOTEHOST}:0.0\tOVERRIDE=${DISPLAY}',
  '',
].join('\n');

const ACCESS_CONF = [
  '# Login access control table.',
  '#',
  '# Comment line must have a "#" sign as the first non-blank character.',
  '#',
  '# Format of the login access control table is three fields separated by a',
  '# ":" character:',
  '#',
  '# [Note, if you supply a \'fieldsep=|\' argument to the pam_access.so',
  '# module, you can change the field separation character to be',
  '# \'|\'. This is useful for configurations where you are trying to use',
  '# pam_access with X applications that provide PAM_TTY values that are',
  '# the display variable like "host:0".]',
  '#',
  '#\tpermission : users/groups : origins',
  '#',
  '# The first field should be a "+" (access granted) or "-" (access denied)',
  '# character.',
  '#',
  '# The second field should be a list of one or more login names, group',
  '# names, or ALL (which always matches). To differentiate user entries from',
  '# group entries, group entries should be surrounded by parentheses, e.g.',
  '# (group).',
  '#',
  '# The third field should be a list of one or more tty names (for',
  '# non-networked logins), host names, domain names (begin with "."), host',
  '# addresses, internet network numbers (end with "."), ALL (which always',
  '# matches) or LOCAL.  LOCAL matches any string that does not contain a "."',
  '# character.',
  '#',
  '# The EXCEPT operator makes it possible to write very compact rules.',
  '#',
  '# Disallow console logins to all but a few accounts.',
  '#',
  '#-:ALL EXCEPT (wheel) shutdown sync:LOCAL',
  '',
].join('\n');

const TIME_CONF = [
  '# this is an example configuration file for the pam_time module. Its syntax',
  '# was initially based heavily on that of the shadow package (shadow-960129).',
  '#',
  '# the syntax of the lines is as follows:',
  '#',
  '#       services;ttys;users;times',
  '#',
  '# white space is ignored and lines maybe extended with \'\\\\n\' (escaped',
  '# newlines).',
  '#',
  '#login ; tty* & !ttyp* ; !root & !guest ; !Al0000-2400',
  '',
].join('\n');

const GROUP_CONF = [
  '# /etc/security/group.conf',
  '#',
  '# this is the configuration file for the pam_group module.',
  '#',
  '# the syntax of the lines is as follows:',
  '#',
  '#       services;ttys;users;times;groups',
  '#',
  '#login;tty*&!ttyp*;alice|bob;!Wk0900-1800;dialout',
  '',
].join('\n');

const ENVIRONMENT = 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"\n';

export interface UbuntuPamFile {
  readonly path: string;
  readonly content: string;
  readonly mode: number;
}

export const UBUNTU_PAM_FILES: readonly UbuntuPamFile[] = [
  { path: '/etc/pam.d/common-auth', content: COMMON_AUTH, mode: 0o644 },
  { path: '/etc/pam.d/common-account', content: COMMON_ACCOUNT, mode: 0o644 },
  { path: '/etc/pam.d/common-session', content: COMMON_SESSION, mode: 0o644 },
  { path: '/etc/pam.d/common-session-noninteractive', content: COMMON_SESSION_NONINTERACTIVE, mode: 0o644 },
  { path: '/etc/pam.d/sshd', content: SSHD, mode: 0o644 },
  { path: '/etc/pam.d/login', content: LOGIN, mode: 0o644 },
  { path: '/etc/pam.d/common-password', content: COMMON_PASSWORD, mode: 0o644 },
  { path: '/etc/pam.d/su', content: SU, mode: 0o644 },
  { path: '/etc/pam.d/su-l', content: SU_L, mode: 0o644 },
  { path: '/etc/pam.d/sudo', content: SUDO, mode: 0o644 },
  { path: '/etc/pam.d/passwd', content: PASSWD, mode: 0o644 },
  { path: '/etc/pam.d/chpasswd', content: PASSWD, mode: 0o644 },
  { path: '/etc/pam.d/chfn', content: 'auth       sufficient pam_rootok.so\n@include common-auth\n@include common-account\n@include common-session\n', mode: 0o644 },
  { path: '/etc/pam.d/chsh', content: 'auth       required   pam_shells.so\nauth       sufficient pam_rootok.so\n@include common-auth\n@include common-account\n@include common-session\n', mode: 0o644 },
  { path: '/etc/pam.d/cron', content: CRON, mode: 0o644 },
  { path: '/etc/pam.d/other', content: OTHER, mode: 0o644 },
  { path: '/etc/environment', content: ENVIRONMENT, mode: 0o644 },
  { path: '/etc/security/limits.conf', content: LIMITS_CONF, mode: 0o644 },
  { path: '/etc/security/pam_env.conf', content: PAM_ENV_CONF, mode: 0o644 },
  { path: '/etc/security/access.conf', content: ACCESS_CONF, mode: 0o644 },
  { path: '/etc/security/time.conf', content: TIME_CONF, mode: 0o644 },
  { path: '/etc/security/group.conf', content: GROUP_CONF, mode: 0o644 },
  { path: '/etc/security/opasswd', content: '', mode: 0o600 },
];
