import {
  address, choice, count, enable, reference, word,
  type FortiTableSpec,
} from './types';

const SEVERITIES = [
  { keyword: 'emergency', description: 'Emergency level.' },
  { keyword: 'alert', description: 'Alert level.' },
  { keyword: 'critical', description: 'Critical level.' },
  { keyword: 'error', description: 'Error level.' },
  { keyword: 'warning', description: 'Warning level.' },
  { keyword: 'notification', description: 'Notification level.' },
  { keyword: 'information', description: 'Information level.' },
  { keyword: 'debug', description: 'Debug level.' },
];

const FORMATS = [
  { keyword: 'default', description: 'Syslog format in key=value pairs.' },
  { keyword: 'csv', description: 'Syslog format in comma separated values.' },
  { keyword: 'cef', description: 'Common Event Format.' },
  { keyword: 'rfc5424', description: 'RFC 5424 syslog format.' },
];

function syslogCollector(
  path: readonly string[], renderOrder: number, help: string,
): FortiTableSpec {
  return {
    path,
    kind: 'object',
    scope: 'vdom',
    accessGroup: 'loggrp',
    renderOrder,
    help,
    attributes: [
      enable('status', 'Enable/disable remote syslog logging.'),
      word('server', 'Address of the remote syslog server.'),
      count('port', 'Server listen port.', 0, 65535, 514),
      choice('mode', 'Remote syslog logging over UDP/Reliable TCP.', [
        { keyword: 'udp', description: 'Enable syslogging over UDP.' },
        { keyword: 'legacy-reliable', description: 'Enable legacy reliable syslogging.' },
        { keyword: 'reliable', description: 'Enable reliable syslogging (RFC 6587).' },
      ], 'udp'),
      choice('facility', 'Remote syslog facility.', [
        { keyword: 'kernel', description: 'Kernel messages.' },
        { keyword: 'user', description: 'Random user-level messages.' },
        { keyword: 'daemon', description: 'System daemons.' },
        { keyword: 'syslog', description: 'Messages generated by syslogd.' },
        { keyword: 'local7', description: 'Reserved for local use.' },
      ], 'local7'),
      choice('format', 'Log format.', FORMATS, 'default'),
      address('source-ip', 'Source IP address of syslog.'),
      reference('interface', 'Specify outgoing interface to reach server.',
        ['system interface']),
      enable('enc-algorithm', 'Enable/disable reliable syslogging with TLS encryption.'),
    ],
    children: [
      {
        path: ['filter'],
        kind: 'object',
        scope: 'vdom',
        accessGroup: 'loggrp',
        renderOrder: renderOrder + 1,
        help: 'Filters for remote system server.',
        attributes: [
          choice('severity', 'Lowest severity level to log.', SEVERITIES, 'information'),
          enable('forward-traffic', 'Enable/disable forward traffic logging.', true),
          enable('local-traffic', 'Enable/disable local in or out traffic logging.'),
          enable('multicast-traffic', 'Enable/disable multicast traffic logging.', true),
          enable('sniffer-traffic', 'Enable/disable sniffer traffic logging.', true),
        ],
        onCommit() {},
      },
    ],
    onCommit() {},
  };
}

export const LOG_SYSLOGD = syslogCollector(
  ['log', 'syslogd'], 300, 'Global settings for remote syslog server.');
export const LOG_SYSLOGD2 = syslogCollector(
  ['log', 'syslogd2'], 310, 'Global settings for remote syslog server.');
export const LOG_SYSLOGD3 = syslogCollector(
  ['log', 'syslogd3'], 320, 'Global settings for remote syslog server.');
export const LOG_SYSLOGD4 = syslogCollector(
  ['log', 'syslogd4'], 330, 'Global settings for remote syslog server.');

export const LOG_MEMORY_SETTING: FortiTableSpec = {
  path: ['log', 'memory', 'setting'],
  kind: 'object',
  scope: 'vdom',
  accessGroup: 'loggrp',
  renderOrder: 340,
  help: 'Settings for memory buffer.',
  attributes: [
    enable('status', 'Enable/disable logging to the FortiGate memory.', true),
    count('diskfull', 'Action to take when memory is full.', 0, 1, 0),
  ],
  onCommit(object, context) {
    context.device.applyMemoryLog({
      enabled: object.effective('status')[0] !== 'disable',
    });
  },
};

export const LOG_MEMORY_GLOBAL_SETTING: FortiTableSpec = {
  path: ['log', 'memory', 'global-setting'],
  kind: 'object',
  scope: 'global',
  accessGroup: 'loggrp',
  renderOrder: 350,
  help: 'Global settings for memory logging.',
  attributes: [
    count('max-lines', 'Maximum number of lines in the memory log.', 100, 20000, 1000),
    count('full-first-warning-threshold',
      'Log full first warning threshold as a percentage.', 1, 98, 75),
  ],
  onCommit(object, context) {
    const lines = Number.parseInt(object.effective('max-lines')[0] ?? '', 10);
    context.device.applyMemoryLog({
      capacity: Number.isFinite(lines) ? lines : undefined,
    });
  },
};

export const LOG_SETTING: FortiTableSpec = {
  path: ['log', 'setting'],
  kind: 'object',
  scope: 'vdom',
  accessGroup: 'loggrp',
  renderOrder: 360,
  help: 'Configure general log settings.',
  attributes: [
    enable('fwpolicy-implicit-log',
      'Enable/disable implicit firewall policy logging.'),
    enable('local-in-allow', 'Enable/disable local-in-allow logging.'),
    enable('local-in-deny-unicast', 'Enable/disable local-in-deny-unicast logging.'),
    enable('local-out', 'Enable/disable local-out logging.'),
    enable('log-invalid-packet', 'Enable/disable invalid packet traffic logging.'),
    enable('resolve-ip', 'Enable/disable adding resolved domain names to traffic logs.'),
  ],
  onCommit() {},
};

export const LOG_SPECS: readonly FortiTableSpec[] = Object.freeze([
  LOG_SYSLOGD,
  LOG_SYSLOGD2,
  LOG_SYSLOGD3,
  LOG_SYSLOGD4,
  LOG_MEMORY_SETTING,
  LOG_MEMORY_GLOBAL_SETTING,
  LOG_SETTING,
]);
