/**
 * Category: Static Routing & OSPF
 *
 * Probes ip route-static, default route, display ip routing-table,
 * OSPF process, router-id, area, network, silent-interface,
 * display ospf brief/peer/lsdb/interface, and undo ospf.
 */

import type { HuaweiDiagnosticCase } from '../types';
import { assert } from '../engine';

export const routingChecks: HuaweiDiagnosticCase[] = [

  // ─── Static routes ───────────────────────────────────────────────
  {
    id: 'RT-001', category: 'Routing', device: 'router',
    description: 'ip route-static adds a static route',
    setup: ['system-view'],
    cmd: 'ip route-static 192.168.10.0 255.255.255.0 10.0.0.2',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-002', category: 'Routing', device: 'router',
    description: 'display ip routing-table shows added static route',
    setup: ['system-view', 'ip route-static 10.10.10.0 255.255.255.0 172.16.0.1'],
    cmd: 'display ip routing-table',
    assert: assert.contains('10.10.10.0'),
    severity: 'FAIL',
  },
  {
    id: 'RT-003', category: 'Routing', device: 'router',
    description: 'static route shows "Static" or "S" in routing table',
    setup: ['system-view', 'ip route-static 10.20.0.0 255.255.0.0 10.0.0.1'],
    cmd: 'display ip routing-table',
    assert: assert.any(assert.contains('Static'), assert.contains(' S ')),
    severity: 'WARN',
    vrpNote: 'Real VRP: static routes marked with "S" and preference 60',
  },
  {
    id: 'RT-004', category: 'Routing', device: 'router',
    description: 'Default route 0.0.0.0/0 configurable',
    setup: ['system-view'],
    cmd: 'ip route-static 0.0.0.0 0.0.0.0 10.0.0.254',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-005', category: 'Routing', device: 'router',
    description: 'Default route appears in routing table',
    setup: ['system-view', 'ip route-static 0.0.0.0 0.0.0.0 10.0.0.1'],
    cmd: 'display ip routing-table',
    assert: assert.any(assert.contains('0.0.0.0'), assert.contains('default')),
    severity: 'WARN',
  },
  {
    id: 'RT-006', category: 'Routing', device: 'router',
    description: 'ip route-static with preference parameter',
    setup: ['system-view'],
    cmd: 'ip route-static 172.16.0.0 255.255.0.0 10.0.0.1 preference 100',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: preference (administrative distance) for static routes is 60 by default',
  },
  {
    id: 'RT-007', category: 'Routing', device: 'router',
    description: 'undo ip route-static removes the route',
    setup: ['system-view', 'ip route-static 10.30.0.0 255.255.255.0 10.0.0.2'],
    cmd: 'undo ip route-static 10.30.0.0 255.255.255.0 10.0.0.2',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-008', category: 'Routing', device: 'router',
    description: 'IPv6 static route configurable',
    setup: ['system-view', 'ipv6'],
    cmd: 'ipv6 route-static 2001:db8:1:: 48 2001:db8::1',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: ipv6 route-static <prefix> <len> <nexthop>',
  },

  // ─── RIP ─────────────────────────────────────────────────────────
  {
    id: 'RT-009', category: 'Routing', device: 'router',
    description: 'rip 1 enters RIP view',
    setup: ['system-view'],
    cmd: 'rip 1',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-010', category: 'Routing', device: 'router',
    description: 'display rip shows RIP status',
    setup: ['system-view', 'rip 1'],
    cmd: 'display rip',
    assert: assert.any(assert.contains('RIP'), assert.contains('rip'), assert.notEmpty()),
    severity: 'WARN',
  },

  // ─── OSPF ────────────────────────────────────────────────────────
  {
    id: 'RT-011', category: 'OSPF', device: 'router',
    description: 'ospf 1 enters OSPF view',
    setup: ['system-view'],
    cmd: 'ospf 1',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-012', category: 'OSPF', device: 'router',
    description: 'router-id sets OSPF router ID',
    setup: ['system-view', 'ospf 1'],
    cmd: 'router-id 1.1.1.1',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-013', category: 'OSPF', device: 'router',
    description: 'area 0 enters OSPF area view',
    setup: ['system-view', 'ospf 1'],
    cmd: 'area 0',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-014', category: 'OSPF', device: 'router',
    description: 'network advertises subnet in area',
    setup: ['system-view', 'ospf 1', 'area 0'],
    cmd: 'network 192.168.1.0 0.0.0.255',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'RT-015', category: 'OSPF', device: 'router',
    description: 'display ospf brief shows OSPF process',
    setup: ['system-view', 'ospf 1', 'router-id 1.1.1.1', 'area 0', 'network 10.0.0.0 0.0.0.255', 'return'],
    cmd: 'display ospf brief',
    assert: assert.any(assert.contains('OSPF'), assert.contains('Router ID'), assert.contains('ospf')),
    severity: 'FAIL',
  },
  {
    id: 'RT-016', category: 'OSPF', device: 'router',
    description: 'display ospf peer shows (empty or peer list)',
    setup: ['system-view', 'ospf 1', 'area 0', 'return'],
    cmd: 'display ospf peer',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
    vrpNote: 'Real VRP: shows OSPF neighbour table (empty if no neighbors)',
  },
  {
    id: 'RT-017', category: 'OSPF', device: 'router',
    description: 'display ospf lsdb shows link state database header',
    setup: ['system-view', 'ospf 1', 'area 0', 'return'],
    cmd: 'display ospf lsdb',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
  },
  {
    id: 'RT-018', category: 'OSPF', device: 'router',
    description: 'display ospf interface shows OSPF interface state',
    setup: ['system-view', 'ospf 1', 'area 0', 'return'],
    cmd: 'display ospf interface',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
  },
  {
    id: 'RT-019', category: 'OSPF', device: 'router',
    description: 'silent-interface suppresses OSPF hello on interface',
    setup: ['system-view', 'ospf 1'],
    cmd: 'silent-interface GE0/0/1',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: suppresses OSPF hellos on the interface',
  },
  {
    id: 'RT-020', category: 'OSPF', device: 'router',
    description: 'undo silent-interface re-enables OSPF hellos',
    setup: ['system-view', 'ospf 1', 'silent-interface GE0/0/1'],
    cmd: 'undo silent-interface GE0/0/1',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-021', category: 'OSPF', device: 'router',
    description: 'default-route-advertise injects default route into OSPF',
    setup: ['system-view', 'ospf 1'],
    cmd: 'default-route-advertise',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-022', category: 'OSPF', device: 'router',
    description: 'area stub configures stub area',
    setup: ['system-view', 'ospf 1', 'area 1'],
    cmd: 'stub',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-023', category: 'OSPF', device: 'router',
    description: 'undo ospf removes the OSPF process',
    setup: ['system-view', 'ospf 1'],
    cmd: 'undo ospf 1',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'RT-024', category: 'OSPF', device: 'router',
    description: 'display current-configuration shows ospf block',
    setup: ['system-view', 'ospf 1', 'router-id 2.2.2.2', 'area 0', 'network 10.0.0.0 0.0.0.255', 'return'],
    cmd: 'display current-configuration',
    assert: assert.contains('ospf'),
    severity: 'WARN',
  },
];
