/**
 * Category: IPSec / IKE
 *
 * Probes IKE proposal, IKE peer, IPSec proposal, IPSec policy,
 * interface IPSec policy binding, display commands, and NAT traversal.
 */

import type { HuaweiDiagnosticCase } from '../types';
import { assert } from '../engine';

export const ipsecChecks: HuaweiDiagnosticCase[] = [

  // ─── IKE proposal ────────────────────────────────────────────────
  {
    id: 'IKE-001', category: 'IPSec', device: 'router',
    description: 'ike proposal 1 creates IKE proposal view',
    setup: ['system-view'],
    cmd: 'ike proposal 1',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: ike proposal <num> enters IKEv1 proposal configuration',
  },
  {
    id: 'IKE-002', category: 'IPSec', device: 'router',
    description: 'encryption-algorithm sets IKE encryption',
    setup: ['system-view', 'ike proposal 1'],
    cmd: 'encryption-algorithm aes-128',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: aes-128, aes-256, des, 3des supported',
  },
  {
    id: 'IKE-003', category: 'IPSec', device: 'router',
    description: 'authentication-algorithm sets IKE hash',
    setup: ['system-view', 'ike proposal 1'],
    cmd: 'authentication-algorithm sha2-256',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: md5, sha1, sha2-256, sha2-384, sha2-512',
  },
  {
    id: 'IKE-004', category: 'IPSec', device: 'router',
    description: 'authentication-method sets IKE auth mode',
    setup: ['system-view', 'ike proposal 1'],
    cmd: 'authentication-method pre-share',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: pre-share or rsa-sig',
  },
  {
    id: 'IKE-005', category: 'IPSec', device: 'router',
    description: 'dh group2 sets Diffie-Hellman group',
    setup: ['system-view', 'ike proposal 1'],
    cmd: 'dh group2',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: group1/2/5/14 supported for IKEv1',
  },
  {
    id: 'IKE-006', category: 'IPSec', device: 'router',
    description: 'sa duration sets IKE SA lifetime',
    setup: ['system-view', 'ike proposal 1'],
    cmd: 'sa duration 86400',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: IKE SA lifetime in seconds (default 86400)',
  },
  {
    id: 'IKE-007', category: 'IPSec', device: 'router',
    description: 'display ike proposal shows configured proposals',
    setup: ['system-view', 'ike proposal 1', 'encryption-algorithm aes-128', 'quit'],
    cmd: 'display ike proposal',
    assert: assert.any(
      assert.contains('1'),
      assert.contains('aes'),
      assert.contains('proposal'),
      assert.notContains('Unrecognized'),
    ),
    severity: 'WARN',
    vrpNote: 'Real VRP: shows proposal number, encryption, hash, DH group, lifetime',
  },

  // ─── IKE peer ────────────────────────────────────────────────────
  {
    id: 'IKE-008', category: 'IPSec', device: 'router',
    description: 'ike peer PEER_A v1 creates IKE peer',
    setup: ['system-view'],
    cmd: 'ike peer PEER_A v1',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: ike peer <name> v1|v2 specifies IKE version',
  },
  {
    id: 'IKE-009', category: 'IPSec', device: 'router',
    description: 'remote-address sets tunnel endpoint IP',
    setup: ['system-view', 'ike peer PEER_A v1'],
    cmd: 'remote-address 203.0.113.1',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'IKE-010', category: 'IPSec', device: 'router',
    description: 'pre-shared-key sets PSK for IKE peer',
    setup: ['system-view', 'ike peer PEER_A v1'],
    cmd: 'pre-shared-key cipher Huawei@123',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: cipher keyword means key is stored encrypted in config',
  },
  {
    id: 'IKE-011', category: 'IPSec', device: 'router',
    description: 'ike-proposal references a numbered IKE proposal',
    setup: ['system-view', 'ike proposal 1', 'quit', 'ike peer PEER_A v1'],
    cmd: 'ike-proposal 1',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'IKE-012', category: 'IPSec', device: 'router',
    description: 'local-address sets local tunnel endpoint',
    setup: ['system-view', 'ike peer PEER_A v1'],
    cmd: 'local-address 198.51.100.1',
    assert: assert.empty(),
    severity: 'WARN',
  },
  {
    id: 'IKE-013', category: 'IPSec', device: 'router',
    description: 'display ike peer shows configured peers',
    setup: ['system-view', 'ike peer PEER_A v1', 'remote-address 203.0.113.1', 'quit'],
    cmd: 'display ike peer',
    assert: assert.any(
      assert.contains('PEER_A'),
      assert.contains('peer'),
      assert.contains('203.0.113.1'),
      assert.notContains('Unrecognized'),
    ),
    severity: 'WARN',
  },

  // ─── IPSec proposal ──────────────────────────────────────────────
  {
    id: 'IKE-014', category: 'IPSec', device: 'router',
    description: 'ipsec proposal PROP1 creates IPSec proposal',
    setup: ['system-view'],
    cmd: 'ipsec proposal PROP1',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: ipsec proposal <name> enters proposal view',
  },
  {
    id: 'IKE-015', category: 'IPSec', device: 'router',
    description: 'transform esp sets ESP as transform protocol',
    setup: ['system-view', 'ipsec proposal PROP1'],
    cmd: 'transform esp',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: esp, ah, or esp-new; esp is most common',
  },
  {
    id: 'IKE-016', category: 'IPSec', device: 'router',
    description: 'esp encryption-algorithm sets ESP cipher',
    setup: ['system-view', 'ipsec proposal PROP1'],
    cmd: 'esp encryption-algorithm aes-128',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'IKE-017', category: 'IPSec', device: 'router',
    description: 'esp authentication-algorithm sets ESP HMAC',
    setup: ['system-view', 'ipsec proposal PROP1'],
    cmd: 'esp authentication-algorithm sha2-256',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'IKE-018', category: 'IPSec', device: 'router',
    description: 'display ipsec proposal shows configured proposals',
    setup: ['system-view', 'ipsec proposal PROP1', 'transform esp', 'quit'],
    cmd: 'display ipsec proposal',
    assert: assert.any(
      assert.contains('PROP1'),
      assert.contains('esp'),
      assert.contains('proposal'),
      assert.notContains('Unrecognized'),
    ),
    severity: 'WARN',
  },

  // ─── IPSec policy ────────────────────────────────────────────────
  {
    id: 'IKE-019', category: 'IPSec', device: 'router',
    description: 'ipsec policy creates an IPSec policy entry',
    setup: ['system-view'],
    cmd: 'ipsec policy POL1 1 isakmp',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: ipsec policy <name> <seq> isakmp|manual',
  },
  {
    id: 'IKE-020', category: 'IPSec', device: 'router',
    description: 'ike-peer references peer in IPSec policy',
    setup: [
      'system-view',
      'ike peer PEER_A v1', 'remote-address 203.0.113.1', 'quit',
      'ipsec policy POL1 1 isakmp',
    ],
    cmd: 'ike-peer PEER_A',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'IKE-021', category: 'IPSec', device: 'router',
    description: 'proposal references IPSec proposal in policy',
    setup: [
      'system-view',
      'ipsec proposal PROP1', 'transform esp', 'quit',
      'ipsec policy POL1 1 isakmp',
    ],
    cmd: 'proposal PROP1',
    assert: assert.empty(),
    severity: 'FAIL',
  },
  {
    id: 'IKE-022', category: 'IPSec', device: 'router',
    description: 'security acl references traffic selector ACL',
    setup: [
      'system-view',
      'acl 3000', 'rule permit ip source 10.0.1.0 0.0.0.255 destination 10.0.2.0 0.0.0.255', 'quit',
      'ipsec policy POL1 1 isakmp',
    ],
    cmd: 'security acl 3000',
    assert: assert.empty(),
    severity: 'WARN',
    vrpNote: 'Real VRP: security acl defines the interesting traffic',
  },
  {
    id: 'IKE-023', category: 'IPSec', device: 'router',
    description: 'display ipsec policy shows configured policies',
    setup: ['system-view', 'ipsec policy POL1 1 isakmp', 'quit'],
    cmd: 'display ipsec policy',
    assert: assert.any(
      assert.contains('POL1'),
      assert.contains('policy'),
      assert.contains('isakmp'),
      assert.notContains('Unrecognized'),
    ),
    severity: 'WARN',
  },

  // ─── Bind policy to interface ────────────────────────────────────
  {
    id: 'IKE-024', category: 'IPSec', device: 'router',
    description: 'ipsec policy applied to interface',
    setup: [
      'system-view',
      'ipsec policy POL1 1 isakmp', 'quit',
      'interface GE0/0/0', 'ip address 198.51.100.1 255.255.255.0',
    ],
    cmd: 'ipsec policy POL1',
    assert: assert.empty(),
    severity: 'FAIL',
    vrpNote: 'Real VRP: ipsec policy <name> (no seq) applies to interface',
  },
  {
    id: 'IKE-025', category: 'IPSec', device: 'router',
    description: 'undo ipsec policy removes policy from interface',
    setup: [
      'system-view',
      'ipsec policy POL1 1 isakmp', 'quit',
      'interface GE0/0/0', 'ip address 198.51.100.1 255.255.255.0', 'ipsec policy POL1',
    ],
    cmd: 'undo ipsec policy',
    assert: assert.empty(),
    severity: 'WARN',
  },

  // ─── Display SA ──────────────────────────────────────────────────
  {
    id: 'IKE-026', category: 'IPSec', device: 'router',
    description: 'display ike sa shows IKE security associations',
    setup: ['system-view'],
    cmd: 'display ike sa',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
    vrpNote: 'Real VRP: shows IKE Phase-1 SA state (even if empty)',
  },
  {
    id: 'IKE-027', category: 'IPSec', device: 'router',
    description: 'display ipsec sa shows IPSec security associations',
    setup: ['system-view'],
    cmd: 'display ipsec sa',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
    vrpNote: 'Real VRP: shows Phase-2 SA for each active tunnel',
  },
  {
    id: 'IKE-028', category: 'IPSec', device: 'router',
    description: 'display ipsec statistics shows packet counters',
    setup: ['system-view'],
    cmd: 'display ipsec statistics',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
  },
  {
    id: 'IKE-029', category: 'IPSec', device: 'router',
    description: 'reset ike sa clears IKE SA table',
    setup: ['system-view'],
    cmd: 'reset ike sa',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
    vrpNote: 'Real VRP: forces IKE re-negotiation',
  },
  {
    id: 'IKE-030', category: 'IPSec', device: 'router',
    description: 'reset ipsec sa clears IPSec SA table',
    setup: ['system-view'],
    cmd: 'reset ipsec sa',
    assert: assert.notContains('Unrecognized'),
    severity: 'WARN',
  },
];
