/**
 * V$SQL_PLAN_MONITOR — per-line plan monitoring for the cursors shown
 * in V$SQL_MONITOR, generated by the real PlanGenerator (same engine as
 * EXPLAIN PLAN) from each cached statement's text.
 */

import { col } from './_columns';
import { queryResult } from '../../engine/executor/ResultSet';
import { registerView } from './registry';

registerView({
  name: 'V$SQL_PLAN_MONITOR',
  comment: 'Per-plan-step monitoring',
  query({ runtime }) {
    const sorted = [...runtime.sqlCache.values()]
      .sort((a, b) => b.lastLoadTime - a.lastLoadTime)
      .slice(0, 50);
    const rows: (string | number | null)[][] = [];
    sorted.forEach((s, idx) => {
      const lines = runtime.planProvider?.(s.text, s.parsingSchema) ?? null;
      if (lines && lines.length > 0) {
        for (const l of lines) {
          rows.push([
            s.sqlId, idx + 1, l.lineId, l.operation, l.options,
            l.objectOwner, l.objectName, s.executions,
            l.lineId === 0 ? s.rowsProcessed : l.cardinality,
          ]);
        }
      } else {
        rows.push([s.sqlId, idx + 1, 0, 'SELECT STATEMENT', '', null, null, s.executions, s.rowsProcessed]);
      }
    });
    return queryResult(
      [
        col.str('SQL_ID', 13),
        col.num('SQL_EXEC_ID'),
        col.num('PLAN_LINE_ID'),
        col.str('PLAN_OPERATION', 30),
        col.str('PLAN_OPTIONS', 30),
        col.str('PLAN_OBJECT_OWNER', 30),
        col.str('PLAN_OBJECT_NAME', 30),
        col.num('STARTS'),
        col.num('OUTPUT_ROWS'),
      ],
      rows,
    );
  },
});
