/**
 * Cisco IOS router — RIP / EIGRP / BGP gap-analysis (~300 steps).
 * RIPv1/v2 (timers, auth, offset, passive, redistribution),
 * EIGRP classic & named-mode (metrics, summarization, stub, auth),
 * BGP (neighbors, networks, route-reflector, communities, aggregation,
 * policy, address-families), plus their show/clear/debug families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-eigrp-rip-bgp', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'end',

      { section: 'RIP', cmd: 'configure terminal' },
      'router rip',
      'version 2',
      'no auto-summary',
      ...sweep(6, (i) => `network 10.${i}.0.0`),
      'network 192.168.1.0',
      'network 10.0.0.0',
      'passive-interface GigabitEthernet0/0',
      'passive-interface default',
      'no passive-interface GigabitEthernet0/1',
      'neighbor 10.0.0.2',
      'timers basic 30 180 180 240',
      'distance 120',
      'offset-list 1 in 5 GigabitEthernet0/1',
      'offset-list 1 out 5 GigabitEthernet0/1',
      'redistribute connected',
      'redistribute static metric 3',
      'redistribute ospf 1 metric 5',
      'default-information originate',
      'default-metric 4',
      'maximum-paths 6',
      'output-delay 50',
      'flash-update-threshold 10',
      'validate-update-source',
      'exit',
      'key chain RIP-KEY',
      'key 1',
      'key-string secretrip',
      'accept-lifetime 00:00:00 Jan 1 2020 infinite',
      'send-lifetime 00:00:00 Jan 1 2020 infinite',
      'exit',
      'exit',
      'interface GigabitEthernet0/1',
      'ip rip authentication mode md5',
      'ip rip authentication key-chain RIP-KEY',
      'ip rip send version 2',
      'ip rip receive version 1 2',
      'ip rip v2-broadcast',
      'ip summary-address rip 10.0.0.0 255.0.0.0',
      'exit',
      'end',
      'show ip rip database',
      'show ip protocols',
      'show ip route rip',
      'debug ip rip',
      'debug ip rip events',
      'undebug all',
      'clear ip route *',

      { section: 'EIGRP classic', cmd: 'configure terminal' },
      'router eigrp 100',
      'eigrp router-id 1.1.1.1',
      'no auto-summary',
      ...sweep(6, (i) => `network 10.${i}.0.0 0.0.255.255`),
      'network 192.168.1.0 0.0.0.255',
      'network 10.0.0.0 0.0.0.3',
      'passive-interface GigabitEthernet0/0',
      'eigrp stub connected summary',
      'metric weights 0 1 0 1 0 0',
      'metric maximum-hops 50',
      'variance 4',
      'maximum-paths 6',
      'distance eigrp 90 170',
      'timers active-time 3',
      'redistribute connected',
      'redistribute static metric 10000 100 255 1 1500',
      'redistribute ospf 1 metric 10000 100 255 1 1500',
      'default-metric 10000 100 255 1 1500',
      'traffic-share balanced',
      'exit',
      'interface GigabitEthernet0/1',
      'ip summary-address eigrp 100 172.16.0.0 255.255.0.0',
      'ip bandwidth-percent eigrp 100 50',
      'ip hello-interval eigrp 100 5',
      'ip hold-time eigrp 100 15',
      'ip authentication mode eigrp 100 md5',
      'ip authentication key-chain eigrp 100 RIP-KEY',
      'no ip split-horizon eigrp 100',
      'exit',
      'end',
      ...each([
        'show ip eigrp neighbors', 'show ip eigrp neighbors detail',
        'show ip eigrp topology', 'show ip eigrp topology all-links',
        'show ip eigrp interfaces', 'show ip eigrp interfaces detail',
        'show ip eigrp traffic', 'show ip eigrp accounting',
        'show ip route eigrp', 'show ip protocols',
      ], (c) => c),
      'clear ip eigrp neighbors',
      'debug eigrp packets',
      'debug ip eigrp',
      'undebug all',

      { section: 'EIGRP named mode', cmd: 'configure terminal' },
      'router eigrp CORP',
      'address-family ipv4 unicast autonomous-system 200',
      'network 192.168.1.0 0.0.0.255',
      'eigrp router-id 1.1.1.1',
      'af-interface GigabitEthernet0/1',
      'hello-interval 5',
      'hold-time 15',
      'authentication mode md5',
      'summary-address 172.16.0.0 255.255.0.0',
      'exit-af-interface',
      'topology base',
      'redistribute static',
      'variance 2',
      'exit-af-topology',
      'exit-address-family',
      'exit',
      'end',
      'show eigrp protocols',
      'show eigrp address-family ipv4 neighbors',

      { section: 'BGP', cmd: 'configure terminal' },
      'router bgp 65000',
      'bgp router-id 1.1.1.1',
      'bgp log-neighbor-changes',
      'no bgp default ipv4-unicast',
      'bgp always-compare-med',
      'bgp deterministic-med',
      'bgp bestpath as-path multipath-relax',
      'bgp graceful-restart',
      'timers bgp 10 30',
      ...sweep(5, (i) => [
        `neighbor 10.0.0.${i + 1} remote-as ${65001 + i}`,
        `neighbor 10.0.0.${i + 1} description PEER-${i}`,
        `neighbor 10.0.0.${i + 1} update-source Loopback0`,
        `neighbor 10.0.0.${i + 1} ebgp-multihop 2`,
        `neighbor 10.0.0.${i + 1} password bgpsecret`,
        `neighbor 10.0.0.${i + 1} timers 10 30`,
        `neighbor 10.0.0.${i + 1} fall-over bfd`,
      ]),
      'neighbor IBGP peer-group',
      'neighbor IBGP remote-as 65000',
      'neighbor IBGP update-source Loopback0',
      'neighbor 10.0.0.10 peer-group IBGP',
      'address-family ipv4 unicast',
      'network 192.168.1.0 mask 255.255.255.0',
      'network 10.0.0.0 mask 255.255.255.252',
      'aggregate-address 192.168.0.0 255.255.0.0 summary-only',
      'aggregate-address 172.16.0.0 255.255.0.0 as-set',
      'redistribute connected',
      'redistribute static',
      'redistribute ospf 1 match internal external',
      'neighbor 10.0.0.1 activate',
      'neighbor 10.0.0.1 next-hop-self',
      'neighbor 10.0.0.1 route-reflector-client',
      'neighbor 10.0.0.1 send-community both',
      'neighbor 10.0.0.1 soft-reconfiguration inbound',
      'neighbor 10.0.0.1 maximum-prefix 1000 80',
      'neighbor 10.0.0.1 route-map RM-IN in',
      'neighbor 10.0.0.1 route-map RM-OUT out',
      'neighbor 10.0.0.1 prefix-list PL-IN in',
      'neighbor 10.0.0.1 filter-list 1 out',
      'neighbor 10.0.0.1 default-originate',
      'neighbor 10.0.0.1 weight 100',
      'neighbor 10.0.0.1 allowas-in 3',
      'distance bgp 20 200 200',
      'maximum-paths 4',
      'maximum-paths ibgp 4',
      'exit-address-family',
      'address-family vpnv4',
      'neighbor 10.0.0.1 activate',
      'exit-address-family',
      'address-family ipv6 unicast',
      'network 2001:db8::/32',
      'exit-address-family',
      'exit',
      'ip community-list 1 permit 65000:100',
      'ip as-path access-list 1 permit ^65001$',
      'route-map RM-IN permit 10',
      'set local-preference 200',
      'set community 65000:100 additive',
      'set as-path prepend 65000 65000',
      'exit',
      'end',
      ...each([
        'show ip bgp', 'show ip bgp summary', 'show ip bgp neighbors',
        'show ip bgp neighbors 10.0.0.2 advertised-routes',
        'show ip bgp neighbors 10.0.0.2 received-routes',
        'show ip bgp neighbors 10.0.0.2 routes',
        'show ip bgp 192.168.1.0', 'show ip bgp paths',
        'show ip bgp community', 'show ip bgp cidr-only',
        'show ip bgp regexp ^65001', 'show bgp ipv6 unicast',
        'show ip route bgp', 'show ip protocols',
        'show bgp all summary', 'show ip bgp vpnv4 all',
      ], (c) => c),
      'clear ip bgp *',
      'clear ip bgp 10.0.0.2 soft in',
      'clear ip bgp * soft out',
      'debug ip bgp',
      'debug ip bgp updates',
      'undebug all',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-eigrp-rip-bgp', topology, steps,
      'focus=RIP/EIGRP(classic+named)/BGP: peers, redist, policy, show');
  }, 120000);
});
