/**
 * Cisco IOS router — DHCP & NAT gap-analysis (~300 steps).
 * DHCP server (pools, options, reservations, exclusions, classes,
 * relay, snooping-ish), DHCPv6, DHCP client; NAT static / dynamic /
 * PAT / port-forwarding / NVI / NAT64-ish, plus show/clear/debug.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-dhcp-nat', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'end',

      { section: 'DHCP server pools', cmd: 'configure terminal' },
      'ip dhcp excluded-address 192.168.1.1 192.168.1.20',
      'ip dhcp excluded-address 192.168.1.250 192.168.1.254',
      ...sweep(8, (i) => [
        `ip dhcp pool VLAN${i * 10}`,
        `network 192.168.${i}.0 255.255.255.0`,
        `default-router 192.168.${i}.1`,
        `dns-server 8.8.8.8 8.8.4.4`,
        `domain-name vlan${i * 10}.lab`,
        `lease ${i} 12 30`,
        `netbios-name-server 192.168.${i}.2`,
        `option 150 ip 192.168.${i}.3`,
        `option 66 ascii tftp.lab.local`,
        `bootfile boot${i}.bin`,
        `next-server 192.168.${i}.4`,
        'exit',
      ]),
      'ip dhcp pool RESERVED',
      'host 192.168.1.50 255.255.255.0',
      'client-identifier 0100.1122.3344.55',
      'hardware-address 0011.2233.4455',
      'client-name printer1',
      'exit',
      'ip dhcp pool INFINITE',
      'network 172.16.0.0 255.255.0.0',
      'lease infinite',
      'exit',
      'end',
      'show ip dhcp pool',
      'show ip dhcp binding',
      'show ip dhcp server statistics',
      'show ip dhcp conflict',
      'show running-config | section dhcp',

      { section: 'DHCP classes / options', cmd: 'configure terminal' },
      'ip dhcp class VOICE',
      'option 60 ascii Cisco',
      'exit',
      'ip dhcp class DATA',
      'option 60 hex 0001',
      'exit',
      'ip dhcp pool MULTI',
      'network 10.50.0.0 255.255.0.0',
      'class VOICE',
      'address range 10.50.1.1 10.50.1.254',
      'exit',
      'class DATA',
      'address range 10.50.2.1 10.50.2.254',
      'exit',
      'exit',
      'ip dhcp use class',
      'ip dhcp ping packets 2',
      'ip dhcp ping timeout 500',
      'ip dhcp database flash:dhcp-bindings write-delay 60',
      'ip dhcp bootp ignore',
      'ip dhcp compatibility suboption link-selection standard',
      'service dhcp',
      'no service dhcp',
      'service dhcp',
      'end',

      { section: 'DHCP relay', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      'ip helper-address 10.0.0.2',
      'ip helper-address 10.0.0.3',
      'ip dhcp relay information trusted',
      'exit',
      'ip dhcp relay information option',
      'ip dhcp relay information policy keep',
      'ip dhcp relay information trust-all',
      'ip dhcp smart-relay',
      'end',
      'show ip dhcp relay statistics',

      { section: 'DHCP snooping', cmd: 'configure terminal' },
      'ip dhcp snooping',
      'ip dhcp snooping vlan 10,20,30',
      'ip dhcp snooping information option',
      'interface GigabitEthernet0/1',
      'ip dhcp snooping trust',
      'ip dhcp snooping limit rate 100',
      'exit',
      'end',
      'show ip dhcp snooping',
      'show ip dhcp snooping binding',

      { section: 'DHCPv6', cmd: 'configure terminal' },
      'ipv6 unicast-routing',
      'ipv6 dhcp pool V6POOL',
      'address prefix 2001:db8:1::/64 lifetime 3600 1800',
      'dns-server 2001:4860:4860::8888',
      'domain-name v6.lab',
      'exit',
      'interface GigabitEthernet0/0',
      'ipv6 address 2001:db8:1::1/64',
      'ipv6 dhcp server V6POOL',
      'ipv6 nd managed-config-flag',
      'ipv6 nd other-config-flag',
      'exit',
      'interface GigabitEthernet0/1',
      'ipv6 dhcp relay destination 2001:db8:ff::1',
      'exit',
      'end',
      'show ipv6 dhcp pool',
      'show ipv6 dhcp binding',
      'show ipv6 dhcp interface',

      { section: 'DHCP client', cmd: 'configure terminal' },
      'interface GigabitEthernet0/1',
      'ip address dhcp',
      'ip address dhcp hostname R1',
      'ip address dhcp client-id GigabitEthernet0/1',
      'ipv6 address dhcp',
      'ipv6 address autoconfig',
      'exit',
      'end',
      'show dhcp lease',
      'show dhcp server',

      { section: 'NAT static', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      'ip nat inside',
      'exit',
      'interface GigabitEthernet0/1',
      'ip nat outside',
      'exit',
      ...sweep(10, (i) =>
        `ip nat inside source static 192.168.1.${i + 10} 10.0.0.${i + 10}`),
      'ip nat inside source static tcp 192.168.1.100 80 10.0.0.100 8080',
      'ip nat inside source static tcp 192.168.1.101 22 10.0.0.100 2222 extendable',
      'ip nat inside source static udp 192.168.1.102 53 10.0.0.100 53',
      'ip nat outside source static 8.8.8.8 192.168.1.200',
      'ip nat inside source static 192.168.1.150 10.0.0.150 route-map RM-NAT',
      'end',
      'show ip nat translations',
      'show ip nat translations verbose',
      'show ip nat statistics',

      { section: 'NAT dynamic / PAT', cmd: 'configure terminal' },
      'ip nat pool POOL1 10.0.0.50 10.0.0.60 netmask 255.255.255.0',
      'ip nat pool POOL2 10.0.0.70 10.0.0.80 prefix-length 24',
      'access-list 1 permit 192.168.1.0 0.0.0.255',
      'access-list 2 permit 192.168.2.0 0.0.0.255',
      'ip nat inside source list 1 pool POOL1',
      'ip nat inside source list 1 pool POOL1 overload',
      'ip nat inside source list 2 interface GigabitEthernet0/1 overload',
      'ip nat inside source route-map RM-NAT pool POOL2 overload',
      'ip nat translation timeout 3600',
      'ip nat translation tcp-timeout 600',
      'ip nat translation udp-timeout 120',
      'ip nat translation icmp-timeout 30',
      'ip nat translation max-entries 10000',
      'ip nat log translations syslog',
      'route-map RM-NAT permit 10',
      'match ip address 2',
      'exit',
      'end',
      'show ip nat translations',
      'show ip nat statistics',
      'show ip nat nvi translations',
      'clear ip nat translation *',
      'clear ip nat translation inside 10.0.0.50 192.168.1.10',
      'debug ip nat',
      'debug ip nat detailed',
      'undebug all',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-dhcp-nat', topology, steps,
      'focus=DHCP server/relay/snoop/v6/client + NAT static/PAT/pool',
      { resyncVendor: 'cisco' });
  }, 120000);
});
