/**
 * Cisco IOS router — logging / SNMP / NTP / observability gap-analysis
 * (~300 steps). Syslog & buffered/console/monitor logging, severity &
 * facilities, discriminators; SNMP v1/v2c/v3 (communities, groups,
 * users, views, hosts, traps); NTP (servers/peers/auth/master/ACL);
 * NetFlow / Flexible NetFlow; EEM applets; archive/config-change;
 * SLA/responder; CDP/LLDP; plus their show families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-logging-snmp-ntp', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'interface Loopback0',
      'ip address 1.1.1.1 255.255.255.255',
      'exit',
      'end',

      { section: 'logging / syslog', cmd: 'configure terminal' },
      'logging on',
      'service timestamps log datetime msec localtime show-timezone',
      'service timestamps debug datetime msec',
      'service sequence-numbers',
      'logging buffered 64000 informational',
      'logging console warnings',
      'logging monitor debugging',
      'logging trap notifications',
      'logging facility local6',
      'logging origin-id hostname',
      'logging source-interface Loopback0',
      ...sweep(4, (i) => `logging host 10.0.0.${i + 1}`),
      'logging host 10.0.0.10 transport tcp port 1514',
      'logging host 10.0.0.11 vrf MGMT',
      'logging rate-limit 100 except errors',
      'logging queue-limit 100',
      'logging buffered xml',
      'logging count',
      'logging userinfo',
      'logging discriminator NOISE severity drops 6 facility drops SYS',
      'logging buffered discriminator NOISE 64000',
      'logging event link-status default',
      'logging snmp-trap emergencies',
      'archive',
      'log config',
      'logging enable',
      'logging size 200',
      'notify syslog contenttype plaintext',
      'hidekeys',
      'exit',
      'path flash:archive-config',
      'maximum 14',
      'time-period 1440',
      'write-memory',
      'exit',
      'exit',
      'end',
      'show logging',
      'show logging history',
      'show archive',
      'show archive config differences',
      'clear logging',

      { section: 'SNMP v1/v2c', cmd: 'configure terminal' },
      'snmp-server community public RO',
      'snmp-server community private RW',
      'snmp-server community ro-acl RO 10',
      'access-list 10 permit 10.0.0.0 0.0.0.255',
      'snmp-server location DC1-Rack5',
      'snmp-server contact noc@lab.local',
      'snmp-server chassis-id R1-CHASSIS',
      'snmp-server ifindex persist',
      'snmp-server packetsize 1500',
      'snmp-server queue-length 50',
      'snmp-server trap-timeout 30',
      'snmp-server enable traps snmp authentication linkdown linkup coldstart warmstart',
      'snmp-server enable traps ospf',
      'snmp-server enable traps bgp',
      'snmp-server enable traps config',
      'snmp-server enable traps cpu threshold',
      'snmp-server enable traps envmon',
      'snmp-server host 10.0.0.5 version 2c public',
      'snmp-server host 10.0.0.6 version 2c private udp-port 162 ospf bgp',
      'snmp-server host 10.0.0.7 informs version 2c public',
      'snmp-server source-interface traps Loopback0',
      'snmp-server system-shutdown',
      'snmp-server tftp-server-list 10',
      'end',
      'show snmp',
      'show snmp community',
      'show snmp host',
      'show snmp group',

      { section: 'SNMPv3', cmd: 'configure terminal' },
      'snmp-server view ALL iso included',
      'snmp-server view LIMITED system included',
      'snmp-server group GRP-RO v3 priv read ALL',
      'snmp-server group GRP-RW v3 priv read ALL write ALL notify ALL',
      'snmp-server group GRP-AUTH v3 auth read LIMITED',
      'snmp-server user adminv3 GRP-RW v3 auth sha AuthPass123 priv aes 256 PrivPass123',
      'snmp-server user rouser GRP-RO v3 auth sha AuthPass123',
      'snmp-server user noauth GRP-AUTH v3',
      'snmp-server host 10.0.0.8 version 3 priv adminv3 cpu',
      'snmp-server engineID local 800000090300DEADBEEF0001',
      'snmp-server engineID remote 10.0.0.8 800000090300CAFEBABE0001',
      'end',
      'show snmp user',
      'show snmp view',
      'show snmp engineID',

      { section: 'NTP / clock', cmd: 'configure terminal' },
      'clock timezone CET 1 0',
      'clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00',
      'ntp authenticate',
      'ntp authentication-key 1 md5 NtpKey123',
      'ntp authentication-key 2 sha1 NtpKey456',
      'ntp trusted-key 1',
      'ntp trusted-key 2',
      ...sweep(3, (i) =>
        `ntp server 10.0.0.${i + 20} key 1 prefer`),
      'ntp server time.lab.local',
      'ntp peer 10.0.0.30',
      'ntp master 3',
      'ntp source Loopback0',
      'ntp update-calendar',
      'ntp max-associations 20',
      'ntp access-group peer 10',
      'ntp access-group serve-only 10',
      'ntp logging',
      'sntp server 10.0.0.40',
      'end',
      'show ntp status',
      'show ntp associations',
      'show ntp associations detail',
      'show clock',
      'show clock detail',
      'show calendar',

      { section: 'NetFlow / Flexible NetFlow', cmd: 'configure terminal' },
      'ip flow-export version 9',
      'ip flow-export destination 10.0.0.50 9996',
      'ip flow-export source Loopback0',
      'ip flow-cache timeout active 1',
      'ip flow-cache timeout inactive 15',
      'interface GigabitEthernet0/1',
      'ip flow ingress',
      'ip flow egress',
      'ip route-cache flow',
      'exit',
      'flow record FR1',
      'match ipv4 source address',
      'match ipv4 destination address',
      'match transport source-port',
      'collect counter bytes',
      'collect counter packets',
      'exit',
      'flow exporter FE1',
      'destination 10.0.0.50',
      'transport udp 2055',
      'export-protocol netflow-v9',
      'exit',
      'flow monitor FM1',
      'record FR1',
      'exporter FE1',
      'cache timeout active 60',
      'exit',
      'interface GigabitEthernet0/1',
      'ip flow monitor FM1 input',
      'exit',
      'end',
      'show ip flow export',
      'show ip cache flow',
      'show flow monitor FM1',
      'show flow exporter FE1',
      'show flow record FR1',
      'show flow monitor FM1 cache',

      { section: 'EEM / scripting', cmd: 'configure terminal' },
      'event manager applet IF-DOWN',
      'event syslog pattern "LINK-3-UPDOWN.*GigabitEthernet0/1"',
      'action 1.0 syslog msg "WAN interface changed state"',
      'action 2.0 cli command "enable"',
      'action 3.0 cli command "show ip interface brief"',
      'exit',
      'event manager applet CRON-BACKUP',
      'event timer cron cron-entry "0 2 * * *"',
      'action 1.0 cli command "enable"',
      'action 2.0 cli command "copy running-config flash:nightly.cfg"',
      'exit',
      'event manager environment _email noc@lab.local',
      'end',
      'show event manager policy registered',
      'show event manager environment',

      { section: 'CDP / LLDP / discovery', cmd: 'configure terminal' },
      'cdp run',
      'cdp timer 30',
      'cdp holdtime 120',
      'cdp advertise-v2',
      'lldp run',
      'lldp timer 30',
      'lldp holdtime 120',
      'lldp reinit 2',
      'interface GigabitEthernet0/1',
      'cdp enable',
      'lldp transmit',
      'lldp receive',
      'exit',
      'end',
      'show cdp',
      'show cdp neighbors',
      'show cdp neighbors detail',
      'show cdp interface',
      'show cdp traffic',
      'show lldp',
      'show lldp neighbors',
      'show lldp neighbors detail',
      'show lldp traffic',
      ...each([
        'show running-config | section logging',
        'show running-config | section snmp',
        'show running-config | section ntp',
        'show processes cpu sorted',
        'show memory statistics',
      ], (c) => c),
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-logging-snmp-ntp', topology, steps,
      'focus=syslog/SNMPv1-3/NTP/NetFlow/EEM/CDP-LLDP',
      { resyncVendor: 'cisco' });
  }, 120000);
});
