/**
 * Cisco IOS router — first-hop redundancy & QoS gap-analysis (~300).
 * HSRP (groups, priority, preempt, auth, track, timers, v2), VRRP,
 * GLBP; MQC QoS (class-maps, policy-maps, marking, policing, shaping,
 * CBWFQ/LLQ, WRED, NBAR), legacy CAR/priority-list; object-tracking;
 * IP SLA + responder; BFD; plus their show families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-redundancy-qos', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.2 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'end',

      { section: 'HSRP', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      ...sweep(4, (i) => [
        `standby ${i} ip 192.168.1.${i}`,
        `standby ${i} ip 192.168.1.${100 + i} secondary`,
        `standby ${i} priority ${100 + i * 10}`,
        `standby ${i} preempt delay minimum 30 reload 60`,
        `standby ${i} timers 1 3`,
        `standby ${i} timers msec 200 msec 750`,
        `standby ${i} authentication md5 key-string HsrpKey${i}`,
        `standby ${i} track GigabitEthernet0/1 30`,
        `standby ${i} track 1 decrement 20`,
        `standby ${i} name HSRP-GRP-${i}`,
        `standby ${i} mac-address 0000.0c07.ac0${i}`,
        `standby ${i} follow HSRP-GRP-1`,
      ]),
      'standby version 2',
      'standby use-bia',
      'standby delay minimum 30 reload 60',
      'exit',
      'end',
      'show standby',
      'show standby brief',
      'show standby GigabitEthernet0/0',
      'show standby GigabitEthernet0/0 1',
      'show standby all',
      'debug standby',
      'debug standby events',
      'undebug all',

      { section: 'VRRP', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      ...sweep(3, (i) => [
        `vrrp ${i} ip 192.168.1.${200 + i}`,
        `vrrp ${i} priority ${110 + i * 10}`,
        `vrrp ${i} preempt delay minimum 15`,
        `vrrp ${i} timers advertise 1`,
        `vrrp ${i} timers learn`,
        `vrrp ${i} authentication md5 key-string VrrpKey${i}`,
        `vrrp ${i} track 1 decrement 20`,
        `vrrp ${i} description VRRP-GRP-${i}`,
      ]),
      'vrrp 1 address-family ipv4',
      'exit',
      'end',
      'show vrrp',
      'show vrrp brief',
      'show vrrp interface GigabitEthernet0/0',

      { section: 'GLBP', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      'glbp 1 ip 192.168.1.250',
      'glbp 1 priority 150',
      'glbp 1 preempt delay minimum 30',
      'glbp 1 load-balancing host-dependent',
      'glbp 1 load-balancing round-robin',
      'glbp 1 weighting 100 lower 90 upper 95',
      'glbp 1 weighting track 1 decrement 10',
      'glbp 1 timers 3 10',
      'glbp 1 timers redirect 600 7200',
      'glbp 1 authentication md5 key-string GlbpKey',
      'glbp 1 name GLBP-GRP-1',
      'glbp 1 forwarder preempt delay minimum 30',
      'exit',
      'end',
      'show glbp',
      'show glbp brief',

      { section: 'object tracking', cmd: 'configure terminal' },
      ...sweep(5, (i) => [
        `track ${i} interface GigabitEthernet0/${i % 2} line-protocol`,
        'delay up 10 down 20',
        'exit',
      ]),
      'track 10 ip route 10.0.0.0 255.0.0.0 reachability',
      'track 11 ip sla 1 reachability',
      'track 12 ip sla 1 state',
      'track 20 list boolean and',
      'object 1',
      'object 10',
      'exit',
      'track 21 list threshold weight',
      'object 1 weight 10',
      'object 10 weight 20',
      'threshold weight up 25 down 10',
      'exit',
      'track 22 stub-object',
      'exit',
      'end',
      'show track',
      'show track brief',
      'show track 1',

      { section: 'IP SLA + responder', cmd: 'configure terminal' },
      'ip sla 1',
      'icmp-echo 10.0.0.2 source-interface GigabitEthernet0/1',
      'frequency 5',
      'threshold 200',
      'timeout 1000',
      'tag WAN-PROBE',
      'history enhanced interval 900 buckets 4',
      'exit',
      'ip sla 2',
      'udp-jitter 10.0.0.2 16384 codec g711alaw',
      'frequency 10',
      'exit',
      'ip sla 3',
      'tcp-connect 10.0.0.2 80',
      'exit',
      'ip sla 4',
      'http get http://10.0.0.2',
      'exit',
      'ip sla 5',
      'dns lab.local name-server 8.8.8.8',
      'exit',
      'ip sla schedule 1 life forever start-time now',
      'ip sla schedule 2 life 3600 start-time after 00:01:00',
      'ip sla group schedule 10 1,2,3 schedule-period 60 frequency 30 start-time now',
      'ip sla responder',
      'ip sla responder udp-echo ipaddress 10.0.0.1 port 5000',
      'ip sla enable reaction-alerts',
      'ip sla reaction-configuration 1 react timeout threshold-type immediate action-type trapAndTrigger',
      'ip sla logging traps',
      'end',
      'show ip sla configuration',
      'show ip sla statistics',
      'show ip sla statistics aggregated',
      'show ip sla responder',
      'show ip sla application',

      { section: 'BFD', cmd: 'configure terminal' },
      'interface GigabitEthernet0/1',
      'bfd interval 100 min_rx 100 multiplier 3',
      'bfd echo',
      'no bfd echo',
      'exit',
      'router ospf 1',
      'bfd all-interfaces',
      'exit',
      'ip route 192.168.9.0 255.255.255.0 10.0.0.2 track 1',
      'end',
      'show bfd neighbors',
      'show bfd neighbors details',
      'show bfd summary',

      { section: 'QoS — MQC class/policy', cmd: 'configure terminal' },
      'ip access-list extended VOICE',
      'permit udp any any range 16384 32767',
      'exit',
      'ip access-list extended VIDEO',
      'permit tcp any any eq 1720',
      'exit',
      'class-map match-any CM-VOICE',
      'match ip dscp ef',
      'match access-group name VOICE',
      'match protocol rtp',
      'exit',
      'class-map match-all CM-VIDEO',
      'match ip dscp af41',
      'match access-group name VIDEO',
      'exit',
      'class-map match-any CM-CRITICAL',
      'match protocol bgp',
      'match protocol ospf',
      'match ip precedence 6',
      'exit',
      'class-map match-any CM-SCAVENGER',
      'match protocol bittorrent',
      'match protocol napster',
      'exit',
      'policy-map PM-WAN-OUT',
      'class CM-VOICE',
      'priority percent 20',
      'set dscp ef',
      'exit',
      'class CM-VIDEO',
      'bandwidth percent 25',
      'random-detect dscp-based',
      'set dscp af41',
      'exit',
      'class CM-CRITICAL',
      'bandwidth percent 15',
      'exit',
      'class CM-SCAVENGER',
      'bandwidth percent 1',
      'set dscp cs1',
      'exit',
      'class class-default',
      'fair-queue',
      'random-detect',
      'shape average 50000000',
      'exit',
      'exit',
      'policy-map PM-SHAPER',
      'class class-default',
      'shape average 100000000 1000000',
      'service-policy PM-WAN-OUT',
      'exit',
      'exit',
      'policy-map PM-POLICE-IN',
      'class CM-SCAVENGER',
      'police 1000000 conform-action transmit exceed-action drop',
      'exit',
      'class class-default',
      'police cir 8000000 bc 1500000 conform-action transmit exceed-action set-dscp-transmit 0',
      'exit',
      'exit',
      'interface GigabitEthernet0/1',
      'service-policy output PM-SHAPER',
      'service-policy input PM-POLICE-IN',
      'bandwidth 100000',
      'max-reserved-bandwidth 90',
      'exit',
      'end',
      'show policy-map',
      'show policy-map PM-WAN-OUT',
      'show policy-map interface GigabitEthernet0/1',
      'show class-map',
      'show class-map CM-VOICE',
      'show table-map',
      'show mls qos',

      { section: 'legacy QoS / NBAR', cmd: 'configure terminal' },
      'interface GigabitEthernet0/1',
      'rate-limit output 8000000 1500000 3000000 conform-action transmit exceed-action drop',
      'ip nbar protocol-discovery',
      'priority-group 1',
      'custom-queue-list 1',
      'fair-queue 64 256 8',
      'random-detect',
      'tx-ring-limit 3',
      'exit',
      'priority-list 1 protocol ip high tcp telnet',
      'queue-list 1 protocol ip 1 tcp www',
      'access-list rate-limit 10 5',
      'end',
      'show ip nbar protocol-discovery',
      'show queueing interface GigabitEthernet0/1',
      'show interfaces GigabitEthernet0/1 rate-limit',
      'show traffic-shape',
      'show traffic-shape statistics',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-redundancy-qos', topology, steps,
      'focus=HSRP/VRRP/GLBP/track/IP-SLA/BFD/MQC-QoS/NBAR',
      { resyncVendor: 'cisco' });
  }, 120000);
});
