/**
 * Cisco IOS router — OSPF / OSPFv3 gap-analysis (~300 steps).
 * Single & multi-area, network types, costs/priorities, timers,
 * authentication (plain/MD5/key-chain), stub/NSSA/totally-stubby,
 * virtual-links, summarization, redistribution, default-information,
 * passive-interface, reference-bandwidth, GR/BFD, and the OSPF
 * show/clear/debug families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-ospf', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      ...sweep(4, (i) => [
        `interface Loopback${i}`,
        `ip address 10.10.${i}.1 255.255.255.0`,
        'exit',
      ]),
      'end',

      { section: 'OSPF process / networks', cmd: 'configure terminal' },
      'router ospf 1',
      'router-id 1.1.1.1',
      'auto-cost reference-bandwidth 10000',
      'log-adjacency-changes detail',
      'maximum-paths 4',
      'compatible rfc1583',
      ...sweep(8, (i) =>
        `network 10.10.${i}.0 0.0.0.255 area ${i % 3}`),
      'network 192.168.1.0 0.0.0.255 area 0',
      'network 10.0.0.0 0.0.0.3 area 0',
      'passive-interface GigabitEthernet0/0',
      'passive-interface default',
      'no passive-interface GigabitEthernet0/1',
      'default-information originate',
      'default-information originate always metric 10 metric-type 1',
      'default-metric 20',
      'distance ospf intra-area 90 inter-area 100 external 110',
      'timers throttle spf 10 100 5000',
      'timers throttle lsa 0 50 5000',
      'timers lsa arrival 100',
      'max-lsa 10000',
      'exit',
      'end',
      'show ip ospf',
      'show ip ospf process 1',

      { section: 'area types', cmd: 'configure terminal' },
      'router ospf 1',
      'area 1 stub',
      'area 1 stub no-summary',
      'area 2 nssa',
      'area 2 nssa default-information-originate',
      'area 2 nssa no-summary',
      'area 3 range 10.30.0.0 255.255.0.0',
      'area 0 range 192.168.0.0 255.255.0.0 advertise',
      'area 1 default-cost 10',
      'area 0 authentication',
      'area 0 authentication message-digest',
      'area 1 virtual-link 2.2.2.2',
      'area 1 virtual-link 2.2.2.2 authentication message-digest',
      'area 1 virtual-link 2.2.2.2 message-digest-key 1 md5 cisco',
      'area 1 sham-link 1.1.1.1 2.2.2.2',
      'exit',
      'end',
      'show ip ospf',
      'show ip ospf border-routers',
      'show ip ospf virtual-links',

      { section: 'per-interface OSPF', cmd: 'configure terminal' },
      'interface GigabitEthernet0/1',
      ...each([
        'ip ospf 1 area 0',
        'ip ospf cost 100',
        'ip ospf priority 200',
        'ip ospf hello-interval 5',
        'ip ospf dead-interval 20',
        'ip ospf dead-interval minimal hello-multiplier 4',
        'ip ospf retransmit-interval 10',
        'ip ospf transmit-delay 2',
        'ip ospf network point-to-point',
        'ip ospf network broadcast',
        'ip ospf network non-broadcast',
        'ip ospf network point-to-multipoint',
        'ip ospf mtu-ignore',
        'ip ospf authentication',
        'ip ospf authentication message-digest',
        'ip ospf authentication null',
        'ip ospf authentication-key cisco123',
        'ip ospf message-digest-key 1 md5 secretkey',
        'ip ospf message-digest-key 2 md5 secretkey2',
        'ip ospf bfd',
        'ip ospf flood-reduction',
        'ip ospf demand-circuit',
        'ip ospf database-filter all out',
        'ip ospf hello-interval 10',
      ], (c) => c),
      'exit',
      'end',
      'show ip ospf interface GigabitEthernet0/1',
      'show ip ospf interface brief',

      { section: 'redistribution', cmd: 'configure terminal' },
      'router ospf 1',
      'redistribute connected subnets',
      'redistribute static subnets metric 20 metric-type 1',
      'redistribute rip subnets',
      'redistribute eigrp 100 metric 30 subnets',
      'redistribute bgp 65000 subnets route-map RM-OSPF',
      'summary-address 172.16.0.0 255.255.0.0',
      'summary-address 172.17.0.0 255.255.0.0 not-advertise',
      'exit',
      'route-map RM-OSPF permit 10',
      'match ip address 10',
      'set metric 100',
      'set metric-type type-1',
      'exit',
      'access-list 10 permit 172.16.0.0 0.0.255.255',
      'end',
      'show ip ospf',

      { section: 'OSPFv3', cmd: 'configure terminal' },
      'ipv6 unicast-routing',
      'ipv6 router ospf 1',
      'router-id 1.1.1.1',
      'area 0 range 2001:db8::/48',
      'passive-interface default',
      'redistribute connected',
      'exit',
      'interface GigabitEthernet0/1',
      'ipv6 address 2001:db8:1::1/64',
      'ipv6 ospf 1 area 0',
      'ipv6 ospf cost 50',
      'ipv6 ospf priority 100',
      'ipv6 ospf network point-to-point',
      'ipv6 ospf hello-interval 5',
      'ipv6 ospf dead-interval 20',
      'exit',
      'end',
      'show ipv6 ospf',
      'show ipv6 ospf interface',
      'show ipv6 ospf neighbor',
      'show ipv6 ospf database',

      { section: 'OSPF show / clear / debug', cmd: 'show ip ospf' },
      ...each([
        'show ip ospf neighbor', 'show ip ospf neighbor detail',
        'show ip ospf database', 'show ip ospf database router',
        'show ip ospf database network', 'show ip ospf database summary',
        'show ip ospf database external', 'show ip ospf database nssa-external',
        'show ip ospf database asbr-summary', 'show ip ospf database self-originate',
        'show ip ospf interface', 'show ip ospf interface brief',
        'show ip ospf border-routers', 'show ip ospf virtual-links',
        'show ip ospf statistics', 'show ip ospf summary-address',
        'show ip ospf rib', 'show ip ospf events', 'show ip ospf timers',
        'show ip route ospf', 'show ip protocols',
      ], (c) => c),
      'clear ip ospf process',
      'clear ip ospf 1 process',
      'clear ip ospf counters',
      'clear ip ospf redistribution',
      'debug ip ospf adj',
      'debug ip ospf events',
      'debug ip ospf hello',
      'debug ip ospf packet',
      'undebug all',

      { section: 'OSPF troubleshooting / tuning', cmd: 'configure terminal' },
      'router ospf 1',
      'maximum-paths 8',
      'timers pacing flood 33',
      'timers pacing retransmission 66',
      'ispf',
      'prefix-suppression',
      'shutdown',
      'no shutdown',
      'segment-routing mpls',
      'capability vrf-lite',
      'discard-route external',
      'exit',
      'end',
      'show ip ospf | include Area',
      'show ip ospf neighbor GigabitEthernet0/1',
      'show ip ospf request-list',
      'show ip ospf retransmission-list',
      'show ip ospf flood-list',
      'show ip ospf max-metric',
      'show ip ospf traffic',
      'show ip ospf segment-routing',
      'show ip route ospf | include O',
      'clear ip ospf force-spf',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-ospf', topology, steps,
      'focus=OSPF/OSPFv3: areas, auth, redistribution, timers, show');
  }, 120000);
});
