/**
 * Cisco IOS router — ACL / AAA / device-security gap-analysis (~300).
 * Standard / extended / named / time-based / reflexive / IPv6 ACLs,
 * AAA (local/RADIUS/TACACS+), SSH, login-block, password policy,
 * privilege, CoPP / control-plane, uRPF, CPP, zone-firewall basics,
 * plus the security show/clear/debug families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-acl-aaa-security', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'end',

      { section: 'standard numbered ACL', cmd: 'configure terminal' },
      ...sweep(20, (i) =>
        `access-list 10 permit 192.168.${i}.0 0.0.0.255`),
      'access-list 10 deny any log',
      'access-list 99 permit host 10.0.0.2',
      'access-list 99 deny any',
      'no access-list 99',
      'end',
      'show access-lists',
      'show access-lists 10',
      'show ip access-lists 10',

      { section: 'extended numbered ACL', cmd: 'configure terminal' },
      ...sweep(15, (i) => [
        `access-list 100 permit tcp 192.168.${i}.0 0.0.0.255 any eq ${80 + i}`,
        `access-list 100 permit udp any host 10.0.0.${i} eq 53`,
      ]),
      'access-list 100 permit icmp any any echo-reply',
      'access-list 100 deny ip any any log-input',
      'access-list 101 permit tcp any any established',
      'access-list 102 dynamic LOCK timeout 120 permit ip any any',
      'access-list 103 permit tcp any any range 1024 65535',
      'access-list 104 permit ip any any dscp af21',
      'access-list 105 permit tcp any any eq www log',
      'end',
      'show access-lists 100',
      'show ip access-lists',

      { section: 'named ACL', cmd: 'configure terminal' },
      'ip access-list standard MGMT',
      'permit 10.0.0.0 0.0.0.255',
      'permit host 192.168.1.10',
      'deny any log',
      'exit',
      'ip access-list extended WAN-IN',
      ...sweep(10, (i) =>
        `permit tcp any host 10.0.0.${i} eq ${443}`),
      'permit udp any any eq snmp',
      'deny icmp any any',
      'permit ip any any',
      'no 30',
      '15 permit tcp any any eq 22',
      'exit',
      'ip access-list resequence WAN-IN 10 10',
      'end',
      'show ip access-lists MGMT',
      'show ip access-lists WAN-IN',

      { section: 'time-based / reflexive', cmd: 'configure terminal' },
      'time-range BUSINESS-HOURS',
      'periodic weekdays 8:00 to 18:00',
      'absolute start 00:00 1 January 2024 end 23:59 31 December 2024',
      'exit',
      'ip access-list extended TIMED',
      'permit ip any any time-range BUSINESS-HOURS',
      'exit',
      'ip access-list extended REFLECT-OUT',
      'permit tcp any any reflect TCP-REFLECT',
      'exit',
      'ip access-list extended REFLECT-IN',
      'evaluate TCP-REFLECT',
      'exit',
      'end',
      'show time-range',
      'show ip access-lists TIMED',

      { section: 'apply ACLs to interface / vty', cmd: 'configure terminal' },
      'interface GigabitEthernet0/1',
      'ip access-group WAN-IN in',
      'ip access-group 100 out',
      'exit',
      'line vty 0 4',
      'access-class MGMT in',
      'access-class 10 out',
      'exit',
      'end',
      'show ip interface GigabitEthernet0/1',

      { section: 'IPv6 ACL', cmd: 'configure terminal' },
      'ipv6 access-list V6-FILTER',
      'permit tcp any any eq 22',
      'permit icmp any any',
      'deny ipv6 any any log',
      'exit',
      'interface GigabitEthernet0/1',
      'ipv6 traffic-filter V6-FILTER in',
      'exit',
      'end',
      'show ipv6 access-list',

      { section: 'AAA', cmd: 'configure terminal' },
      'aaa new-model',
      'aaa authentication login default local',
      'aaa authentication login VTY group radius local',
      'aaa authentication login CON line',
      'aaa authentication enable default group tacacs+ enable',
      'aaa authentication ppp default local',
      'aaa authorization exec default local',
      'aaa authorization commands 15 default group tacacs+ local',
      'aaa authorization network default group radius',
      'aaa accounting exec default start-stop group tacacs+',
      'aaa accounting commands 15 default stop-only group tacacs+',
      'aaa accounting network default start-stop group radius',
      'aaa session-id common',
      'radius server RAD1',
      'address ipv4 10.0.0.2 auth-port 1812 acct-port 1813',
      'key radiussecret',
      'exit',
      'tacacs server TAC1',
      'address ipv4 10.0.0.3',
      'key tacacssecret',
      'exit',
      'aaa group server radius RADGRP',
      'server name RAD1',
      'exit',
      'aaa group server tacacs+ TACGRP',
      'server name TAC1',
      'exit',
      'radius-server host 10.0.0.2 key legacy',
      'tacacs-server host 10.0.0.3 key legacy',
      'end',
      'show aaa servers',
      'show aaa sessions',
      'show radius statistics',
      'show tacacs',

      { section: 'SSH / device hardening', cmd: 'configure terminal' },
      'hostname R1',
      'ip domain-name lab.local',
      'crypto key generate rsa modulus 2048',
      'crypto key generate rsa general-keys modulus 4096 label SSH-KEY',
      'ip ssh version 2',
      'ip ssh time-out 60',
      'ip ssh authentication-retries 3',
      'ip ssh source-interface Loopback0',
      'ip ssh dh min size 2048',
      'ip ssh logging events',
      'username admin privilege 15 secret StrongP@ss1',
      'enable secret StrongEn@ble1',
      'service password-encryption',
      'security passwords min-length 10',
      'login block-for 120 attempts 3 within 60',
      'login quiet-mode access-class MGMT',
      'login delay 2',
      'login on-failure log',
      'login on-success log',
      'line vty 0 4',
      'transport input ssh',
      'login authentication VTY',
      'exec-timeout 5 0',
      'exit',
      'line console 0',
      'login authentication CON',
      'exec-timeout 10 0',
      'logging synchronous',
      'exit',
      'end',
      'show ip ssh',
      'show ssh',
      'show crypto key mypubkey rsa',
      'show login',
      'show login failures',

      { section: 'control-plane / CoPP / uRPF', cmd: 'configure terminal' },
      'ip access-list extended COPP-CRITICAL',
      'permit ospf any any',
      'permit tcp any any eq bgp',
      'exit',
      'class-map match-all CM-COPP',
      'match access-group name COPP-CRITICAL',
      'exit',
      'policy-map PM-COPP',
      'class CM-COPP',
      'police 8000 conform-action transmit exceed-action drop',
      'exit',
      'exit',
      'control-plane',
      'service-policy input PM-COPP',
      'exit',
      'interface GigabitEthernet0/1',
      'ip verify unicast source reachable-via rx',
      'ip verify unicast reverse-path',
      'no ip unreachables',
      'no ip redirects',
      'no ip proxy-arp',
      'exit',
      'ip cef',
      'end',
      'show policy-map control-plane',
      'show ip traffic',
      'show ip cef',

      { section: 'zone-based firewall', cmd: 'configure terminal' },
      'zone security INSIDE',
      'exit',
      'zone security OUTSIDE',
      'exit',
      'class-map type inspect match-any CM-INSPECT',
      'match protocol tcp',
      'match protocol udp',
      'match protocol icmp',
      'exit',
      'policy-map type inspect PM-IN-OUT',
      'class type inspect CM-INSPECT',
      'inspect',
      'exit',
      'class class-default',
      'drop log',
      'exit',
      'exit',
      'zone-pair security IN-OUT source INSIDE destination OUTSIDE',
      'service-policy type inspect PM-IN-OUT',
      'exit',
      'interface GigabitEthernet0/0',
      'zone-member security INSIDE',
      'exit',
      'interface GigabitEthernet0/1',
      'zone-member security OUTSIDE',
      'exit',
      'end',
      'show zone security',
      'show zone-pair security',
      'show policy-map type inspect zone-pair',
      'show parameter-map type inspect',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-acl-aaa-security', topology, steps,
      'focus=ACL(all kinds)/AAA/SSH-hardening/CoPP/uRPF/ZBF',
      { resyncVendor: 'cisco' });
  }, 120000);
});
