/**
 * Cisco IOS router — IPsec / VPN gap-analysis (~300 steps).
 * ISAKMP/IKEv1 policies & keys, IKEv2 proposals/policies/keyrings/
 * profiles, IPsec transform-sets, crypto maps (static/dynamic),
 * IPsec profiles, GRE-over-IPsec, sVTI/dVTI tunnels, DMVPN (NHRP),
 * PKI/trustpoint basics, plus the crypto show/clear/debug families.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-ipsec-vpn', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'no shutdown',
      'exit',
      'interface GigabitEthernet0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'interface Loopback0',
      'ip address 1.1.1.1 255.255.255.255',
      'exit',
      'end',

      { section: 'IKEv1 / ISAKMP policies', cmd: 'configure terminal' },
      ...sweep(5, (i) => [
        `crypto isakmp policy ${i * 10}`,
        `encryption aes ${128 + (i % 3) * 64}`,
        'hash sha256',
        'authentication pre-share',
        `group ${[2, 5, 14, 19, 24][i - 1]}`,
        `lifetime ${3600 * i}`,
        'exit',
      ]),
      'crypto isakmp key MyPreShared0 address 10.0.0.2',
      'crypto isakmp key MyPreShared1 address 10.0.0.0 255.255.255.0',
      'crypto isakmp key MyPreShared2 hostname peer.lab.local',
      'crypto isakmp keepalive 10 3',
      'crypto isakmp keepalive 10 3 periodic',
      'crypto isakmp nat keepalive 20',
      'crypto isakmp invalid-spi-recovery',
      'crypto isakmp identity address',
      'crypto isakmp identity hostname',
      'crypto isakmp aggressive-mode disable',
      'crypto isakmp profile IKEV1-PROF',
      'keyring default',
      'match identity address 10.0.0.2 255.255.255.255',
      'self-identity address',
      'exit',
      'end',
      'show crypto isakmp policy',
      'show crypto isakmp key',
      'show crypto isakmp sa',
      'show crypto isakmp sa detail',
      'show crypto isakmp profile',

      { section: 'IPsec transform-sets / profiles', cmd: 'configure terminal' },
      ...sweep(5, (i) => [
        `crypto ipsec transform-set TS${i} esp-aes 256 esp-sha256-hmac`,
        i === 1 ? 'mode tunnel' : 'mode transport',
        'exit',
      ]),
      'crypto ipsec transform-set TS-GCM esp-gcm 256',
      'crypto ipsec transform-set TS-AH ah-sha-hmac esp-aes',
      'crypto ipsec security-association lifetime seconds 3600',
      'crypto ipsec security-association lifetime kilobytes 4608000',
      'crypto ipsec security-association replay window-size 1024',
      'crypto ipsec security-association idle-time 600',
      'crypto ipsec df-bit clear',
      'crypto ipsec fragmentation before-encryption',
      'crypto ipsec profile IPSEC-PROF',
      'set transform-set TS1 TS2',
      'set pfs group14',
      'set security-association lifetime seconds 1800',
      'set ikev2-profile IKEV2-PROF',
      'exit',
      'end',
      'show crypto ipsec transform-set',
      'show crypto ipsec profile',
      'show crypto ipsec security-association lifetime',

      { section: 'crypto map (static/dynamic)', cmd: 'configure terminal' },
      'access-list 110 permit ip 192.168.1.0 0.0.0.255 192.168.2.0 0.0.0.255',
      'access-list 111 permit ip 192.168.1.0 0.0.0.255 192.168.3.0 0.0.0.255',
      ...sweep(3, (i) => [
        `crypto map CMAP ${i * 10} ipsec-isakmp`,
        `set peer 10.0.0.${i + 1}`,
        `set transform-set TS${i}`,
        `match address ${110 + (i - 1)}`,
        'set pfs group14',
        'set security-association lifetime seconds 3600',
        `description TUNNEL-${i}`,
        'exit',
      ]),
      'crypto dynamic-map DMAP 10',
      'set transform-set TS1',
      'reverse-route',
      'exit',
      'crypto map CMAP 100 ipsec-isakmp dynamic DMAP',
      'crypto map CMAP local-address GigabitEthernet0/1',
      'interface GigabitEthernet0/1',
      'crypto map CMAP',
      'exit',
      'end',
      'show crypto map',
      'show crypto map interface GigabitEthernet0/1',
      'show crypto ipsec sa',
      'show crypto ipsec sa detail',
      'show crypto engine connections active',

      { section: 'IKEv2', cmd: 'configure terminal' },
      'crypto ikev2 proposal IKEV2-PROP',
      'encryption aes-cbc-256 aes-gcm-256',
      'integrity sha256 sha512',
      'group 14 19 21',
      'prf sha256',
      'exit',
      'crypto ikev2 policy IKEV2-POL',
      'match address local 10.0.0.1',
      'proposal IKEV2-PROP',
      'exit',
      'crypto ikev2 keyring IKEV2-KR',
      'peer PEER1',
      'address 10.0.0.2',
      'pre-shared-key local LocalKey123',
      'pre-shared-key remote RemoteKey123',
      'exit',
      'exit',
      'crypto ikev2 profile IKEV2-PROF',
      'match identity remote address 10.0.0.2 255.255.255.255',
      'identity local address 10.0.0.1',
      'authentication local pre-share',
      'authentication remote pre-share',
      'keyring local IKEV2-KR',
      'lifetime 86400',
      'dpd 10 3 periodic',
      'exit',
      'crypto ikev2 dpd 10 3 periodic',
      'crypto ikev2 nat keepalive 20',
      'crypto ikev2 cookie-challenge 450',
      'crypto ikev2 window 10',
      'end',
      'show crypto ikev2 proposal',
      'show crypto ikev2 policy',
      'show crypto ikev2 profile',
      'show crypto ikev2 keyring',
      'show crypto ikev2 sa',
      'show crypto ikev2 sa detailed',
      'show crypto ikev2 stats',

      { section: 'sVTI / dVTI / GRE-over-IPsec', cmd: 'configure terminal' },
      'interface Tunnel0',
      'ip address 172.16.0.1 255.255.255.252',
      'tunnel source GigabitEthernet0/1',
      'tunnel destination 10.0.0.2',
      'tunnel mode ipsec ipv4',
      'tunnel protection ipsec profile IPSEC-PROF',
      'exit',
      'interface Tunnel1',
      'ip address 172.16.0.5 255.255.255.252',
      'tunnel source GigabitEthernet0/1',
      'tunnel destination 10.0.0.2',
      'tunnel mode gre ip',
      'tunnel protection ipsec profile IPSEC-PROF shared',
      'exit',
      'interface Virtual-Template1 type tunnel',
      'ip unnumbered Loopback0',
      'tunnel mode ipsec ipv4',
      'tunnel protection ipsec profile IPSEC-PROF',
      'exit',
      'crypto ipsec profile IPSEC-PROF',
      'set ikev2-profile IKEV2-PROF',
      'exit',
      'end',
      'show interfaces Tunnel0',
      'show crypto ipsec sa interface Tunnel0',
      'show crypto session',
      'show crypto session detail',

      { section: 'DMVPN / NHRP', cmd: 'configure terminal' },
      'interface Tunnel100',
      'ip address 172.20.0.1 255.255.255.0',
      'tunnel source GigabitEthernet0/1',
      'tunnel mode gre multipoint',
      'tunnel key 100',
      'ip nhrp authentication NHRPKEY',
      'ip nhrp network-id 100',
      'ip nhrp map 172.20.0.2 10.0.0.2',
      'ip nhrp map multicast 10.0.0.2',
      'ip nhrp nhs 172.20.0.2',
      'ip nhrp holdtime 600',
      'ip nhrp shortcut',
      'ip nhrp redirect',
      'tunnel protection ipsec profile IPSEC-PROF',
      'exit',
      'end',
      'show ip nhrp',
      'show ip nhrp brief',
      'show dmvpn',
      'show dmvpn detail',

      { section: 'PKI / trustpoint', cmd: 'configure terminal' },
      'crypto pki trustpoint CA1',
      'enrollment url http://10.0.0.5:80',
      'subject-name CN=R1.lab.local',
      'revocation-check crl',
      'rsakeypair SSH-KEY',
      'exit',
      'crypto pki authenticate CA1',
      'crypto pki enroll CA1',
      'end',
      'show crypto pki trustpoints',
      'show crypto pki certificates',
      'show crypto pki certificates verbose',

      { section: 'crypto clear / debug', cmd: 'clear crypto isakmp' },
      'clear crypto sa',
      'clear crypto session',
      'clear crypto ikev2 sa',
      'clear crypto isakmp sa',
      'debug crypto isakmp',
      'debug crypto ipsec',
      'debug crypto ikev2',
      'debug crypto pki transactions',
      'undebug all',
      'show crypto engine brief',
      'show crypto eli',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-ipsec-vpn', topology, steps,
      'focus=IKEv1/IKEv2/IPsec/crypto-map/VTI/DMVPN/PKI',
      { resyncVendor: 'cisco' });
  }, 120000);
});
