/**
 * Cisco IOS router — interface configuration gap-analysis (~300 steps).
 * IPv4/IPv6 addressing, secondary, unnumbered, loopbacks, tunnels,
 * subinterfaces + 802.1Q, bandwidth/MTU/delay, duplex/speed,
 * keepalive, NAT roles, helper-address, CDP/LLDP, shutdown cycles,
 * and the full per-interface show family.
 */
import { describe, it } from 'vitest';
import {
  buildCiscoLab, dumpRouter, resetSim, regressionSweep, sweep, each, type RouterStepInput,
} from './_router-suite';

describe('debug-dump: cisco-router-interfaces', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildCiscoLab();
    const steps: RouterStepInput[] = [
      { section: 'physical interface battery', cmd: 'enable' },
      'configure terminal',
      'interface GigabitEthernet0/0',
      ...each([
        'ip address 192.168.1.1 255.255.255.0',
        'ip address 192.168.100.1 255.255.255.0 secondary',
        'ipv6 address 2001:db8:1::1/64',
        'ipv6 address fe80::1 link-local',
        'ipv6 enable',
        'description ## LAN to L1 ##',
        'bandwidth 100000',
        'delay 100',
        'mtu 1500',
        'ip mtu 1400',
        'ipv6 mtu 1280',
        'duplex full',
        'speed 1000',
        'speed auto',
        'negotiation auto',
        'no keepalive',
        'keepalive 10',
        'load-interval 30',
        'ip redirects',
        'no ip redirects',
        'no ip proxy-arp',
        'ip proxy-arp',
        'no ip unreachables',
        'ip directed-broadcast',
        'no ip directed-broadcast',
        'arp timeout 600',
        'ip accounting',
        'cdp enable',
        'no cdp enable',
        'lldp transmit',
        'lldp receive',
        'ip flow ingress',
        'ip flow egress',
        'service-policy input PM1',
        'no shutdown',
      ], (c) => c),
      'exit',

      { section: 'loopbacks', cmd: 'configure terminal' },
      ...sweep(8, (i) => [
        `interface Loopback${i}`,
        `ip address 10.255.255.${i} 255.255.255.255`,
        `description LOOP-${i}`,
        'exit',
      ]),
      'end',
      'show ip interface brief',

      { section: 'unnumbered / dhcp / negotiated', cmd: 'configure terminal' },
      'interface Loopback100',
      'ip address 172.31.0.1 255.255.255.255',
      'exit',
      'interface GigabitEthernet0/1',
      'ip unnumbered Loopback100',
      'no ip unnumbered',
      'ip address dhcp',
      'ip address negotiated',
      'ip address 10.0.0.1 255.255.255.252',
      'no shutdown',
      'exit',
      'end',

      { section: '802.1Q subinterfaces', cmd: 'configure terminal' },
      ...sweep(10, (i) => [
        `interface GigabitEthernet0/0.${i * 10}`,
        `encapsulation dot1Q ${i * 10}`,
        `ip address 192.168.${i}.1 255.255.255.0`,
        i === 1 ? 'encapsulation dot1Q 10 native' : `description VLAN${i * 10}`,
        'exit',
      ]),
      'interface GigabitEthernet0/0.999',
      'encapsulation isl 999',
      'ip address 192.168.99.1 255.255.255.0',
      'exit',
      'end',
      'show ip interface brief',
      'show interfaces GigabitEthernet0/0.10',
      'show vlans',

      { section: 'tunnels', cmd: 'configure terminal' },
      'interface Tunnel0',
      'ip address 172.16.0.1 255.255.255.252',
      'tunnel source GigabitEthernet0/1',
      'tunnel destination 10.0.0.2',
      'tunnel mode gre ip',
      'tunnel key 1234',
      'keepalive 5 3',
      'exit',
      'interface Tunnel1',
      'ip address 172.16.0.5 255.255.255.252',
      'tunnel source Loopback0',
      'tunnel destination 10.0.0.2',
      'tunnel mode ipip',
      'tunnel protection ipsec profile IPSEC-PROF',
      'exit',
      'interface Tunnel2',
      'ipv6 address 2001:db8:ffff::1/64',
      'tunnel mode ipv6ip',
      'exit',
      'end',
      'show ip interface brief',
      'show interfaces Tunnel0',

      { section: 'DHCP relay / helper', cmd: 'configure terminal' },
      'interface GigabitEthernet0/0',
      'ip helper-address 10.0.0.2',
      'ip helper-address 10.0.0.3',
      'no ip helper-address 10.0.0.3',
      'ip dhcp relay information trusted',
      'exit',
      'end',

      { section: 'shutdown / error / clear', cmd: 'configure terminal' },
      ...each(['GigabitEthernet0/0', 'GigabitEthernet0/1'], (intf) => [
        `interface ${intf}`,
        'shutdown',
        'do show ip interface brief',
        'no shutdown',
        'exit',
      ]),
      'end',
      'clear counters GigabitEthernet0/0',
      'clear ip route *',
      'clear arp-cache',
      'clear ip arp 192.168.1.10',

      { section: 'per-interface show family', cmd: 'show interfaces' },
      ...each([
        'GigabitEthernet0/0', 'GigabitEthernet0/1', 'Loopback0', 'Tunnel0',
      ], (intf) => [
        `show interfaces ${intf}`,
        `show ip interface ${intf}`,
        `show ipv6 interface ${intf}`,
        `show interfaces ${intf} accounting`,
        `show interfaces ${intf} switchport`,
        `show interfaces ${intf} stats`,
        `show controllers ${intf}`,
        `show running-config interface ${intf}`,
      ]),
      'show interfaces description',
      'show interfaces status',
      'show ip interface brief',
      'show ipv6 interface brief',
      'show interfaces trunk',
      'show ip interface brief | include up',
      'end',
      ...regressionSweep('cisco'),
    ];
    await dumpRouter('cisco-router-interfaces', topology, steps,
      'focus=IPv4/IPv6 addressing, subinterfaces, tunnels, relay, show');
  }, 120000);
});
