/**
 * Huawei VRP router — RIP / IS-IS / BGP gap-analysis (~300 steps).
 * RIP (version/network/timers/import/silent/auth), IS-IS (level,
 * network-entity, cost-style, circuit), BGP (peer/group, network,
 * import-route, address-family, communities, reflector), plus their
 * display/reset/debugging families.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-isis-rip-bgp', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'undo shutdown',
      'quit',
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      'return',

      { section: 'RIP', cmd: 'system-view' },
      'rip 1',
      'version 2',
      'undo summary',
      ...sweep(6, (i) => `network 10.${i}.0.0`),
      'network 192.168.1.0',
      'network 10.0.0.0',
      'preference 100',
      'timers rip 30 180 120',
      'default-route originate',
      'import-route direct',
      'import-route static cost 3',
      'import-route ospf 1 cost 5',
      'maximum load-balancing 6',
      'silent-interface GigabitEthernet0/0/0',
      'undo silent-interface GigabitEthernet0/0/0',
      'checkzero',
      'verify-source',
      'quit',
      'interface GigabitEthernet0/0/1',
      'rip version 2 multicast',
      'rip authentication-mode md5 usual cipher RipKey123',
      'rip metricin 1',
      'rip metricout 2',
      'rip split-horizon',
      'rip poison-reverse',
      'rip summary-address 10.0.0.0 255.0.0.0',
      'quit',
      'return',
      'display rip',
      'display rip 1 route',
      'display rip 1 interface',
      'display rip 1 database',
      'display ip routing-table protocol rip',
      'reset rip 1 statistics',
      'debugging rip 1',
      'undo debugging all',

      { section: 'IS-IS', cmd: 'system-view' },
      'isis 1',
      'is-level level-2',
      'network-entity 49.0001.0000.0000.0001.00',
      'cost-style wide',
      'is-name R1',
      'timer lsp-refresh 900',
      'import-route direct',
      'import-route static',
      'import-route ospf 1 cost 10 level-2',
      'default-route-advertise',
      'set-overload',
      'undo set-overload',
      'maximum load-balancing 4',
      'preference 15',
      'quit',
      'interface GigabitEthernet0/0/1',
      'isis enable 1',
      'isis circuit-level level-2',
      'isis cost 10 level-2',
      'isis circuit-type p2p',
      'isis timer hello 10 level-2',
      'isis timer holding-multiplier 3 level-2',
      'isis authentication-mode md5 cipher IsisKey level-2',
      'quit',
      'return',
      'display isis peer',
      'display isis interface',
      'display isis route',
      'display isis lsdb',
      'display isis brief',
      'display ip routing-table protocol isis',
      'reset isis all',
      'debugging isis adjacency',
      'undo debugging all',

      { section: 'BGP', cmd: 'system-view' },
      'bgp 65000',
      'router-id 1.1.1.1',
      'graceful-restart',
      'timer keepalive 10 hold 30',
      ...sweep(4, (i) => [
        `peer 10.0.0.${i + 1} as-number ${65001 + i}`,
        `peer 10.0.0.${i + 1} description PEER-${i}`,
        `peer 10.0.0.${i + 1} connect-interface LoopBack0`,
        `peer 10.0.0.${i + 1} ebgp-max-hop 2`,
        `peer 10.0.0.${i + 1} password cipher BgpKey${i}`,
        `peer 10.0.0.${i + 1} timer keepalive 10 hold 30`,
      ]),
      'group IBGP internal',
      'peer IBGP connect-interface LoopBack0',
      'peer 10.0.0.10 group IBGP',
      'ipv4-family unicast',
      'network 192.168.1.0 255.255.255.0',
      'network 10.0.0.0 255.255.255.252',
      'aggregate 192.168.0.0 255.255.0.0 detail-suppressed',
      'import-route direct',
      'import-route static',
      'import-route ospf 1',
      'peer 10.0.0.1 enable',
      'peer 10.0.0.1 next-hop-local',
      'peer 10.0.0.1 reflect-client',
      'peer 10.0.0.1 route-policy RP import',
      'peer 10.0.0.1 ip-prefix PL-IN import',
      'peer 10.0.0.1 advertise-community',
      'peer 10.0.0.1 default-route-advertise',
      'peer 10.0.0.1 route-limit 1000',
      'maximum load-balancing 4',
      'quit',
      'ipv6-family unicast',
      'network 2001:db8:: 32',
      'quit',
      'quit',
      'return',
      ...each([
        'display bgp peer', 'display bgp peer verbose',
        'display bgp routing-table', 'display bgp routing-table statistics',
        'display bgp network', 'display bgp group',
        'display bgp routing-table community', 'display bgp paths',
        'display bgp ipv6 peer', 'display ip routing-table protocol bgp',
      ], (c) => c),
      'reset bgp all',
      'reset bgp 10.0.0.2 import',
      'debugging bgp event',
      'undo debugging all',

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-isis-rip-bgp', topology, steps,
      'focus=VRP RIP/IS-IS/BGP: peers, import-route, policy, display');
  }, 120000);
});
