/**
 * Huawei VRP router — IPsec / VPN gap-analysis (~300 steps).
 * IKE proposal/peer (v1/v2), IPsec proposal/policy (ISAKMP & manual)
 * + policy-template, IPsec profile, GRE-over-IPsec tunnel binding,
 * efficient-vpn, plus the crypto display/reset/debugging families.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-ipsec-vpn', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'undo shutdown',
      'quit',
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      'interface LoopBack0',
      'ip address 1.1.1.1 255.255.255.255',
      'quit',
      'return',

      { section: 'IKE proposal / peer', cmd: 'system-view' },
      ...sweep(4, (i) => [
        `ike proposal ${i}`,
        `encryption-algorithm aes-${[128, 192, 256, 256][i - 1]}`,
        'dh group14',
        'authentication-algorithm sha2-256',
        'authentication-method pre-share',
        `integrity-algorithm hmac-sha2-256`,
        `sa duration ${3600 * i}`,
        'quit',
      ]),
      'ike peer PEER1 v2',
      'pre-shared-key cipher MyKey@12345',
      'ike-proposal 1',
      'remote-address 10.0.0.2',
      'local-address 10.0.0.1',
      'remote-id-type ip',
      'dpd type periodic',
      'quit',
      'ike peer PEER2 v1',
      'exchange-mode aggressive',
      'pre-shared-key cipher Key2@12345',
      'remote-address 10.0.0.6',
      'quit',
      'return',
      'display ike proposal',
      'display ike peer',
      'display ike peer brief',
      'display ike sa',

      { section: 'IPsec proposal / policy', cmd: 'system-view' },
      ...sweep(3, (i) => [
        `ipsec proposal TP${i}`,
        'transform esp',
        'encapsulation-mode tunnel',
        'esp encryption-algorithm aes-256',
        'esp authentication-algorithm sha2-256',
        'quit',
      ]),
      'acl 3100',
      'rule 5 permit ip source 192.168.1.0 0.0.0.255 destination 192.168.2.0 0.0.0.255',
      'quit',
      'ipsec policy MAP1 10 isakmp',
      'security acl 3100',
      'ike-peer PEER1',
      'proposal TP1',
      'pfs dh-group14',
      'sa duration time-based 3600',
      'quit',
      'ipsec policy MAP1 20 manual',
      'security acl 3100',
      'proposal TP2',
      'tunnel local 10.0.0.1 remote 10.0.0.2',
      'sa spi inbound esp 12345',
      'sa spi outbound esp 54321',
      'sa string-key inbound esp cipher InKey123',
      'sa string-key outbound esp cipher OutKey123',
      'quit',
      'ipsec policy-template TPL1 1',
      'proposal TP1',
      'ike-peer PEER1',
      'quit',
      'ipsec policy DYN1 100 isakmp template TPL1',
      'return',
      'display ipsec proposal',
      'display ipsec policy',
      'display ipsec policy brief',
      'display ipsec sa',
      'display ipsec statistics esp',

      { section: 'apply policy / IPsec profile', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      'ipsec policy MAP1',
      'quit',
      'ipsec profile PROF1',
      'ike-peer PEER1',
      'proposal TP1',
      'pfs dh-group19',
      'quit',
      'interface Tunnel0/0/0',
      'tunnel-protocol ipsec',
      'ip address 172.16.0.1 255.255.255.252',
      'source 10.0.0.1',
      'destination 10.0.0.2',
      'ipsec profile PROF1',
      'quit',
      'interface Tunnel0/0/1',
      'tunnel-protocol gre',
      'ip address 172.16.0.5 255.255.255.252',
      'source LoopBack0',
      'destination 10.0.0.2',
      'ipsec profile PROF1',
      'quit',
      'return',
      'display ipsec policy interface GigabitEthernet0/0/1',
      'display ipsec profile',
      'display interface Tunnel0/0/0',

      { section: 'IKEv2', cmd: 'system-view' },
      'ikev2 proposal IKEV2P',
      'encryption-algorithm aes-256',
      'integrity-algorithm hmac-sha2-256',
      'dh group14',
      'prf hmac-sha2-256',
      'quit',
      'ikev2 policy IKEV2POL',
      'match local-address 10.0.0.1',
      'proposal IKEV2P',
      'quit',
      'ikev2 keychain KC1',
      'peer P1',
      'address 10.0.0.2',
      'pre-shared-key cipher V2Key@123',
      'quit',
      'quit',
      'ikev2 profile IKEV2PRF',
      'authentication-method local pre-share',
      'keychain KC1',
      'quit',
      'return',
      'display ikev2 proposal',
      'display ikev2 policy',
      'display ikev2 profile',
      'display ikev2 sa',

      { section: 'crypto reset / debug', cmd: 'reset ike sa' },
      'reset ipsec sa',
      'reset ike sa remote 10.0.0.2',
      'debugging ike all',
      'debugging ipsec all',
      'undo debugging all',
      'display ike error-info',
      'display ipsec sa brief',

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-ipsec-vpn', topology, steps,
      'focus=VRP IKE/IKEv2/IPsec proposal-policy/profile/GRE-IPsec',
      { resyncVendor: 'huawei' });
  }, 120000);
});
