/**
 * Huawei VRP router — OSPF / OSPFv3 gap-analysis (~300 steps).
 * Process/area/network, area types (stub/nssa), authentication,
 * cost/priority/timers/network-type, summarization, import-route,
 * default-route-advertise, silent-interface, bfd, OSPFv3, plus the
 * OSPF display/reset/debugging families.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-ospf', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/0',
      'ip address 192.168.1.1 255.255.255.0',
      'undo shutdown',
      'quit',
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      ...sweep(4, (i) => [
        `interface LoopBack${i}`,
        `ip address 10.10.${i}.1 255.255.255.0`,
        'quit',
      ]),
      'return',

      { section: 'OSPF process / area', cmd: 'system-view' },
      'ospf 1 router-id 1.1.1.1',
      'bandwidth-reference 10000',
      'spf-schedule-interval 5',
      'lsa-arrival-interval 100',
      'opaque-capability enable',
      'graceful-restart',
      'default-route-advertise always',
      'default-route-advertise cost 10 type 1',
      'import-route direct',
      'import-route static cost 20 type 1',
      'import-route rip 1',
      'import-route bgp route-policy RP',
      'maximum load-balancing 4',
      'preference 150',
      'silent-interface GigabitEthernet0/0/0',
      'undo silent-interface GigabitEthernet0/0/0',
      'area 0',
      ...sweep(6, (i) => `network 10.10.${i}.0 0.0.0.255`),
      'network 192.168.1.0 0.0.0.255',
      'network 10.0.0.0 0.0.0.3',
      'quit',
      'quit',
      'return',
      'display ospf brief',
      'display ospf cumulative',

      { section: 'area types / auth', cmd: 'system-view' },
      'ospf 1',
      'area 1',
      'stub',
      'stub no-summary',
      'default-cost 10',
      'quit',
      'area 2',
      'nssa',
      'nssa default-route-advertise no-summary',
      'quit',
      'area 3',
      'abr-summary 10.30.0.0 255.255.0.0',
      'quit',
      'area 0',
      'authentication-mode md5 1 cipher Huawei@123',
      'authentication-mode simple plain Huawei',
      'quit',
      'vlink-peer 2.2.2.2',
      'sham-link 1.1.1.1 2.2.2.2',
      'quit',
      'return',
      'display ospf brief',
      'display ospf abr-asbr',

      { section: 'per-interface OSPF', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      ...each([
        'ospf cost 100',
        'ospf dr-priority 200',
        'ospf timer hello 5',
        'ospf timer dead 20',
        'ospf timer retransmit 10',
        'ospf trans-delay 2',
        'ospf network-type p2p',
        'ospf network-type broadcast',
        'ospf network-type nbma',
        'ospf network-type p2mp',
        'ospf authentication-mode md5 1 cipher Key123',
        'ospf authentication-mode null',
        'ospf mtu-enable',
        'ospf bfd enable',
        'ospf bfd min-tx-interval 100 min-rx-interval 100',
        'ospf silent-interface',
      ], (c) => c),
      'quit',
      'return',
      'display ospf interface GigabitEthernet0/0/1',
      'display ospf interface all',

      { section: 'OSPFv3', cmd: 'system-view' },
      'ospfv3 1',
      'router-id 1.1.1.1',
      'area 0',
      'quit',
      'quit',
      'interface GigabitEthernet0/0/1',
      'ipv6 enable',
      'ipv6 address 2001:db8:1::1/64',
      'ospfv3 1 area 0',
      'ospfv3 cost 50',
      'ospfv3 network-type p2p',
      'ospfv3 timer hello 5',
      'quit',
      'return',
      'display ospfv3',
      'display ospfv3 peer',
      'display ospfv3 interface',
      'display ospfv3 routing-table',

      { section: 'OSPF display / reset / debug', cmd: 'display ospf peer' },
      ...each([
        'display ospf peer brief', 'display ospf interface',
        'display ospf lsdb', 'display ospf lsdb router',
        'display ospf lsdb network', 'display ospf lsdb summary',
        'display ospf lsdb ase', 'display ospf lsdb nssa',
        'display ospf routing', 'display ospf abr-asbr',
        'display ospf nexthop', 'display ospf vlink',
        'display ospf sham-link', 'display ospf statistics',
        'display ospf error', 'display ospf request-queue',
        'display ospf retrans-queue', 'display ip routing-table protocol ospf',
      ], (c) => c),
      'reset ospf process',
      'reset ospf 1 counters',
      'debugging ospf event',
      'debugging ospf packet',
      'undo debugging all',

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-ospf', topology, steps,
      'focus=VRP OSPF/OSPFv3: areas, auth, import-route, timers, display');
  }, 120000);
});
