/**
 * Huawei VRP router — info-center / SNMP / NTP / observability
 * gap-analysis (~300 steps). info-center logging (channels, logbuffer,
 * loghost, source), SNMP v1/v2c/v3 (community/group/usm-user/target-
 * host/traps), NTP (unicast/auth/source/access), LLDP, NQA, sFlow,
 * plus their display families.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-info-snmp-ntp', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      'interface LoopBack0',
      'ip address 1.1.1.1 255.255.255.255',
      'quit',
      'return',

      { section: 'info-center logging', cmd: 'system-view' },
      'info-center enable',
      'info-center timestamp log date',
      'info-center timestamp debugging date precision-time tenth-second',
      'info-center logbuffer',
      'info-center logbuffer size 1024',
      'info-center logbuffer channel 4',
      'info-center console channel 0',
      'info-center monitor channel 1',
      ...sweep(3, (i) =>
        `info-center loghost 10.0.0.${i + 1} channel 2 facility local6`),
      'info-center loghost source LoopBack0',
      'info-center source default channel 2 log level informational',
      'info-center source IFNET channel 2 log level warning',
      'info-center filter-id bymodule-alias default default',
      'info-center max-logfile-number 8',
      'info-center statistic-suppress enable',
      'return',
      'display info-center',
      'display logbuffer',
      'display logbuffer summary',
      'display trapbuffer',
      'display channel',
      'reset logbuffer',

      { section: 'SNMP v1/v2c', cmd: 'system-view' },
      'snmp-agent',
      'snmp-agent sys-info version v2c v3',
      'snmp-agent sys-info contact noc@lab.local',
      'snmp-agent sys-info location DC1-Rack5',
      'snmp-agent community read cipher RoComm123',
      'snmp-agent community write cipher RwComm123',
      'snmp-agent community read cipher AclComm mib-view iso acl 2000',
      'acl 2000',
      'rule 5 permit source 10.0.0.0 0.0.0.255',
      'quit',
      'snmp-agent mib-view included iso-view iso',
      'snmp-agent trap enable',
      'snmp-agent trap enable feature-name ospf',
      'snmp-agent trap enable feature-name bgp',
      'snmp-agent target-host trap-hostname H1 address 10.0.0.5 udp-port 162 trap-paramsname P1',
      'snmp-agent target-host trap-paramsname P1 v2c securityname cipher Pub123',
      'snmp-agent trap source LoopBack0',
      'snmp-agent packet max-size 1500',
      'snmp-agent protocol source-interface LoopBack0',
      'return',
      'display snmp-agent sys-info',
      'display snmp-agent community',
      'display snmp-agent mib-view',
      'display snmp-agent target-host',
      'display snmp-agent trap-list',
      'display snmp-agent statistics',

      { section: 'SNMPv3', cmd: 'system-view' },
      'snmp-agent group v3 GRP-RW privacy read-view iso write-view iso notify-view iso',
      'snmp-agent group v3 GRP-RO authentication read-view iso',
      'snmp-agent usm-user v3 adminv3 group GRP-RW',
      'snmp-agent usm-user v3 adminv3 authentication-mode sha2-256 cipher Auth@12345',
      'snmp-agent usm-user v3 adminv3 privacy-mode aes256 cipher Priv@12345',
      'snmp-agent usm-user v3 rouser group GRP-RO authentication-mode sha cipher Auth@67890',
      'snmp-agent local-engineid 800007DB0300DEADBEEF01',
      'snmp-agent target-host trap-hostname H3 address 10.0.0.8 trap-paramsname P3',
      'snmp-agent target-host trap-paramsname P3 v3 securityname adminv3 privacy',
      'return',
      'display snmp-agent usm-user',
      'display snmp-agent group',
      'display snmp-agent local-engineid',

      { section: 'NTP', cmd: 'system-view' },
      'ntp-service enable',
      'ntp-service authentication enable',
      'ntp-service authentication-keyid 1 authentication-mode md5 cipher NtpKey@123',
      'ntp-service authentication-keyid 2 authentication-mode hmac-sha256 cipher NtpKey@456',
      'ntp-service reliable authentication-keyid 1',
      ...sweep(3, (i) =>
        `ntp-service unicast-server 10.0.0.${i + 20} authentication-keyid 1 preference`),
      'ntp-service unicast-peer 10.0.0.30',
      'ntp-service refclock-master 3',
      'ntp-service source-interface LoopBack0',
      'ntp-service access peer 2000',
      'ntp-service access server 2000',
      'ntp-service max-dynamic-sessions 20',
      'ntp-service server disable',
      'undo ntp-service server disable',
      'return',
      'display ntp-service status',
      'display ntp-service sessions',
      'display ntp-service trace',
      'display clock',

      { section: 'LLDP / NQA / sFlow', cmd: 'system-view' },
      'lldp enable',
      'lldp message-transmission interval 30',
      'lldp message-transmission hold-multiplier 4',
      'lldp management-address 1.1.1.1',
      'interface GigabitEthernet0/0/1',
      'lldp enable',
      'lldp admin-status txrx',
      'quit',
      'nqa test-instance admin jitter',
      'test-type jitter',
      'destination-address ipv4 10.0.0.2',
      'destination-port 16384',
      'frequency 60',
      'start now',
      'quit',
      'sflow collector 1 ip 10.0.0.9',
      'sflow agent ip 1.1.1.1',
      'interface GigabitEthernet0/0/1',
      'sflow flow-sampling collector 1',
      'sflow flow-sampling rate 1000',
      'sflow counter-sampling collector 1',
      'quit',
      'return',
      ...each([
        'display lldp local', 'display lldp neighbor',
        'display lldp neighbor brief', 'display lldp statistics',
        'display nqa results test-instance admin jitter',
        'display sflow', 'display ip routing-table',
      ], (c) => c),

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-info-snmp-ntp', topology, steps,
      'focus=VRP info-center/SNMPv1-3/NTP/LLDP/NQA/sFlow',
      { resyncVendor: 'huawei' });
  }, 120000);
});
