/**
 * Huawei VRP router — ACL / AAA / device-security gap-analysis (~300).
 * Basic/advanced/named ACLs, time-range, traffic-filter binding,
 * AAA (local/RADIUS/HWTACACS, domain), local-user, SSH/STelnet,
 * service hardening, CPU-defend / attack-defense, plus the security
 * display family.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-acl-aaa-security', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      'return',

      { section: 'basic ACL (2000-2999)', cmd: 'system-view' },
      'acl 2000',
      ...sweep(20, (i) =>
        `rule ${i * 5} permit source 192.168.${i}.0 0.0.0.255`),
      'rule 1000 deny source any',
      'step 10',
      'quit',
      'acl number 2001',
      'rule permit source 10.0.0.0 0.0.0.255',
      'quit',
      'return',
      'display acl 2000',
      'display acl all',

      { section: 'advanced ACL (3000-3999)', cmd: 'system-view' },
      'acl 3000',
      ...sweep(12, (i) => [
        `rule ${i * 5} permit tcp source 192.168.${i}.0 0.0.0.255 destination-port eq ${80 + i}`,
        `rule ${i * 5 + 1} permit udp source any destination 10.0.0.${i} 0 destination-port eq 53`,
      ]),
      'rule 900 permit icmp icmp-type echo',
      'rule 1000 deny ip',
      'quit',
      'acl name WAN-IN advance',
      'rule 5 permit tcp destination-port eq 443',
      'rule 10 deny ip',
      'quit',
      'return',
      'display acl 3000',
      'display acl name WAN-IN',

      { section: 'time-range / traffic-filter', cmd: 'system-view' },
      'time-range BUSINESS 08:00 to 18:00 working-day',
      'time-range OFF 00:00 to 23:59 off-day',
      'acl 3001',
      'rule 5 permit ip time-range BUSINESS',
      'quit',
      'interface GigabitEthernet0/0/1',
      'traffic-filter inbound acl 3000',
      'traffic-filter outbound acl 2000',
      'quit',
      'return',
      'display time-range all',
      'display traffic-filter applied-record',

      { section: 'AAA', cmd: 'system-view' },
      'aaa',
      'authentication-scheme sch1',
      'authentication-mode radius local',
      'quit',
      'authorization-scheme aut1',
      'authorization-mode hwtacacs local',
      'quit',
      'accounting-scheme acc1',
      'accounting-mode radius',
      'quit',
      'domain lab.local',
      'authentication-scheme sch1',
      'accounting-scheme acc1',
      'radius-server group RG1',
      'quit',
      'local-user admin password irreversible-cipher Admin@12345',
      'local-user admin privilege level 15',
      'local-user admin service-type ssh terminal',
      'local-user oper password irreversible-cipher Oper@12345',
      'local-user oper privilege level 3',
      'quit',
      'radius-server template RT1',
      'radius-server authentication 10.0.0.2 1812',
      'radius-server accounting 10.0.0.2 1813',
      'radius-server shared-key cipher RadKey123',
      'quit',
      'hwtacacs-server template HT1',
      'hwtacacs-server authentication 10.0.0.3',
      'hwtacacs-server shared-key cipher TacKey123',
      'quit',
      'return',
      'display aaa configuration',
      'display domain',
      'display local-user',
      'display radius-server configuration',
      'display hwtacacs-server template',

      { section: 'SSH / STelnet hardening', cmd: 'system-view' },
      'sysname R1',
      'rsa local-key-pair create',
      'dsa local-key-pair create',
      'ssh server enable',
      'stelnet server enable',
      'ssh server timeout 60',
      'ssh server authentication-retries 3',
      'ssh server rekey-interval 60',
      'ssh server port 2222',
      'ssh server cipher aes256_ctr',
      'ssh user admin',
      'ssh user admin authentication-type password',
      'ssh user admin service-type stelnet',
      'ssh authorization-type default aaa',
      'user-interface vty 0 4',
      'authentication-mode aaa',
      'protocol inbound ssh',
      'user privilege level 15',
      'quit',
      'undo telnet server enable',
      'undo ftp server enable',
      'return',
      'display ssh server status',
      'display ssh server session',
      'display ssh user-information',
      'display rsa local-key-pair public',

      { section: 'attack-defense / CPU-defend', cmd: 'system-view' },
      'cpu-defend policy P1',
      'car packet-type arp-request cir 64',
      'car packet-type icmp cir 32',
      'quit',
      'cpu-defend-policy P1 global',
      'firewall enable',
      'firewall defend ip-spoofing enable',
      'firewall defend land enable',
      'firewall defend smurf enable',
      'firewall defend icmp-flood enable',
      'firewall defend tcp-syn-flood enable',
      'interface GigabitEthernet0/0/1',
      'ip urpf strict',
      'undo ip urpf',
      'quit',
      'return',
      'display cpu-defend policy P1',
      'display firewall defend flag',

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-acl-aaa-security', topology, steps,
      'focus=VRP ACL(basic/adv/named)/AAA/SSH-hardening/attack-defense',
      { resyncVendor: 'huawei' });
  }, 120000);
});
