/**
 * Huawei router — end-to-end routed connectivity gap-analysis (~300).
 * Brings up R1+R2 (VRP) with addressing, then exercises the data path
 * under static, OSPF, RIP, BGP and DHCP, with host (Linux/Windows)
 * ping/tracert, ARP/route inspection, and fault-injection + recovery.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, each,
  type RouterStepInput,
} from './_router-suite';

const cfgR1 = (extra: string[] = []): RouterStepInput[] => ([
  { on: 'r1', cmd: 'system-view' },
  { on: 'r1', cmd: 'sysname R1' },
  { on: 'r1', cmd: 'interface GigabitEthernet0/0/1' },
  { on: 'r1', cmd: 'ip address 192.168.1.1 255.255.255.0' },
  { on: 'r1', cmd: 'undo shutdown' },
  { on: 'r1', cmd: 'quit' },
  { on: 'r1', cmd: 'interface GigabitEthernet0/0/0' },
  { on: 'r1', cmd: 'ip address 10.0.0.1 255.255.255.252' },
  { on: 'r1', cmd: 'undo shutdown' },
  { on: 'r1', cmd: 'quit' },
  ...extra.map((c) => ({ on: 'r1', cmd: c })),
  { on: 'r1', cmd: 'return' },
]);

const cfgR2 = (extra: string[] = []): RouterStepInput[] => ([
  { on: 'r2', cmd: 'system-view' },
  { on: 'r2', cmd: 'sysname R2' },
  { on: 'r2', cmd: 'interface GigabitEthernet0/0/1' },
  { on: 'r2', cmd: 'ip address 192.168.2.1 255.255.255.0' },
  { on: 'r2', cmd: 'undo shutdown' },
  { on: 'r2', cmd: 'quit' },
  { on: 'r2', cmd: 'interface GigabitEthernet0/0/0' },
  { on: 'r2', cmd: 'ip address 10.0.0.2 255.255.255.252' },
  { on: 'r2', cmd: 'undo shutdown' },
  { on: 'r2', cmd: 'quit' },
  ...extra.map((c) => ({ on: 'r2', cmd: c })),
  { on: 'r2', cmd: 'return' },
]);

const verify = (label: string): RouterStepInput[] => ([
  { section: `verify (${label})`, on: 'r1', cmd: 'display ip interface brief' },
  { on: 'r1', cmd: 'display ip routing-table' },
  { on: 'r2', cmd: 'display ip routing-table' },
  { on: 'r1', cmd: 'ping 10.0.0.2' },
  { on: 'r1', cmd: 'ping 192.168.2.1' },
  { on: 'r2', cmd: 'ping 192.168.1.1' },
  { on: 'linux1', cmd: 'ping -c 3 192.168.1.1' },
  { on: 'linux1', cmd: 'ping -c 3 192.168.2.1' },
  { on: 'linux1', cmd: 'ping -c 3 192.168.2.10' },
  { on: 'linux1', cmd: 'traceroute 192.168.2.10' },
  { on: 'win1', cmd: 'ping 192.168.1.10' },
  { on: 'win1', cmd: 'tracert 192.168.1.10' },
  { on: 'r1', cmd: 'display arp' },
  { on: 'r2', cmd: 'display arp' },
]);

describe('debug-dump: huawei-router-connectivity', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'host setup', on: 'linux1', cmd: 'ip addr add 192.168.1.10/24 dev eth0' },
      { on: 'linux1', cmd: 'ip link set eth0 up' },
      { on: 'linux1', cmd: 'ip route add default via 192.168.1.1' },
      { on: 'linux1', cmd: 'ip addr show eth0' },
      { on: 'win1', cmd: 'netsh interface ip set address eth0 static 192.168.2.10 255.255.255.0 192.168.2.1' },
      { on: 'win1', cmd: 'ipconfig /all' },

      { section: 'scenario 1: static', on: 'r1', cmd: 'system-view' },
      ...cfgR1(['ip route-static 192.168.2.0 255.255.255.0 10.0.0.2']),
      ...cfgR2(['ip route-static 192.168.1.0 255.255.255.0 10.0.0.1']),
      ...verify('static'),

      { section: 'scenario 2: default', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'undo ip route-static 192.168.2.0 255.255.255.0 10.0.0.2' },
      { on: 'r1', cmd: 'ip route-static 0.0.0.0 0.0.0.0 10.0.0.2' },
      { on: 'r1', cmd: 'return' },
      { on: 'r2', cmd: 'system-view' },
      { on: 'r2', cmd: 'undo ip route-static 192.168.1.0 255.255.255.0 10.0.0.1' },
      { on: 'r2', cmd: 'ip route-static 0.0.0.0 0.0.0.0 10.0.0.1' },
      { on: 'r2', cmd: 'return' },
      ...verify('default'),

      { section: 'scenario 3: OSPF', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'undo ip route-static 0.0.0.0 0.0.0.0 10.0.0.2' },
      { on: 'r1', cmd: 'ospf 1 router-id 1.1.1.1' },
      { on: 'r1', cmd: 'area 0' },
      { on: 'r1', cmd: 'network 192.168.1.0 0.0.0.255' },
      { on: 'r1', cmd: 'network 10.0.0.0 0.0.0.3' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'return' },
      { on: 'r2', cmd: 'system-view' },
      { on: 'r2', cmd: 'undo ip route-static 0.0.0.0 0.0.0.0 10.0.0.1' },
      { on: 'r2', cmd: 'ospf 1 router-id 2.2.2.2' },
      { on: 'r2', cmd: 'area 0' },
      { on: 'r2', cmd: 'network 192.168.2.0 0.0.0.255' },
      { on: 'r2', cmd: 'network 10.0.0.0 0.0.0.3' },
      { on: 'r2', cmd: 'quit' },
      { on: 'r2', cmd: 'quit' },
      { on: 'r2', cmd: 'return' },
      { on: 'r1', cmd: 'display ospf peer' },
      { on: 'r1', cmd: 'display ospf peer brief' },
      { on: 'r1', cmd: 'display ospf lsdb' },
      { on: 'r2', cmd: 'display ospf peer' },
      ...verify('ospf'),

      { section: 'scenario 4: RIP', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'undo ospf 1' },
      { on: 'r1', cmd: 'rip 1' },
      { on: 'r1', cmd: 'version 2' },
      { on: 'r1', cmd: 'undo summary' },
      { on: 'r1', cmd: 'network 192.168.1.0' },
      { on: 'r1', cmd: 'network 10.0.0.0' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'return' },
      { on: 'r2', cmd: 'system-view' },
      { on: 'r2', cmd: 'undo ospf 1' },
      { on: 'r2', cmd: 'rip 1' },
      { on: 'r2', cmd: 'version 2' },
      { on: 'r2', cmd: 'undo summary' },
      { on: 'r2', cmd: 'network 192.168.2.0' },
      { on: 'r2', cmd: 'network 10.0.0.0' },
      { on: 'r2', cmd: 'quit' },
      { on: 'r2', cmd: 'return' },
      { on: 'r1', cmd: 'display rip 1 route' },
      { on: 'r2', cmd: 'display rip 1 route' },
      ...verify('rip'),

      { section: 'scenario 5: BGP', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'undo rip 1' },
      { on: 'r1', cmd: 'bgp 65001' },
      { on: 'r1', cmd: 'router-id 1.1.1.1' },
      { on: 'r1', cmd: 'peer 10.0.0.2 as-number 65002' },
      { on: 'r1', cmd: 'ipv4-family unicast' },
      { on: 'r1', cmd: 'network 192.168.1.0 255.255.255.0' },
      { on: 'r1', cmd: 'peer 10.0.0.2 enable' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'return' },
      { on: 'r2', cmd: 'system-view' },
      { on: 'r2', cmd: 'undo rip 1' },
      { on: 'r2', cmd: 'bgp 65002' },
      { on: 'r2', cmd: 'router-id 2.2.2.2' },
      { on: 'r2', cmd: 'peer 10.0.0.1 as-number 65001' },
      { on: 'r2', cmd: 'ipv4-family unicast' },
      { on: 'r2', cmd: 'network 192.168.2.0 255.255.255.0' },
      { on: 'r2', cmd: 'peer 10.0.0.1 enable' },
      { on: 'r2', cmd: 'quit' },
      { on: 'r2', cmd: 'quit' },
      { on: 'r2', cmd: 'return' },
      { on: 'r1', cmd: 'display bgp peer' },
      { on: 'r1', cmd: 'display bgp routing-table' },
      ...verify('bgp'),

      { section: 'scenario 6: DHCP', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'dhcp enable' },
      { on: 'r1', cmd: 'ip pool LAN1' },
      { on: 'r1', cmd: 'network 192.168.1.0 mask 255.255.255.0' },
      { on: 'r1', cmd: 'gateway-list 192.168.1.1' },
      { on: 'r1', cmd: 'dns-list 8.8.8.8' },
      { on: 'r1', cmd: 'excluded-ip-address 192.168.1.1 192.168.1.9' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'interface GigabitEthernet0/0/1' },
      { on: 'r1', cmd: 'dhcp select global' },
      { on: 'r1', cmd: 'quit' },
      { on: 'r1', cmd: 'return' },
      { on: 'linux1', cmd: 'ip addr flush dev eth0' },
      { on: 'linux1', cmd: 'dhclient eth0' },
      { on: 'linux1', cmd: 'ip addr show eth0' },
      { on: 'r1', cmd: 'display ip pool' },
      { on: 'r1', cmd: 'display dhcp server statistics' },

      { section: 'fault injection', on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'interface GigabitEthernet0/0/0' },
      { on: 'r1', cmd: 'shutdown' },
      { on: 'r1', cmd: 'return' },
      { on: 'r1', cmd: 'display ip interface brief' },
      { on: 'linux1', cmd: 'ping -c 2 192.168.2.10' },
      { on: 'r1', cmd: 'system-view' },
      { on: 'r1', cmd: 'interface GigabitEthernet0/0/0' },
      { on: 'r1', cmd: 'undo shutdown' },
      { on: 'r1', cmd: 'return' },
      { on: 'linux1', cmd: 'ping -c 3 192.168.2.10' },

      { section: 'final state', on: 'r1', cmd: 'display current-configuration' },
      ...each([
        'display ip routing-table', 'display arp', 'display ip interface brief',
      ], (c) => ({ on: 'r1', cmd: c })),

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-connectivity', topology, steps,
      'focus=VRP routed data path: static/default/OSPF/RIP/BGP/DHCP + faults');
  }, 180000);
});
