/**
 * Huawei VRP router — VRRP & QoS gap-analysis (~300 steps).
 * VRRP (vrid virtual-ip/priority/preempt/timers/auth/track/admin-
 * vrrp), BFD-for-VRRP; QoS (traffic classifier/behavior/policy,
 * remark, car, queue/wfq/llq, gts/line-rate), MQC apply, plus the
 * VRRP/QoS display families.
 */
import { describe, it } from 'vitest';
import {
  buildHuaweiLab, dumpRouter, resetSim, regressionSweep, sweep, each,
  type RouterStepInput,
} from './_router-suite';

describe('debug-dump: huawei-router-vrrp-qos', () => {
  it('writes the transcript', async () => {
    resetSim();
    const { topology } = buildHuaweiLab();
    const steps: RouterStepInput[] = [
      { section: 'base addressing', cmd: 'system-view' },
      'interface GigabitEthernet0/0/0',
      'ip address 192.168.1.2 255.255.255.0',
      'undo shutdown',
      'quit',
      'interface GigabitEthernet0/0/1',
      'ip address 10.0.0.1 255.255.255.252',
      'undo shutdown',
      'quit',
      'return',

      { section: 'VRRP', cmd: 'system-view' },
      'interface GigabitEthernet0/0/0',
      ...sweep(4, (i) => [
        `vrrp vrid ${i} virtual-ip 192.168.1.${i}`,
        `vrrp vrid ${i} virtual-ip 192.168.1.${100 + i}`,
        `vrrp vrid ${i} priority ${100 + i * 10}`,
        `vrrp vrid ${i} preempt-mode timer delay 20`,
        `vrrp vrid ${i} timer advertise 1`,
        `vrrp vrid ${i} authentication-mode md5 Vrrp@Key${i}`,
        `vrrp vrid ${i} track interface GigabitEthernet0/0/1 reduced 30`,
        `vrrp vrid ${i} track ip route 10.0.0.0 255.0.0.0 reduced 20`,
        `vrrp vrid ${i} description VRRP-GRP-${i}`,
        `admin-vrrp vrid ${i}`,
      ]),
      'vrrp vrid 1 version 3',
      'quit',
      'return',
      'display vrrp',
      'display vrrp brief',
      'display vrrp interface GigabitEthernet0/0/0',
      'display vrrp statistics',

      { section: 'BFD for VRRP', cmd: 'system-view' },
      'bfd',
      'quit',
      'bfd VRRP1 bind peer-ip 10.0.0.2 source-ip 10.0.0.1 auto',
      'discriminator local 1',
      'discriminator remote 2',
      'min-tx-interval 100',
      'min-rx-interval 100',
      'detect-multiplier 3',
      'commit',
      'quit',
      'interface GigabitEthernet0/0/0',
      'vrrp vrid 1 track bfd-session 1 reduced 50',
      'quit',
      'return',
      'display bfd configuration all',
      'display bfd session all',

      { section: 'QoS — classifier/behavior/policy', cmd: 'system-view' },
      'acl 3000',
      'rule 5 permit ip dscp ef',
      'quit',
      'traffic classifier VOICE operator or',
      'if-match dscp ef',
      'if-match acl 3000',
      'if-match protocol rtp',
      'if-match 8021p 5',
      'quit',
      'traffic classifier VIDEO operator and',
      'if-match dscp af41',
      'quit',
      'traffic classifier CRITICAL',
      'if-match protocol ospf',
      'if-match ip-precedence 6',
      'quit',
      'traffic behavior B-VOICE',
      'remark dscp ef',
      'queue ef bandwidth 2000',
      'car cir 2000 pir 4000 cbs 50000 pbs 100000',
      'statistics enable',
      'quit',
      'traffic behavior B-VIDEO',
      'remark dscp af41',
      'queue af bandwidth pct 25',
      'quit',
      'traffic behavior B-CRIT',
      'remark 8021p 6',
      'queue af bandwidth pct 15',
      'quit',
      'traffic behavior B-DROP',
      'deny',
      'quit',
      'traffic policy WAN-OUT',
      'classifier VOICE behavior B-VOICE',
      'classifier VIDEO behavior B-VIDEO',
      'classifier CRITICAL behavior B-CRIT',
      'quit',
      'return',
      'display traffic classifier user-defined',
      'display traffic behavior user-defined',
      'display traffic policy user-defined WAN-OUT',

      { section: 'QoS apply / shaping', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      'traffic-policy WAN-OUT outbound',
      'qos lr outbound cir 100000 cbs 1875000',
      'qos gts dscp ef cir 2000 cbs 50000',
      'qos queue 5 length packets 100',
      'qos wfq',
      'qos wred dscp',
      'trust dscp',
      'trust 8021p',
      'qos queue-profile QP1',
      'quit',
      'qos queue-profile QP1',
      'schedule wfq 0 to 5',
      'quit',
      'return',
      'display traffic-policy applied-record',
      'display qos configuration interface GigabitEthernet0/0/1',
      'display qos queue statistics interface GigabitEthernet0/0/1',
      'display qos map-table',

      { section: 'legacy QoS', cmd: 'system-view' },
      'interface GigabitEthernet0/0/1',
      'qos car inbound cir 8000 cbs 1500000',
      'qos pq',
      'qos cq',
      'qos wrr',
      'qos priority 5',
      'undo qos pq',
      'quit',
      'return',
      'display qos pq interface GigabitEthernet0/0/1',
      'display qos cq interface GigabitEthernet0/0/1',
      'display qos car interface GigabitEthernet0/0/1',

      ...regressionSweep('huawei'),
    ];
    await dumpRouter('huawei-router-vrrp-qos', topology, steps,
      'focus=VRP VRRP/BFD-for-VRRP + MQC QoS classifier/behavior/policy',
      { resyncVendor: 'huawei' });
  }, 120000);
});
