import { CommandRegistry } from '@/command-kernel/registry/command-registry';
import { CmdInterpreter } from './CmdInterpreter';
import { ArpCommand } from './commands/Arp';
import { CdCommand } from './commands/Cd';
import { ChcpCommand } from './commands/Chcp';
import { ClsCommand } from './commands/Cls';
import { CopyCommand } from './commands/Copy';
import { DateCommand } from './commands/Date';
import { DelCommand } from './commands/Del';
import { DirCommand } from './commands/Dir';
import { DoskeyCommand } from './commands/Doskey';
import { WinEchoCommand } from './commands/Echo';
import { AttribCommand } from './commands/Attrib';
import { AuditpolCommand } from './commands/Auditpol';
import { FcCommand } from './commands/Fc';
import { FindCommand } from './commands/Find';
import { FindstrCommand } from './commands/Findstr';
import { GetmacCommand } from './commands/Getmac';
import { HostnameCommand } from './commands/Hostname';
import { IcaclsCommand } from './commands/Icacls';
import { IpconfigCommand } from './commands/Ipconfig';
import { MkdirCommand } from './commands/Mkdir';
import { MoreCommand } from './commands/More';
import { MoveCommand } from './commands/Move';
import { NbtstatCommand } from './commands/Nbtstat';
import { NetCommand } from './commands/Net';
import { NslookupCommand } from './commands/Nslookup';
import { PingCommand } from './commands/Ping';
import { PrintCommand } from './commands/Print';
import { RegCommand } from './commands/Reg';
import { RenCommand } from './commands/Ren';
import { RmdirCommand } from './commands/Rmdir';
import { RouteCommand } from './commands/Route';
import { SchtasksCommand } from './commands/Schtasks';
import { NetstatCommand } from './commands/Netstat';
import { ScCommand } from './commands/Sc';
import { SetCommand } from './commands/Set';
import { SetxCommand } from './commands/Setx';
import { SortCommand } from './commands/Sort';
import { StartCommand } from './commands/Start';
import { SysteminfoCommand } from './commands/Systeminfo';
import { TaskkillCommand } from './commands/Taskkill';
import { TasklistCommand } from './commands/Tasklist';
import { TimeCommand } from './commands/Time';
import { TracertCommand } from './commands/Tracert';
import { WhereCommand } from './commands/Where';
import { WhoamiCommand } from './commands/Whoami';
import { WmicCommand } from './commands/Wmic';
import { TreeCommand } from './commands/Tree';
import { TypeCommand } from './commands/Type';
import { VerCommand } from './commands/Ver';
import { VolCommand } from './commands/Vol';
import { WinrmCommand } from './commands/Winrm';
import { XcopyCommand } from './commands/Xcopy';
import { WindowsMachineApi, WindowsMachineApiDeps } from './WindowsMachineApi';

/**
 * Assemble le registre de commandes cmd.exe migrées et le `CmdInterpreter`
 * qui les exécute — l'unique point d'entrée que `WindowsPC` doit connaître
 * (migration_framework.md §6).
 */
export function createWindowsHostShell(deps: WindowsMachineApiDeps): { registry: CommandRegistry; interpreter: CmdInterpreter } {
  const registry = new CommandRegistry();
  const machine = new WindowsMachineApi(deps);

  registry.register(() => new ArpCommand());
  registry.register(() => new GetmacCommand());
  registry.register(() => new RouteCommand());
  registry.register(() => new PingCommand());
  registry.register(() => new TracertCommand());
  registry.register(() => new NslookupCommand());
  registry.register(() => new IpconfigCommand());
  registry.register(() => new CdCommand());
  registry.register(() => new MkdirCommand());
  registry.register(() => new RmdirCommand());
  registry.register(() => new TypeCommand());
  registry.register(() => new CopyCommand());
  registry.register(() => new MoveCommand());
  registry.register(() => new RenCommand());
  registry.register(() => new DelCommand());
  registry.register(() => new TreeCommand());
  registry.register(() => new SetCommand());
  registry.register(() => new ClsCommand());
  registry.register(() => new WinEchoCommand());
  registry.register(() => new DirCommand());
  registry.register(() => new VerCommand());
  registry.register(() => new HostnameCommand());
  registry.register(() => new VolCommand());
  registry.register(() => new ChcpCommand());
  registry.register(() => new DateCommand());
  registry.register(() => new TimeCommand());
  registry.register(() => new SysteminfoCommand());
  registry.register(() => new TasklistCommand());
  registry.register(() => new TaskkillCommand());
  registry.register(() => new NetstatCommand());
  registry.register(() => new ScCommand());
  registry.register(() => new WmicCommand());
  registry.register(() => new FindstrCommand());
  registry.register(() => new WhoamiCommand());
  registry.register(() => new IcaclsCommand());
  registry.register(() => new AttribCommand());
  registry.register(() => new FindCommand());
  registry.register(() => new SortCommand());
  registry.register(() => new MoreCommand());
  registry.register(() => new FcCommand());
  registry.register(() => new XcopyCommand());
  registry.register(() => new WhereCommand());
  registry.register(() => new DoskeyCommand());
  registry.register(() => new NetCommand());
  registry.register(() => new SchtasksCommand());
  registry.register(() => new PrintCommand());
  registry.register(() => new RegCommand());
  registry.register(() => new SetxCommand());
  registry.register(() => new StartCommand());
  registry.register(() => new NbtstatCommand());
  registry.register(() => new AuditpolCommand());
  registry.register(() => new WinrmCommand());

  const interpreter = new CmdInterpreter(registry, machine);

  return { registry, interpreter };
}
