/**
 * md5crypt — the "$1$" Unix/Cisco crypt scheme (Poul-Henning Kamp).
 *
 * Reference vectors generated by an independent implementation (glibc crypt
 * via python3, cross-checked with `openssl passwd -1`). This is the genuine
 * algorithm behind Cisco `secret 5` and Linux `$1$` shadow entries, where the
 * simulator currently leaks the plaintext.
 */

import { describe, it, expect } from 'vitest';
import { md5Crypt } from '@/crypto/passwords';

describe('md5Crypt — glibc/openssl reference vectors', () => {
  it.each([
    ['password', 'abcdefgh', '$1$abcdefgh$G//4keteveJp0qb8z2DxG/'],
    ['', 'abcdefgh', '$1$abcdefgh$M55TzYaaccxVGbptZWaxX/'],
    ['cisco', 'saltsalt', '$1$saltsalt$mgtPQSkJ1HLLNgz95mmHS/'],
    ['Hello World!', 'x', '$1$x$dE7FnOBlumtZdInBsdUcm.'],
    ['a', '12345678', '$1$12345678$3Uz6TyHSiGZR0yDMOX3jO0'],
    ['P@ssw0rd', 'Ab9Cd3Ef', '$1$Ab9Cd3Ef$.AFfLLC1SSVdyuM.P1fS7.'],
  ])('md5Crypt(%j, %j)', (password, salt, expected) => {
    expect(md5Crypt(password, salt)).toBe(expected);
  });
});

describe('md5Crypt — structure', () => {
  it('produces the $1$<salt>$<22-char> layout', () => {
    const out = md5Crypt('secret', 'abcd');
    expect(out).toMatch(/^\$1\$abcd\$[./0-9A-Za-z]{22}$/);
  });

  it('truncates the salt to 8 characters (glibc behaviour)', () => {
    // The 9th salt character is ignored, so both salts yield the same hash.
    expect(md5Crypt('password', 'abcdefghIGNORED')).toBe(
      md5Crypt('password', 'abcdefgh'),
    );
  });

  it('is deterministic', () => {
    expect(md5Crypt('repeat', 'salt')).toBe(md5Crypt('repeat', 'salt'));
  });

  it('different salts give different hashes', () => {
    expect(md5Crypt('same', 'salt1')).not.toBe(md5Crypt('same', 'salt2'));
  });
});
