/**
 * Default `?` help descriptions for CLI keywords that appear as
 * intermediate trie nodes (e.g. the `dhcp` in `show ip dhcp binding`).
 *
 * When a command path is registered, intermediate nodes are created with a
 * placeholder description equal to their own keyword. Rendering that
 * placeholder verbatim produced "dhcp   dhcp" style help lines — unlike
 * IOS/VRP, which always describe every keyword. This dictionary supplies
 * vendor-neutral descriptions for the common protocol/feature keywords;
 * `descriptionForKeyword` is the single lookup used by the help renderer.
 */

const KEYWORD_DESCRIPTIONS: ReadonlyMap<string, string> = new Map<string, string>([
  ['aaa', 'Authentication, Authorization and Accounting'],
  ['archive', 'Archive the configuration'],
  ['dot1q', 'IEEE 802.1Q Virtual LAN'],
  ['isl', 'Cisco ISL Virtual LAN'],
  ['native', 'Make this as native vlan'],
  ['inside', 'Inside address translation'],
  ['outside', 'Outside address translation'],
  ['translation', 'NAT translation entry configuration'],
  ['log', 'NAT logging options'],
  ['ping', 'Specify ping parameters for DHCP server'],
  ['relay', 'DHCP relay agent parameters'],
  ['use', 'Configure DHCP server to use external data'],
  ['level', 'Set exec level password'],
  ['area', 'Set the OSPF area ID'],
  ['eq', 'Match only packets on a given port number'],
  ['boot', 'Boot Commands'],
  ['clock', 'Configure time-of-day clock'],
  ['member', 'Configure a VNI member'],
  ['monitor', 'Monitoring different system events'],
  ['port-channel', 'EtherChannel/PortChannel configuration'],
  ['switchport', 'Set switching mode characteristics'],
  ['tunnel', 'Protocol-over-protocol tunneling'],
  ['udld', 'Configure UDLD protocol'],
  ['zone-member', 'Apply zone'],
  ['permit', 'Specify packets to forward'],
  ['deny', 'Specify packets to reject'],
  ['remark', 'Access list entry comment'],
  ['access', 'Set access mode characteristics'],
  ['access-lists', 'Access lists'],
  ['arp', 'Address Resolution Protocol'],
  ['as-path', 'BGP autonomous-system path filter'],
  ['bfd', 'Bidirectional Forwarding Detection'],
  ['bgp', 'Border Gateway Protocol'],
  ['bootp', 'Bootstrap Protocol'],
  ['cache', 'Cache entries'],
  ['cdp', 'Cisco Discovery Protocol'],
  ['cef', 'Cisco Express Forwarding'],
  ['community-list', 'BGP community list'],
  ['cpu-defend', 'CPU defend policy configuration'],
  ['crypto', 'Encryption and key management'],
  ['dhcp', 'Dynamic Host Configuration Protocol'],
  ['dhcp-server', 'DHCP server configuration'],
  ['dhcp-snooping', 'DHCP snooping configuration'],
  ['dhcpv6', 'DHCPv6 configuration'],
  ['dns', 'Domain Name System'],
  ['domain', 'IP domain configuration'],
  ['dot1x', 'IEEE 802.1X port-based authentication'],
  ['eigrp', 'Enhanced Interior Gateway Routing Protocol'],
  ['firewall', 'Firewall configuration'],
  ['flow', 'NetFlow'],
  ['gdoi', 'Group Domain of Interpretation'],
  ['glbp', 'Gateway Load Balancing Protocol'],
  ['hsrp', 'Hot Standby Router Protocol'],
  ['http', 'Hypertext Transfer Protocol'],
  ['icmp', 'Internet Control Message Protocol'],
  ['idprom', 'Display IDPROM contents'],
  ['igmp', 'Internet Group Management Protocol'],
  ['ike', 'Internet Key Exchange'],
  ['ikev2', 'Internet Key Exchange version 2'],
  ['interface', 'Interface configuration'],
  ['ip', 'Internet Protocol'],
  ['ipsec', 'IP Security'],
  ['ipv6', 'Internet Protocol version 6'],
  ['isakmp', 'Internet Security Association and Key Management Protocol'],
  ['isis', 'Intermediate System to Intermediate System'],
  ['key', 'Key management'],
  ['lacp', 'Link Aggregation Control Protocol'],
  ['lldp', 'Link Layer Discovery Protocol'],
  ['local', 'Local settings'],
  ['mac', 'MAC configuration'],
  ['mls', 'Multilayer switching'],
  ['mode', 'Set trunking mode of the interface'],
  ['multicast', 'IP multicast'],
  ['nat', 'Network Address Translation'],
  ['nbar', 'Network-Based Application Recognition'],
  ['netflow', 'NetFlow statistics'],
  ['nhrp', 'Next Hop Resolution Protocol'],
  ['no', 'Negate a command or set its defaults'],
  ['nqa', 'Network Quality Analysis'],
  ['ntp', 'Network Time Protocol'],
  ['nve', 'Network Virtualization Endpoint'],
  ['ospf', 'Open Shortest Path First'],
  ['ospfv3', 'OSPF version 3 (IPv6)'],
  ['parameter-map', 'Display parameter-map'],
  ['pim', 'Protocol Independent Multicast'],
  ['pki', 'Public Key Infrastructure'],
  ['policy', 'Policy configuration'],
  ['priority', 'Set appliance 802.1p priority'],
  ['private-vlan', 'Configure private VLAN'],
  ['proxy-arp', 'Proxy ARP'],
  ['qos', 'Quality of Service'],
  ['queueing', 'Display queueing configuration'],
  ['radius', 'RADIUS authentication'],
  ['rip', 'Routing Information Protocol'],
  ['route', 'Route information'],
  ['router', 'Router configuration information'],
  ['rsa', 'RSA key pair'],
  ['sla', 'Service Level Agreement'],
  ['snmp', 'Simple Network Management Protocol'],
  ['ssh', 'Secure Shell'],
  ['static', 'Static entries'],
  ['stelnet', 'Secure Telnet (SSH-based)'],
  ['stp', 'Spanning Tree Protocol'],
  ['summary-address', 'Summary address entries'],
  ['tacacs', 'TACACS+ authentication'],
  ['tcp', 'Transmission Control Protocol'],
  ['telnet', 'Telnet protocol'],
  ['temperature', 'Display device temperature'],
  ['time-range', 'Time range configuration'],
  ['traffic', 'Display traffic statistics'],
  ['traffic-filter', 'Traffic filter configuration'],
  ['traffic-policy', 'Traffic policy configuration'],
  ['trunk', 'Set trunking characteristics'],
  ['udp', 'User Datagram Protocol'],
  ['vlan', 'VLAN configuration'],
  ['vrf', 'VPN Routing/Forwarding'],
  ['vrrp', 'Virtual Router Redundancy Protocol'],
  ['vtp', 'VLAN Trunking Protocol'],
  ['vxlan', 'Virtual Extensible LAN'],
  ['zone', 'Display security zone'],
  ['zone-pair', 'Display security zone-pair'],
]);

/**
 * Best-effort description for a keyword whose registration left only the
 * keyword-as-description placeholder. Returns an empty string when the
 * keyword is unknown — the help renderer then shows a blank description,
 * which is still better than echoing the keyword twice.
 */
export function descriptionForKeyword(keyword: string): string {
  return KEYWORD_DESCRIPTIONS.get(keyword.toLowerCase()) ?? '';
}
