/**
 * Default `?` help descriptions for CLI keywords that appear as
 * intermediate trie nodes (e.g. the `dhcp` in `show ip dhcp binding`).
 *
 * When a command path is registered, intermediate nodes are created with a
 * placeholder description equal to their own keyword. Rendering that
 * placeholder verbatim produced "dhcp   dhcp" style help lines — unlike
 * IOS/VRP, which always describe every keyword. This dictionary supplies
 * vendor-neutral descriptions for the common protocol/feature keywords;
 * `descriptionForKeyword` is the single lookup used by the help renderer.
 */

const KEYWORD_DESCRIPTIONS: ReadonlyMap<string, string> = new Map<string, string>([
  ['access-group', 'Specify access control for packets'],
  ['access-list', 'Add an access list entry'],
  ['accounting', 'Accounting configuration'],
  ['activate', 'Enable the address family for this neighbor'],
  ['active', 'Active state'],
  ['address-family', 'Enter address family configuration'],
  ['address-table', 'MAC forwarding table'],
  ['advertise', 'Advertisement configuration'],
  ['age-timer', 'Aging timer'],
  ['aggressive', 'Aggressive mode'],
  ['aggressive-mode', 'IKE aggressive mode'],
  ['aging', 'Set the aging time'],
  ['all', 'All entries'],
  ['all-interfaces', 'Apply to all interfaces'],
  ['allowed', 'Set allowed VLAN characteristics'],
  ['ascii', 'ASCII text'],
  ['association', 'Association configuration'],
  ['attempts', 'Number of attempts'],
  ['authenticate', 'Authentication configuration'],
  ['authentication', 'Authentication configuration'],
  ['authentication-key', 'Authentication key'],
  ['authentication-retries', 'Number of authentication retries'],
  ['authenticator', 'IEEE 802.1X authenticator'],
  ['authorization', 'Authorization configuration'],
  ['auto', 'Automatic mode'],
  ['autocommand', 'Command to execute on login'],
  ['aux', 'Auxiliary line'],
  ['backbonefast', 'Enable BackboneFast convergence'],
  ['bandwidth-percent', 'Percentage of interface bandwidth'],
  ['banner', 'Define a login banner'],
  ['block-for', 'Block logins for a period'],
  ['bpdufilter', 'Do not send or receive BPDUs'],
  ['bpduguard', 'Error-disable the port on BPDU reception'],
  ['brief', 'Brief summary'],
  ['cause', 'Reason'],
  ['client', 'Client configuration'],
  ['community', 'SNMP community string'],
  ['config', 'Configuration'],
  ['connected', 'Connected routes'],
  ['console', 'Primary terminal line'],
  ['count', 'Number of packets'],
  ['counters', 'Interface counters'],
  ['decrement', 'Value to decrement the priority by'],
  ['default', 'Set to the default value'],
  ['default-cost', 'Cost of the default summary route'],
  ['default-information', 'Control distribution of default information'],
  ['description', 'Description text'],
  ['destination', 'Destination'],
  ['detail', 'Detailed output'],
  ['expanded', 'Expanded community list, matched by regular expression'],
  ['dh', 'Diffie-Hellman group'],
  ['disable', 'Disable the feature'],
  ['dynamic', 'Dynamically learnt'],
  ['echo', 'Echo'],
  ['enable', 'Enable the feature'],
  ['engine', 'SNMP engine'],
  ['eui-64', 'Use an EUI-64 interface identifier'],
  ['follow', 'Name of the HSRP group to follow'],
  ['forwarder', 'GLBP forwarder configuration'],
  ['link-local', 'Configure an IPv6 link-local address'],
  ['events', 'Events'],
  ['exec', 'EXEC process'],
  ['extend', 'Extended form'],
  ['extended', 'Extended access list'],
  ['external', 'External routes'],
  ['fast', 'Fast mode'],
  ['filter-list', 'Filter prefixes'],
  ['forward-protocol', 'Protocols to forward'],
  ['forward-time', 'Spanning tree forward delay'],
  ['full', 'Force full duplex operation'],
  ['generate', 'Generate'],
  ['grace-period', 'Grace period'],
  ['group', 'Group number'],
  ['guard', 'Guard mode'],
  ['half', 'Force half-duplex operation'],
  ['hello-interval', 'Hello interval in seconds'],
  ['hello-time', 'Spanning tree hello interval'],
  ['hex', 'Hexadecimal'],
  ['hold-time', 'Hold time in seconds'],
  ['holdtime', 'Hold time'],
  ['host', 'A single host address'],
  ['host-dependent', 'Host-dependent load balancing'],
  ['in', 'Inbound direction'],
  ['inactive', 'Inactive'],
  ['incoming', 'Incoming'],
  ['input', 'Input direction'],
  ['inspect', 'Inspection'],
  ['inspection', 'Dynamic ARP inspection'],
  ['inter-area', 'Inter-area routes'],
  ['interface-dlci', 'Frame Relay DLCI'],
  ['intra-area', 'Intra-area routes'],
  ['inverse-arp', 'Frame Relay Inverse ARP'],
  ['ipsec-isakmp', 'IPSec with ISAKMP negotiation'],
  ['ipv4-unicast', 'IPv4 unicast address family'],
  ['isolated', 'Isolated private VLAN'],
  ['key-chain', 'Key chain name'],
  ['lmi-type', 'Frame Relay LMI type'],
  ['load-balancing', 'Load balancing method'],
  ['local-preference', 'BGP local preference'],
  ['logging', 'Logging configuration'],
  ['login', 'Login configuration'],
  ['long', 'Long form'],
  ['loop', 'Loop'],
  ['loopguard', 'Enable loop guard'],
  ['lsa', 'Link State Advertisement'],
  ['mac-address', 'Virtual MAC address'],
  ['manager', 'Manager'],
  ['map', 'Map'],
  ['master', 'Master'],
  ['match-all', 'Match all criteria'],
  ['match-any', 'Match any criterion'],
  ['max-age', 'Spanning tree maximum age'],
  ['max-fail', 'Maximum number of failures'],
  ['max-metric', 'Advertise the maximum metric'],
  ['maximum-hops', 'Maximum hop count'],
  ['mcast-group', 'Multicast group'],
  ['md5', 'MD5 authentication'],
  ['message', 'Message text'],
  ['message-digest', 'MD5 authentication'],
  ['method', 'Method'],
  ['metric-type', 'External metric type'],
  ['min', 'Minimum'],
  ['min-mtu', 'Minimum MTU'],
  ['motd', 'Message of the day banner'],
  ['mpls', 'Multiprotocol Label Switching'],
  ['multiplier', 'Multiplier'],
  ['name', 'Name'],
  ['nd', 'IPv6 neighbor discovery'],
  // Noeud intermediaire de `ipv6 nd ra {suppress|lifetime|interval|…}` :
  // ses enfants portaient une description, lui non, donc `?` le
  // proposait nu. (Defaut pre-existant, attrape par le garde-fou
  // `cisco-help-every-keyword-described`.)
  ['ra', 'Router advertisement configuration'],
  ['network-id', 'Network identifier'],
  ['new-model', 'Enable the new AAA model'],
  ['nhs', 'Next Hop Server'],
  ['no-summary', 'Do not send summary LSAs into the area'],
  ['none', 'No authentication'],
  ['nopassword', 'No password required'],
  ['normal', 'Normal mode'],
  ['nssa', 'Not-So-Stubby Area'],
  ['nssa-only', 'Limit the route to the NSSA area'],
  ['off', 'Disable'],
  ['on-failure', 'On authentication failure'],
  ['on-startup', 'At system startup'],
  ['on-success', 'On successful authentication'],
  ['opaque', 'Opaque LSA'],
  ['out', 'Outbound direction'],
  ['output', 'Output direction'],
  ['pacing', 'Pacing'],
  ['packet', 'Packet'],
  ['pae', 'Port Access Entity'],
  ['password', 'Password'],
  ['passwords', 'Passwords'],
  ['pathcost', 'Path cost method'],
  ['peer', 'Peer'],
  ['peer-group', 'BGP peer group'],
  ['peer-ip', 'Peer IP address'],
  ['poll-interval', 'Polling interval'],
  ['port', 'Port number'],
  ['portfast', 'Enable PortFast'],
  ['preempt', 'Preempt the active router'],
  ['prefer', 'Preferred server'],
  ['primary', 'Primary'],
  ['privilege', 'Privilege level'],
  ['protection', 'Protection'],
  ['pruning', 'VTP pruning'],
  ['quiet-mode', 'Quiet mode'],
  ['quiet-period', 'Quiet period'],
  ['range', 'Range of values'],
  ['rapid-pvst', 'Rapid per-VLAN spanning tree'],
  ['rate-limit', 'Rate limit'],
  ['receive', 'Receive'],
  ['recovery', 'Error-disable recovery'],
  ['resequence', 'Resequence access list entries'],
  ['recurring', 'Recurring time range'],
  ['redirect', 'Redirect'],
  ['reference-bandwidth', 'Reference bandwidth for cost calculation'],
  ['remote-as', 'Autonomous system of the neighbour'],
  ['rfc1583', 'Use RFC 1583 compatible route selection'],
  ['root', 'Root bridge'],
  ['round-robin', 'Round-robin load balancing'],
  ['route-cache', 'Route cache'],
  ['router-id', 'Router identifier'],
  ['routing', 'Routing'],
  ['secondary', 'Secondary address'],
  ['secret', 'Encrypted secret'],
  ['security-association', 'IPSec security association'],
  ['send', 'Send'],
  ['server', 'Server'],
  ['session-id', 'Session identifier'],
  ['sham-link', 'OSPF sham link'],
  ['short', 'Short form'],
  ['shortcut', 'Shortcut'],
  ['size', 'Size'],
  ['snooping', 'DHCP snooping'],
  ['source', 'Source'],
  ['source-interface', 'Source interface for packets'],
  ['split-horizon', 'Split horizon'],
  ['standard', 'Standard access list'],
  ['expanded', 'Add an expanded community-list entry'],
  ['packets', 'NTP packets'],
  ['statistics', 'Statistics'],
  ['stats', 'Statistics'],
  ['status', 'Status'],
  ['stub', 'Stub area'],
  ['summary', 'Summary'],
  ['synchronous', 'Synchronous logging'],
  ['template', 'Template'],
  ['text', 'Clear text'],
  ['throttle', 'Throttle timers'],
  ['time', 'Time'],
  ['time-out', 'Timeout interval'],
  ['timeout', 'Timeout interval'],
  ['timers', 'Protocol timers'],
  ['track', 'Track an object'],
  ['transit', 'Transit area'],
  ['transparent', 'Transparent mode'],
  ['trust', 'Trust state'],
  ['trusted-key', 'Trusted authentication key'],
  ['type', 'Type'],
  ['up', 'Up state'],
  ['update-source', 'Source of routing updates'],
  ['uplinkfast', 'Enable UplinkFast'],
  ['verify', 'Verify'],
  ['version', 'Protocol version'],
  ['virtual-link', 'OSPF virtual link'],
  ['voice', 'Voice VLAN'],
  ['vty', 'Virtual terminal'],
  ['weight', 'BGP weight'],
  ['weighted', 'Weighted'],
  ['weighting', 'GLBP weighting configuration'],
  ['weights', 'Metric weights'],
  ['within', 'Within'],
  ['zeroize', 'Delete the key pair'],
  ['aaa', 'Authentication, Authorization and Accounting'],
  ['cost', 'Change an interface path cost'],
  ['port-priority', 'Change an interface priority'],
  ['address', 'Specify an address'],
  ['arp-proxy', 'ARP proxy configuration'],
  ['compare', 'Compare function'],
  ['debugging', 'Enable system debugging functions'],
  ['display', 'Display current system information'],
  ['dsa', 'DSA key pair configuration'],
  ['gre', 'Generic Routing Encapsulation'],
  ['jumboframe', 'Set the jumbo frame size'],
  ['keepalive', 'Set the keepalive interval'],
  ['loopback', 'Set the loopback mode'],
  ['protocol', 'Specify a protocol'],
  ['reset', 'Reset operation'],
  ['set', 'Set system information'],
  ['sflow', 'sFlow configuration'],
  ['startup', 'Startup configuration'],
  ['terminal', 'Set the terminal line characteristics'],
  ['user', 'User configuration'],
  ['voice-vlan', 'Voice VLAN configuration'],
  ['archive', 'Archive the configuration'],
  ['dot1q', 'IEEE 802.1Q Virtual LAN'],
  ['isl', 'Cisco ISL Virtual LAN'],
  ['native', 'Make this as native vlan'],
  ['inside', 'Inside address translation'],
  ['outside', 'Outside address translation'],
  ['translation', 'NAT translation entry configuration'],
  ['log', 'NAT logging options'],
  ['ping', 'Specify ping parameters for DHCP server'],
  ['relay', 'DHCP relay agent parameters'],
  ['use', 'Configure DHCP server to use external data'],
  ['level', 'Set exec level password'],
  ['area', 'Set the OSPF area ID'],
  ['eq', 'Match only packets on a given port number'],
  ['boot', 'Boot Commands'],
  ['clock', 'Configure time-of-day clock'],
  ['member', 'Configure a VNI member'],
  ['monitor', 'Monitoring different system events'],
  ['port-channel', 'EtherChannel/PortChannel configuration'],
  ['switchport', 'Set switching mode characteristics'],
  ['tunnel', 'Protocol-over-protocol tunneling'],
  ['udld', 'Configure UDLD protocol'],
  ['zone-member', 'Apply zone'],
  ['permit', 'Specify packets to forward'],
  ['deny', 'Specify packets to reject'],
  ['remark', 'Access list entry comment'],
  ['access', 'Set access mode characteristics'],
  ['access-lists', 'Access lists'],
  ['arp', 'Address Resolution Protocol'],
  ['as-path', 'BGP autonomous-system path filter'],
  ['bfd', 'Bidirectional Forwarding Detection'],
  ['bgp', 'Border Gateway Protocol'],
  ['bootp', 'Bootstrap Protocol'],
  ['cache', 'Cache entries'],
  ['cdp', 'Cisco Discovery Protocol'],
  ['cef', 'Cisco Express Forwarding'],
  ['community-list', 'BGP community list'],
  ['cpu-defend', 'CPU defend policy configuration'],
  ['crypto', 'Encryption and key management'],
  ['dhcp', 'Dynamic Host Configuration Protocol'],
  ['dhcp-server', 'DHCP server configuration'],
  ['dhcp-snooping', 'DHCP snooping configuration'],
  ['dhcpv6', 'DHCPv6 configuration'],
  ['dns', 'Domain Name System'],
  ['domain', 'IP domain configuration'],
  ['dot1x', 'IEEE 802.1X port-based authentication'],
  ['eigrp', 'Enhanced Interior Gateway Routing Protocol'],
  ['firewall', 'Firewall configuration'],
  ['flow', 'NetFlow'],
  ['gdoi', 'Group Domain of Interpretation'],
  ['glbp', 'Gateway Load Balancing Protocol'],
  ['hsrp', 'Hot Standby Router Protocol'],
  ['http', 'Hypertext Transfer Protocol'],
  ['icmp', 'Internet Control Message Protocol'],
  ['idprom', 'Display IDPROM contents'],
  ['igmp', 'Internet Group Management Protocol'],
  ['ike', 'Internet Key Exchange'],
  ['ikev2', 'Internet Key Exchange version 2'],
  ['interface', 'Interface configuration'],
  ['ip', 'Internet Protocol'],
  ['ipsec', 'IP Security'],
  ['ipv6', 'Internet Protocol version 6'],
  ['isakmp', 'Internet Security Association and Key Management Protocol'],
  ['isis', 'Intermediate System to Intermediate System'],
  ['key', 'Key management'],
  ['lacp', 'Link Aggregation Control Protocol'],
  ['lldp', 'Link Layer Discovery Protocol'],
  ['local', 'Local settings'],
  ['mac', 'MAC configuration'],
  ['mls', 'Multilayer switching'],
  ['mode', 'Set trunking mode of the interface'],
  ['multicast', 'IP multicast'],
  ['nat', 'Network Address Translation'],
  ['nbar', 'Network-Based Application Recognition'],
  ['netflow', 'NetFlow statistics'],
  ['nhrp', 'Next Hop Resolution Protocol'],
  ['no', 'Negate a command or set its defaults'],
  ['nqa', 'Network Quality Analysis'],
  ['ntp', 'Network Time Protocol'],
  ['nve', 'Network Virtualization Endpoint'],
  ['ospf', 'Open Shortest Path First'],
  ['ospfv3', 'OSPF version 3 (IPv6)'],
  ['parameter-map', 'Display parameter-map'],
  ['pim', 'Protocol Independent Multicast'],
  ['pki', 'Public Key Infrastructure'],
  ['policy', 'Policy configuration'],
  ['priority', 'Set appliance 802.1p priority'],
  ['private-vlan', 'Configure private VLAN'],
  ['proxy-arp', 'Proxy ARP'],
  ['qos', 'Quality of Service'],
  ['queueing', 'Display queueing configuration'],
  ['radius', 'RADIUS authentication'],
  ['rip', 'Routing Information Protocol'],
  ['route', 'Route information'],
  ['router', 'Router configuration information'],
  ['rsa', 'RSA key pair'],
  ['sla', 'Service Level Agreement'],
  ['snmp', 'Simple Network Management Protocol'],
  ['ssh', 'Secure Shell'],
  ['static', 'Static entries'],
  ['stelnet', 'Secure Telnet (SSH-based)'],
  ['stp', 'Spanning Tree Protocol'],
  ['summary-address', 'Summary address entries'],
  ['tacacs', 'TACACS+ authentication'],
  ['tcp', 'Transmission Control Protocol'],
  ['telnet', 'Telnet protocol'],
  ['temperature', 'Display device temperature'],
  ['time-range', 'Time range configuration'],
  ['traffic', 'Display traffic statistics'],
  ['traffic-filter', 'Traffic filter configuration'],
  ['traffic-policy', 'Traffic policy configuration'],
  ['trunk', 'Set trunking characteristics'],
  ['udp', 'User Datagram Protocol'],
  ['vlan', 'VLAN configuration'],
  ['vrf', 'VPN Routing/Forwarding'],
  // Le pendant VRP de `vrf`. Extrait automatiquement du corps de `rip`
  // depuis que ce handler lit sa queue, il arrivait dans l'aide SANS
  // description — `rip ?` répondait « vpn-instance » et rien d'autre.
  // Le nommer vaut mieux que le taire : c'est un vrai mot-clé de VRP.
  ['vpn-instance', 'VPN instance'],
  ['vrrp', 'Virtual Router Redundancy Protocol'],
  ['vtp', 'VLAN Trunking Protocol'],
  ['vxlan', 'Virtual Extensible LAN'],
  ['zone', 'Display security zone'],
  ['zone-pair', 'Display security zone-pair'],
  ['acct-port', 'UDP port for RADIUS accounting server'],
  ['action-type', 'Action to take when a threshold is violated'],
  ['advertised-routes', 'Routes advertised to this neighbor'],
  ['after', 'Start after a delay'],
  ['ageout', 'How long to keep the entry when inactive'],
  ['aggregated', 'Aggregated statistics'],
  ['algorithm', 'Cryptographic algorithm list'],
  ['algorithm-type', 'Algorithm used to hash the password'],
  ['auth-port', 'UDP port for RADIUS authentication server'],
  ['average', 'Average of the collected samples'],
  ['bridge', 'Bridge information'],
  ['certificate', 'Certificate material'],
  ['configured', 'Configured entries'],
  ['consecutive', 'Consecutive violations'],
  ['database', 'Database contents'],
  ['details', 'Detailed information'],
  ['dst', 'Destination address'],
  ['encryption', 'Encryption algorithm list'],
  ['force-spf', 'Force a shortest path first recalculation'],
  ['forever', 'Run without a time limit'],
  ['groups', 'Group membership information'],
  ['hostname', 'Identify the peer by hostname'],
  ['immediate', 'Act immediately'],
  ['immediate-leave', 'Leave the group without a last-member query'],
  ['ipv4', 'IPv4 configuration'],
  ['kex', 'Key exchange algorithm list'],
  ['life', 'How long the operation runs'],
  ['mrouter', 'Multicast router ports'],
  ['neighbor', 'Neighbor information'],
  ['never', 'Never act'],
  ['now', 'Start immediately'],
  ['on-demand', 'On-demand keepalives'],
  ['pem', 'Privacy Enhanced Mail formatted material'],
  ['pending', 'Leave the operation pending'],
  ['process', 'Routing process'],
  ['proto', 'Protocol number'],
  ['querier', 'Querier configuration'],
  ['react', 'Condition to react upon'],
  ['redistribution', 'Redistributed route information'],
  ['remote', 'Remote peer'],
  ['retransmit', 'Number of retransmissions'],
  ['routes', 'Routes learned from this neighbor'],
  ['scrypt', 'Use the scrypt hashing algorithm'],
  ['seq', 'Sequence number of an entry'],
  ['sha256', 'Use the SHA-256 hashing algorithm'],
  ['src', 'Source address'],
  ['start-time', 'When the operation starts'],
  ['sticky', 'Sticky learned addresses'],
  ['tcp-connect', 'TCP connect operation'],
  ['threshold-type', 'How the threshold is evaluated'],
  ['threshold-value', 'Rising and falling threshold values'],
  ['udp-echo', 'UDP echo operation'],
  ['username', 'Identify a user'],
  ['view', 'Command-line interface view'],
  ['ns', 'Name server for this host entry'],
  // Vingt-huit suites que l'extraction proposait sans savoir les
  // decrire, donc que `?` taisait pendant que `Tab` les completait.
  // Elles sont declarees depuis `ciscoContinuations`, et decrites ici,
  // donc enfin annoncees.
  ['absolute', 'Absolute aging time'],
  ['add', 'Add to the current list'],
  ['all-links', 'Show all links in the topology table'],
  ['any', 'Any source'],
  ['bootpc', 'Bootstrap Protocol client (68)'],
  ['bootps', 'Bootstrap Protocol server (67)'],
  ['delay', 'Delay before taking effect'],
  ['desirable', 'Actively negotiate a channel with PAgP'],
  ['dot1p', 'Tag traffic with 802.1p priority'],
  ['etherchannel', 'EtherChannel information'],
  ['except', 'All VLANs except the ones listed'],
  ['hmac-sha-256', 'HMAC-SHA-256 authentication'],
  ['inactivity', 'Aging based on inactivity time'],
  ['key-string', 'Authentication key'],
  ['minimum', 'Minimum value'],
  ['negotiate', 'Negotiate the trunk encapsulation'],
  ['negotiated', 'Learn the address by IPCP negotiation'],
  ['on', 'Force the channel up with no negotiation'],
  ['passive', 'Wait for the peer to negotiate with LACP'],
  ['promiscuous', 'Promiscuous private-VLAN port'],
  ['protect', 'Drop offending frames silently'],
  ['reachable-via', 'Check the source against the routing table'],
  ['remove', 'Remove from the current list'],
  ['restrict', 'Drop offending frames and report'],
  ['reverse-path', 'Unicast reverse path forwarding check'],
  ['shared', 'Share the profile between tunnels'],
  ['shutdown', 'Shut the port down on violation'],
  ['untagged', 'Send untagged voice traffic'],
  ['xml', 'XML-formatted output'],
  ['infinite', 'Never expire'],
  ['exclude', 'Exclude the matching entries'],
  ['include-exclusive', 'Include only the exclusive entries'],
  ['body', 'Body of the message'],
  ['cli', 'Run a CLI command'],
  ['command', 'The command to run'],
  ['mail', 'Send an e-mail'],
  ['msg', 'Message text'],
  ['puts', 'Write to the applet output'],
  ['snmp-trap', 'Send an SNMP trap'],
  ['subject', 'Subject of the message'],
  ['syslog', 'Write a syslog message'],
  ['to', 'Destination'],
  ['wait', 'Wait before continuing'],
  ['pattern', 'Regular expression to match'],
  ['entry-val', 'Value that triggers the entry'],
  ['get-type', 'Kind of SNMP get to perform'],
  ['oid', 'SNMP object identifier'],
  ['countdown', 'Count down once from the interval'],
  ['cron-entry', 'Schedule in crontab format'],
  ['watchdog', 'Restart the timer after each firing'],
  ['regenerate', 'Generate a new key pair'],
  ['profile', 'Enrollment profile'],
  ['self-signed', 'Issue a self-signed certificate'],
  ['selfsigned', 'Issue a self-signed certificate'],
  ['url', 'Enrollment URL'],
  ['crl-or-ocsp', 'Check the CRL, or OCSP if it is unavailable'],
  ['crl-then-ocsp', 'Check the CRL, then OCSP'],
  ['ocsp', 'Online Certificate Status Protocol'],
  ['ipfix', 'IPFIX export format'],
  ['netflow-v5', 'NetFlow version 5 export format'],
  ['netflow-v9', 'NetFlow version 9 export format'],
  ['lifetime', 'Lifetime of the association'],
  ['mask', 'Address mask'],
  ['always', 'Unconditionally'],
  ['transport', 'Transport protocol'],
  ['down', 'Down state'],
  ['not', 'Negate the following condition'],
  ['drop', 'Drop the traffic'],
  ['forward', 'Forward the traffic'],
  ['instance', 'MST instance'],
  ['revision', 'Configuration revision number'],
  // VRP — trente-sept mots offerts par `?` et rendus NUS, releves par le
  // balayage des descriptions porte a Huawei.
  ['free', 'Release a user terminal interface'],
  ['kill', 'Terminate a user session'],
  ['check', 'Check the packet against the binding table'],
  ['trusted', 'Configure the interface as trusted'],
  ['hwtacacs-server', 'HWTACACS server information'],
  ['radius-server', 'RADIUS server information'],
  ['anti-attack', 'Attack-defence configuration'],
  ['configuration', 'Configuration information'],
  ['session', 'Session information'],
  ['binding', 'Address binding table'],
  ['user-bind', 'Binding table of the DHCP snooping users'],
  ['defend', 'Attack-defence statistics'],
  ['v2', 'IKE version 2'],
  ['history', 'Historical records'],
  ['car', 'Committed access rate'],
  ['cq', 'Custom queueing'],
  ['pq', 'Priority queueing'],
  ['queue', 'Queue information'],
  ['local-key-pair', 'Local host key pair'],
  ['host-unreachable', 'ICMP host-unreachable messages'],
  ['ttl-exceeded', 'ICMP TTL-exceeded messages'],
  ['sa', 'IPSec security association'],
  ['anti-replay', 'Anti-replay window'],
  ['esn', 'Extended sequence number'],
  ['global-duration', 'Global lifetime of the security association'],
  ['message-transmission', 'LLDP message transmission parameters'],
  ['routing-table', 'Routing table'],
  ['behavior', 'Traffic behavior'],
  ['classifier', 'Traffic classifier'],
]);

/**
 * Best-effort description for a keyword whose registration left only the
 * keyword-as-description placeholder. Returns an empty string when the
 * keyword is unknown — the help renderer then shows a blank description,
 * which is still better than echoing the keyword twice.
 */
export function descriptionForKeyword(keyword: string): string {
  return KEYWORD_DESCRIPTIONS.get(keyword.toLowerCase()) ?? '';
}
