/**
 * Le bocal à témoins de `curl` : `-b` pour en envoyer, `-c` pour en
 * garder.
 *
 * Ce fichier n'implémente PAS les témoins — `http/cookies/` le fait
 * déjà, et complètement : correspondance de domaine et de chemin,
 * `Secure`, `HttpOnly`, `SameSite`, `Max-Age`, `Expires`. C'était un
 * moteur sans porte, sans un seul appelant hors de son propre
 * répertoire, donc un code que rien n'avait jamais vérifié. Ce fichier
 * est la porte.
 *
 * Le format lu et écrit est celui de Netscape, parce que c'est celui
 * que `curl -c` écrit et que `curl -b` relit — les deux options doivent
 * pouvoir se parler, sinon `-c` produit un fichier que rien ne
 * consomme.
 */

import { CookieJar } from '../cookies/CookieJar';
import type { Cookie } from '../cookies/SetCookie';

const ENTETE = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# This file was generated by libcurl! Edit at your own risk.',
  '',
].join('\n');

/** `#HttpOnly_` préfixe le domaine d'un témoin HttpOnly, comme chez curl. */
const MARQUE_HTTPONLY = '#HttpOnly_';

/**
 * `-b` accepte deux choses très différentes sous la même option, et
 * `curl` les distingue exactement ainsi : un argument contenant `=` est
 * une chaîne de témoins, tout le reste est un nom de fichier.
 */
export function cookieArgIsLiteral(arg: string): boolean {
  return arg.includes('=');
}

/**
 * Une ligne de fichier Netscape :
 * `domaine  sous-domaines  chemin  securise  expiration  nom  valeur`
 *
 * Les champs sont séparés par des TABULATIONS. Une ligne malformée est
 * ignorée plutôt que de faire échouer la lecture — c'est ce que fait
 * curl, et un fichier édité à la main ne doit pas rendre la commande
 * inutilisable.
 */
export function parseNetscapeCookies(texte: string, maintenant = Date.now()): Cookie[] {
  const out: Cookie[] = [];
  for (const ligne of texte.split('\n')) {
    const brute = ligne.replace(/\r$/, '');
    if (brute.trim() === '') continue;
    let reste = brute;
    let httpOnly = false;
    if (reste.startsWith(MARQUE_HTTPONLY)) {
      httpOnly = true;
      reste = reste.slice(MARQUE_HTTPONLY.length);
    } else if (reste.startsWith('#')) {
      continue;
    }
    const champs = reste.split('\t');
    if (champs.length < 7) continue;
    const [domaine, sousDomaines, chemin, securise, expiration, nom, ...valeur] = champs;
    const expire = Number(expiration);
    if (!Number.isFinite(expire)) continue;
    // `0` veut dire « témoin de session » : il n'expire pas, il meurt
    // avec le navigateur. Le confondre avec « expiré en 1970 » viderait
    // le bocal à chaque relecture.
    if (expire !== 0 && expire * 1000 <= maintenant) continue;
    out.push({
      name: nom,
      value: valeur.join('\t'),
      domain: domaine.replace(/^\./, ''),
      path: chemin === '' ? '/' : chemin,
      expires: expire === 0 ? undefined : expire * 1000,
      secure: securise.toUpperCase() === 'TRUE',
      httpOnly,
      sameSite: 'Lax',
      // Une entrée qui s'applique aux sous-domaines n'est PAS liée à
      // l'hôte : c'est le sens même de la deuxième colonne.
      hostOnly: sousDomaines.toUpperCase() !== 'TRUE',
    });
  }
  return out;
}

export function serializeNetscapeCookies(
  entrees: ReadonlyArray<{ cookie: Cookie; expiryMs: number | null }>,
): string {
  const lignes = [ENTETE];
  for (const { cookie: c, expiryMs } of entrees) {
    const domaine = c.hostOnly ? c.domain : `.${c.domain}`;
    const champs = [
      (c.httpOnly ? MARQUE_HTTPONLY : '') + domaine,
      c.hostOnly ? 'FALSE' : 'TRUE',
      c.path,
      c.secure ? 'TRUE' : 'FALSE',
      // L'échéance vient de `expiryMs` et non de `Cookie.expires` :
      // un témoin posé par `Max-Age` n'a pas de date dans `expires`, et
      // le sérialiser depuis là en ferait un témoin de session.
      expiryMs === null ? '0' : String(Math.floor(expiryMs / 1000)),
      c.name,
      c.value,
    ];
    lignes.push(champs.join('\t'));
  }
  return `${lignes.join('\n')}\n`;
}

/**
 * Le bocal de départ d'un transfert.
 *
 * `-b` littéral (`sid=abc; autre=1`) pose des témoins qui n'ont ni
 * domaine ni chemin : curl les envoie à qui l'opérateur vise, puisqu'il
 * les a écrits à la main pour cette requête-là. Ils sont donc marqués
 * du domaine visé plutôt que rejetés par la correspondance.
 */
export function jarFromArgument(
  arg: string | null,
  hote: string,
  lire: (chemin: string) => string | null,
  maintenant = Date.now(),
): CookieJar {
  const jar = new CookieJar();
  if (arg === null) return jar;
  if (cookieArgIsLiteral(arg)) {
    for (const morceau of arg.split(';')) {
      const t = morceau.trim();
      if (t === '') continue;
      if (t.indexOf('=') <= 0) continue;
      jar.setFromHeader(`${t}; Path=/`, hote, '/', maintenant);
    }
    return jar;
  }
  const texte = lire(arg);
  // Un fichier absent n'est pas une erreur pour curl : il commence
  // simplement avec un bocal vide, ce qui est le cas normal du PREMIER
  // appel d'une séquence `-b jar -c jar`.
  if (texte === null) return jar;
  for (const c of parseNetscapeCookies(texte, maintenant)) jar.add(c);
  return jar;
}
