export interface CmdletHelpEntry {
  synopsis: string;
  description: string;
  syntax: string;
  examples?: string;
  parameters?: string;
}

export const CMDLET_HELP: Record<string, CmdletHelpEntry> = {
  'clear-host': {
    synopsis: 'Clears the display in the host program.',
    description: 'The Clear-Host cmdlet deletes the current text from the display, including commands and any output that might have accumulated.',
    syntax: 'Clear-Host [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Clear-Host\n    (Screen is cleared)',
    parameters: '-WhatIf, -Confirm, -Verbose',
  },
  'copy-item': {
    synopsis: 'Copies an item from one location to another.',
    description: 'The Copy-Item cmdlet copies an item from one location to another location in the same namespace.',
    syntax: 'Copy-Item [-Path] <String[]> [[-Destination] <String>] [-Recurse] [-Force] [-Filter <String>] [-Include <String[]>] [-Exclude <String[]>] [-LiteralPath <String[]>] [-PassThru] [-Container] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Copy-Item C:\\source.txt C:\\dest.txt',
    parameters: '-Path, -Destination, -Recurse, -Force, -Filter, -Include, -Exclude, -LiteralPath, -PassThru, -Container',
  },
  'get-childitem': {
    synopsis: 'Gets the items and child items in one or more specified locations.',
    description: 'The Get-ChildItem cmdlet gets the items in one or more specified locations. If the item is a container, it gets the items inside the container.',
    syntax: 'Get-ChildItem [[-Path] <String[]>] [-Filter <String>] [-Include <String[]>] [-Exclude <String[]>] [-Recurse] [-Depth <UInt32>] [-Name] [-Directory] [-File] [-Hidden] [-System] [-Force] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-ChildItem C:\\',
    parameters: '-Path, -Filter, -Include, -Exclude, -Recurse, -Depth, -Name, -Directory, -File, -Hidden, -System, -Force',
  },
  'get-command': {
    synopsis: 'Gets all commands.',
    description: 'The Get-Command cmdlet gets all commands that are installed on the computer.',
    syntax: 'Get-Command [[-Name] <String[]>] [-CommandType <CommandTypes>] [-Module <String[]>] [-Noun <String>] [-Verb <String>] [-All] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Command\n    (Lists all available commands)',
    parameters: '-Name, -CommandType, -Module, -Noun, -Verb, -All',
  },
  'get-content': {
    synopsis: 'Gets the content of the item at the specified location.',
    description: 'The Get-Content cmdlet gets the content of the item at the location specified by the path.',
    syntax: 'Get-Content [-Path] <String[]> [-TotalCount <Int64>] [-Tail <Int32>] [-Raw] [-AsByteStream] [-Stream <String>] [-Wait] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Content C:\\file.txt',
    parameters: '-Path, -LiteralPath, -TotalCount, -Tail, -Raw, -AsByteStream, -Stream, -Wait, -First, -Last',
  },
  'get-help': {
    synopsis: 'Displays information about Windows PowerShell commands and concepts.',
    description: 'The Get-Help cmdlet displays information about PowerShell concepts and commands.',
    syntax: 'Get-Help [[-Name] <String>] [-Full] [-Detailed] [-Examples] [-Online] [-Parameter <String>] [-Category <String>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Help Get-Process',
    parameters: '-Name, -Full, -Detailed, -Examples, -Online, -Parameter, -Category, -Component, -Role, -Functionality',
  },
  'get-location': {
    synopsis: 'Gets information about the current working location or a location stack.',
    description: 'The Get-Location cmdlet gets an object that represents the current directory.',
    syntax: 'Get-Location [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Location\n    Path\n    ----\n    C:\\Users\\User',
    parameters: '-Stack, -StackName',
  },
  'get-netadapter': {
    synopsis: 'Gets the basic network adapter properties.',
    description: 'The Get-NetAdapter cmdlet gets the basic network adapter properties, including the name, interface description, interface index, and MAC address.',
    syntax: 'Get-NetAdapter [[-Name] <String[]>] [-Physical] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-NetAdapter',
    parameters: '-Name, -Physical, -IncludeHidden, -All',
  },
  'get-netipaddress': {
    synopsis: 'Gets the IP address configuration.',
    description: 'The Get-NetIPAddress cmdlet gets the IP address configuration for the specified interface.',
    syntax: 'Get-NetIPAddress [[-IPAddress] <String[]>] [-InterfaceAlias <String[]>] [-AddressFamily <AddressFamily>] [-PrefixLength <Byte>] [-AddressState <AddressState>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-NetIPAddress\n    (Lists all IP addresses)',
    parameters: '-IPAddress, -InterfaceAlias, -InterfaceIndex, -AddressFamily, -PrefixLength, -AddressState, -PrefixOrigin, -SuffixOrigin',
  },
  'new-netipaddress': {
    synopsis: 'Creates and configures an IP address.',
    description: 'The New-NetIPAddress cmdlet creates and configures an IP address and related settings.',
    syntax: 'New-NetIPAddress [-IPAddress] <String> -InterfaceAlias <String> -PrefixLength <Byte> [-DefaultGateway <String>] [-AddressFamily <AddressFamily>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress 192.168.1.10 -PrefixLength 24',
    parameters: '-IPAddress, -InterfaceAlias, -InterfaceIndex, -PrefixLength, -DefaultGateway, -AddressFamily, -SkipAsSource',
  },
  'remove-netipaddress': {
    synopsis: 'Removes an IP address and its configuration.',
    description: 'The Remove-NetIPAddress cmdlet removes an IP address and its related settings.',
    syntax: 'Remove-NetIPAddress [[-IPAddress] <String[]>] [-InterfaceAlias <String[]>] [-AddressFamily <AddressFamily>] [-Confirm:$false] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Remove-NetIPAddress -IPAddress 192.168.1.10 -Confirm:$false',
    parameters: '-IPAddress, -InterfaceAlias, -AddressFamily, -Confirm',
  },
  'set-netipaddress': {
    synopsis: 'Modifies the configuration of an IP address.',
    description: 'The Set-NetIPAddress cmdlet modifies the configuration of an IP address.',
    syntax: 'Set-NetIPAddress [[-IPAddress] <String[]>] [-PrefixLength <Byte>] [-PrefixOrigin <PrefixOrigin>] [-SkipAsSource <Boolean>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Set-NetIPAddress -IPAddress 192.168.1.10 -PrefixLength 16',
    parameters: '-IPAddress, -PrefixLength, -PrefixOrigin, -SuffixOrigin, -SkipAsSource',
  },
  'get-netipconfiguration': {
    synopsis: 'Gets IP network configuration.',
    description: 'The Get-NetIPConfiguration cmdlet gets network configuration including adapter, IP address, and DNS server information.',
    syntax: 'Get-NetIPConfiguration [[-InterfaceAlias] <String>] [-All] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-NetIPConfiguration',
    parameters: '-InterfaceAlias, -InterfaceIndex, -All',
  },
  'get-netroute': {
    synopsis: 'Gets the IP route information from the IP routing table.',
    description: 'The Get-NetRoute cmdlet gets the IP route information from the IP routing table.',
    syntax: 'Get-NetRoute [[-DestinationPrefix] <String[]>] [-InterfaceAlias <String[]>] [-NextHop <String[]>] [-RouteMetric <UInt16>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-NetRoute\n    (Lists routing table)',
    parameters: '-DestinationPrefix, -InterfaceAlias, -NextHop, -RouteMetric, -AddressFamily',
  },
  'new-netroute': {
    synopsis: 'Creates a route in the IP routing table.',
    description: 'The New-NetRoute cmdlet creates a route in the IP routing table.',
    syntax: 'New-NetRoute -DestinationPrefix <String> -InterfaceAlias <String> [-NextHop <String>] [-RouteMetric <UInt16>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> New-NetRoute -DestinationPrefix "10.0.0.0/8" -InterfaceAlias "Ethernet" -NextHop 192.168.1.1',
    parameters: '-DestinationPrefix, -InterfaceAlias, -NextHop, -RouteMetric, -PolicyStore',
  },
  'remove-netroute': {
    synopsis: 'Removes IP routes from the IP routing table.',
    description: 'The Remove-NetRoute cmdlet removes IP routes from the IP routing table.',
    syntax: 'Remove-NetRoute [[-DestinationPrefix] <String[]>] [-InterfaceAlias <String[]>] [-NextHop <String[]>] [-Confirm:$false] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Remove-NetRoute -DestinationPrefix "10.0.0.0/8" -Confirm:$false',
    parameters: '-DestinationPrefix, -InterfaceAlias, -NextHop, -Confirm',
  },
  'get-dnsclientserveraddress': {
    synopsis: 'Gets the DNS server IP addresses from the TCP/IP properties on an interface.',
    description: 'The Get-DnsClientServerAddress cmdlet gets the DNS server IP addresses from the TCP/IP properties on an interface.',
    syntax: 'Get-DnsClientServerAddress [[-InterfaceAlias] <String[]>] [-AddressFamily <AddressFamily>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-DnsClientServerAddress -InterfaceAlias "Ethernet"',
    parameters: '-InterfaceAlias, -InterfaceIndex, -AddressFamily',
  },
  'set-dnsclientserveraddress': {
    synopsis: 'Sets the DNS server IP addresses for a network interface.',
    description: 'The Set-DnsClientServerAddress cmdlet sets one or more IP addresses for DNS servers associated with the specified interface.',
    syntax: 'Set-DnsClientServerAddress -InterfaceAlias <String> -ServerAddresses <String[]> [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses "8.8.8.8","8.8.4.4"',
    parameters: '-InterfaceAlias, -InterfaceIndex, -ServerAddresses, -ResetServerAddresses',
  },
  'get-process': {
    synopsis: 'Gets the processes that are running on the local computer.',
    description: 'The Get-Process cmdlet gets the processes that are running on the local computer.',
    syntax: 'Get-Process [[-Name] <String[]>] [-Id <Int32[]>] [-ComputerName <String[]>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Process\n    (Lists all processes)',
    parameters: '-Name, -Id, -ComputerName, -IncludeUserName, -Module, -FileVersionInfo',
  },
  'stop-process': {
    synopsis: 'Stops one or more running processes.',
    description: 'The Stop-Process cmdlet stops one or more running processes.',
    syntax: 'Stop-Process [-Id] <Int32[]> [-Force] [<CommonParameters>]\nStop-Process -Name <String[]> [-Force] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Stop-Process -Name "notepad"',
    parameters: '-Id, -Name, -Force, -PassThru, -WhatIf',
  },
  'get-service': {
    synopsis: 'Gets the services on a local or remote computer.',
    description: 'The Get-Service cmdlet gets objects that represent the services on a local computer.',
    syntax: 'Get-Service [[-Name] <String[]>] [-DisplayName <String[]>] [-DependentServices] [-RequiredServices] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Service\n    (Lists all services)',
    parameters: '-Name, -DisplayName, -Include, -Exclude, -DependentServices, -RequiredServices',
  },
  'move-item': {
    synopsis: 'Moves an item from one location to another.',
    description: 'The Move-Item cmdlet moves an item from one location to another.',
    syntax: 'Move-Item [-Path] <String[]> [[-Destination] <String>] [-Force] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Move-Item C:\\source.txt C:\\dest.txt',
    parameters: '-Path, -Destination, -Force, -Filter, -Include, -Exclude, -LiteralPath, -PassThru',
  },
  'new-item': {
    synopsis: 'Creates a new item.',
    description: 'The New-Item cmdlet creates a new item. The type of item that is created depends on the location.',
    syntax: 'New-Item [-Path] <String[]> [-ItemType <String>] [-Value <Object>] [-Force] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> New-Item -Path C:\\newdir -ItemType Directory',
    parameters: '-Path, -Name, -ItemType, -Value, -Force',
  },
  'remove-item': {
    synopsis: 'Deletes the specified items.',
    description: 'The Remove-Item cmdlet deletes one or more items.',
    syntax: 'Remove-Item [-Path] <String[]> [-Recurse] [-Force] [-Filter <String>] [-Include <String[]>] [-Exclude <String[]>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Remove-Item C:\\oldfile.txt',
    parameters: '-Path, -Recurse, -Force, -Filter, -Include, -Exclude, -WhatIf',
  },
  'rename-item': {
    synopsis: 'Renames an item in a PowerShell provider namespace.',
    description: 'The Rename-Item cmdlet changes the name of a specified item.',
    syntax: 'Rename-Item [-Path] <String> [-NewName] <String> [-Force] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Rename-Item -Path C:\\old.txt -NewName new.txt',
    parameters: '-Path, -LiteralPath, -NewName, -Force, -PassThru',
  },
  'set-content': {
    synopsis: 'Writes new content or replaces existing content in a file.',
    description: 'The Set-Content cmdlet is a string-processing cmdlet that writes new content or replaces existing content in a file.',
    syntax: 'Set-Content [-Path] <String[]> [-Value] <Object[]> [-Force] [-NoNewline] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Set-Content -Path C:\\file.txt -Value "Hello World"',
    parameters: '-Path, -LiteralPath, -Value, -Force, -NoNewline, -Encoding',
  },
  'set-location': {
    synopsis: 'Sets the current working location to a specified location.',
    description: 'The Set-Location cmdlet sets the working location to a specified location.',
    syntax: 'Set-Location [[-Path] <String>] [-LiteralPath <String>] [-PassThru] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Set-Location C:\\Windows',
    parameters: '-Path, -LiteralPath, -PassThru, -Stack, -StackName',
  },
  'test-connection': {
    synopsis: 'Sends ICMP echo request packets (pings) to one or more computers.',
    description: 'The Test-Connection cmdlet sends Internet Control Message Protocol (ICMP) echo request packets to one or more remote computers.',
    syntax: 'Test-Connection [-ComputerName] <String[]> [-Count <Int32>] [-Delay <Int32>] [-Quiet] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Test-Connection -ComputerName 8.8.8.8',
    parameters: '-ComputerName, -Count, -Delay, -BufferSize, -Quiet, -TTL, -DontFragment',
  },
  'write-host': {
    synopsis: 'Writes customized output to a host.',
    description: 'The Write-Host cmdlet writes output to the host. It bypasses the output stream.',
    syntax: 'Write-Host [[-Object] <Object>] [-NoNewline] [-Separator <Object>] [-ForegroundColor <ConsoleColor>] [-BackgroundColor <ConsoleColor>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Write-Host "Hello World" -ForegroundColor Green',
    parameters: '-Object, -NoNewline, -Separator, -ForegroundColor, -BackgroundColor',
  },
  'write-output': {
    synopsis: 'Sends the specified objects to the next command in the pipeline.',
    description: 'The Write-Output cmdlet sends the specified objects to the next command in the pipeline.',
    syntax: 'Write-Output [-InputObject] <PSObject[]> [-NoEnumerate] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Write-Output "Hello"',
    parameters: '-InputObject, -NoEnumerate',
  },
  'get-disk': {
    synopsis: 'Gets one or more disks visible to the operating system.',
    description: 'The Get-Disk cmdlet gets one or more disks visible to the operating system.',
    syntax: 'Get-Disk [[-Number] <UInt32[]>] [-FriendlyName <String[]>] [-SerialNumber <String[]>] [-UniqueId <String[]>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Disk\n    (Lists all disks)',
    parameters: '-Number, -FriendlyName, -SerialNumber, -UniqueId',
  },
  'get-volume': {
    synopsis: 'Gets the specified Volume object, or all Volume objects if no filter is specified.',
    description: 'The Get-Volume cmdlet returns a list of all available volumes.',
    syntax: 'Get-Volume [[-DriveLetter] <Char[]>] [-FriendlyName <String[]>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-Volume\n    (Lists all volumes)',
    parameters: '-DriveLetter, -FriendlyName, -FileSystemLabel',
  },
  'get-localuser': {
    synopsis: 'Gets local user accounts.',
    description: 'The Get-LocalUser cmdlet gets local user accounts.',
    syntax: 'Get-LocalUser [[-Name] <String[]>] [-SID <SecurityIdentifier[]>] [<CommonParameters>]',
    examples: 'EXAMPLE 1\n    PS> Get-LocalUser\n    (Lists all local users)',
    parameters: '-Name, -SID',
  },
};

export function helpFor(name: string): CmdletHelpEntry | undefined {
  return CMDLET_HELP[name.toLowerCase().replace(/^["']|["']$/g, '')];
}
