import { Interpreter } from '@/command-kernel/interpreter';
import { registerCoreCommands } from '@/command-kernel/register-core-commands';
import { CommandRegistry } from '@/command-kernel/registry/command-registry';
import { CatCommand } from './commands/Cat';
import { CdCommand } from './commands/Cd';
import { ChmodCommand } from './commands/Chmod';
import { ChownCommand } from './commands/Chown';
import { CpCommand } from './commands/Cp';
import { CutCommand } from './commands/Cut';
import { GrepCommand } from './commands/Grep';
import { GroupsCommand } from './commands/Groups';
import { HeadCommand } from './commands/Head';
import { IdCommand } from './commands/Id';
import { LnCommand } from './commands/Ln';
import { LsCommand } from './commands/Ls';
import { MkdirCommand } from './commands/Mkdir';
import { MvCommand } from './commands/Mv';
import { PwdCommand } from './commands/Pwd';
import { RmCommand } from './commands/Rm';
import { SortCommand } from './commands/Sort';
import { StatCommand } from './commands/Stat';
import { TailCommand } from './commands/Tail';
import { TouchCommand } from './commands/Touch';
import { TrCommand } from './commands/Tr';
import { UniqCommand } from './commands/Uniq';
import { WcCommand } from './commands/Wc';
import { WhoamiCommand } from './commands/Whoami';
import { LinuxMachineApi, LinuxMachineApiDeps } from './LinuxMachineApi';

export function createLinuxHostShell(deps: LinuxMachineApiDeps): Interpreter {
  const registry = new CommandRegistry();
  const machine = new LinuxMachineApi(deps);

  registerCoreCommands(registry);
  registry.register(() => new PwdCommand());
  registry.register(() => new CdCommand());
  registry.register(() => new LsCommand());
  registry.register(() => new CatCommand());
  registry.register(() => new MkdirCommand());
  registry.register(() => new TouchCommand());
  registry.register(() => new RmCommand());
  registry.register(() => new CpCommand());
  registry.register(() => new MvCommand());
  registry.register(() => new StatCommand());
  registry.register(() => new ChmodCommand());
  registry.register(() => new ChownCommand());
  registry.register(() => new GrepCommand());
  registry.register(() => new HeadCommand());
  registry.register(() => new TailCommand());
  registry.register(() => new WcCommand());
  registry.register(() => new SortCommand());
  registry.register(() => new CutCommand());
  registry.register(() => new UniqCommand());
  registry.register(() => new TrCommand());
  registry.register(() => new WhoamiCommand());
  registry.register(() => new GroupsCommand());
  registry.register(() => new IdCommand());
  registry.register(() => new LnCommand());

  return new Interpreter(registry, machine);
}
