import { Interpreter } from '@/command-kernel/interpreter';
import { registerCoreCommands } from '@/command-kernel/register-core-commands';
import { CommandRegistry } from '@/command-kernel/registry/command-registry';
import { BasenameCommand } from './commands/Basename';
import { CatCommand } from './commands/Cat';
import { CdCommand } from './commands/Cd';
import { Md5sumCommand, Sha1sumCommand, Sha256sumCommand } from './commands/Checksum';
import { DiffCommand } from './commands/Diff';
import { DmesgCommand } from './commands/Dmesg';
import { JournalctlCommand } from './commands/Journalctl';
import { DirnameCommand } from './commands/Dirname';
import { ExprCommand } from './commands/Expr';
import { FileCommand } from './commands/File';
import { ChgrpCommand } from './commands/Chgrp';
import { ChmodCommand } from './commands/Chmod';
import { ChownCommand } from './commands/Chown';
import { ClearCommand, ResetCommand } from './commands/Clear';
import { CpCommand } from './commands/Cp';
import { CutCommand } from './commands/Cut';
import { GrepCommand } from './commands/Grep';
import { PingCommand, Ping6Command } from './commands/Ping';
import { TracerouteCommand } from './commands/Traceroute';
import { ArpingCommand } from './commands/Arping';
import { SftpLauncherCommand } from './commands/Sftp';
import { UseraddCommand } from './commands/Useradd';
import { AdduserCommand, AddgroupCommand } from './commands/Adduser';
import { GroupsCommand } from './commands/Groups';
import { HeadCommand } from './commands/Head';
import { IdCommand } from './commands/Id';
import { LnCommand } from './commands/Ln';
import { LocaleCommand } from './commands/Locale';
import { LoggerCommand } from './commands/Logger';
import { LsCommand } from './commands/Ls';
import { MkdirCommand } from './commands/Mkdir';
import { MktempCommand } from './commands/Mktemp';
import { MvCommand } from './commands/Mv';
import { ChrtCommand } from './commands/Chrt';
import { IoniceCommand } from './commands/Ionice';
import { NiceCommand } from './commands/Nice';
import { ReniceCommand } from './commands/Renice';
import { TasksetCommand } from './commands/Taskset';
import { KillCommand } from './commands/Kill';
import { KillallCommand } from './commands/Killall';
import { PgrepCommand } from './commands/Pgrep';
import { PidofCommand } from './commands/Pidof';
import { PkillCommand } from './commands/Pkill';
import { PrintenvCommand } from './commands/Printenv';
import { PwdCommand } from './commands/Pwd';
import { ReadlinkCommand } from './commands/Readlink';
import { RealpathCommand } from './commands/Realpath';
import { RevCommand } from './commands/Rev';
import { RmCommand } from './commands/Rm';
import { RmdirCommand } from './commands/Rmdir';
import { SeqCommand } from './commands/Seq';
import { SleepCommand } from './commands/Sleep';
import { SortCommand } from './commands/Sort';
import { StatCommand } from './commands/Stat';
import { TailCommand } from './commands/Tail';
import { VmstatCommand } from './commands/Vmstat';
import { FreeCommand } from './commands/Free';
import { MpstatCommand } from './commands/Mpstat';
import { PidstatCommand } from './commands/Pidstat';
import { IostatCommand } from './commands/Iostat';
import { TouchCommand } from './commands/Touch';
import { TrCommand } from './commands/Tr';
import { TruncateCommand } from './commands/Truncate';
import { TtyCommand } from './commands/Tty';
import { UmaskCommand } from './commands/Umask';
import { UniqCommand } from './commands/Uniq';
import { WcCommand } from './commands/Wc';
import { WhoamiCommand } from './commands/Whoami';
import { LinuxMachineApi, LinuxMachineApiDeps } from './LinuxMachineApi';

export function createLinuxHostShell(deps: LinuxMachineApiDeps): Interpreter {
  const registry = new CommandRegistry();
  const machine = new LinuxMachineApi(deps);

  registerCoreCommands(registry);
  registry.register(() => new PwdCommand());
  registry.register(() => new CdCommand());
  registry.register(() => new LsCommand());
  registry.register(() => new CatCommand());
  registry.register(() => new MkdirCommand());
  registry.register(() => new TouchCommand());
  registry.register(() => new RmCommand());
  registry.register(() => new CpCommand());
  registry.register(() => new MvCommand());
  registry.register(() => new StatCommand());
  registry.register(() => new ChmodCommand());
  registry.register(() => new ChownCommand());
  registry.register(() => new ChgrpCommand());
  registry.register(() => new GrepCommand());
  registry.register(() => new HeadCommand());
  registry.register(() => new TailCommand());
  registry.register(() => new WcCommand());
  registry.register(() => new SortCommand());
  registry.register(() => new CutCommand());
  registry.register(() => new UniqCommand());
  registry.register(() => new TrCommand());
  registry.register(() => new WhoamiCommand());
  registry.register(() => new GroupsCommand());
  registry.register(() => new IdCommand());
  registry.register(() => new LnCommand());
  registry.register(() => new RmdirCommand());
  registry.register(() => new UmaskCommand());
  registry.register(() => new ReadlinkCommand());
  registry.register(() => new RealpathCommand());
  registry.register(() => new BasenameCommand());
  registry.register(() => new DirnameCommand());
  registry.register(() => new SeqCommand());
  registry.register(() => new ExprCommand());
  registry.register(() => new SleepCommand());
  registry.register(() => new RevCommand());
  registry.register(() => new PrintenvCommand());
  registry.register(() => new PidofCommand());
  registry.register(() => new PgrepCommand());
  registry.register(() => new PkillCommand());
  registry.register(() => new KillCommand());
  registry.register(() => new KillallCommand());
  registry.register(() => new NiceCommand());
  registry.register(() => new ReniceCommand());
  registry.register(() => new ChrtCommand());
  registry.register(() => new IoniceCommand());
  registry.register(() => new TasksetCommand());
  registry.register(() => new TtyCommand());
  registry.register(() => new TruncateCommand());
  registry.register(() => new MktempCommand());
  registry.register(() => new FileCommand());
  registry.register(() => new LocaleCommand());
  registry.register(() => new LoggerCommand());
  registry.register(() => new DmesgCommand());
  registry.register(() => new JournalctlCommand());
  registry.register(() => new VmstatCommand());
  registry.register(() => new FreeCommand());
  registry.register(() => new MpstatCommand());
  registry.register(() => new PidstatCommand());
  registry.register(() => new IostatCommand());
  registry.register(() => new Md5sumCommand());
  registry.register(() => new Sha1sumCommand());
  registry.register(() => new Sha256sumCommand());
  registry.register(() => new DiffCommand());
  registry.register(() => new ClearCommand());
  registry.register(() => new ResetCommand());
  registry.register(() => new PingCommand());
  registry.register(() => new Ping6Command());
  registry.register(() => new TracerouteCommand());
  registry.register(() => new ArpingCommand());
  registry.register(() => new SftpLauncherCommand());
  registry.register(() => new UseraddCommand());
  registry.register(() => new AdduserCommand());
  registry.register(() => new AddgroupCommand());

  return new Interpreter(registry, machine);
}
