import { Interpreter } from '@/command-kernel/interpreter';
import { registerCoreCommands } from '@/command-kernel/register-core-commands';
import { CommandRegistry } from '@/command-kernel/registry/command-registry';
import { BasenameCommand } from './commands/Basename';
import { CatCommand } from './commands/Cat';
import { CdCommand } from './commands/Cd';
import { Md5sumCommand, Sha1sumCommand, Sha256sumCommand } from './commands/Checksum';
import { DirnameCommand } from './commands/Dirname';
import { ExprCommand } from './commands/Expr';
import { FileCommand } from './commands/File';
import { ChgrpCommand } from './commands/Chgrp';
import { ChmodCommand } from './commands/Chmod';
import { ChownCommand } from './commands/Chown';
import { CpCommand } from './commands/Cp';
import { CutCommand } from './commands/Cut';
import { GrepCommand } from './commands/Grep';
import { GroupsCommand } from './commands/Groups';
import { HeadCommand } from './commands/Head';
import { IdCommand } from './commands/Id';
import { LnCommand } from './commands/Ln';
import { LocaleCommand } from './commands/Locale';
import { LsCommand } from './commands/Ls';
import { MkdirCommand } from './commands/Mkdir';
import { MktempCommand } from './commands/Mktemp';
import { MvCommand } from './commands/Mv';
import { PrintenvCommand } from './commands/Printenv';
import { PwdCommand } from './commands/Pwd';
import { ReadlinkCommand } from './commands/Readlink';
import { RealpathCommand } from './commands/Realpath';
import { RevCommand } from './commands/Rev';
import { RmCommand } from './commands/Rm';
import { RmdirCommand } from './commands/Rmdir';
import { SeqCommand } from './commands/Seq';
import { SleepCommand } from './commands/Sleep';
import { SortCommand } from './commands/Sort';
import { StatCommand } from './commands/Stat';
import { TailCommand } from './commands/Tail';
import { TouchCommand } from './commands/Touch';
import { TrCommand } from './commands/Tr';
import { TruncateCommand } from './commands/Truncate';
import { TtyCommand } from './commands/Tty';
import { UmaskCommand } from './commands/Umask';
import { UniqCommand } from './commands/Uniq';
import { WcCommand } from './commands/Wc';
import { WhoamiCommand } from './commands/Whoami';
import { LinuxMachineApi, LinuxMachineApiDeps } from './LinuxMachineApi';

export function createLinuxHostShell(deps: LinuxMachineApiDeps): Interpreter {
  const registry = new CommandRegistry();
  const machine = new LinuxMachineApi(deps);

  registerCoreCommands(registry);
  registry.register(() => new PwdCommand());
  registry.register(() => new CdCommand());
  registry.register(() => new LsCommand());
  registry.register(() => new CatCommand());
  registry.register(() => new MkdirCommand());
  registry.register(() => new TouchCommand());
  registry.register(() => new RmCommand());
  registry.register(() => new CpCommand());
  registry.register(() => new MvCommand());
  registry.register(() => new StatCommand());
  registry.register(() => new ChmodCommand());
  registry.register(() => new ChownCommand());
  registry.register(() => new ChgrpCommand());
  registry.register(() => new GrepCommand());
  registry.register(() => new HeadCommand());
  registry.register(() => new TailCommand());
  registry.register(() => new WcCommand());
  registry.register(() => new SortCommand());
  registry.register(() => new CutCommand());
  registry.register(() => new UniqCommand());
  registry.register(() => new TrCommand());
  registry.register(() => new WhoamiCommand());
  registry.register(() => new GroupsCommand());
  registry.register(() => new IdCommand());
  registry.register(() => new LnCommand());
  registry.register(() => new RmdirCommand());
  registry.register(() => new UmaskCommand());
  registry.register(() => new ReadlinkCommand());
  registry.register(() => new RealpathCommand());
  registry.register(() => new BasenameCommand());
  registry.register(() => new DirnameCommand());
  registry.register(() => new SeqCommand());
  registry.register(() => new ExprCommand());
  registry.register(() => new SleepCommand());
  registry.register(() => new RevCommand());
  registry.register(() => new PrintenvCommand());
  registry.register(() => new TtyCommand());
  registry.register(() => new TruncateCommand());
  registry.register(() => new MktempCommand());
  registry.register(() => new FileCommand());
  registry.register(() => new LocaleCommand());
  registry.register(() => new Md5sumCommand());
  registry.register(() => new Sha1sumCommand());
  registry.register(() => new Sha256sumCommand());

  return new Interpreter(registry, machine);
}
