/**
 * Canonical contents of the NSS-managed system files. Seeded by
 * `LinuxMachine` at provisioning time so a freshly powered-on host has
 * the same baseline as a default Ubuntu 22.04 install.
 *
 * The contents are deliberately compact — enough so the standard
 * `getent services 80/tcp`, `getent protocols icmp`, `getent networks`
 * queries return realistic answers — without bloating every Linux PC's
 * memory footprint. Power-users can append to these files at runtime;
 * the NSS resolver re-reads the VFS each call so additions are live.
 */

/** `/etc/services` — well-known port-to-name map. */
export const ETC_SERVICES: string = [
  '# Network services, Internet style',
  '# Note that it is presently the policy of IANA to assign a single well-known',
  '# port number for both TCP and UDP; hence, officially ports have two entries',
  '# even if the protocol doesn\'t support UDP operations.',
  '',
  'tcpmux          1/tcp                           # TCP port service multiplexer',
  'echo            7/tcp',
  'echo            7/udp',
  'discard         9/tcp           sink null',
  'discard         9/udp           sink null',
  'systat          11/tcp          users',
  'daytime         13/tcp',
  'daytime         13/udp',
  'netstat         15/tcp',
  'qotd            17/tcp          quote',
  'chargen         19/tcp          ttytst source',
  'chargen         19/udp          ttytst source',
  'ftp-data        20/tcp',
  'ftp             21/tcp',
  'fsp             21/udp          fspd',
  'ssh             22/tcp                          # SSH Remote Login Protocol',
  'ssh             22/udp',
  'telnet          23/tcp',
  'smtp            25/tcp          mail',
  'time            37/tcp          timserver',
  'time            37/udp          timserver',
  'whois           43/tcp          nicname',
  'tacacs          49/tcp                          # Login Host Protocol (TACACS)',
  'tacacs          49/udp',
  'domain          53/tcp                          # Domain Name Server',
  'domain          53/udp',
  'bootps          67/udp',
  'bootpc          68/udp',
  'tftp            69/udp',
  'gopher          70/tcp                          # Internet Gopher',
  'finger          79/tcp',
  'http            80/tcp          www                     # WorldWideWeb HTTP',
  'kerberos        88/tcp          kerberos5 krb5 kerberos-sec # Kerberos v5',
  'kerberos        88/udp          kerberos5 krb5 kerberos-sec',
  'pop2            109/tcp         postoffice',
  'pop3            110/tcp         pop-3',
  'sunrpc          111/tcp         portmapper              # RPC 4.0 portmapper',
  'sunrpc          111/udp         portmapper',
  'auth            113/tcp         authentication tap ident',
  'sftp            115/tcp',
  'nntp            119/tcp         readnews untp           # USENET News Transfer Protocol',
  'ntp             123/tcp',
  'ntp             123/udp                                 # Network Time Protocol',
  'netbios-ns      137/tcp                                 # NETBIOS Name Service',
  'netbios-ns      137/udp',
  'netbios-dgm     138/tcp                                 # NETBIOS Datagram Service',
  'netbios-dgm     138/udp',
  'netbios-ssn     139/tcp                                 # NETBIOS session service',
  'netbios-ssn     139/udp',
  'imap2           143/tcp         imap                    # Interim Mail Access P 2 and 4',
  'imap2           143/udp         imap',
  'snmp            161/tcp                                 # Simple Net Mgmt Protocol',
  'snmp            161/udp',
  'snmp-trap       162/tcp         snmptrap                # Traps for SNMP',
  'snmp-trap       162/udp         snmptrap',
  'bgp             179/tcp',
  'bgp             179/udp                                 # Border Gateway Protocol',
  'ldap            389/tcp',
  'ldap            389/udp',
  'https           443/tcp                                 # http protocol over TLS/SSL',
  'https           443/udp                                 # HTTP/3',
  'syslog          514/udp',
  'rsync           873/tcp                                 # rsync',
  'imaps           993/tcp                                 # IMAP over SSL',
  'pop3s           995/tcp                                 # POP-3 over SSL',
  '',
].join('\n');

/** `/etc/protocols` — well-known protocol numbers (IANA). */
export const ETC_PROTOCOLS: string = [
  '# Internet (IP) protocols',
  '#',
  'ip      0       IP              # internet protocol, pseudo protocol number',
  'icmp    1       ICMP            # internet control message protocol',
  'igmp    2       IGMP            # Internet Group Management',
  'ggp     3       GGP             # gateway-gateway protocol',
  'ipencap 4       IP-ENCAP        # IP encapsulated in IP (RFC 2003)',
  'st      5       ST              # ST datagram mode',
  'tcp     6       TCP             # transmission control protocol',
  'egp     8       EGP             # exterior gateway protocol',
  'pup     12      PUP             # PARC universal packet protocol',
  'udp     17      UDP             # user datagram protocol',
  'hmp     20      HMP             # host monitoring protocol',
  'xns-idp 22      XNS-IDP         # Xerox NS IDP',
  'rdp     27      RDP             # "reliable datagram" protocol',
  'iso-tp4 29      ISO-TP4         # ISO Transport Protocol class 4 (RFC 905)',
  'dccp    33      DCCP            # Datagram Congestion Control Protocol (RFC 4340)',
  'xtp     36      XTP             # Xpress Transfer Protocol',
  'ddp     37      DDP             # Datagram Delivery Protocol',
  'idpr-cmtp 38    IDPR-CMTP       # IDPR Control Message Transport',
  'ipv6    41      IPv6            # Internet Protocol, version 6',
  'ipv6-route 43   IPv6-Route      # Routing Header for IPv6',
  'ipv6-frag  44   IPv6-Frag       # Fragment Header for IPv6',
  'idrp    45      IDRP            # Inter-Domain Routing Protocol',
  'rsvp    46      RSVP            # Reservation Protocol',
  'gre     47      GRE             # General Routing Encapsulation',
  'esp     50      IPSEC-ESP       # Encap Security Payload [RFC2406]',
  'ah      51      IPSEC-AH        # Authentication Header [RFC2402]',
  'skip    57      SKIP            # SKIP',
  'ipv6-icmp 58    IPv6-ICMP icmpv6 # ICMP for IPv6',
  'ipv6-nonxt 59   IPv6-NoNxt      # No Next Header for IPv6',
  'ipv6-opts 60    IPv6-Opts       # Destination Options for IPv6',
  'rspf    73      RSPF CPHB       # Radio Shortest Path First (officially CPHB)',
  'vmtp    81      VMTP            # Versatile Message Transport',
  'eigrp   88      EIGRP           # Enhanced Interior Routing Protocol (Cisco)',
  'ospf    89      OSPFIGP         # Open Shortest Path First IGP',
  'ax.25   93      AX.25           # AX.25 frames',
  'ipip    94      IPIP            # IP-within-IP Encapsulation Protocol',
  'etherip 97      ETHERIP         # Ethernet-within-IP Encapsulation [RFC3378]',
  'encap   98      ENCAP           # Yet Another IP encapsulation [RFC1241]',
  'pim     103     PIM             # Protocol Independent Multicast',
  'ipcomp  108     IPCOMP          # IP Payload Compression Protocol',
  'vrrp    112     VRRP carp       # Virtual Router Redundancy Protocol',
  'l2tp    115     L2TP            # Layer Two Tunneling Protocol [RFC2661]',
  'isis    124     ISIS            # IS-IS over IPv4',
  'sctp    132     SCTP            # Stream Control Transmission Protocol',
  'fc      133     FC              # Fibre Channel',
  'mobility-header 135 Mobility-Header # Mobility Support for IPv6 [RFC3775]',
  'udplite 136     UDPLite         # UDP-Lite [RFC3828]',
  'mpls-in-ip 137  MPLS-in-IP      # MPLS-in-IP [RFC4023]',
  '',
].join('\n');

/** `/etc/networks` — symbolic network names. */
export const ETC_NETWORKS: string = [
  '# symbolic names for networks, see networks(5) for more information',
  'link-local      169.254.0.0',
  '',
].join('\n');

/** `/etc/rpc` — RPC programme numbers. */
export const ETC_RPC: string = [
  '# This file contains user readable names that can be used in place of rpc',
  '# program numbers.',
  'portmapper      100000  portmap sunrpc rpcbind',
  'rstatd          100001  rstat rup rstat_svc',
  'rusersd         100002  rusers',
  'nfs             100003  nfsprog',
  'ypserv          100004  ypprog',
  'mountd          100005  mount showmount',
  'ypbind          100007',
  'walld           100008  rwall shutdown',
  'yppasswdd       100009  yppasswd',
  'etherstatd      100010  etherstat',
  'rquotad         100011  rquotaprog quota rquota',
  'sprayd          100012  spray',
  'pcnfsd          150001  pcnfs',
  'amd             300019  amq',
  '',
].join('\n');
